### ISSUE TITLE
[help wanted] virt-xml, remove --boot hd,cdrom

### ISSUE THREAD

**Issue by MrM40** [virt-manager/virt-manager#100]
Got this rather common \<os\> element:

`<os>`
`     <type arch='x86_64'  machine='pc-q35-3.1'>hvm</type>`
`    <loader readonly='yes'  type='pflash'>/usr/share/OVMF/OVMF_CODE.fd</loader>`
`    <nvram>/var/lib/libvirt/qemu/nvram/DebianSDK_VARS.fd</nvram>`
`    <boot dev='hd'/>`
`    <boot dev='cdrom'/>`
`</os>`

How do I remove the two \<boot\> elements with virt-xml?
`virt-xml DebianSDK --edit --boot hd,cdrom`
The way I see it doesn't make sense to use `option=,` (hd and cdrom don't take any values right)

I could replace the whole <os> element with `clearxml` but it that really my only option?
It's a lot of values to rewrite, which I first have to retrieve.

**Comment by crobinso** [comment]
It's not intuitive, but you can clear the first two individual `<boot dev=X/>` elements like: `--boot boot0.dev=,boot1.dev=`

**Comment by MrM40** [comment]
Thank for reply, but I'm not able to succeed.
` virt-xml "DebianSDK child" --edit --boot boot0.dev=,boot1.dev= --confirm`
Result:
`ERROR    Unknown options ['boot0.dev', 'boot1.dev']`

I'm running **virt-xml 2.0.0**, perhaps it's only supported in newer version?

**Comment by crobinso** [comment]
Yes it was added in version 2.2.0. You can probably run it easily enough with:

```console
git clone https://github.com/virt-manager/virt-manager
cd virt-manager
./virt-xml ...
```

**Comment by MrM40** [comment]
Perfect, thanks :-)
