### ISSUE TITLE
Add switch for keyboard locks

### ISSUE THREAD

**Issue by dvalter** [virt-manager/virt-manager#102]
Lock key state sync is broken when one of lock keys is used for an alternative action.
Steps to reproduce:
1. Have 2 or more keyboard layouts on a host machine
2. Set layout switch combination to `Caps Lock`
3. Connect to a remote machine using Spice.
4. Use Caps Lock in a remote machine. It will get back off in a few seconds.

Possible fix:
spice-gtk (including spicy GUI client) allows to turn lock syncing off.
It just needs to be added to virt-manager.

Or alternatively it may be reasonable to add some sort of detection  technique to spice-gtk for this (or similar) cases

**Comment by crobinso** [comment]
Thanks for the suggestion, but per [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md) I consider this an advanced viewer option, which is better suited for a more featureful UI like spicy or virt-viewer. So I don't think this should be configurable in virt-manager
