### ISSUE TITLE
virt-install: Cannot use storage /var/lib/libvirt/images/k8sc29n05a.qcow2: internal error: pool 'default' has asynchronous jobs running.

### ISSUE THREAD

**Issue by pascal71** [virt-manager/virt-manager#104]
Good afternoon,

I am using an Ansible playbook that will execute a task to create 6 VMs simultaneously using 
shell: virt-install

Out of the 6 VMs, 3 complete successfully the installation and the other 3 get this error:

_Cannot use storage /var/lib/libvirt/images/k8sc29n05a.qcow2: internal error: pool 'default' has asynchronous jobs running._ 

(Of course the other 2 will have a different image filename).

What is causing this? Is looks like a bug as it's not always occuring.

Thanks in advance.

Kind regards,

  Pascal van Dam

**Comment by devrob20** [comment]
try moving the .qcow2 to your home folder and create a new user session connection.

by default virt-manager is using qemu://system. so all the files are in root or group 0 and everything is stored in local system folders like /var. if your system has a newer filesystem like xfs or btrfs these end up in system snapshots, so with with a rollbacks or sync jobs things break.

a dirty trick is to simply move the images to your local home folder and edit the system pool, but setting up a user session is the preferred way.

`virsh pool-edit default`


see also https://serverfault.com/questions/840519/how-to-change-the-default-storage-pool-from-libvirt

**Comment by crobinso** [comment]
I haven't seen this before but it's not entirely unexpected if you are invoking a bunch of libvirt storage APIs at once, but this error is coming from libvirt and basically saying 'an action is already being performed on this pool'. You can probably avoid the error by serializing the storage creation ahead of time, using `qemu-img` or `virsh vol-create-as`. Or depending on your storage parameters it might just be enough to put a 5 second sleep in between virt-install invocations.

**Comment by crobinso** [comment]
I don't think this is a virt-manager but something happening at the libvirt level, so I'm closing this
