### ISSUE TITLE
Issue with virt-install 1.5.0 installing Ubuntu 20.04 focal

### ISSUE THREAD

**Issue by synergiator** [virt-manager/virt-manager#105]
Hi all,

is it possible to install Ubuntu 20.04 LTS with virt-install 1.5.0? 

```virt-install``` command (virt-install version 1.5.0):

    virt-install --wait -1 --force --debug --noreboot --name ubuntu-20.04-00123456 \
                 --noautoconsole --graphics vnc \
                 --disk path=/var/lib/libvirt/images/ubuntu-20.04-114046.qcow2,format=qcow2,size=10,bus=scsi \
                 --controller type=scsi \
                 --location $OS_ISO \
                 --os-type=linux --os-variant ubuntu18.04 -r 2048 --vcpus=2 --network network=default \
                 --features acpi=on,apic=on --initrd-inject config/20.04/preseed.cfg -x edd-off -x ipv6.disable=1

The ```--cdrom``` option works but then no custom configuration is possible.

Error:

    [virt-install 44526] ERROR (cli:318) Couldn't find hvm kernel for Ubuntu tree.
    [virt-install 44526] DEBUG (cli:320)

**Comment by ptoscano** [comment]
This is due to the "new Ubuntu installer", and will be fixed with #101 or #112.

**Comment by crobinso** [comment]
This is fixed in git now

**Comment by crobinso** [comment]
Unfortunately there's nothing we can do to fix virt-install 1.5.0 though. You'll need to ask your distro to backport support

**Comment by synergiator** [comment]
@crobinso how to use the fix then? Is there an upcoming new release soon?

**Comment by crobinso** [comment]
@synergiator I'm planning to do a release before the end of the month
