### ISSUE TITLE
Add support for specifying websocket port

### ISSUE THREAD

**Issue by wbenny** [virt-manager/virt-manager#107]
Please, add support for specifying websocket port into virt-install.

It should be as simple as adding one line in file: `virtinst/cli.py`:

```python
...
        cls.add_arg("type", "type", cb=cls.set_type_cb)
        cls.add_arg("port", "port")
#       cls.add_arg("websocket", "websocket")
        cls.add_arg("tlsPort", "tlsPort")
        cls.add_arg("listen", "listen")
...
```

**Comment by wbenny** [comment]
and this change, in `devices/graphics.py`:

```diff

-    _XML_PROP_ORDER = ["type", "gl", "_port", "_tlsPort", "autoport",
+    _XML_PROP_ORDER = ["type", "gl", "_port", "websocket", "_tlsPort", "autoport",
                        "_keymap", "_listen",
                        "passwd", "display", "xauth"]

@@ -118,6 +118,7 @@ class DeviceGraphics(Device):
         return self._port
     _port = XMLProperty("./@port", is_int=True)
     port = property(_get_port, _set_port)
+    websocket = XMLProperty("./@websocket", is_int=True)

     def _set_tlsport(self, val):
         val = _validate_port("TLS Port", val)
```

**Comment by crobinso** [comment]
Since you've already worked out the code, care to submit a PR? There's a tutorial for this type of change here: https://github.com/virt-manager/virt-manager/wiki/Extending-the-command-line

**Comment by crobinso** [comment]
@wbenny do you have plans to submit a patch for this?

**Comment by wbenny** [comment]
I would really like to, my focus just diverted to something else and also I've been straight up lazy, honestly. If it can wait by end of this week, I'll finally look at it. :)

**Comment by wbenny** [comment]
I didn't forget but can't make it this week - vacation. So... next week 🤞

**Comment by crobinso** [comment]
2862b682928d1162929c7e41d5251194d778c687
