### ISSUE TITLE
Error removing device

### ISSUE THREAD

**Issue by jorpilo** [virt-manager/virt-manager#108]
Hello.
Whenever I try to remove a device from a machine I get the following error:
I am runing on Manjaro
Python 3.8.2
virt-manager 2.2.1
```
Error Removing Device: iter() returned non-iterator of type 'xmlCoreDepthFirstItertor'
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/details/details.py", line 1935, in remove_device
    self.vm.remove_device(devobj)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 429, in remove_device
    xmlobj.remove_device(editdev)
  File "/usr/share/virt-manager/virtinst/guest.py", line 505, in remove_device
    self.devices.remove_child(dev)
  File "/usr/share/virt-manager/virtinst/xmlbuilder.py", line 723, in remove_child
    self._xmlstate.xmlapi.node_force_remove(xpath)
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 183, in node_force_remove
    self._node_remove_child(parentnode, childnode)
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 390, in _node_remove_child
    if all([node_is_text(n) for n in parentnode.children]):
TypeError: iter() returned non-iterator of type 'xmlCoreDepthFirstItertor'
```

**Comment by crobinso** [comment]
What is your libxml2 version, and version of the python3 bindings? There was a similar report in the past that was resolved by updating libxml2 bindings: https://bugzilla.redhat.com/show_bug.cgi?id=1764336

**Comment by jorpilo** [comment]
my libxml2 version is 2.9.10-1
my libxml2-python3 is 2.9.5
So they are not outdated... they might be too updated.

**Comment by crobinso** [comment]
The latest libxml2-python bindings are 2.9.10. Please try updating and see if that fixes it

**Comment by Antique** [comment]
The issue that you are hitting should be fixed by this commit https://github.com/GNOME/libxml2/commit/b3e488b0d90d5b0dbebf02cbd20894367f728d3e
It is weird that you have libxml2 and libxml2-python3 packages.  On arch linux and most likely Manjaro the python bindings are part of libxml2 package.

**Comment by jorpilo** [comment]
You are completely right. it was all due to my python and wrong library folder. python installed with pyenv has another site-package folder which doesn't follow system /usr/lib/python3.8/site-package where all the packages libraries are installed.
Manjaro libxml2 does come with python bindings.
pip installation of libxml2-python3 bindings seems outdated.

Thanks for the help. This is all solved.
