### ISSUE TITLE
Blank screen in remote-viewer on windows with spice-streaming-agent

### ISSUE THREAD

**Issue by doublehelix24** [virt-manager/virt-manager#110]
Remote-Viewer 9.0-256 x64 on Windows 10 1909.

The new spice window created by running spice-streamgin-agent is black, only mouse cursor is visible.
Using remote-viewer on linux the same setup works.

Spice-streaming-agent built from sources today, with gstreamer support.

felix@guest:~$ ./spice-streaming-agent -d
spice-streaming-agent[2465]: GOT START_STOP message -- request to START streaming
spice-streaming-agent[2465]: streaming starts now
spice-streaming-agent[2465]: Got device info of 1 devices from the plugin
spice-streaming-agent[2465]:    stream id 0: device address: pci/0000/06.0, device display id: 2
spice-streaming-agent[2465]: got a frame -- size is 321265 (26 ms) (1589641660285 ms from last frame)(1589641660258136 us)
spice-streaming-agent[2465]: wXh 1920X1200  codec=1
spice-streaming-agent[2465]: got a frame -- size is 335175 (87 ms) (87 ms from last frame)(189 us)
spice-streaming-agent[2465]: got a frame -- size is 341098 (133 ms) (133 ms from last frame)(66 us)

Log from remote-viewer.exe on client (Windows):
remote-viewer.exe:1436): GSpice-WARNING **: 16:36:47.347: notify the server that stream 48 does not exist
(remote-viewer.exe:1436): GSpice-CRITICAL **: 16:36:47.348: display_handle_stream_clip: assertion 'st != NULL' failed
(remote-viewer.exe:1436): GSpice-WARNING **: 16:36:47.356: notify the server that stream 41 does not exist
(remote-viewer.exe:1436): GSpice-CRITICAL **: 16:36:47.357: display_handle_stream_clip: assertion 'st != NULL' failed
(remote-viewer.exe:1436): GSpice-WARNING **: 16:36:47.363: notify the server that stream 33 does not exist
(remote-viewer.exe:1436): GSpice-CRITICAL **: 16:36:47.364: display_handle_stream_clip: assertion 'st != NULL' failed
(remote-viewer.exe:1436): GSpice-WARNING **: 16:36:47.366: notify the server that stream 34 does not exist
(remote-viewer.exe:1436): GSpice-CRITICAL **: 16:36:47.367: display_handle_stream_clip: assertion 'st != NULL

**Comment by crobinso** [comment]
Thanks for the report, but remote-viewer is part of the virt-viewer project, issue tracker here: https://gitlab.com/virt-viewer/virt-viewer/-/issues
