### ISSUE TITLE
Migration to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [virt-manager/virt-manager#111]
Hi there,

Daniel P. Berrange reached me to migrate the project to weblate as part of our migration: https://fedoraproject.org/wiki/L10N_Move_to_Weblate

I created this project for you and made Daniel admin:
https://translate.fedoraproject.org/projects/virt-manager/

Once done, I would appreciate to see you project to include a translation widget in your readme:
https://translate.fedoraproject.org/widgets/virt-manager/

Please let me know if any help is required,

**Comment by crobinso** [comment]
I think this is all set up now, we are receiving translation PRs from weblate. I've updated the project documentation to point to the fedora weblate instance. Thank you for your work!
