### ISSUE TITLE
ModuleNotFoundError: No module named 'libxml2' on Ubuntu 20.04

### ISSUE THREAD

**Issue by theeomm** [virt-manager/virt-manager#116]
After update to ubuntu 20.04, I've not been able to launch virt-manager.

```bash
Traceback (most recent call last):
  File "/usr/share/virt-manager/virt-manager", line 19, in <module>
    from virtinst import BuildConfig
  File "/usr/share/virt-manager/virtinst/__init__.py", line 49, in <module>
    from virtinst.domain import *  # pylint: disable=wildcard-import
  File "/usr/share/virt-manager/virtinst/domain/__init__.py", line 5, in <module>
    from .blkiotune import DomainBlkiotune
  File "/usr/share/virt-manager/virtinst/domain/blkiotune.py", line 8, in <module>
    from ..xmlbuilder import XMLBuilder, XMLChildProperty, XMLProperty
  File "/usr/share/virt-manager/virtinst/xmlbuilder.py", line 16, in <module>
    from .xmlapi import XMLAPI
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 7, in <module>
    import libxml2
ModuleNotFoundError: No module named 'libxml2'
```
I have `python3-libxml2` installed already. Please help

**Comment by Antique** [comment]
I've installed fresh Ubuntu 20.04 and virt-manager from ubuntu packages and everything works correctly, after that I also tried to clone virt-manager git and run it from git repository and again works correctly.  How did you install virt-manager and all the dependencies?

**Comment by theeomm** [comment]
Managed to fix the issue by removing `python3-libxml2 and virt-manager` and then reinstalled virt-manager

**Comment by AdamPerkins** [comment]
Thanks for the solution. I had the same problem after upgrade.

Indeed this has done the job:
```
sudo apt remove python3-libxml2
sudo apt install virt-manager
```

**Comment by mantzas** [comment]
Hey, unfortunately it did not work for me... I am pretty much blocked and i have to install virtualbox for now until this is resolve... :(

**Comment by Antique** [comment]
Looks like there is something seriously broken in Ubuntu packaging. I would recommend reporting this in Ubuntu issue tracker.

In the mean time make sure that you don't have any python libraries installed using PIP, that you are running correct virt-manager from the system installed directory.

**Comment by mantzas** [comment]
@Antique already done... https://bugs.launchpad.net/ubuntu/+source/virt-manager/+bug/1883565

**Comment by clandestine8** [comment]
> Thanks for the solution. I had the same problem after upgrade.
> 
> Indeed this has done the job:
> 
> ```
> sudo apt remove python3-libxml2
> sudo apt install virt-manager
> ```

Works on 21.04 As well

**Comment by w-barath** [comment]
I had this problem on hirsute, and it was caused by the mkusb ppa holding outdated versions of the libxml2 module, which then failed to load.  

I figured this out with strace which showed both the module and the shared library being loaded.  

The error isn't very helpful given that the module did in fact exist, it just failed to initialise correctly.

**Comment by Vitexus** [comment]
my solution:

```shell
sudo aptitude purge python3-libxml2
apt-get source python3-libxml2
cd libxml2-2.9.10+dfsg/
sudo apt install  dh-sequence-python3 libpython3-all-dbg libpython3-all-dev python3-all-dbg:any python3-all-dev rename
debuild -i -us -uc -b
gdebi python3-libxml2_2.9.10+dfsg-6.3ubuntu0.1_amd64.deb 
apt install virt-manager
```

virt-manager  is fixed now

**Comment by w-barath** [comment]
If you're going to go that route then you should lock the package version
to prevent updates.  Otherwise apt will overwrite your manual build when
the broken apt source has a newer broken version available, lol.

Cheers -

*William Barath *

**Comment by Vitexus** [comment]
> If you're going to go that route then you should lock the package version to prevent updates. Otherwise apt will overwrite your manual build when the broken apt source has a newer broken version available, lol.

As you said ...  

ModuleNotFoundError: No module named 'libxml2' is back :)

**Comment by Gyztor** [comment]
after updating to debian 11 from 10 it has appeared for me now too
```
Traceback (most recent call last):
  File "/usr/bin/virt-manager", line 6, in <module>
    from virtManager import virtmanager
  File "/usr/share/virt-manager/virtManager/virtmanager.py", line 19, in <module>
    from virtinst import BuildConfig
  File "/usr/share/virt-manager/virtinst/__init__.py", line 50, in <module>
    from virtinst.domain import *  # pylint: disable=wildcard-import
  File "/usr/share/virt-manager/virtinst/domain/__init__.py", line 5, in <module>
    from .blkiotune import DomainBlkiotune
  File "/usr/share/virt-manager/virtinst/domain/blkiotune.py", line 8, in <module>
    from ..xmlbuilder import XMLBuilder, XMLChildProperty, XMLProperty
  File "/usr/share/virt-manager/virtinst/xmlbuilder.py", line 16, in <module>
    from .xmlapi import XMLAPI
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 7, in <module>
    import libxml2
ModuleNotFoundError: No module named 'libxml2'
```
i have done the reinstalls too and nothing has worked so far :/

**Comment by w-barath** [comment]
> i have done the reinstalls too and nothing has worked so far :/

Have you tried disabling all apt repos which are not part of stock Debian, then reinstalling libxml2, locking the package, and lastly re-enabling your foreign repos?

**Comment by elliotmtx** [comment]
How to get this python3-libxml2 in yocto? 
where is source code for python3-libxml2?

**Comment by Nuraddeen** [comment]
> Thanks for the solution. I had the same problem after upgrade.
> 
> Indeed this has done the job:
> 
> ```
> sudo apt remove python3-libxml2
> sudo apt install virt-manager
> ```

This also works for me (Ubuntu 22.04 LTS)

**Comment by drm** [comment]
It seems to me that this is a packaging issue in python3-libxml2, which installed in /usr/lib/python3.7/dist-packages in my distro, while the running python version (3.9) did not contain that in `sys.path`. I symlinked the files in /usr/lib/python3/dist-packages which fixes the issue for now.

**Comment by gotgot1995** [comment]
Thanks you so much @drm ! That solved the issue for me.

**Comment by shellandco** [comment]
@drm I confirm it is ok on Debian 11. Thank you !

**Comment by Ghazif-Adeem** [comment]
> Thanks for the solution. I had the same problem after upgrade.
> 
> Indeed this has done the job:
> 
> ```
> sudo apt remove python3-libxml2
> sudo apt install virt-manager
> ```

This didn't work for me.
Debian 11.5

**Comment by pabloasanchez** [comment]
This is what helped me
```
cd /usr/lib/python3/dist-packages/
ls | grep libxml2mod
sudo ln -s libxml2mod.cpython-310-x86_64-linux-gnu.so libxml2mod.so
```

**Comment by rafutek** [comment]
Had the same issue with version 5.0 :
```
Traceback (most recent call last):
  File "/usr/bin/virt-install", line 6, in <module>
    from virtinst import virtinstall
  File "/usr/share/virt-manager/virtinst/__init__.py", line 50, in <module>
    from virtinst.domain import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/domain/__init__.py", line 5, in <module>
    from .blkiotune import DomainBlkiotune
  File "/usr/share/virt-manager/virtinst/domain/blkiotune.py", line 8, in <module>
    from ..xmlbuilder import XMLBuilder, XMLChildProperty, XMLProperty
  File "/usr/share/virt-manager/virtinst/xmlbuilder.py", line 16, in <module>
    from .xmlapi import XMLAPI
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 7, in <module>
    import libxml2
ModuleNotFoundError: No module named 'libxml2'
```

Tried to remove python3-libxml2 and virt-manager and then reinstall virt-manager as suggested, but the error is still here.

Any idea ?
