### ISSUE TITLE
Wrong input coordination on HiDPI and VirGL

### ISSUE THREAD

**Issue by hexchain** [virt-manager/virt-manager#117]
On a HiDPI display (2x in my case), using VirGL (virtio-gpu) with "Scale display - Never", it seems that the mouse input coordinate is wrong. The virtual screen shows up in the middle but takes input from the bottom right corner.

Here is a screencast: https://gofile.io/d/IZemTS

I haven't tested other graphics types. "Scale display - Always" does not have this issue. Also, I think the guest display should be able to completely fill the display area instead of staying in the center with only 1/4 the size.

OS: Arch Linux
Component versions:
```
virt-manager 2.2.1-2
spice 0.14.3-2
spice-protocol 0.14.1-1
spice-gtk 0.38-1
```

(Sorry for filing the bug here. RHBZ is very unstable and unusable for me at the moment.)

**Comment by hexchain** [comment]
As part of it seems to be a spice issue, I've filed another report at https://gitlab.freedesktop.org/spice/spice-gtk/-/issues/127.

**Comment by crobinso** [comment]
Thanks for the report. virt-manager doesn't do anything special here I think, just relying on spice-gtk code to get this correct for us. So I don't think there's anything virt-manager can do to fix this. Closing this in favor of the spice-gtk issue but we can reopen if we determine there is work to do in virt-manager
