### ISSUE TITLE
What's the state of virt-manager?

### ISSUE THREAD

**Issue by ardevd** [virt-manager/virt-manager#118]
Apologies if this has been brought up before. I tried searching to no avail.

My understanding is that virt-manager has been deprecated in favour of Cockpit. Does this mean development of virt-manager has effectively stopped (despite recent commits) or does it simply mean that it's now a 100% community driven project?

**Comment by sesopenko** [comment]
Have you looked at the depoloyment guide of cockpit?  virt-manager and cockpit aren't the same things. Development hasn't stopped, there was a merge 27 days ago.

**Comment by catborise** [comment]
cockpit is too primitive compare to virt-manager. implementation very limited by now.

**Comment by ardevd** [comment]
https://www.redhat.com/en/blog/managing-virtual-machines-rhel-8-web-console

> One of the features included with RHEL 8 Beta is the ability to manage virtual machines from the Web Console (also known as Cockpit), and the announcement that virt-manager has been deprecated. The Web Console is intended to become its replacement in a subsequent release. It is recommended that you use the Web Console as your virtual machine graphical management tool.

**Comment by catborise** [comment]
yes i know that statement. the depreciation time could be very long. may be in rhel 9...
if you want to do simple things like create view delete stop start cockpit is enough, but virt-manager can do nitty gritty things. you will need it...

**Comment by ardevd** [comment]
> yes i know that statement. the depreciation time could be very long. may be in rhel 9...
> if you want to do simple things like create view delete stop start cockpit is enough, but virt-manager can do nitty gritty things. you will need it...

I've been using it for years so I'm fully aware how it works. My question remains though. If virt-manager is officially deprecated, what's the development plan moving forward.

**Comment by phrdina** [comment]
Hi, that statement is valid but it applies only to RHEL distribution and if it will be removed in future RHEL versions it might affect CentOS as well, but my guess is that it will be provided by EPEL if the removal from RHEL happens.

From community point of view virt-manager is not deprecated and will continue as community project and all other distributions will most likely package it for their users. So no need to worry.

**Comment by crobinso** [comment]
FWIW, as googling 'virt-manager deprecated' brings up quite a bit of misinformation on this topic, I wrote a blog post explaining the situation: https://blog.wikichoon.com/2020/06/virt-manager-deprecated-in-rhel.html
