### ISSUE TITLE
Why was io mode option removed?

### ISSUE THREAD

**Issue by chriscjs** [virt-manager/virt-manager#119]
In version 2.2.1 I was able to choose native or threads but after building latest git the option is no longer there.

**Comment by crobinso** [comment]
This was discussed here: https://www.redhat.com/archives/virt-tools-list/2019-June/msg00117.html

In the interest of focusing the UI and setting up rules for what types of features we should add in the future, io=threads|native was dropped from the UI, in my experience it's rarely changed from the default, and it is an advanced enough feature that if users know about it then I'm fine having them set it in the graphical XML editor that was added in v2.2.0.

**Comment by crobinso** [comment]
See https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md for more general justification of the UI strategy
