### ISSUE TITLE
Sugestion: Shutdown all VMs from virt-manager

### ISSUE THREAD

**Issue by darwincr** [virt-manager/virt-manager#121]
It would be great if there was an option here to shutdown all VMs

<a href='https://postimg.cc/sQQQtNSk' target='_blank'><img src='https://i.postimg.cc/sQQQtNSk/Screenshot-2020-06-22-02-52-07.png' border='0' alt='Screenshot-2020-06-22-02-52-07'/></a>

**Comment by sesopenko** [comment]
@darwincr, what are some example workflows which would require a feature like this?

**Comment by crobinso** [comment]
Thanks for the suggestion, but multi VM operations is explicitly not something we want to support in virt-manager. Please see [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md) for more explanation
