### ISSUE TITLE
In tool help

### ISSUE THREAD

**Issue by sesopenko** [virt-manager/virt-manager#123]
Proxmox has handy in-tool help for various settings and virt-manager can benefit from the same.  The design goals of the software make it a no-brainer, with some settings potentially saving a user from choosing destructive options.  Low hanging fruit could be explaining cache strategies in-tool, so that users understand the potential consequences of their choice.

Have there already been any design discussions on the topic of in-tool help?

**Comment by crobinso** [comment]
Thanks for the suggestion. Truthfully we have never had the resources to maintain help content like you describe (and it's the long term maintenance that is the difficult part, synced with UI changes and periodically refreshing screenshots etc). In a perfect world it would probably exist.

There's downsides to putting content like cache value descriptions into app docs too. I think docs about config specifics should live at the qemu or libvirt layer where they have a better chance of getting continuing attention from devs that work on the actual implementation.

Given more resources, duplicating docs at the UI level wouldn't be that big of a deal, but with limited dev resources history tells me they just go out of date as the lower level stack moves on.

The bit about unsafe cache modes is valid though. cache=unsafe in particular is an advanced option and should not explicitly be in the UI. users that know what they are doing can edit the XML in the UI manually to add that value. It should be removed from clickable UI though so users don't shoot themselves in the foot, despite the value obviously advertising itself as unsafe. I would take a patch or issue report for that

**Comment by sesopenko** [comment]
I can put a patch together.  Can you share a few sentences on where to look for the options in the code base and where the tests are? I'm not too familiar with the code base.

**Comment by crobinso** [comment]
@sesopenko I think if you remove the two instances of CACHE_MODE_UNSAFE in the codebase it will stop being advertised in the UI. The UI field is a text box so users that know they need it can still type it in by hand, or use the XML editor for it, so just removing it as an option in the dropdown is fine by me.
