### ISSUE TITLE
Is it possible to config NAT port forwarding with virt-manager

### ISSUE THREAD

**Issue by shaohq** [virt-manager/virt-manager#125]
I'm trying out virt-manager, it's great, and I want to do port forwarding so that I can access some port of the guest from out side.

**Comment by crobinso** [comment]
I'm glad you like virt-manager! Port forwarding is possible with the NAT 'default' network but you need to mess with host iptables, see https://wiki.libvirt.org/page/Networking#Forwarding_Incoming_Connections

**Comment by PerryWerneck** [comment]
It would be a really nice enhancement for virt-manager.

> I'm glad you like virt-manager! Port forwarding is possible with the NAT 'default' network but you need to mess with host iptables, see https://wiki.libvirt.org/page/Networking#Forwarding_Incoming_Connections
