### ISSUE TITLE
RFE: virtio-fs support

### ISSUE THREAD

**Issue by jwatt** [virt-manager/virt-manager#127]
I believe virtio-fs support was added in QEMU 5.0/Linux 5.4 and offers significantly better performance. Can this be exposed as an option in virt-manager?

**Comment by jwatt** [comment]
It looks like support in the Windows drivers won't arrive until September FWIW: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/126#issuecomment-648009192

**Comment by crobinso** [comment]
Thanks for the report. Yes we should add support to the UI for this. It's a bit tricky because it requires other guest features to be enabled, shared memory and numa config, so it can't presently be enabled in isolation. I don't think it should be added to the UI until we can make it transparently 'just work' when the user requests it for an offline VM

**Comment by jwatt** [comment]
> it requires other guest features to be enabled, shared memory and numa config

The [docs](https://libvirt.org/kbase/virtiofs.html#host-setup) now say "As of QEMU 5.0.0 and libvirt 6.9.0, it is possible to specify the memory backend without NUMA". Hopefully that helps, although I haven't tested VMs without NUMA myself yet since, while Fedora 33 come with QEMU 5.1, it currently only has libvirt 6.6.0.

Happy New Year, and thanks for your work on virt-manager! 😄

**Comment by crobinso** [comment]
Thanks @jwatt ! The NUMA bit is no longer required which is great. The remaining bits to figure out are:

1) confirm there are little to no downsides to use memfd or shared mem by default
2) confirm libvirt advertises all the features we need to know about in domcapabilities so we can safely change the memory default without hardcoding fragile version checks

Once those are answered and implemented, newly created VMs wouldn't need any extra VM config to make virtio-fs devices work out of the box.

**Comment by mniehren** [comment]
Hi, 
i just tested virtiofs with qemu V5.2.0 and libvirt-6.10.0 and it works like a charm.
In the xml-File of the domain i only added 2 entries:
<memoryBacking>
    <access mode='shared'/>
  </memoryBacking>

and

    <filesystem type='mount' accessmode='passthrough'>
      <driver type='virtiofs'/>
      <source dir='/system/virtiofs-test'/>
      <target dir='vtest'/>
    </filesystem>

It would be very nice to setup the mount-point in virt-manager. I don't understand why this feature is
on state blocked ?

best regards
  Michael

**Comment by tinywrkb** [comment]
I'm also looking forward to this being supported without having to edit the xml.  
There's a [WIP branch with DAX support here](https://github.com/rhvgoyal/qemu/commits/dax-support), I'm not sure if this also needs libvirt changes but it worth taking this into consideration when adding virtiofs support to Virt Manager.

**Comment by jwatt** [comment]
The GNOME Boxes issue, for reference: https://gitlab.gnome.org/GNOME/gnome-boxes/-/issues/292

**Comment by sej7278** [comment]
virtiofs doesn't work on user sessions, so may lead to some confusion, i just went through manually editing the memory backing xml etc. and only got the error when changing from 9p filesystem to virtiofs

**Comment by crobinso** [comment]
Upstream has a UI field on the Memory page 'Enable shared memory', and a Driver selection field on the Filesystem page. If the user selects virtiofs but shared memory isn't enabled, we show a warning label pointing them to the Memory page. I think that mostly covers it for now.
