### ISSUE TITLE
When using CDROM media with --graphics=none, virt-install suggests using --location with CDROM media which isn't possible

### ISSUE THREAD

**Issue by sam-cross** [virt-manager/virt-manager#135]
When creating a VM with `--graphics none` and `--cdrom` set, `virt-install` gives this warning:

```
WARNING  CDROM media does not print to the text console by default, so you likely will not see text install output. You might want to use --location. See the man page for examples of using --location with CDROM media
```

The man page doesn't actually give much information about using `--location` with CDROM media, because it does not seem to actually be supported.

**Comment by crobinso** [comment]
Thanks for the report. The current man page does have some info, see `--location` under here: https://github.com/virt-manager/virt-manager/blob/master/man/virt-install.pod#installation-options

The man page text has diverged a bit from when that message was added though.

What version of virt-install are you using?
What ISO are you trying to use? Whether location works for an ISO or not is dependent on whether there's a bootable kernel on the ISO, and virt-install knows where to find it

**Comment by mdebord-dlr** [comment]
>  https://github.com/virt-manager/virt-manager/blob/main/man/virt-install.pod#installation-options

That's a 404 now. Do you have an updated link by chance?

**Comment by ptoscano** [comment]
> > https://github.com/virt-manager/virt-manager/blob/master/man/virt-install.pod#installation-options

https://github.com/virt-manager/virt-manager/blob/main/man/virt-install.rst#installation-options
