### ISSUE TITLE
Howto Uninstall?

### ISSUE THREAD

**Issue by bypper** [virt-manager/virt-manager#136]
Hi,
I've probed in Fedora 32, and not work.
I've installed with "**_python3 setup.py install_**" command

I want uninstall. How can I do it?

Regards,

**Comment by phrdina** [comment]
Hi, there is no uninstall method in python distutils module which we use in setup.py in virt-manager. Usually you don't want to install anything like this into your system as it will not keep track of the installed files and it's not trivial to uninstall it cleanly. For that purpose you should always use some package manager which tracks all installed files and can remove them easily.

In addition, with upstream virt-manager there is no need to install it to try it out as you can run `python3 virt-manager` directly from the git repository.

Now to solve your current situation you can run `python3 setup.py install --record files.txt` to install it again but this time you will also get the list of all installed files and you can remove them based on that list.
