### ISSUE TITLE
Unable to connect lxc

### ISSUE THREAD

**Issue by simplesand** [virt-manager/virt-manager#144]
Unable to connect to libvirt lxc:///.

Failed to connect socket to '/var/run/libvirt/virtlxcd-sock': No such file or directory

Libvirt URI is: lxc:///

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 956, in _do_open
    self._backend.open(connectauth.creds_dialog, self)
  File "/usr/share/virt-manager/virtinst/connection.py", line 172, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/lib/python3/dist-packages/libvirt.py", line 104, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/virtlxcd-sock': No such file or directory

os: kdeneon (ubuntu-20.04 as base)

**Comment by crobinso** [comment]
That error means virtlxcd and/or libvirtd service is not running. Did you intentionally try to connect to lxc or was this just first virt-manager startup?

**Comment by simplesand** [comment]
Its just first virt-manager startup message, but I found out the lxc package was not installed by default in ubuntu, by installing it solved the issue.
