### ISSUE TITLE
RFE: more use of virtio-gpu by default, possibly with 3D accel enabled

### ISSUE THREAD

**Issue by Be-ing** [virt-manager/virt-manager#146]
Continuing discussion from https://bugzilla.redhat.com/show_bug.cgi?id=1867343
The recent changes in a10d746 make configuring OpenGL significantly easier. However, it is still strange that the user has to check two different boxes in different panels, one in Display Spice and the other in Video Virtio. Is there a use case for checking the "3D acceleration" box for Video Virtio without checking the "OpenGL" checkbox in Display Spice or vice versa? If not, I think there should only be one checkbox. I suggest keeping the one in Video Virtio because I'd expect to find the configuration for 3D acceleration/OpenGL in the configuration related to video. I didn't even know what SPICE was when I first tried to configure 3D acceleration, so I didn't think to look at the Display Spice panel until I spent a while searching the web how to get OpenGL working in a VM.

**Comment by crobinso** [comment]
Thanks for the suggestion. I think there's some obscure use cases for virtio+3d without spicegl like egl-headless but we don't aim to support that in virt-manager.

I agree that moving this to a single checkbox is conceptually simpler for new users but it forces us to deal with the complexity and tradeoffs behind the scenes which I'm not interested in doing for Spice GL yet.

That said, I don't know of any downsides to enabling virtio 3D accel option by default, even if spice GL is not used. IIRC if Spice GL isn't used the 3D hardware option is effectively turned off at qemu startup anyways. So maybe we just enable this option by default when adding virtio graphics. I'll need to investigate though

Per Gerd's suggestions [here](https://www.kraxel.org/blog/2019/09/display-devices-in-qemu/) virt-manager should be using virtio video as default for far more cases than we do today. I'll repurpose this issue to track that change, and the 3D accel default can be included.

**Comment by Be-ing** [comment]
Enabling 3D acceleration for virtio by default seems to me like a good improvement. Then users will only need to enable one checkbox.

**Comment by crobinso** [comment]
I made changes upstream to use virtio-gpu by default more often (when the guest OS supports it basically). But in the mean time, using virtio 3d/spice gl by default is less likely. Spice and virgl development have slowed. the GL bits in qemu have also been modularized which means it's more likely to have a distro provided qemu build which doesn't pull in the GL support by default, and libvirt doesn't have any mechanism to report to us when GL is available or not so we don't know whether it's safe to hardcode enabling it. Also there's still regular reports about spice GL having graphical issues and being unstable.

So I think more use of virtio-gpu is all we are changing in virt-manager for the foreseeable future
