### ISSUE TITLE
virt-manager misses search/filter functionality for VMs

### ISSUE THREAD

**Issue by bjacke** [virt-manager/virt-manager#147]
if you have a server with many VMs, then it would be extremely helpful, if virt-manager would allow to search/filter the listed VMs. If I have for exemple 100 VMs on the server and I want to find the VMs that contain the string "rhel", then I would like to see be able to apply a filter and then only see the matching VMs. This is an feature that I miss ever since I started using with virt-manager.

**Comment by crobinso** [comment]
Thanks for the suggestion. There is some stock built in search functionality already provided by GTK. ctrl+f in the list brings up a search box, which will search from the start of the VM name. So if your VMs have a consistent 'rhel-' prefix you could search 'rhel-' then use up and down arrows to jump through the results. Coupled with VM titles which lets you configure the way the machine is labelled in the manager window that gives a moderate amount of searching power.

Generally though while virt-manager aims to work fine for the 100 VM case we don't plan to add any features specifically to enable that case, see [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md) for more details. So I don't expect things to change in this area.

I will update the DESIGN.md document with details about the existing search support

**Comment by bjacke** [comment]
thanks for the answer, even though I have to admint that I'm disapointed about the design decision not to implement a search, that matches also substrings. This makes the usablility much worse for many setups.
