### ISSUE TITLE
RFE: Command line option to run virt-manager in the system tray

### ISSUE THREAD

**Issue by nmdnm** [virt-manager/virt-manager#149]
Please add a command line option to run virt-manager in the system tray, this would be useful for those who add virt-manager to autostart

**Comment by crobinso** [comment]
Thanks for the suggestion, I agree this would be useful. We could just call it `--show-systray`, someone could follow `--show-domain-creator` implementation as an example, it would likely only require changes to `virtManager/virtmanager.py` and `virtManager/engine.py`

**Comment by yochaigal** [comment]
I would very much like to see this as well!

**Comment by xfgusta** [comment]
Hi @crobinso. I have implemented this option, but I don't know if I did it correctly, although it's working fine here. It even works without the `--connect` option. I'm using the [`_show_systray` function](https://github.com/virt-manager/virt-manager/blob/master/virtManager/systray.py#L457) to launch virt-manager in the system tray.

https://user-images.githubusercontent.com/66979446/140652828-bddc95ce-7bb2-4476-8f8b-789e9b3fee72.mp4

**Comment by yochaigal** [comment]
@xfgusta did you make pull request? I'd love to test this out for you (Arch, GNOME).
Thanks!

**Comment by xfgusta** [comment]
Hi @yochaigal. I did not open a Pull Request yet, but I have a fork of this repository with a branch with this feature. You can clone it by running `git clone https://github.com/xfgusta/virt-manager` and checkout the branch with `git checkout show-systray-option`.

**Comment by crobinso** [comment]
@yochaigal Thanks for taking a stab at this! Please submit a PR and I will review the code there

**Comment by brendenhoffman** [comment]
> Hi @yochaigal. I did not open a Pull Request yet, but I have a fork of this repository with a branch with this feature. You can clone it by running `git clone https://github.com/xfgusta/virt-manager` and checkout the branch with `git checkout show-systray-option`.

Please make a pull request in the main branch

**Comment by AdrianVollmer** [comment]
I'd love to have this feature, so to move this forward  I went ahead and created a PR on behalf of @xfgusta. Hope you don't mind!

PR: #505

**Comment by jorkanofaln** [comment]
Can someone approve this pull request or at least review it? I think issue can be closed, when https://github.com/virt-manager/virt-manager/pull/505 gets merged into master.

**Comment by crobinso** [comment]
This is fixed in git now, the option is `--show-systray`

**Comment by crobinso** [comment]
courteousy of @AdrianVollmer
