### ISSUE TITLE
Minor gripe in New VM UI

### ISSUE THREAD

**Issue by Toolybird** [virt-manager/virt-manager#159]
**Distro**: Arch (running latest virt-manager from git).

Aside: Good work on the latest release! I love the new --xml option to virt-install. It's super useful.

This report is about a minor UI glitch that's bugged me for a while.

If I select an iso file during the New VM Wizard, the OS is detected properly.

If I cancel out of the Wizard then go back and start again, the iso is still selected but the OS is seemingly not detected. It displays "Waiting for install media..". I have to then go and choose a *different* iso, then back to the original iso to force the re-detection.

EDIT - Doh! Just realised if I hit "Forward" it will actually do the detection anyway.

Like I said - it's very minor. Nevertheless, if you can fix it easily... Thanks.

**Comment by crobinso** [comment]
Thanks for the suggestion. The more inconsistent bit here is that we keep the iso value filled in, it's the pattern of the rest of the dialog to reset to fresh state when we re-run the dialog.

**Comment by crobinso** [comment]
We now empty the CDROM field across 'New VM' runs. Sorry I realize that likely isn't what you wanted but it's most consistent with the behavior of the other parts of the dialog
