### ISSUE TITLE
Q: Network Interfaces tab in Connection settings

### ISSUE THREAD

**Issue by lamka02sk** [virt-manager/virt-manager#160]
Where did the Network Interfaces in Connection settings go? I noticed, that on my laptop with version 1.5.1 has it, but other 2 PCs with newer version do not. Was it removed, or are just some packages missing on other systems?
Thanks!

**Comment by crobinso** [comment]
It was removed: https://blog.wikichoon.com/2019/04/host-network-interfaces-panel-removed.html
