### ISSUE TITLE
Arch - Unable to launch virt-manager

### ISSUE THREAD

**Issue by danechambers** [virt-manager/virt-manager#164]
**Distro**: Arch
Hello. I have resolved my issue myself so please feel free to close this whenever you like. But I think this is still worth explaining a bit more in detail here (it took me several hours to work it out for myself DX ). 

I've read over issue #87  a bit but I'm still having trouble getting the application to launch. Looking over the documentation for gi repository, the link provided in issue 87 ([https://packages.ubuntu.com/bionic/gir1.2-libvirt-glib-1.0](https://packages.ubuntu.com/bionic/gir1.2-libvirt-glib-1.0)) and my own currently installed packages:

```
Name            : gobject-introspection-runtime
Version         : 1.66.1-1
Description     : Introspection system for GObject-based libraries (runtime library)
Architecture    : x86_64
URL             : https://wiki.gnome.org/Projects/GObjectIntrospection
Licenses        : LGPL  GPL
Groups          : None
Provides        : libgirepository-1.0.so=1-64

Name            : libvirt-glib
Version         : 3.0.0-1
Description     : libvirt-glib wraps libvirt to provide a high-level object-oriented API better suited for glib-based applications
Architecture    : x86_64
URL             : https://libvirt.org/
Licenses        : None
Groups          : None
Provides        : None

```
I dug into the files provided by the gir library for arch [https://www.archlinux.org/packages/extra/x86_64/gobject-introspection-runtime](https://www.archlinux.org/packages/extra/x86_64/gobject-introspection-runtime)
```
Files in package:
gobject-introspection-runtime /usr/
gobject-introspection-runtime /usr/lib/
gobject-introspection-runtime /usr/lib/girepository-1.0/
gobject-introspection-runtime /usr/lib/girepository-1.0/DBus-1.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/DBusGLib-1.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/GIRepository-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/GL-1.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/GLib-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/GModule-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/GObject-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/Gio-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/Vulkan-1.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/cairo-1.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/fontconfig-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/freetype2-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/libxml2-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/win32-1.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/xfixes-4.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/xft-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/xlib-2.0.typelib
gobject-introspection-runtime /usr/lib/girepository-1.0/xrandr-1.3.typelib
gobject-introspection-runtime /usr/lib/libgirepository-1.0.so
gobject-introspection-runtime /usr/lib/libgirepository-1.0.so.1
gobject-introspection-runtime /usr/lib/libgirepository-1.0.so.1.0.0
```
I noticed that LibvirtGLib-1.0.typelib is not in this list. However, it _**is**_  in the libvirt-glib package [https://www.archlinux.org/packages/community/x86_64/libvirt-glib](https://www.archlinux.org/packages/community/x86_64/libvirt-glib)

For some reason, even though I had both the gir package and the libvirt-glib package installed, the typelib files did not make it into the girepository. If you're still getting this error, please try uninstalling libvirt-glib, ensuring you have gobject-introspection-runtime installed, then re-installing libvirt-glib. Hopefully that works. If not, you can also build the libvirt-glib project from source [https://gitlab.com/libvirt/libvirt-glib](https://gitlab.com/libvirt/libvirt-glib) which will give you the typelib files for each library.

Hopefully this will save a few people some trouble in the future. Good luck.

**Comment by crobinso** [comment]
Thanks for the info
