### ISSUE TITLE
Memory, Disk, and I/O Graphs Disabled

### ISSUE THREAD

**Issue by ecnepsnai** [virt-manager/virt-manager#167]
**Distro**: Fedora 33 Beta, also reproducible on git master

Some of the graphs options are disabled from the view menu but no reason is given, and I'm not sure what I need to do in order to enable these options?

![virtmanager](https://user-images.githubusercontent.com/1607109/96302552-e2935f80-0fad-11eb-9966-ec7c6540e443.png)

I'm connecting via SSH to the host, which is running CentOS 8.2 with libvirt 4.5.0-42.module_el8.2.0+320+13f867d7

If this is intended behaviour, could we improve the user experience by explaining what they need to do to enable these features?

**Comment by crobinso** [comment]
They are disabled because polling is disabled in the app 'Preferences' dialog. It defaults to that to save unnecessary CPU and network traffic. If you hover over the disabled menu item a tooltip will pop up that mentions this
