### ISSUE TITLE
Libvirt connection does not support snapshots

### ISSUE THREAD

**Issue by volker-raschek** [virt-manager/virt-manager#170]
Hey folks, 
I installed version 3.1.0. Since that version I can not rollback snapshots over virt-manager. The icon is greyed out with the information "Libvirt connection does not support snapshots".

Why the hell does the Libvirt connection suddenly not support snapshots anymore? 

Many greetings
Volker

Distribution: Arch Linux

```bash
$ uname -a
Linux markus-pc 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linu
```

```bash
$ pacman --query --explicit | grep --perl-regexp '(virt|qemu)'
libvirt 6.8.0-3
qemu 5.1.0-1
qemu-arch-extra 5.1.0-1
virt-install 3.1.0-1
virt-manager 3.1.0-1
virt-viewer 8.0-2
virtio-win 0.1.189.1-1
```

**Comment by JulienDlq** [comment]
I have the same issue on my gentoo, and I filled the following bugreport: https://bugs.gentoo.org/747871
The issue here seems that virt-manager is not compatible with libvirt and especially libvirt-python 6.8.0.
I downgraded libvirt and libvirt-python to 6.7.0, then virt-manager 3.1.0 was able to manage snapshots then!

**Comment by Toolybird** [comment]
Yes, libvirt-python-6.8.0 is bugged. Fix already applied upstream [1]. Distros will need to cherry pick the fix. See also [2]

[1] https://gitlab.com/libvirt/libvirt-python/-/merge_requests/27
[2] https://gitlab.com/libvirt/libvirt/-/issues/86#note_430292027

**Comment by crobinso** [comment]
Thanks @Toolybird, yes this is a libvirt-python regression and not something that to be fixed in virt-manager, so I'm closing this issue
