### ISSUE TITLE
Not "releasing" libvirtd connection upon disconnect

### ISSUE THREAD

**Issue by Toolybird** [virt-manager/virt-manager#172]
**Distro**: Arch

This is only a minor issue and might even be a libvirt problem. Is easily reproduced for me with latest virt-manager git. It never used to do this so it seems like a recent regression.

libvirtd is using default settings (systemd socket activation with LIBVIRTD_ARGS="--timeout 120")

The problem: libvirtd never stops after timeout even though virt-manager has been "right click disconnected" from the QEMU/KVM uri. To trigger this you have to go to the "Connection Details" window (where Overview, Virtual Networks, Storage tabs are showing), then back out. Nothing unusual showing in the virt-manager log:

```
[Sun, 25 Oct 2020 17:47:51 virt-manager 12280] DEBUG (storage:139) Found default pool name=default target=/var/lib/libvirt/images
[Sun, 25 Oct 2020 17:47:51 virt-manager 12280] DEBUG (connection:482) conn=qemu:///system changed to state=Active
[Sun, 25 Oct 2020 17:47:53 virt-manager 12280] DEBUG (host:85) Showing host details: <vmmConnection uri=qemu:///system id=0x7efff95de540>
[Sun, 25 Oct 2020 17:47:53 virt-manager 12280] DEBUG (engine:316) window counter incremented to 2
[Sun, 25 Oct 2020 17:50:14 virt-manager 12280] DEBUG (host:96) Closing host window for <vmmConnection uri=qemu:///system id=0x7efff95de540>
[Sun, 25 Oct 2020 17:50:14 virt-manager 12280] DEBUG (engine:323) window counter decremented to 1
[Sun, 25 Oct 2020 17:50:16 virt-manager 12280] DEBUG (connection:837) conn.close() uri=qemu:///system
[Sun, 25 Oct 2020 17:50:16 virt-manager 12280] DEBUG (connection:482) conn=qemu:///system changed to state=Disconnected
```
Closing virt-manager completely then allows libvirtd to timeout and shutdown.

**Comment by crobinso** [comment]
Hmm interesting. Can you run `virt-manager --debug --test-options=leak-debug` and see if after closing the connection there's a 'LEAK' string in a log message. I think that will explain the behavior but not narrow down what the issues is.

FWIW I tried to reproduce it myself, I reproduced it the first try, but then every subsequent attempt did not report a leak so I didn't get to explore it more than that

**Comment by Toolybird** [comment]
Yeah, LEAK shows up:
```
[Wed, 04 Nov 2020 17:57:31 virt-manager 12867] DEBUG (host:96) Closing host window for <vmmConnection uri=qemu:///system id=0x7fc8fb713f80>
[Wed, 04 Nov 2020 17:57:31 virt-manager 12867] DEBUG (engine:323) window counter decremented to 1
[Wed, 04 Nov 2020 17:57:51 virt-manager 12867] DEBUG (connection:837) conn.close() uri=qemu:///system
[Wed, 04 Nov 2020 17:57:51 virt-manager 12867] DEBUG (connection:876) LEAK: conn close() returned 1, meaning refs may have leaked.
[Wed, 04 Nov 2020 17:57:51 virt-manager 12867] DEBUG (connection:482) conn=qemu:///system changed to state=Disconnected
```

**Comment by crobinso** [comment]
Okay. Can you reproduce again with virt-manager --debug --test-options=leak-debug --trace-libvirt=all and pastebin the full output? But make sure it triggers the LEAK before posting.

Does the LEAK reproduce 100% reliably for you or is it variable?

**Comment by Toolybird** [comment]
> Does the LEAK reproduce 100% reliably for you

Yes, every time (but only when I go to the Details windows of the connection)

> pastebin the full output

Here you go, thanks for looking into it:

https://gist.github.com/Toolybird/b7cf7acc4163c74f3a5d127114761811

**Comment by crobinso** [comment]
Can you see if this branch fixes the issue?

```
git clone https://github.com/crobinso/virt-manager
cd virt-manager
git checkout test
./virt-manager --debug
```

**Comment by Toolybird** [comment]
Yes, that fixes it. Thanks a lot!
