### ISSUE TITLE
AAVMF32_CODE.fd as UEFI bianry in Debian

### ISSUE THREAD

**Issue by emojifreak** [virt-manager/virt-manager#174]
The following code relates architectures and UEFI binary names:

https://github.com/virt-manager/virt-manager/blob/d0650aa48fd52a7c52c673ab19bd6ccbe5351d74/virtinst/domcapabilities.py#L179-L204

On the other hand, Debian has `AAVMF32_CODE.fd` as its UEFI binary of armv7l as shown at https://packages.debian.org/sid/all/qemu-efi-arm/filelist . The current vert-install does not recognize it, and show the following error by virt-manager:

![screenshot](https://user-images.githubusercontent.com/53028623/97989676-38775c80-1e22-11eb-84c4-29e96958ea2d.png)

The following patch fixes this issue

```
--- usr/share/virt-manager/virtinst/domcapabilities.py-orig	2020-09-14 23:37:35.000000000 +0900
+++ usr/share/virt-manager/virtinst/domcapabilities.py	2020-11-03 16:57:18.523204300 +0900
@@ -194,6 +194,7 @@
             r".*edk2-aarch64-code\.fd",  # upstream qemu
         ],
         "armv7l": [
+            r".*AAVMF32_CODE\.fd",  # Debian
             r".*arm/QEMU_EFI.*",  # fedora, gerd's firmware repo
             r".*edk2-arm-code\.fd"  # upstream qemu
         ],
```

**Comment by crobinso** [comment]
Thanks. Can you submit that patch as a PR? I will test and accept it

**Comment by emojifreak** [comment]
Thank you. I made PR #176
