### ISSUE TITLE
NC (ncat) error connecting to remote host

### ISSUE THREAD

**Issue by kinshakov** [virt-manager/virt-manager#184]
_Unable to connect to libvirt qemu+ssh://root@192.168.66.27/system.
End of file while reading data: sh: line 1:   647 Segmentation fault      (core dumped) nc $ARG -U /var/run/libvirt/libvirt-sock: Input/output error
Verify that the 'libvirtd' daemon is running on the remote host._

libvirtd is running for sure.
**ln -sf /usr/bin/ncat /bin/nc**  on the remote host was done. Didn't help.

**Distro**: Arch Linux, kernel 5.9.6-arch1-1.
**Virt-manager version**: 3.1.0

**Comment by crobinso** [comment]
If nc is segfaulting on the remote host there's nothing virt-manager can do about that. If it's happening when connecting to the libvirt connection then file a bug against your distro's libvirt or nc package
