### ISSUE TITLE
Question/RFE: does --boot network,uefi support OVMF's HTTPv4/HTTPv6

### ISSUE THREAD

**Issue by space88man** [virt-manager/virt-manager#187]
**Distro**: Fedora 33 3.1.0, edk2-ovmf-20200801stable

Is there a way to get `--boot` to invoke UEFI HTTPv4/HTTPv6 network boot support?

**Comment by crobinso** [comment]
No as far as I know there's no way to insert data like that into VM UEFI from libvirt/qemu config. So you'll need to trigger it from inside the VM uefishell or similar
