### ISSUE TITLE
Unable to unistall virt-manager 3.x.x

### ISSUE THREAD

**Issue by BeFrankly** [virt-manager/virt-manager#188]
Hello,

I am running an Ubuntu 18.04 LTS system that is nearly up to date. Because an advice from someone to use the XML Tabpage in virt-manager to directly edit the XML i found out, that the ubuntu package only contains the 1.x.x. version. So I decided to test and install the newest virt-manger 3.x.x. First I started it directly and it seems to work. But when I highlight the drive in detail page I get an error. 

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/details/details.py", line 1714, in _refresh_page
    self._refresh_disk_page(dev)
  File "/usr/share/virt-manager/virtManager/details/details.py", line 2007, in _refresh_disk_page
    self._addstorage.set_dev(disk)
  File "/usr/share/virt-manager/virtManager/device/addstorage.py", line 327, in set_dev
    self.widget("disk-removable").set_active(removable)
TypeError: Argument 1 does not allow None as a value

So I tested a bit and found out that version 3.1.x and 3.2.x got this error and 2.2.1 has not.
So I was looking for a way to uninstall 3.2.0, that i have installed with `sudo ./setup.py install` before. But there is no hint about how to uninstall. Simply trying to install 2.2.1 over 3.2.0 is not working either. When starting `sudo ./setup.py install` in the 2.2.1 folder I get 

...Generating build/bash-completion/virt-xml
running build_i18n
Writing po/POTFILES.in
intltool-update -p -g virt-manager
unable to execute 'intltool-update': No such file or directory
Removing po/POTFILES.in
error: [Errno 2] No such file or directory: 'po/POTFILES.in'

So I get stuck here. As well there where problems with choosing the right intltool package. In Ubuntu, there is a intltool and an intltool-debian package. Wich one to choose. The last one is maintained by ubuntu.

Any idea if its a bug our a user problem?

**Comment by crobinso** [comment]
That first backtrace is a bug in virt-manager. Older pygobject can't handle a set_active(None) but the newer version I code against treats it like set_active(False). I fixed that instance in git now, please retest.

The `intltool-update` issue is a missing distro package but I don't know which one, I use Fedora. I don't generally recommend doing 'python3 setup.py install` anyways because it involves solving these cross distro issues. It's better IMO to just run it from the git directory
