### ISSUE TITLE
Should --noreboot be implied with --cloud-init?

### ISSUE THREAD

**Issue by kparal** [virt-manager/virt-manager#189]
I always found it weird that `virt-install` reboots the VM even if I do a poweroff in the installer. However, with `--cloud-init`, it makes double no-sense to me. There is no installation happening. Yes, there are a few things configured on the first boot, but that very boot gives you a fully functional VM you can immediately use. So why does `virt-install` reboot it when I want to shut it down? It's very confusing. I start up a new cloud VM, do the work I wanted, shut it down, and... it's still running.

Perhaps `--cloud-init` could imply `--noreboot`? Thanks.

**Distro**: Fedora 33, virt-install-3.2.0-1.fc33.noarch

**Comment by crobinso** [comment]
Yes I agree. Internally we have a notion of 'has_install_phase' which is used both for performing post install boot, and for setting the post install XML. cloud-init needs the latter but not the former, so we need to decompose these two pieces. It was more work than I was comfortable doing for a bug fix release after fixing your previous bug
