### ISSUE TITLE
remote viewer is autoamtically changing resolution to uncorrenct values.

### ISSUE THREAD

**Issue by Mlocik97** [virt-manager/virt-manager#192]
**Distro**: Ubuntu 20.04
virt-manager: 2.2.1
remote viewer: 7.0

Hello, if I use virt-manager graphic console, resolution work as supposed (have it set to 1920x1080 on my 1920x1080 display)...

but when I use remote viewer, resolution automatically change to 1848x958 (in fullscreen on 1920x1080 display), and it automatically change resolution depending on Windows size (for example when I'm not in fullscreen and resize window to half size, I get resolution 1104x609), but I want it to set on 1920x1080 always...

Is there way to have it like in virt-manager?

**Comment by phrdina** [comment]
Hi, remote-viewer is part of virt-viewer project https://gitlab.com/virt-viewer/virt-viewer where you should create a new issue to add an option to disable the automatic resolution based on the remote-viewer windows size. I checked quickly and it doesn't look like there is an option to disable it.

You can, however, disable spice-vdagentd.service or remove the spice-vdagent package completely as this is the VM side part of this feature.

**Comment by Mlocik97** [comment]
Thanks for answer,.. about that vdagentd.service, if I know, it add other features as well (like ability to move files between host and VM, or some other things). Is that true? If yes, then I don't know if I want to remove that package.

**Comment by phrdina** [comment]
Correct, it does more then the automatic resolution. In that case you'll have to live with the fact that it changes it until the option to control it is implemented in virt-viewer/remote-viewer.

As far as I know there is nothing else that can be done right now.
