### ISSUE TITLE
Should improve the common grammar for 1 minute(singular form) and 2 minutes(Plural form) usage for "--wait" option

### ISSUE THREAD

**Issue by celery2011** [virt-manager/virt-manager#196]
When I  Install a vm with "--wait 1", it will show "Waiting 1 minutes for installation to complete." , the word minute is in plural form, I think it should be in singular form , thanks.

\# virt-install --memory 2048 --disk  /var/lib/libvirt/images/rhel8.3-av.qcow2  --import --wait 1
Using default --name vm1
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
Gtk-Message: 03:50:00.448: Failed to load module "pk-gtk-module"
Gtk-Message: 03:50:00.466: Failed to load module "pk-gtk-module"
Domain installation still in progress.
Waiting 1 minutes for installation to complete.

...
Installation has exceeded specified time limit. Exiting application.

**Comment by ptoscano** [comment]
Which version of virt-manager you are using? I did many i18n fixes few months ago, and the commit 6f30ab2437b9f6bae424b5ce67603a23de33ecda was the one fixing this plural form, available in virt-manager 3.0.0.

**Comment by celery2011** [comment]
Hi ptoscano,
I used the downstream virt-manager version to test.

virt-manager-common-2.2.1-4.el8.noarch
virt-install-2.2.1-4.el8.noarch

And I will try upstream version as you said, thanks.

**Comment by celery2011** [comment]
Hi ptoscano,
Yes, you're right, this issue has been fixed on upstream.

Test with upstream version:
virt-manager-3.1.0-1.fc33.noarch

Steps:
1. Test with --wait 1 
$ sudo virt-install --memory 2048 --disk /var/lib/libvirt/images/rhel8.3-av.qcow2,size=9 --location http://download.eng.pek2.redhat.com/rhel-8/rel-eng/RHEL-8/RHEL-8.3.0-20201009.2/compose/BaseOS/x86_64/os/  --wait 1
Using default --name rhel8.3-2

...

Domain is still running. Installation may be in progress.
**Waiting 1 minute for the installation to complete.**

2. Test with --wait 2 
$ sudo virt-install --memory 2048 --disk /var/lib/libvirt/images/rhel8.3-av.qcow2,size=9 --location http://download.eng.pek2.redhat.com/rhel-8/rel-eng/RHEL-8/RHEL-8.3.0-20201009.2/compose/BaseOS/x86_64/os/  --wait 2
Using default --name rhel8.3-2
...
Domain is still running. Installation may be in progress.
**Waiting 2 minutes for the installation to complete.**

So I get the expected result with the upstream version, thanks.
