### ISSUE TITLE
virt-manager fails to open

### ISSUE THREAD

**Issue by McFrag** [virt-manager/virt-manager#197]
![image](https://user-images.githubusercontent.com/75093941/100385841-7d12a400-302c-11eb-9f61-f9c592262957.png)

File "/usr/share/virt-manager/virtManager/config.py", line 53, in __init__
    backend = Gio.SettingsBackend.get_default()
AttributeError: type object 'SettingsBackend' has no attribute 'get_default'

OS: Debian GNU/Linux 9.13 (stretch)

Searched for "type object 'SettingsBackend' has no attribute 'get_default'" (in quots) 
Google finds nothing. Don't have a clue where to start

**Comment by crobinso** [comment]
What are the glib2 and pygobject version on your host?

**Comment by McFrag** [comment]
> What are the glib2 and pygobject version on your host?

2.50.3-2+deb9u2

**Comment by crobinso** [comment]
That glib version is almost 4 years old, but it should be new enough to provide the backend_get_default API. Could be pygobject age issue. I don't know the name of that offhand on debian. On fedora it was called pygobject3, then python3-gobject. Upstream it is called pygobject

**Comment by McFrag** [comment]
@crobinso 
Thanx. I'll see what I can find about it.
> That glib version is almost 4 years old, but it should be new enough to provide the backend_get_default API. Could be pygobject age issue. I don't know the name of that offhand on debian. On fedora it was called pygobject3, then python3-gobject. Upstream it is called pygobject

**Comment by crobinso** [comment]
Closing this, but feel free to reopen if you are still hitting issues
