### ISSUE TITLE
Import an existing virtual machine

### ISSUE THREAD

**Issue by makgab** [virt-manager/virt-manager#198]
Hi!
Can I import an existing virtual machine?
I created a VM: `virt-install --name=fcos \
--vcpus=2 \
--ram=2048 \
--import \
--network=bridge=virbr0 \
--graphics=none \
--qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${PWD}/config.ign" \
--disk=size=20,backing_store=${PWD}/fedora-coreos-32.20200907.3.0-qemu.x86_64.qcow2`
I cannot see it in virt-manager.

**Distro**: Fedora 33 x64

**Comment by crobinso** [comment]
If you ran virt-install under a non-root account, the VM was created on the qemu:///session connection, but virt-manager uses qemu:///system by default. Add qemu:///session via the File->Add Connection  and you should see your VM. More info about session vs system here: https://blog.wikichoon.com/2016/01/qemusystem-vs-qemusession.html
