### ISSUE TITLE
How to achieve vga=none with virt-manager ?

### ISSUE THREAD

**Issue by dpatel257** [virt-manager/virt-manager#201]
It is not an issue but looking for help.
Thanks

**Comment by crobinso** [comment]
What is vga=none? Can you be more specific?

**Comment by dpatel257** [comment]
We can close it as eventually got it working with editing the XML file with 'virsh edit'.
Appreciate your help.

**Comment by crobinso** [comment]
@dpatel257 Can you share your solution incase anyone else ends up here through google?

**Comment by dpatel257** [comment]
- Get the list of inactive VMs. Make sure the VM you are trying to modify is inactive and shows up in the list below:

    `virsh list –inactive`

- Edit VM config using virsh. Change the video type to “none”.

```
virsh edit <NAME_OF_THE_VM>
<video>
     <model type='none'/>
</video>
```

**Comment by crobinso** [comment]
FWIW you can type `none` into the Video model box in the virt-manager UI to make that work

**Comment by tacerus** [comment]
Thank you both! Exactly what I was looking for.
