### ISSUE TITLE
Auto-start checkbox in VM gets unchecked after renaming VM

### ISSUE THREAD

**Issue by gollum53** [virt-manager/virt-manager#204]
**Distro**: <Ubuntu server 20.04>
Bug: The "Start virtual machine on host boot up" checkbox gets unchecked after renaming VM.

Steps to reproduce:
- Start virtmanager and select a shut-down (not running) virtual machine on another KVM/QEMU hypervisor connected over ssh.
- Open the Show virtual hardware details tab - Boot options and verify that the "Start virtual machine on host boot up" checkbox is checked. If it is not, check it and click Apply.
- Go to Overview, rename the VM, click Apply.
- Close the window and entire virt-manager.
- Run virt-manager again, open the remote hypervisor and see if the checkbox is checked. It is not.

Expected behavior: Leave the checkbox in previous state.

**Comment by crobinso** [comment]
Thanks for the report. Yes this kinda expected given how we implement domain rename, which is basically undefine+define API calls. If we use the virDomainRename API then this will work correctly for the qemu driver but not the other drivers. It shouldn't be too hard to implement fix this for our virt-manager implementation.
