### ISSUE TITLE
Default Win10 OS settings, lead to slow VM performance.

### ISSUE THREAD

**Issue by tkontogi** [virt-manager/virt-manager#205]
**Software environment**
**Host**:
Operating system: CEntOS7 7.9.2009
Architecture: X86-64
kernel version: 3.10.0-1169.6.1.el7.x86_64
libvirt version: libvirt-4.5.0-36.el7_9.3.x86_64
Hypervisor and version: qemu-kvm-ev-2.12.0-44.1.el7_8.1.x86_64

**Virt-Manager**: Host is accessed from Fedora 33 using virt-manager-3.2.0-1.fc33.noarch

**Description of problem**

**Steps to reproduce**
Create and install a Win10 guest
Run Win10 guest
Load goes off the roof
Make suggested changes
Restart guest
Load goes really low

**Additional information**

Default Win10 xml (when creating the guest and defining it as Win10) is the following:
```
 <clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
    <timer name='hypervclock' present='yes'/>
  </clock>
```
The load of the host goes off the roof even with the guest idle.

Changing to:
``` 
 <clock offset='localtime'>
    <timer name='hpet' present='yes'/>
    <timer name='hypervclock' present='yes'/>
  </clock>
```
Host's load goes down to expected acceptable levels when Win10 guest is idle (or even loaded).

The fix looks to solve the problem for all Windows guests.

Maybe a virt-manager issue, related to default settings on VM creation?

Initially reported: https://gitlab.com/libvirt/libvirt/-/issues/110
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=742736
External ref: https://www.reddit.com/r/VFIO/comments/80p1q7/high_kvmqemu_cpu_utilization_when_windows_10/

**Comment by crobinso** [comment]
Thanks for the report.

That XML changes 3 settings. Have you tried narrowing it down to one specific change?
For exmaple, I'm pretty sure on Centos7 -no-hpet is the default and the CLI option is ignored, so hpet is not available for qemu at all. So I doubt that hpet bit is responsible. It would be nice to figure out what other bit is responsible.

Is this after host suspend resume? Is the VM manually 'paused' at all? Or is this reproducible after fully powering off the VM and then restarting it.

To eliminate this as a qemu or kvm bug it would be helpful to try this on a newer platform, something like a modern Fedora.

**Comment by crobinso** [comment]
No response, closing

**Comment by labrat97** [comment]
What happens on my system is a CLOCK_WATCHDOG_TIMEOUT causing a bluescreen. Making the PIT play catchup helps, but causes some program crashes at high load or high shared core load. Enabling the HPET seems to keep Windows' watchdog at bay.

**Comment by zewebdev1337** [comment]
upwards of 3 years since this was report was opened and it is still both an issue and the main behavior. 
Completed status false as well, this is not completed nor was even addressed.  I understand the person did not reply, that doesn't result in a "Completed" status imo. I can perform the required tests and info for reproduction and fix if needed.

**Comment by SaladinoGW** [comment]
Same problem. Unfortunately the fix don't worked for me.

**Comment by bughunter2** [comment]
I noticed high CPU usage on various guests, both on Windows and Linux guests. The systems usually booted quite slowly, or at least slower than one would expect. Also, CPU usage remained high, even when the guest should be idling.

For me, these steps **solved** it:

```
  1. Set the VM's hypervisor to KVM.

     To do this, you may need to enable XML editing (temporarily) in virt-manager's Preferences.

     The first line in the virtual machine's XML configuration usually starts with ...:

         <domain type="qemu">

     Change it to:

         <domain type="kvm">

     This changes the hypervisor from 'QEMU TCG' to 'KVM'.

  2. RECOMMENDED EXTRA STEP, since this is the default when creating a new KVM virtual machine:

     In the VM's CPU settings, you can now ...:

         Enable the 'Copy host CPU configuration' option.

     This allows the guest OS to use all CPU features, such as specialized instruction sets.
     It also means the guest OS can see the host's actual CPU model, rather than identifying
     it as a QEMU virtual CPU.

  3. Done.
```

For the developers, it might be useful to know that the host system on which I noticed this issue was using the following CPU: 13th Gen Intel(R) Core(TM) i5-1335U

Perhaps virt-manager should use KVM as the default hypervisor for all Linux and Windows guests?

On the Alpine Linux guest, I saw these messages in dmesg after the system booted, and it seems relevant:
```
[    2.632922] clocksource: timekeeping watchdog on CPU0: Marking clocksource 'tsc-early' as unstable because the skew is too large:
[    2.632922] clocksource:                       'refined-jiffies' wd_nsec: 506633632 wd_now: fffea2d8 wd_last: fffea240 mask: ffffffff
[    2.632922] clocksource:                       'tsc-early' cs_nsec: 604087333 cs_now: 3d4b18050 cs_last: 37ad22fc1 mask: ffffffffffffffff
[    2.632922] clocksource:                       Clocksource 'tsc-early' skewed 97453701 ns (97 ms) over watchdog 'refined-jiffies' interval of 506633632 ns (506 ms)
[    2.632922] clocksource:                       'jiffies' (not 'tsc-early') is current clocksource.
[    2.632922] tsc: Marking TSC unstable due to clocksource watchdog
[    2.632922] clocksource: Switched to clocksource tsc-early
[    2.644142] clocksource: Switched to clocksource refined-jiffies
```
After the Alpine Linux guest had this dramatically slow boot (3-5 minutes or so), CPU usage seemed to drop to a much lower level, although the system booted much faster when using KVM as the hypervisor instead of QEMU TCG. When using KVM as the hypervisor, the above dmesg messages did not appear.

**Comment by phrdina** [comment]
> ~Perhaps virt-manager should use KVM as the default hypervisor for all Linux and Windows guests?~ EDIT: It seems virt-manager already uses KVM as the default hypervisor, unless it's not available (I guess). And I was using VirtualBox at the same time while migrating VMs, which meant KVM wasn't always available and hence (I suspect that) virt-manager created new VMs with QEMU TCG as the hypervisor instead of KVM.

Hi @bughunter2, your issue seems to be unrelated to the original issue. In you case as you've already pointed out KVM was most likely not available and when creating new VM in virt-manager GUI there should be warning about that https://github.com/virt-manager/virt-manager/blob/main/virtManager/createvm.py#L606 .

**Comment by bughunter2** [comment]
> Hi @bughunter2, your issue seems to be unrelated to the original issue. In you case as you've already pointed out KVM was most likely not available and when creating new VM in virt-manager GUI there should be warning about that https://github.com/virt-manager/virt-manager/blob/main/virtManager/createvm.py#L606 .

Hi @phrdina Thanks for your response. I have indeed seen that error message as well, but I don't remember in what order things happened. At some point I ended up with a VM that used the QEMU TCG hypervisor. But since I solved it, I thought I'd leave a note for others as it may be useful information. All good. :slightly_smiling_face:

**Comment by phrdina** [comment]
For the original report I did some testing and it seems the issue is still present. With the default configuration that virt-manager creates for Windows VMs the host CPU usage was around 15% while the VM has less then 1% CPU usage.

Enabling hpet "fixed" the host usage but I don't think that's the correct solution. I did some investigation that got me to this QEMU documentation https://www.qemu.org/docs/master/system/i386/hyperv.html where `hv-stimer` seems to be the correct hyper-v feature to enable to fix this issue.

I will not reopen this issue as there is a different one to enable more hyper-v features by default https://github.com/virt-manager/virt-manager/issues/154 .

**Comment by phrdina** [comment]
Hi @Mushoz , can you please provide full VM XML and make sure that all Windows updates are installed and Windows OS is really idle by checking task manager?

I just installed fresh Windows 11 VM and it started installing updated right away but the CPU load inside the VM seems to correspond to the CPU load on the host.

**Comment by Mushoz** [comment]
Hi @phrdina , thanks for having a look for me! Here's a screenshot showing the CPU load both in the Windows guest and the Archlinux host:

![Image](https://github.com/user-attachments/assets/4addb5df-7eb3-479f-9389-417533154a52)

And here is the full xml:

<details>
```
<domain type="kvm">
  <name>win11</name>
  <uuid>c43abbab-640c-40f5-8842-37a1672644ff</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/11"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit="KiB">8388608</memory>
  <currentMemory unit="KiB">8388608</currentMemory>
  <vcpu placement="static">16</vcpu>
  <os firmware="efi">
    <type arch="x86_64" machine="pc-q35-9.2">hvm</type>
    <firmware>
      <feature enabled="no" name="enrolled-keys"/>
      <feature enabled="yes" name="secure-boot"/>
    </firmware>
    <loader readonly="yes" secure="yes" type="pflash" format="raw">/usr/share/edk2/x64/OVMF_CODE.secboot.4m.fd</loader>
    <nvram template="/usr/share/edk2/x64/OVMF_VARS.4m.fd" templateFormat="raw" format="raw">/var/lib/libvirt/qemu/nvram/win11_VARS.fd</nvram>
    <boot dev="hd"/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv mode="custom">
      <relaxed state="on"/>
      <vapic state="on"/>
      <spinlocks state="on" retries="8191"/>
      <vpindex state="on"/>
      <runtime state="on"/>
      <synic state="on"/>
      <stimer state="on"/>
      <frequencies state="on"/>
      <tlbflush state="on"/>
      <ipi state="on"/>
      <avic state="on"/>
    </hyperv>
    <vmport state="off"/>
    <smm state="on"/>
  </features>
  <cpu mode="host-passthrough" check="none" migratable="on">
    <topology sockets="1" dies="1" clusters="1" cores="8" threads="2"/>
  </cpu>
  <clock offset="localtime">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
    <timer name="hypervclock" present="yes"/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2" discard="unmap"/>
      <source file="/var/lib/libvirt/images/win11.qcow2"/>
      <target dev="vda" bus="virtio"/>
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw"/>
      <source file="/home/jaap/Downloads/Win11_24H2_EnglishInternational_x64.iso"/>
      <target dev="sdb" bus="sata"/>
      <readonly/>
      <address type="drive" controller="0" bus="0" target="0" unit="1"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw"/>
      <source file="/home/jaap/Downloads/virtio-win-0.1.266.iso"/>
      <target dev="sdc" bus="sata"/>
      <readonly/>
      <address type="drive" controller="0" bus="0" target="0" unit="2"/>
    </disk>
    <controller type="usb" index="0" model="qemu-xhci" ports="15">
      <address type="pci" domain="0x0000" bus="0x02" slot="0x00" function="0x0"/>
    </controller>
    <controller type="pci" index="0" model="pcie-root"/>
    <controller type="pci" index="1" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="1" port="0x10"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="2" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="2" port="0x11"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x1"/>
    </controller>
    <controller type="pci" index="3" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="3" port="0x12"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x2"/>
    </controller>
    <controller type="pci" index="4" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="4" port="0x13"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x3"/>
    </controller>
    <controller type="pci" index="5" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="5" port="0x14"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x4"/>
    </controller>
    <controller type="pci" index="6" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="6" port="0x15"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x5"/>
    </controller>
    <controller type="pci" index="7" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="7" port="0x16"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x6"/>
    </controller>
    <controller type="pci" index="8" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="8" port="0x17"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x7"/>
    </controller>
    <controller type="pci" index="9" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="9" port="0x18"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="10" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="10" port="0x19"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x1"/>
    </controller>
    <controller type="pci" index="11" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="11" port="0x1a"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x2"/>
    </controller>
    <controller type="pci" index="12" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="12" port="0x1b"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x3"/>
    </controller>
    <controller type="pci" index="13" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="13" port="0x1c"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x4"/>
    </controller>
    <controller type="pci" index="14" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="14" port="0x1d"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x5"/>
    </controller>
    <controller type="sata" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1f" function="0x2"/>
    </controller>
    <controller type="virtio-serial" index="0">
      <address type="pci" domain="0x0000" bus="0x03" slot="0x00" function="0x0"/>
    </controller>
    <interface type="network">
      <mac address="52:54:00:64:d6:07"/>
      <source network="default"/>
      <model type="virtio"/>
      <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
    </interface>
    <serial type="pty">
      <target type="isa-serial" port="0">
        <model name="isa-serial"/>
      </target>
    </serial>
    <console type="pty">
      <target type="serial" port="0"/>
    </console>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
      <address type="virtio-serial" controller="0" bus="0" port="1"/>
    </channel>
    <input type="tablet" bus="usb">
      <address type="usb" bus="0" port="1"/>
    </input>
    <input type="mouse" bus="ps2"/>
    <input type="keyboard" bus="ps2"/>
    <tpm model="tpm-crb">
      <backend type="emulator" version="2.0"/>
    </tpm>
    <graphics type="spice">
      <listen type="none"/>
      <image compression="off"/>
      <gl enable="no"/>
    </graphics>
    <sound model="ich9">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1b" function="0x0"/>
    </sound>
    <audio id="1" type="spice"/>
    <video>
      <model type="qxl" ram="65536" vram="65536" vgamem="16384" heads="1" primary="yes"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
    </video>
    <redirdev bus="usb" type="spicevmc">
      <address type="usb" bus="0" port="2"/>
    </redirdev>
    <redirdev bus="usb" type="spicevmc">
      <address type="usb" bus="0" port="3"/>
    </redirdev>
    <watchdog model="itco" action="reset"/>
    <memballoon model="virtio">
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
    </memballoon>
  </devices>
</domain>
```
</details>

Let me know if you need any additional details!

**Comment by Mushoz** [comment]
@phrdina Did you happen to have a chance to look at the provided information by any chance? This is the only real lead I have with respect to the issue I am facing, so I was hoping we could get figure out what is causing it so it can be fixed. Thanks!

**Comment by Mushoz** [comment]
Hi @phrdina , sorry for bothering you again. Did you have a look at my full XML configuration by any chance? I still have the exact same issue. Was this issue already supposed to be fixed? Because if so, it might be worthwhile for me to open a new issue. I just want to make sure I am not affected by this issue so I don't open a duplicate one.

**Comment by rdiez** [comment]
I am having exactly the same problems. I posted all details here, but I got no answer yet:

https://lists.nongnu.org/archive/html/qemu-discuss/2025-04/msg00005.html

I have tried everything. Enabling hpet does not fix the high CPU utilisation for me either. I have found many other people on the Internet who share a similar experience.
