### ISSUE TITLE
vm console spice display: ScreenReader key combinations are not grepped

### ISSUE THREAD

**Issue by ilyapashuk** [virt-manager/virt-manager#206]
ScreenReader is a program which provides an ability to use computers to the blind users.
for their work they needs to reassign behavior of some keyboard keys, mainly on a numpad.
I think they captures keys with help of the Atspi gtk module that provides an accessibility stack for linux.
may be you should consult this:
https://developer.gnome.org/accessibility-devel-guide/stable/dev-start-5.html.en
so when I m in vm's console and keyboard is grepped, system keys are cought and sent to the vm, but screenreader's - not.
when keyboard is grepped, you should disable this feature of the atk library, or by some other way make your app to not send this keys to an atspi.

**Comment by crobinso** [comment]
Thanks for the report. Do you know of any other application similar to virt-manager that works in the way you expect?
Does gnome-boxes, or virt-viewer work that way?
Something with an existing example would help me understand.

Is there a guide somewhere about setting up these screenreader keyboard keys, so I can understand more how that is supposed to work?

**Comment by ilyapashuk** [comment]
I know only virtualbox, but it uses qt.

**Comment by crobinso** [comment]
Is the screenreader app you use orca? Do you have links to any instructions how to set up these numpad shortcuts?

**Comment by ilyapashuk** [comment]
Yes it is  orca, consult atspi gtk module doxs

**Comment by crobinso** [comment]
I'm sorry I still don't think I understand. This is what I tried.

I have fedora 33 running on my host, and fedora 32 running the VM. Both using gnome-shell. In gnome-shell ctrl+win+s turns on the screenreader. When I am clicked outside the VM and I use that shortcut, the screenreader turns on in my host. When the mouse is over the VM window and I click there with the mouse, then I use the ctrl+win+s shortcut, the screenreader turns on inside the VM.

Is this the behavior you expect, or do you want something different?
If you mean something else, please provide more details about what features you map to your numpad keys.

**Comment by ilyapashuk** [comment]
the ctrl+win+s key is handled by the system itself, but screenreader has there own handling system and it's own shortcuts, working only when screenreader is on.
screenreader's handlers usually takes prezidence over system's and application's ones.
for example screenreader captures a numpad insert key during it's work and it don't switches ins/over mode yet but gets different behavior.
to test this do the following:
run orca both in the vm and in the host system
go to the vm and set focus to, for example, any file in file manager
press numpad enter key
if you hear info about that file inside the vm all works fine
if you hear something like "drawing area", "painting area" or something other unrelated to filemanager it means that host's orca caught the key.
to feel the difference try to repeat this in host directly.
we need to numpad enter key work by the same way in the vm and on the host.

also you can try insert+enter key to report the window title, if you hear vm's name when keys are grepped it works wrong.

**Comment by crobinso** [comment]
Okay I understand now. The reproducer I'm using is to enable screenreader in both host and the VM and set it to read off keystrokes, both the VM and host screenreader will respond to every letter I type.

Like you say, orca finds these keystrokes using atspi, specifically the API pyatspi.Registry.registerKeystrokeListener
You are suggesting that when the VM window has grabbed keyboard input then we should disable atspi keygrab on
the host.

I understand in your usecase why that would be useful (avoid screenreader in VM and host from conflicting). But I don't think it's safe to do unconditionally. Consider using a VM without a desktop environment in it, just a terminal. A user may still want the screenreader in the host to repeat keypresses when the VM doesn't have a screenreader at the ready. If we disable atspi unconditionally the user may have no way to get keypress feedback for those VMs. I don't know much about screenreader, or other accessibility functions, but I assume there's plenty more examples

A workaround for your particular case is: once you are connected to the VM, with the screenreader in the VM working and the VM has has keyboard focus, press ctrl+alt to release keygrab, use alt+win+s to disable screenreader in your host, then press ctrl+alt to give keyboard focus back to the VM. I realize that's not ideal, but does that work for you?

**Comment by ilyapashuk** [comment]
Yes pleas do the disabling, as a blind user i say thar this will be best, it is working by such way in all other virtualizers

**Comment by ilyapashuk** [comment]
if I will have system without ready screenReader the letters feedback will be the last about I will think. It will be useless for me without an ability to get text output from the vm, really useless.

your variant is very unsafe. try to imagine: I'm working without screenReader on the host, and any popup dialog appears on the host os, and keyboard focus jumps to it from the vm window, and we are without any feedback.
on old systems or if system is overloaded screenreader may need some time to reload.
all other virtualizers in windows in linux (VmWare, vbox) working by the way described by me.

and if I need bare terminal in the system, I will use serial console mode, of corse atspi should not be touched in such situation, only when graphical spice console is used, but always when it is true.

**Comment by crobinso** [comment]
You mentioned virtualbox. Have you seen this behavior in other apps?

I understand that disabling atspi (or whatever the required change is) is ideal for your usecase, and maybe it is what most blind users want or expect. But like I pointed out there are usecases where keeping the host screenreader working may be important for VM users. serial console doesn't work automatically in many cases, like pre-systemd distros for example.

If we change the behavior by default, the way it has always worked, are we going to break someone elses workflow? If we do, what is the workaround for them? Depends on the implementation I guess. But in your case there is at least a known and simple, if tedious, workaround.

Another option could be to write a small bash script which does:

```
gsettings set org.gnome.desktop.a11y.applications screen-reader-enabled false
virt-viewer $1
gsettings set org.gnome.desktop.a11y.applications screen-reader-enabled true
```

Which would disable the host screen reader while launching a VM console.

But honestly I don't expect this to change, not on virt-manager side. If this behavior should be the default, it should happen at the spice-gtk and gtk-vnc layer IMO, so that all apps (like virt-viewer and gnome-boxes) benefit from change.

**Comment by ilyapashuk** [comment]
Vmware works by this way too
And most windows remote xesktop clients

**Comment by crobinso** [comment]
My previous comment still stands. I don't think we will be changing anything here in virt-manager, so I'm closing this issue.
