### ISSUE TITLE
How do I disable the focus feature?

### ISSUE THREAD

**Issue by CHJ85** [virt-manager/virt-manager#207]
So I'm coming from VMWare where this didn't exist. But in VirtManager there's this annoying feature that doesn't allow me to use file menus and other apps outside the VM. Because once you click the mouse inside the VM, it's just stuck there and I have to use CTRL+Alt in order to disable it. But then I can't do anything within the VM.
This is so super annoying. How do I fix this so I can use both the VM and everything else at the same time?

**Comment by vfgfg** [comment]
https://cdn.jpth10.jpnettv.live/jptv/janimax_720/index.m3u8 off
Cdn subdomain

**Comment by crobinso** [comment]
Thanks for the report.

Do you have a virtual USB tablet device configured for the VM? This gives better mouse grab handling than the without. It should show a tablet device in the VM details hardware list.

If that doesn't fix it there's probably workarounds for your needs but it's hard to tell exactly what workflow you mean. Can you describe a scenario that used to work with vmware that does not work with virt-manager? Where is the mouse pointer located, what keystrokes are you entering, where do you intend for them to go but where do they actually go.

**Comment by CHJ85** [comment]
Well. The way Virt Manager wants exclusive right to the mouse is annoying because I can't easily copy/paste between host and guest. I have to always press ALT in order to use the host machine. In the host machine, Alt+mousewheel is for zoom. If desktop is zoomed in while I'm in the guest OS, I can't move the mouse around. It's just stuck there. And I need the zoom enabled while I read, so I can't just disable it. But why does Virt need to focus and give exclusivity like that? Why can't both host and guest be ocused at the same time like it is in VMWare?

**Comment by crobinso** [comment]
Okay based on what you are saying I don't think I can reproduce the behavior. Host distro is Fedora 33, VM distro is RHEL8. 

When the VM is open in virt-manager on logged in, I move the mouse pointer over the window, and verify that alt+scrollwheel is received and processed in the guest (using firefox which maps back/forward to that combo). I move the mouse pointer out of the VM window, over a firefoxwindow on the host machine, and verify alt+scrollwheel is working on the host window.

If that doesn't describe what you are trying, can you please be more specific what you are trying to do, and how it is not working?
If that _is_ what you are roughly trying, and it's not working, please do the following:

* Report guest and host distro
* Provide VM XML from the Overview->XML page in virt-manager VM details window
