### ISSUE TITLE
i686 UEFI booting is difficult/impossible

### ISSUE THREAD

**Issue by emojifreak** [virt-manager/virt-manager#209]
This seems somewhat similar to my previously reported issue
https://github.com/virt-manager/virt-manager/issues/174
virt-manager version is 3.2.0.
In short, on x86_64 host, 32-bit OVMF seems unable to be chosen by virt-manager GUI.

Firstly, one cannot choose `i686` architecture on x86_64 host, as:

![Screenshot from 2021-01-09 10-48-44](https://user-images.githubusercontent.com/53028623/104080270-4efac380-526a-11eb-8fa6-17b77d9bcd1d.png)

This restriction comes from:
https://github.com/virt-manager/virt-manager/blob/60ecc1c22301ea3796281c2e2237e1fe01a7e221/virtManager/createvm.py#L780-L783

By directly running qemu-system-i386 with 32-bit OVMF, my disk image can start with no problem. But with virt-manager GUI, I cannot choose 32-bit OVMF (on Debian testing) as

![Screenshot from 2021-01-09 10-50-56](https://user-images.githubusercontent.com/53028623/104080347-b31d8780-526a-11eb-8b07-690a658a91bd.png)

This restriction comes from:
https://github.com/virt-manager/virt-manager/blob/60ecc1c22301ea3796281c2e2237e1fe01a7e221/virtinst/domcapabilities.py#L182-L205

Then, the 64-bit OVMF does not recognize 32-bit UEFI diskimage or CDROM as bootable one...

Does virt-manager support 32-bit i686 UEFI booting? QEMU supports it.

**Comment by crobinso** [comment]
Thanks for the report, but this is not something we plan to explicitly support in virt-manager's UI: 32-on-64 x86 is quite niche, and supporting it would require adding extra elements to the UI like the arch selector, and extra firmware entries, would could mislead users who just want x86_64.

If you know you want this, set up x86_64 + ovmf VM, but before starting the install, you can try editing the XML and changing the arch= and loader path to point to i686 variants. I haven't tried it, but something like that should work.

**Comment by emojifreak** [comment]
Thank you for your response. I understood this as a feature, and have no objection.
