### ISSUE TITLE
remot login via qemu+ssh: as root fails after update to 3.2.0-4.1 from -3.1 on opensuse tumbleweed

### ISSUE THREAD

**Issue by ulilaube** [virt-manager/virt-manager#210]
Hi!

Last friday I updated my local machine to 3.2.0. It runs opensuse tumbleweed 20210108.

```
$ rpm -qa -last | grep -Fi virt
virt-manager-3.2.0-4.1.noarch                 Fr 08 Jan 2021 15:14:09 CET
virt-install-3.2.0-4.1.noarch                 Fr 08 Jan 2021 15:14:08 CET
virt-manager-common-3.2.0-4.1.noarch          Fr 08 Jan 2021 15:14:07 CET
```
The remote VM host foobar runs CentOS 8.2 and has not been changed last week. Last week I was able to login to the remote host via the command line:

`$ virsh --connect qemu+ssh://root@foobar/system`

OR by double clicking on the entry for that host in the virtual machine manager window. In both cases I am asked for the password and the login succeeded. This morning I can still use the virsh cmdline, so I know that the password is correct and the sshd.conf and the network is still good. Double clicking on the entry in the virtual machine manager window opens the password entry dialog as before. However when I press return after entering the password, the remote system logs contain the lines:

```
Jan 11 11:45:29 foobar sshd[1112039]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.1.1  user=root
Jan 11 11:45:29 foobar sshd[1112039]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "root"
Jan 11 11:45:32 foobar sshd[1112039]: Failed password for root from 192.168.1.1 port 43314 ssh2
```
and the login fails. I get two more attempts that also fail and then the error dialog box shows:

```
Unable to connect to libvirt qemu+ssh://root@foobar/system.

Cannot recv data: Permission denied, please try again.
Permission denied, please try again.
root@foobar: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).: Connection reset by peer

Verify that the 'libvirtd' daemon is running on the remote host.

Libvirt URI is: qemu+ssh://root@foobar/system

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 924, in _do_open
    self._backend.open(cb, data)
  File "/usr/share/virt-manager/virtinst/connection.py", line 153, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/lib64/python3.8/site-packages/libvirt.py", line 148, in openAuth
    raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: Cannot recv data: Permission denied, please try again.
Permission denied, please try again.
root@foobar: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).: Connection reset by peer
```

The relevant part of the default `authselect` file `password-auth` of a the CentOS 8.2 installation on foobar contains:

```
auth        [default=1 ignore=ignore success=ok]         pam_succeed_if.so uid >= 1000 quiet
auth        [default=1 ignore=ignore success=ok]         pam_localuser.so
auth        sufficient                                   pam_unix.so nullok try_first_pass
auth        requisite                                    pam_succeed_if.so uid >= 1000 quiet_success
```

As the third line is "sufficient" `pam_unix.so nullok` should return for the user root. The fourth line should never be reached. That was the case last week before the update and is still the case for the `virsh` command line version.

As the update to 3.2.0. was the only change last friday, the question is now: What has changed in 3.2.0 that breaks the remote login via qemu+ssh as root?

**Comment by crobinso** [comment]
Thanks for the report but I have no idea what changed in virt-manager that could be responsible. Did you reboot after the update? Maybe some host config change took effect from a previous update.

Can you downgrade virt-manager to an older version and see if it still fails? That could help specifically narrow it down to virt-manager

What was the previous virt-manager version you were on?

**Comment by ulilaube** [comment]
>What was the previous virt-manager version you were on?

My bad, according to the zypper history logs:

```
2020-09-16 07:59:14|install|virt-manager|2.2.1-12.1
2020-09-21 07:46:33|install|virt-manager|3.0.0-1.1
2020-10-12 08:07:20|install|virt-manager|3.1.0-1.1
2020-10-30 07:45:35|install|virt-manager|3.1.0-2.1
2020-11-02 07:56:56|install|virt-manager|3.1.0-3.1
2020-11-09 07:54:00|install|virt-manager|3.1.0-4.1
2020-11-20 14:05:58|install|virt-manager|3.2.0-1.1
2020-12-02 16:45:30|install|virt-manager|3.2.0-2.1
2021-01-04 08:10:17|install|virt-manager|3.2.0-3.1
2021-01-08 15:14:09|install|virt-manager|3.2.0-4.1
```
So I was already on 3.2.0 since November...

> Can you downgrade virt-manager to an older version and see if it still fails? That could help specifically narrow it down to virt-manager

Unfortunately the rolling releases make it easy to roll forward. But rolling back is a whole other topic. However my local system uses btrfs with snapshots on top. So I can travel back to the state the local filesystem was in last week before -4.1 was installed. I just did that and it turns out the virt-manager from -3.1 does the job as expected. No errors. However last weeks snapshot also has another kernel etc... so rolling back only virt-manager alone is trickier.

So I have to see what happened between  -3.1  and  -4.1. Unfortunately the package maintainer has not provided a detailed changelog in the binary rpm.

`> rpm -qc virt-manager`

Looking at the opensuse rpm.spec file of -4.1, there is a whole buch of patches on top of 3.2.0...

```
[...]
Name:           virt-manager
Version:        3.2.0
Release:        4.1
Summary:        Virtual Machine Manager
License:        GPL-2.0-or-later
Group:          System/Monitoring
URL:            http://virt-manager.org/
Source0:        %{name}-%{version}.tar.bz2
Source1:        virt-install.rb
Source2:        virt-install.desktop
Source3:        virt-manager-supportconfig
# Upstream Patches
Patch1:         e7222b50-addstorage-Dont-pass-None-to-widget.set_active.patch
Patch2:         4d0e3232-virtinst-Fix-TOCTOU-in-domain-enumeration.patch
# SUSE Only
Patch70:        virtman-desktop.patch
Patch71:        virtman-kvm.patch
Patch72:        virtman-show-suse-install-repos.patch
Patch73:        virtman-dont-allow-grub.xen-to-be-deleted.patch
Patch74:        virtinst-pvgrub2-bootloader.patch
Patch75:        virtinst-change-location-for-grub_xen.patch
Patch76:        virtinst-set-qemu-emulator.patch
# Features or Enhancements
Patch103:       virtman-load-stored-uris.patch
Patch104:       virtman-add-tooltip-to-firmware.patch
Patch120:       virtinst-default-xen-to-qcow2-format.patch
Patch121:       virtinst-detect-oes-distros.patch
Patch122:       virtinst-modify-gui-defaults.patch
Patch123:       virtinst-vol-default-nocow.patch
Patch124:       virtinst-set-cache-mode-unsafe-for-install.patch
Patch125:       virtinst-s390x-disable-graphics.patch
Patch126:       virtinst-add-caasp-support.patch
Patch127:       virtinst-add-sle15-detection-support.patch
Patch128:       virtinst-add-pvh-support.patch
Patch129:       virtinst-media-detection.patch
Patch130:       virtinst-graphics-add-check-for-qemu-modules-in-spice-graphic.patch
# Bug Fixes
Patch151:       virtman-increase-setKeepAlive-count.patch
Patch152:       virtman-allow-destroy-from-shutdown-menu-of-crashed-vm.patch
Patch153:       virtman-check-for-valid-display.patch
Patch154:       virtman-allow-creating-i686-vm.patch
Patch155:       virtman-dont-specify-vte-version.patch
Patch156:       virtman-dont-specify-gtksource-version.patch
Patch157:       virtman-fix-restore-vm-menu-selection.patch
Patch158:       virtman-disallow-adding-floppy-disk.patch
Patch159:       virtman-register-delete-event-for-details-dialog.patch
Patch170:       virtinst-xen-drive-type.patch
Patch171:       virtinst-xenbus-disk-index-fix.patch
Patch172:       virtinst-refresh_before_fetch_pool.patch
Patch173:       virtinst-use-xenpae-kernel-for-32bit.patch
Patch174:       virtinst-use-qemu-for-cdrom-device.patch
Patch175:       virtinst-keep-install-iso-attached.patch
Patch176:       virtinst-dont-use-special-copy-cpu-features.patch
Patch177:       virtinst-set-default-nic.patch
Patch178:       virtinst-sap-detection.patch
[...]
```
Maybe it is easier to grab another distro that has 3.2.0 and see if the problem is in the patches. Unfortunately CentOS 8.3 still has
virt-manager-2.2.1-3.el8.noarch, so I would have to setup a Fedora 33 system...

**Comment by ulilaube** [comment]
I fired up a local VM installed Fedora 33 and gave virt-manager-3.2.0-1.fc33.noarch a test ride. I works, as expected...*sigh*

I am sorry for the noise.

As Fedora defaults Gnome openssh-askpass-gnome-8.4p1-4.fc33.x86_64 is used. On my local machine KDE Plasma 5 is the desktop environment in use, so may ksshaskpass5-5.20.5-1.1.x86_64 is the culprit...

**Comment by crobinso** [comment]
Okay thanks for checking. FWIW it's easy to test upstream as well, just git clone and from the checkout directory run ./virt-manager --debug
