### ISSUE TITLE
[Feature Request] Being able to start and exit the default network and manage on what vm's it's turned on

### ISSUE THREAD

**Issue by Toadfield** [virt-manager/virt-manager#211]
That would be really cool,that would be better than using the terminal for that.

**Comment by crobinso** [comment]
You can managed the virtual network: From the main window, Edit->Connection Details->Virtual Networks. You can also change what VMs use it in the individual VM details page, in the NIC details. So I think this is already covered. Or did I misunderstand?

**Comment by Toadfield** [comment]
oh,thanks
