### ISSUE TITLE
libvirt.libvirtError: Operation not supported: operation 'setCpusetMemoryMigrate' not supported

### ISSUE THREAD

**Issue by kalpha2** [virt-manager/virt-manager#212]
so I started not being able to start any KVM's in a Deb10 install after Debian updates via SPM.
So I have  `git clone https://github.com/virt-manager/virt-manager.git`
and when I run ./virt-manager from the folder the clone was made into I get 
`Error starting domain: Operation not supported: operation 'setCpusetMemoryMigrate' not supported

Traceback (most recent call last):
  File "./virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "./virtManager/asyncjob.py", line 101, in tmpcb
    callback(*args, **kwargs)
  File "./virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "./virtManager/object/domain.py", line 1329, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1080, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: Operation not supported: operation 'setCpusetMemoryMigrate' not supported`
**Distro**: Debian10

**Comment by phrdina** [comment]
Hi, thanks for the report. The error is not from virt-manager but from libvirt. It is related to cgroups. From the code it looks like you have cgroups v2 enabled and you are running libvirt version between 4.8.0 and 5.2.0 and looking into Debian 10 it uses libvirt 5.0.0 which doesn't have that feature implemented for cgroups v2.

There is nothing we can do in virt-manager. You need to create a debian BUG to ask them to backport this patch https://gitlab.com/libvirt/libvirt/-/commit/77c1cf4da2f in order to use this feature.

Alternatively you can disable cpuset cgroup controller by editing `cgroup_controllers` in `/etc/libvirt/qemu.conf`.

**Comment by kalpha2** [comment]
thank you. It appears all lines in /etc/libvirt/qemu.conf are commented I presume it is essentially a template of potential overrides and with them commented there are defaults that are used? I modified the following from  
    #cgroup_controllers = [ "cpu", "devices", "memory", "blkio", "cpuset", "cpuacct" ]
to
    cgroup_controllers = [ "cpu", "devices", "memory", "blkio", "cpuacct" ]
and restart the computer but I still get the same error.
Is there something else I would need to do on a Debian system?
Yes it is libvirt 5.0.0 on this Debian. Where is the libvirt source hosted could I compile myself or is that likely too much fun and better left to debian maintainers?
I will look at raising a debian bug with the patch you reference

**Comment by kalpha2** [comment]
please ignore, sorry for the noise... works fine in a fresh Debian10 install ... don't know what specifically caused the issue but it is related to that unit having a mixture of standard and backports repo originally done to allow update to kernel but has bitten on updates a few times.

**Comment by siilike** [comment]
You need to set `cgroup_controllers = []`.

**Comment by phrdina** [comment]
> You need to set `cgroup_controllers = []`.

Only in case that you want to disable cgroups for all QEMU VMs which I would not recommend in most cases.

**Comment by siilike** [comment]
Sure, but at least it works. In my case there are no untrusted systems.

**Comment by kvtb** [comment]
I have this error using `LibVirt 8.8.0` :(
