### ISSUE TITLE
Could we have a USB redirector option in the menu when fullscreened?

### ISSUE THREAD

**Issue by hamishmb** [virt-manager/virt-manager#213]
I am running Linux Mint 20.1 (based on Ubuntu 20.04 LTS).

I was wondering if there would be any interest in adding a USB direction option to the fullscreen menu? I think this would be a super-nice thing to have.

**Comment by crobinso** [comment]
Thanks for the suggestion, but I don't think we will add this. SPICE auto usb redirection covers a subset of your case, example: swapping out USB sticks on the host while a VM is the active window, the device will be automatically redirected to the VM. There's permanent USB attach via the 'Add Hardware' wizard. I think that's sufficient. Nowadays we are trying to avoid extending the UI unless it's really important, like enabling new import features. See [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md) for more info

**Comment by hamishmb** [comment]
Ah that is fair enough, SPICE auto USB redirections sound like it'd be useful, I didn't know I could do that. I've moved from VirtualBox recently so I'm still not familiar with all the new tools.

Hypothetically, would you potentially accept a pull request for this? I have a decent amount of experience with Python so at some unspecified date in the future, I may be able to write that feature.

**Comment by crobinso** [comment]
I see now that `virt-viewer` actually has a fullscreen menu option for launching the `Redirect USB Device` dialog. If someone submitted a patch duplicating that behavior (and implemented uitest coverage for it) I'd be fine with that. Thanks!

**Comment by hamishmb** [comment]
Okay. Until I looked at the source, I had assumed that virt-manager used virt-viewer or components thereof for the viewing aspect, so I didn't know that either.

Unfortunately I'm very busy at the moment and unfamiliar with the setup and structure for how this works, so it'll be a while if it's me who does this. Should we re-open this so an interested passer-by is more likely to find it?

**Comment by hamishmb** [comment]
Right, interested in working on this soon, can we re-open?

Also, is there some documentation for implementing uitest coverage? I'm not familiar with that tool.

**Comment by crobinso** [comment]
If you get something working, please submit a PR, and we can discuss UI tests after that, I can help implement them.
