### ISSUE TITLE
Is there a way to group VMs?

### ISSUE THREAD

**Issue by hamishmb** [virt-manager/virt-manager#214]
I am running Linux Mint 20.1.

I was wondering if there was a way to group VMs, similar to how it works on virtualbox. This would mean I could eg have a group for Windows VMs, and separate groups for different Linux distros.

**Comment by crobinso** [comment]
No there is no way, and there is no intention to add it: https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md#previously-rejectedremoved-ui-elements

**Comment by hamishmb** [comment]
Oops, sorry, missed that when I read through

**Comment by Am0rphous** [comment]
It is ridiculously sad that this feature is not on the roadmap :(
