### ISSUE TITLE
When secure boot is requested, virt-install fails to pick the correct OVMF binary

### ISSUE THREAD

**Issue by kashyapc** [virt-manager/virt-manager#216]
Description
-----------

When using (refer to below for reproducer) the options `--q35 --boot 
uefi,loader_secure=yes`, `virt-install` should pick  up the OVMF binary
that supports secure boot, which is only supported with Q35 machine
type.  However, `virt-install` fails with:

    ERROR    operation failed: unable to find any master var store for
    loader: /usr/share/edk2/ovmf/OVMF_CODE.fd

Notice, `virt-install` here picks the non-secure boot binary
(OVMF_CODE.fd), instead of the secure boot variant
(OVMF_CODE.secboot.fd).

This is because `virt-install` is choosing the above binary based on
`virsh domcapabilities`, which, by default uses `i440fx` machine type.
However, 'q35' is mandatory for secure boot.  In this case,
`virt-install` should pick up the OVMF binary based on 'q35'
capabilities.

---

Fedora (plus Debian and Ubuntu, at least) now ship the "firmware
descriptor files"[1] for some time now.  These are small JSON files that
describe details about UEFI firmware binaries — such as the fimware
binary path, its architecture, the supported machine type, NVRAM
template and so forth.  This greatly simplifies the selection of OVMF
binary and NVRAM template.  `virt-install` might want to take advantage
of this.

[1] https://src.fedoraproject.org/rpms/edk2/c/674b3c8a27a8

Versions
--------

I tested on a Fedora 32 host, with these relevant package versions:

- qemu-system-x86-5.2.0-4.fc32.x86_64
- libvirt-daemon-kvm-7.0.0-1.fc32.x86_64
- edk2-ovmf-20200801stable-3.fc32.noarch
- virt-install-3.2.0-2.fc32.noarch

Reproducer
----------

Have a kickstart file, `fedora-minimal.ks`, with the below content:

    install
    text
    shutdown
    lang en_US.UTF-8
    keyboard us
    network --bootproto dhcp
    rootpw secret
    firewall --enabled --ssh
    selinux --enforcing
    timezone --utc America/New_York
    bootloader --location=mbr --append="console=tty0 console=ttyS0,115200 rd_NO_PLYMOUTH"
    zerombr
    clearpart --all --initlabel
    autopart --type=plain --fstype=ext4
    
    %packages
    @core
    %end

Then launch a Fedora 33 (or any other distro) requesting Q35, SMM 
feature, and UEFI secure boot; among other general options:

    $> virt-install --connect=qemu:///system \
       --network=network:default \
       --initrd-inject=./fedora-minimal.ks \
       --extra-args="ks=file:./fedora-minimal.ks console=tty0 console=ttyS0,115200" \
       --name=vm1 \
       --disk path=/var/lib/libvirt/images/vm1.qcow2,format=qcow2 \
       --ram 4096 \
       --vcpus=4 \
       --cpu host-passthrough \
       --accelerate \
       --os-variant f33 \
       --hvm \
       --location=https://dl.fedoraproject.org/pub/fedora/linux/releases/33/Server/x86_64/os/ \
       --nographics \
       --machine q35 \
       --serial=pty \
       --noreboot \
       --features smm=on \
       --boot uefi,loader_secure=yes

    
Result
------

The above `virt-install` invocation fails with:

    ERROR    operation failed: unable to find any master var store for
    loader: /usr/share/edk2/ovmf/OVMF_CODE.fd

Workaround
----------

Explicitly specify the OVMF binary file and NVRAM template.  So, in the
above reproducer, replace `--boot uefi,loader_secure=yes` with:

`--boot
uefi,loader=/usr/share/edk2/ovmf/OVMF_CODE.secboot.fd,loader_ro=yes,loader_type=pflash,nvram_template=/usr/share/edk2/ovmf/OVMF_VARS.secboot.fd,loader_secure=yes`.

Then the `virt-install` invocation works.

**Comment by kashyapc** [comment]
A note on the workaround:

I just noticed something unexpected (after booting a fresh F33 guest):
looks like mixing "uefi and "loader" options under a single `--boot` has 
an unintended side-effect.  E.g.

With this invocation in `virt-install`:

    [...]
    --machine q35 \
    --serial=pty \
    --noreboot \
    --features smm=on \
    --boot uefi,loader=/usr/share/edk2/ovmf/OVMF_CODE.secboot.fd,loader_ro=yes,loader_type=pflash,nvram_template=/usr/share/edk2/ovmf/OVMF_VARS.secboot.fd,loader_secure=yes.

The resulting guest XML is:

    <os>
      <type arch='x86_64' machine='pc-q35-5.2'>hvm</type>
      <loader readonly='yes' secure='yes' type='pflash'>/usr/share/edk2/ovmf/OVMF_CODE.fd</loader>
      <nvram template='/usr/share/edk2/ovmf/OVMF_VARS.secboot.fd'>/var/lib/libvirt/qemu/nvram/sb_f33_1_VARS.fd</nvram>
      <boot dev='hd'/>
    </os>

Notice how the requested `OVMF_CODE.secboot.fd` (in the `virt-install'
invocation) is silently replaced by `virt-install` with the plain 
binary, `OVMF_CODE.fd`.

What worked for me in the past was, specifying "uefi" and "loader"
separately:

    --boot uefi \
    --boot loader=/usr/share/edk2/ovmf/OVMF_CODE.secboot.fd,loader_ro=yes,loader_type=pflash,nvram_template=/usr/share/edk2/ovmf/OVMF_VARS.secboot.fd,loader_secure=yes

**Comment by crobinso** [comment]
Thanks for the report! `--boot firmware=efi,loader_secure=yes` will do the correct thing. I think we should consider leaving the `--boot uefi` method as is and just use libvirt's firmware=efi magic when it's available. Trying to get `--boot uefi` to do sensible things with option overrides is kinda tough

**Comment by kashyapc** [comment]
> Thanks for the report! `--boot firmware=efi,loader_secure=yes` will do the correct thing. 

Yep, noticed it via trial and error.  Thanks for confirming.

> I think we should consider leaving the `--boot uefi` method as is and just use libvirt's firmware=efi magic when it's available. Trying to get `--boot uefi` to do sensible things with option overrides is kinda tough

Yeah, understandable.  I don't mind if you close this bug, given the complexity trade-off.

**Comment by crobinso** [comment]
Thanks, I'll close this then
