### ISSUE TITLE
virt-manager cannot start image

### ISSUE THREAD

**Issue by Rosika2** [virt-manager/virt-manager#217]
Hi altogether,

after a fresh install of **Lubuntu 20.04.1** and installation of **kvm**, **qemu** and **virt-manager** I encountered the following problem:

My VM image (which I still have on my third data partition) - it´s BodhiLinux BTW - can be found by virt-manager but it **cannot be accessed** due to permission problems.
When trying to access it I get the following messages (translated roughly from German):

> - The emulator doesn´t have search authorization for the path "[...].img"
> - virt-manager asks if that should be changed; afterwards: changing of the permissions caused some errors: Errno 1 process not allowed
> - Installation cannot be completed (no authorization)

Here (https://wiki.ubuntuusers.de/virt-manager/#Benutzer-hinzufuegen ) it says:

"During the installation, libvirt-bin creates its own group, this is called libvirtd. All users who are to use VMM must be added to this group."
(translated from German)

But this is **not** the case. The group libvirtd doesn´t exist at all, just **libvirt**, **libvirt-dnsmasq** and **libvirt-qemu**.

I myself am a member of the following groups:

```
groups rosika
rosika : rosika adm cdrom sudo dip plugdev kvm lpadmin sambashare libvirt
```

I´m stuck at that point.

UPDATE:

As this problem seems to be based on permissions granted (or not granted) I tried the following:

As a test I copied the img-file from the third partition to /home/rosika. Now virt-manager works as desired. 
It can access the file without any difficulties, i.e. my VM runs perfectly.

As a second step I looked at permissions:
The img-file has got the same permissions on the third partition and on the home partition.:

```
-rw-rw-rw-  1 root   root    18G Jan 20 23:10 testing-image.img # dritte Partition
-rw-rw-rw- 1 rosika rosika 18G Jan 22 18:55 testing-image.img # /home-Partition
```
But there´s a difference to be observed when looking at owner and group.
So I changed the ownership of the img-file on the third partition:

`sudo chown rosika:rosika testing-image.img`

But the problem still remains.

I so hope there´s someone out there who may be able to help.

Thanks so much in advance.
Many greetings.
Rosika

**Comment by crobinso** [comment]
Thanks for the report. Please pastebin full `virt-manager --debug` when reproducing

**Comment by phrdina** [comment]
Hi, the wiki page is incorrect and should be updated, so you need to ask the person managing that wiki. The group `libvirt` is the correct name. However, this doesn't have anything in common with the permission issue that you see.

On Ubuntu libvirt starts the QEMU process with libvirt-qemu:kvm user:group and the message that you see means that the QEMU process is not able to access that file. Usually it means that you need to set X (execute) permission on each directory for the whole path to the image.

In some cases virt-manager offers you to fix the issue and I guess in this case it only complains.

**Comment by Rosika2** [comment]
@crobinso:

Hi, Cole. Thanks for the hint. I´ll do that next time if I still need help.
But it turns out I could fix the problem with @phrdina ´s help. See below.

Thanks so much.
Rosika

@phrdina :

Hi Pavel,

thank you so much for your help. 
`it means that you need to set X (execute) permission on each directory for the whole path to the image.`

That´s it.

The apth to my img-file is: 
`/media/rosika/f14a27c2-0b49-4607-94ea-2e56bbf76fe1/für_qemu2/testing-image.img  ` .

It turned out that the folder `/media/rosika/` lacked execute permissions. Those I granted:
` drwxr-x--x+ 6 root root 4,0K Jan 26 13:37 rosika/`
And now it works as desired. Virt-manager can access the img-file on the data partition and the VM can run.

I never would have thought of that.
Thank you so much for your help. It´s highly appreciated.

Many greetings and stay safe.
Rosika

**Comment by tristan-k** [comment]
@Rosika2 For the newbies. Can you describe how you did that? I'm facing a similar issue after trying to import a qcow2 image.

**Comment by Rosika2** [comment]
Hi @tristan-k , :wave: 

Oh, I see that was quite a while ago. In the meantime I´m on Linux Lite 6.2.
But if  that´s what you are referring to:

> it means that you need to set X (execute) permission on each directory for the whole path to the image.

that should easily be accomplished by the command
`chmod ugo+x testing-image.img`
from within the respective folder.

Use your own img-file name for that, of course.

Hope it helps.
Many greetings from Rosika :slightly_smiling_face:
