### ISSUE TITLE
virt-install: initrd transfer is slow

### ISSUE THREAD

**Issue by sk1p** [virt-manager/virt-manager#221]
**Distro**: Debian (I have confirmed that the bug is also present in the master branch)

To reproduce: `virt-install --connect qemu:///system --name just-testing --memory 2048 --location https://deb.debian.org/debian/dists/stable/main/installer-amd64/ --disk size=16 --os-variant debian10`

The step "Transferring virtinst-XXX-initrd.gz" is quite slow - it starts out fast when transferring the first few MB, afterwards it slows down to ~200kB/s or slower. In total, the 29MB take 1m35s to transfer.

I tracked the problem down to the blocksize here:

https://github.com/virt-manager/virt-manager/blob/56cb813d42af8250b20d6d5516faa026e2fb7c76/virtinst/install/volumeupload.py#L111-L112

When un-commenting the 1MiB blocksize, the transfer takes less than a second. Is there a reason for the small blocksize?

**Comment by crobinso** [comment]
Thanks for the suggestion, definitely makes local uploads way faster. I pushed a fix
