### ISSUE TITLE
How to use Wacom in KVM?

### ISSUE THREAD

**Issue by Mlocik97** [virt-manager/virt-manager#223]
**Distro**:  Ubuntu 20.04.

Hello,

I have KVM, and I need to be able to use wacom in my guest OS.

My settings is:

```xml
<input type="tablet" bus="usb">
  <address type="usb" bus="0" port="1"/>
</input>
```
Passing as USB device I had this setting:

```xml
<hostdev mode="subsystem" type="usb" managed="yes">
  <source>
    <vendor id="0x056a"/>
    <product id="0x037a"/>
  </source>
  <address type="usb" bus="0" port="4"/>
</hostdev>
```
but there is problem with pressure detection, so I tried to pass it with USB, but then, I can use pressure, but cursor doesn't move. Can someone help?

**Comment by Mlocik97** [comment]
```
<qemu:commandline>
    <qemu:arg value='-device'/>
    <qemu:arg value='usb-wacom-tablet'/>
  </qemu:commandline>
```
I tried this, but virt-manager automatically remove it from XML after saving.

**Comment by crobinso** [comment]
if `<hostdev>` passthrough works but isn't exposing all features in the VM, I'm guessing it's either a guest OS problem or qemu problem, libvirt/virt-manager shouldn't be involved there. The only thing I can think of is make sure your VM USB controller is USB3 and not something older like USB1 or USB2.

**Comment by Mlocik97** [comment]
I even tried using 

```xml
<qemu:commandline>
    <qemu:arg value="-device"/>
    <qemu:arg value="usb-wacom-tablet"/>
  </qemu:commandline>
```

**Comment by Mlocik97** [comment]
Btw. one more question, is it possible to set "-display sdl" or "-display gtk" in virt-manager?

**Comment by crobinso** [comment]
For qemu:commandline, make sure you add `<domain xmlns:qemu="https://libvirt.org/schemas/domain/qemu/1.0" type="kvm">` like shown in the diff here: https://blog.wikichoon.com/2017/03/easy-qemu-commandline-passthrough-with.html

but I have no idea if the usb-wacom-tablet emulated device is going to make any difference for your usecase.

No virt-manager doesn't support SDL or GTK graphics directly, those require launching a separate viewer which isn't really compatible with the app
