### ISSUE TITLE
Mapped filesystem share can write but not truncate files owned by another user but same group

### ISSUE THREAD

**Issue by anthonybilinski** [virt-manager/virt-manager#227]
**Distro**:
Host: Ubuntu Desktop 20.10
Guest: Debian 10

Running virt-manager from git, I have created a Debian 10 guest, and added a filesystem share with:
```
Type: mount
Mode: mapped
Source path: /tmp/test
Target path: A
```
With `/tmp/test` owned by `root.libvirt-qemu` `chmod 770`.

Then mounted that from the guest with:
```
A /mnt/share 9p trans=virtio,version=9p2000.L,msize=1048576,_netdev 0 0
```
in fstab.

From host, I created a file at `/tmp/test/foo` owned by `root.libvirt-qemu`, containing:
```
1
2
3
4
5
```
and chmod its permissions to `660`.

In the guest VM, if I edit this file at `/mnt/share/test` as `root`, and delete the first line from vim, then save and exit, vim says "8C written", but then `ls` shows that the file is still 10 bytes big.

If I then check the contents of the file from either guest or host, the file now contains:
```
2
3
4
5
5
```
which makes it look like the first line _was_ deleted, everything was shifted up, but the size of the file wasn't updated leading the the last line being doubled?

If I try to edit the file with `nano` rather than `vim` inside the guest, it throws `Operation not permitted` when trying to save.

If I change the owner of the file from host to `libvirt-qemu` rather than `root`, the problem goes away. 

Sorry if this should be reported somewhere else, or if I'm just missing some weird part of regular permissions.

**Comment by crobinso** [comment]
Hmm I can't really explain the behavior you are seeing. If files are owned by root on the host, and qemu launched by libvirt is running as libvirt-qemu user, I would not expect any changes to be reflected on the host, due to permission errors, so the weird partial change result is confusing to me. But if you want this to work correctly all the name, the shared directory and all the files beneath it need to have permissions open to libvirt-qemu user.

For the strange behavior, it may be a qemu or kernel bug but unlikely to be libvirt or virt-manager, they don't do much here. So if you want to continue tracking it down, best case is to get the newest version of qemu you can find, confirm the issue is still present, and file an upstream bug against qemu

**Comment by anthonybilinski** [comment]
Thanks I'll try reproing with qemu tip and reporting upstream.

When you say:
> If files are owned by root on the host, and qemu launched by libvirt is running as libvirt-qemu user, I would not expect any changes to be reflected on the host, due to permission errors

Is that taking into account that the group permissions on the files should allow the libvirt-qemu user to write to them, i.e. is there something special about the owner of the file rather than just user/group permissions?

In my case the directory and all files under it have read/write permissions for a group that the libvirt-qemu user is part of, even though they're all owned by root. So I expected all writes to work fully, rather than be blocked fully like you're saying. Of course in either case the behaviour I'm seeing seems bugged.

**Comment by crobinso** [comment]
Sorry, I missed that group permissions are correct, I was not attempting to imply that owner is somehow special. My knowledge isn't too deep about how things are meant to work here. But I just googled a bit, the `mapped` setting is qemu's `mapped-xattr` setting, and qemu attempts to store the guest uid/gid values in host file extended attributes. And from `[man 7 xattr](https://man7.org/linux/man-pages/man7/xattr.7.html)` there's this block:

```
       For this reason, user extended attributes are allowed only for
       regular files and directories, and access to user extended
       attributes is restricted to the owner and to users with
       appropriate capabilities for directories with the sticky bit set
       (see the chmod(1) manual page for an explanation of the sticky
       bit).
```

So sounds like the story is more complicated that it seems. But you're right it doesn't excuse the weird behavior here either way
