### ISSUE TITLE
Choppy graphics when enabling virtio + opengl acceleration

### ISSUE THREAD

**Issue by nirvinm** [virt-manager/virt-manager#228]
The last few releases have a weird issue when enabling _VirtIO_ video + _Spice_ + _OpenGL_ to enable 3D acceleration. Any Linux guests running on the VM has slow/choppy graphics. In addition window resize does not resize guests if on virtio video. QXL works fine.

Guests confirm virgl acceleration enabled

    $ glxinfo | grep OpenGL

    OpenGL vendor string: Red Hat
    OpenGL renderer string: virgl
    OpenGL core profile version string: 4.3 (Core Profile) Mesa 19.3.4
    OpenGL core profile shading language version string: 4.30
    OpenGL core profile context flags: (none)
    OpenGL core profile profile mask: core profile
    OpenGL core profile extensions:
    OpenGL version string: 3.1 Mesa 19.3.4
    OpenGL shading language version string: 1.40
    OpenGL context flags: (none)
    OpenGL extensions:
    OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.4
    OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

Host's OpenGL spec (Fedora Workstation 33, Intel UHD 630)

    $ glxinfo | grep OpenGL

    OpenGL vendor string: Intel
    OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
    OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.4
    OpenGL core profile shading language version string: 4.60
    OpenGL core profile context flags: (none)
    OpenGL core profile profile mask: core profile
    OpenGL core profile extensions:
    OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.4
    OpenGL shading language version string: 4.60
    OpenGL context flags: (none)
    OpenGL profile mask: compatibility profile
    OpenGL extensions:
    OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.4
    OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

However running the VM with QEMU directly with `gl=on` performs butter smooth. 

    $ qemu-system-x86_64 -enable-kvm -m 2048 -vga virtio -display gtk,gl=on -cdrom AnyLinuxGuest.iso

**Comment by crobinso** [comment]
Thanks for the report. Please provide your full VM XML, grab it from the XML tab of virt-manager
Can you try `sudo virt-viewer VMNAME` and see if it shows the same results?

**Comment by nirvinm** [comment]
Same issue with `virt-viewer --attach`. VirtIO + OpenGL graphics is choppy. Here is the full VM XML I tried on **Fedora 33** and **Virt-Manager 3.2.0**

    <domain type="kvm">
      <name>opensusetumbleweed</name>
      <uuid>5084ed4f-f27c-4f37-9c3e-227471fb6161</uuid>
      <metadata>
        <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
          <libosinfo:os id="http://opensuse.org/opensuse/tumbleweed"/>
        </libosinfo:libosinfo>
      </metadata>
      <memory unit="KiB">4194304</memory>
      <currentMemory unit="KiB">4194304</currentMemory>
      <vcpu placement="static">4</vcpu>
      <os>
        <type arch="x86_64" machine="pc-q35-5.1">hvm</type>
        <boot dev="cdrom"/>
      </os>
      <features>
        <acpi/>
        <apic/>
        <vmport state="off"/>
      </features>
      <cpu mode="host-model" check="partial"/>
      <clock offset="utc">
        <timer name="rtc" tickpolicy="catchup"/>
        <timer name="pit" tickpolicy="delay"/>
        <timer name="hpet" present="no"/>
      </clock>
      <on_poweroff>destroy</on_poweroff>
      <on_reboot>restart</on_reboot>
      <on_crash>destroy</on_crash>
      <pm>
        <suspend-to-mem enabled="no"/>
        <suspend-to-disk enabled="no"/>
      </pm>
      <devices>
        <emulator>/usr/bin/qemu-system-x86_64</emulator>
        <disk type="file" device="cdrom">
          <driver name="qemu" type="raw"/>
          <target dev="sda" bus="sata"/>
          <readonly/>
          <address type="drive" controller="0" bus="0" target="0" unit="0"/>
        </disk>
        <controller type="usb" index="0" model="qemu-xhci" ports="15">
          <address type="pci" domain="0x0000" bus="0x02" slot="0x00" function="0x0"/>
        </controller>
        <controller type="sata" index="0">
          <address type="pci" domain="0x0000" bus="0x00" slot="0x1f" function="0x2"/>
        </controller>
        <controller type="pci" index="0" model="pcie-root"/>
        <controller type="pci" index="1" model="pcie-root-port">
          <model name="pcie-root-port"/>
          <target chassis="1" port="0x10"/>
          <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0" multifunction="on"/>
        </controller>
        <controller type="pci" index="2" model="pcie-root-port">
          <model name="pcie-root-port"/>
          <target chassis="2" port="0x11"/>
          <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x1"/>
        </controller>
        <controller type="pci" index="3" model="pcie-root-port">
          <model name="pcie-root-port"/>
          <target chassis="3" port="0x12"/>
          <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x2"/>
        </controller>
        <controller type="pci" index="4" model="pcie-root-port">
          <model name="pcie-root-port"/>
          <target chassis="4" port="0x13"/>
          <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x3"/>
        </controller>
        <controller type="pci" index="5" model="pcie-root-port">
          <model name="pcie-root-port"/>
          <target chassis="5" port="0x14"/>
          <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x4"/>
        </controller>
        <controller type="pci" index="6" model="pcie-root-port">
          <model name="pcie-root-port"/>
          <target chassis="6" port="0x15"/>
          <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x5"/>
        </controller>
        <controller type="virtio-serial" index="0">
          <address type="pci" domain="0x0000" bus="0x03" slot="0x00" function="0x0"/>
        </controller>
        <interface type="network">
          <mac address="52:54:00:ba:43:33"/>
          <source network="default"/>
          <model type="virtio"/>
          <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
        </interface>
        <serial type="pty">
          <target type="isa-serial" port="0">
            <model name="isa-serial"/>
          </target>
        </serial>
        <console type="pty">
          <target type="serial" port="0"/>
        </console>
        <channel type="unix">
          <target type="virtio" name="org.qemu.guest_agent.0"/>
          <address type="virtio-serial" controller="0" bus="0" port="1"/>
        </channel>
        <channel type="spicevmc">
          <target type="virtio" name="com.redhat.spice.0"/>
          <address type="virtio-serial" controller="0" bus="0" port="2"/>
        </channel>
        <input type="tablet" bus="usb">
          <address type="usb" bus="0" port="1"/>
        </input>
        <input type="mouse" bus="ps2"/>
        <input type="keyboard" bus="ps2"/>
        <graphics type="spice">
          <listen type="none"/>
          <image compression="off"/>
          <gl enable="yes" rendernode="/dev/dri/by-path/pci-0000:00:02.0-render"/>
        </graphics>
        <sound model="ich9">
          <address type="pci" domain="0x0000" bus="0x00" slot="0x1b" function="0x0"/>
        </sound>
        <video>
          <model type="virtio" heads="1" primary="yes">
            <acceleration accel3d="yes"/>
          </model>
          <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
        </video>
        <redirdev bus="usb" type="spicevmc">
          <address type="usb" bus="0" port="2"/>
        </redirdev>
        <redirdev bus="usb" type="spicevmc">
          <address type="usb" bus="0" port="3"/>
        </redirdev>
        <memballoon model="virtio">
          <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
        </memballoon>
        <rng model="virtio">
          <backend model="random">/dev/urandom</backend>
          <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
        </rng>
      </devices>
    </domain>

**Comment by crobinso** [comment]
If you are seeing the same issue with virt-viewer as well, that likely eliminates virt-manager as the culprit since they are different codebases. It's probably something between spice-gtk, qemu, or virglrenderer. Notably your manual qemu example bypasses spice entirely so it's not an apples to apples comparison.

**Comment by DRRDietrich** [comment]
I ended up here because of the same problem. I also use Fedora Workstation 33, but with an AMD RX 580.

Even if this issue may be the wrong place, I don't know where better to address the problem. Perhaps at least someone is reading it here, with the same problem.

Benchmarks with glmark2 delivered the following results:
- GPU pass-tough / bare metal: > 12000 points
- virtio/opengl [1]: **4042** points
- virtio/opengl (virt-manager): **126** points
- QXL (virt-manager): 241 points

[1] `qemu-system-x86_64 -drive file=fedora.raw -m 8192 -enable-kvm -M q35 -cpu host -smp 12,sockets=1,cores=6,threads=2 -vga virtio -display gtk,gl=on,show-cursor=on -usb -device usb-tablet`

The performance in virt-manager in comparison is really frustrating.

**Comment by Firlaev-Hans** [comment]
I also noticed this problem. Performance is quite choppy in virt-manager with virtio graphics, but flawless when using QEMU (both GTK and SDL) directly.

I noticed, however, that the performance ONLY sucks when a OpenGL based X11 compositor is running. On a guest running KDE Plasma, when disabling the compositor (disabling desktop effects with Shift+Alt+F12) or switching the backend to Xrender, OpenGL performance in other applications and games is normal again.
On Wayland guests however, the performance is ALWAYS choppy, even when Xrender is used or when desktop effects are disabled (but once again it's fine when using QEMU without virt-manager).

**Comment by voidanix** [comment]
Just started to notice the same issue on Fedora Rawhide (36) but wanted to expand on @Firlaev-Hans's findings on compositors.

I am running GNOME on both the host and the guest (version 41.2 and 3.34 respectively) and here is what happens:

* Wayland host+Wayland guest: virgl works, glxgears limited to vsync
* Wayland host+Xorg guest: virgl works, glxgears not limited to vsync
* Xorg host+Wayland guest: slow motion UI animations, very low fps in glxgears
* Xorg host+Xorg guest: same as above

I can also confirm that running QEMU "the CLI way" makes virgl work just fine.

**Comment by MadoScientist97** [comment]
Has this been fixed now? Because even now it seems to be there when running fedora 35 guest on wayland + KDE.

**Comment by Firlaev-Hans** [comment]
> Has this been fixed now? Because even now it seems to be there when running fedora 35 guest on wayland + KDE.

Last time I tried it on an X11 host it was still choppy and horrible, but nowadays I use Wayland on my host machine, where I guess this issue never existed as described in the previous comment, so I don't experience this problem any more no matter what the guest is running.

If you meant that you're running a Wayland guest on an X11 host and performance is fine, then I guess the issue might indeed have been fixed, but if your host is on Wayland too, then that's nothing new.

**Comment by MadoScientist97** [comment]
> > Has this been fixed now? Because even now it seems to be there when running fedora 35 guest on wayland + KDE.
> 
> Last time I tried it on an X11 host it was still choppy and horrible, but nowadays I use Wayland on my host machine, where I guess this issue never existed as described in the previous comment, so I don't experience this problem any more no matter what the guest is running.
> 
> If you meant that you're running a Wayland guest on an X11 host and performance is fine, then I guess the issue might indeed have been fixed, but if your host is on Wayland too, then that's nothing new.

I am running X11 host with wayland guest.
Using qemu directly on commandline gives way better performance than when using virt manager.

So are you saying that if I use x11 guest I would be getting better performance?

**Comment by Firlaev-Hans** [comment]
> I am running X11 host with wayland guest. Using qemu directly on commandline gives way better performance than when using virt manager.
> 
> So are you saying that if I use x11 guest I would be getting better performance?

No, sorry, I actually misread your comment and thought you _didn't_ experience the issue anymore.

I'm saying that if you used a **Wayland host** you'd get better performance.
If you need to use X11 on your host then you can also get better performance by using an X11 guest without compositing or with XRender compositing. But Plasma dropped support for Xrender, and disabling the compositor also kinda sucks.

**Comment by RedFlaged** [comment]
> > I am running X11 host with wayland guest. Using qemu directly on commandline gives way better performance than when using virt manager.
> > So are you saying that if I use x11 guest I would be getting better performance?
> 
> No, sorry, I actually misread your comment and thought you _didn't_ experience the issue anymore.
> 
> I'm saying that if you used a **Wayland host** you'd get better performance. If you need to use X11 on your host then you can also get better performance by using an X11 guest without compositing or with XRender compositing. But Plasma dropped support for Xrender, and disabling the compositor also kinda sucks.

I am using Ubuntu 22.04, switching between X and Wayland does not help.

**Comment by RedFlaged** [comment]
> > I am running X11 host with wayland guest. Using qemu directly on commandline gives way better performance than when using virt manager.
> > So are you saying that if I use x11 guest I would be getting better performance?
> 
> No, sorry, I actually misread your comment and thought you _didn't_ experience the issue anymore.
> 
> I'm saying that if you used a **Wayland host** you'd get better performance. If you need to use X11 on your host then you can also get better performance by using an X11 guest without compositing or with XRender compositing. But Plasma dropped support for Xrender, and disabling the compositor also kinda sucks.

I am using Ubuntu 22.04, switching between X and wayland does not help

**Comment by Kissycat** [comment]
It is strange, same config, same vm, same boot, smoothly at gnome boxes, but low fps at virt-manager...

**Comment by gree303** [comment]
> > > I am running X11 host with wayland guest. Using qemu directly on commandline gives way better performance than when using virt manager.
> > > So are you saying that if I use x11 guest I would be getting better performance?
> > 
> > 
> > No, sorry, I actually misread your comment and thought you _didn't_ experience the issue anymore.
> > I'm saying that if you used a **Wayland host** you'd get better performance. If you need to use X11 on your host then you can also get better performance by using an X11 guest without compositing or with XRender compositing. But Plasma dropped support for Xrender, and disabling the compositor also kinda sucks.
> 
> I am using Ubuntu 22.04, switching between X and wayland does not help

same here; pop-os 22.4 + wayland / X on win10 + 11
virtu-manaer + virtIO drivers + nvidia 540 driver
further problems with openGL; app won't start even after setting up Mesa3D workaround.
GPU shows up with 16GB VRAM, screen resolution limited to 1080p (16:9) 
any idea how to get "real" openGL? is it even possible atm?

Offtopic: The app just pops an error "The Path is not in a correct format." Any ideas how to debug anything like it? I suspect openGL behind it

**Comment by rlanting** [comment]
So I ran into the choppyness issues where fps was low and even worse when moving the mouse, and for shits and giggles I tried something.

Before:

```
$ glxgears
101 frames in 5.0 seconds = 20.087 FPS
```

After:
```
$ glxgears
881 frames in 5.0 seconds = 175.999 FPS
```

What did I do? I started virt-manager like this: 

`vblank_mode=0 virt-manager`

No need to stop the VM for it, just make sure you quit out of virt-manager properly. A quick check with extreme tux racer shows that it's perfectly usable now.

This is with a kde/xorg session on the host and a kde/wayland session in the VM.

**Comment by Jakeo-93** [comment]
Just wanted to say the above tip worked for me as well. No idea what this does but guess ill write up an alias

**Comment by Xtrems876** [comment]
Had the same issue with wayland on both host and guest. The above workaround resolved it.

**Comment by Selora** [comment]
Doesn't work for me, both on virt-manager and virt-viewer,  using wayland with a wlroots compositor for the host. 

Starting `virt-viewer -a` I get a warning that vblank_mode has been overridden by the environment, but no visible effect, it's just a laggy mess on both Xorg and Wayland for the VM.

It also works great with near-native experience for me on raw QEMU, with both SDL and QT as viewport.

**Comment by agorgl** [comment]
Had the same issue with xorg host and wayland guest. The issue was visible when doing `export WLR_NO_HARDWARE_CURSORS=1` before starting the guest wayland compositor as you could see the VM cursor lag behind the real cursor a LOT.

Starting virt-viewer with:
```
vblank_mode=0 virt-viewer --attach --reconnect --hotkeys=release-cursor=ctrl+alt --full-screen archlinux
```
seems to do the trick

**Comment by ACR-Jeff** [comment]
> What did I do? I started virt-manager like this:
> 
> `vblank_mode=0 virt-manager`

Thank you, Worked great for me on Void Linux running FreeBSD KDE and Devuan 5 KDE as guests.

**Comment by trisweb** [comment]
This is a great thread with some good leads.

`vblank_mode=0 virt-manager` does work, however if you have virt-manager running in the background, it may not appear to work.

If this happens, `killall virt-manager` and try again.

I've updated my desktop file so it's built in and this appears to be a good solution.

Is there a possibility of making this the default? Or providing more visibility into the solution somehow? I was under the impression that 3D performance with Linux guest/host was simply an unsolved problem until I found this ticket, and that is problematic.

**Comment by Yoskaldyr** [comment]
`vblank_mode=0` doesn't help for me :(
fedora 42 gnome wayland

**Comment by nazar-pc** [comment]
Wow! I had no idea it could work so well until I tried `vblank_mode=0`, it is simply ridiculous!

I'm running 6.18.9 kernel with Mesa 25.3.5 on Ubuntu 24.04 with X11.

**Comment by MadoScientist97** [comment]
Its almost 3 years later and I dont have that machine anymore but I will have to try it out thanks in one of my old thinkpads @agorgl

**Comment by nazar-pc** [comment]
Can this issue be reopened? This is clearly still a substantial problem, despite possibly being caused by dependencies. If this is caused by dependencies, it'd be highly appreciated if someone knowledgeable can create an issue upstream and drop a link here.

`vblank_mode=0` does work, but it results in image tearing. So one either has awful performance or unpleasand visual artifacts, neither of which is ideal.

**Comment by trisweb** [comment]
I concur with @nazar-pc -- this is such a substantial performance impact that greatly impacts the quality of the experience, that it deserves a thorough solution and revisiting.

**Comment by nazar-pc** [comment]
The issue was in `spice-gtk` and fixed by this MR (at least for X11): https://gitlab.freedesktop.org/spice/spice-gtk/-/merge_requests/150

Can be tested on Ubuntu 26.04 by installing patched version of the library.

For this I prepared a Dockerfile, so you can build it with Docker or Podman without installing anything on your system:
<details>
<summary>Dockerfile</summary>

```dockerfile
# Rebuilds Ubuntu's spice-gtk package with the GL-scanout vblank fix applied.
#
#   mkdir out
#   sudo docker build -o out .
#   sudo ./out/install.sh
#
# Nothing is needed on the host except Docker. The .debs and an install script
# land in ./out. Install the whole set, not a subset: the packages depend on
# each other with strict "= same version" dependencies, so installing only the
# two libraries leaves apt unable to satisfy them.

ARG UBUNTU_VERSION=26.04

FROM ubuntu:${UBUNTU_VERSION} AS build

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBEMAIL=nobody@localhost
ENV DEBFULLNAME="Local build"

# apt-get source and build-dep need deb-src entries, which Ubuntu images ship disabled
RUN set -eux; \
    if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then \
        sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources; \
    else \
        sed -i -E 's/^deb (.*)$/deb \1\ndeb-src \1/' /etc/apt/sources.list; \
    fi; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        build-essential devscripts dpkg-dev quilt ca-certificates

WORKDIR /build

RUN set -eux; \
    apt-get source spice-gtk; \
    apt-get build-dep -y spice-gtk

ARG PATCH_URL=https://gitlab.freedesktop.org/spice/spice-gtk/-/merge_requests/150.patch

ADD ${PATCH_URL} /build/gl-vblank.patch

ARG VERSION_SUFFIX=+fixed

# quilt push fails loudly if the distro version has drifted away from the patch
RUN set -eux; \
    cd spice-gtk-*/; \
    export QUILT_PATCHES=debian/patches; \
    quilt import /build/gl-vblank.patch; \
    quilt push -a; \
    dch --local "${VERSION_SUFFIX}" \
        "Schedule the GL scanout present instead of waiting for vblank"; \
    dpkg-buildpackage -b -uc -us -j"$(nproc)"

# Installs whichever of the rebuilt packages this system already has, so the
# strict inter-package version dependencies stay satisfiable
RUN set -eux; \
    { \
        echo '#!/bin/sh'; \
        echo 'set -eu'; \
        echo 'cd "$(dirname "$0")"'; \
        echo 'set --'; \
        echo 'for deb in *.deb; do'; \
        echo '    pkg=$(dpkg-deb -f "$deb" Package)'; \
        echo '    if dpkg-query -W -f="\${Status}" "$pkg" 2>/dev/null | grep -q "^install ok installed$"; then'; \
        echo '        set -- "$@" "./$deb"'; \
        echo '    fi'; \
        echo 'done'; \
        echo 'if [ "$#" -eq 0 ]; then'; \
        echo '    echo "None of the built packages are installed on this system." >&2'; \
        echo '    exit 1'; \
        echo 'fi'; \
        echo 'echo "Installing: $*"'; \
        echo 'apt install "$@"'; \
    } > /build/install.sh; \
    chmod +x /build/install.sh; \
    sh -n /build/install.sh

FROM scratch AS export
COPY --from=build /build/*.deb /
COPY --from=build /build/install.sh /
```

</details>

Then:
```bash
mkdir out
sudo docker build -o out .
sudo ./out/install.sh
```

If Ubuntu 26.04 ever ships an updated version of the library without the fix, you'll need to re-patch and re-install it. Just rebuild things and you should be good. Note that you can always roll back these packages to originals if you don't like it, nothing is permanent.

The only minor issue is that tearing re-appears when full-screen and toolbar appears in the top center of the screen. I think it is a relatively minor issue all things considered, so I didn't dig into GTK stuff that causes it for now.

I hope you find this is useful.
