### ISSUE TITLE
RFE: Automatically remove 'file:///' protocol from image paths

### ISSUE THREAD

**Issue by JJRcop** [virt-manager/virt-manager#230]
**Distro**: Debian Testing (bullseye)

When dragging a file into virt-manager field from KDE, the `file:///` protocol is prepended to the URI. libvirt does not handle or support this protocol in a path name, and errors.

I'm not certain if this is okay, but maybe virt-manager could replace `file:///` with `/` when it is encountered at the beginning of a field that expects a file path, before sending to libvirt.

This is just a trivial ease of use enhancement, only removing the tedium of erasing the protocol myself. Might not  be worth the trouble, but I figured I'd suggest it.

**Comment by JJRcop** [comment]
I opened the issue on accident

**Comment by crobinso** [comment]
Thanks for the report. I see something similar on gnome, dragging a file from nautilus into the New VM->Import text entry gives `file://PATH\0\n'. I'm guessing it's been like this forever.

Given that the impact is pretty low here, and per [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md) this is desktop integration stuff that we don't prioritize, I don't think it's worth tracking this as an issue. But if someone showed up with a patch demonstrating it's simple to fix this for select UI fields, I will consider it.
