### ISSUE TITLE
host doesn't support requested feature MSR(48DH).vmx-posted-intr [bit 7]

### ISSUE THREAD

**Issue by xekon** [virt-manager/virt-manager#234]
**Distro**: Ubuntu 20.04.2 LTS (Focal Fossa)
**Kernel**: 5.10.23-xanmod1 x86_64
**Desktop**: KDE Plasma 5.18.5
**CPU**: e3-1275v2
**Motherboard**: Supermicro X9SAE

These features seem to not be working:
MSR(48DH).vmx-posted-intr [bit 7]
MSR(48BH).vmx-apicv-register [bit 8]
MSR(48BH).vmx-apicv-vid [bit 9]

With the research I have done so far I found a related report on the kubevirt project: https://github.com/kubevirt/kubevirt/issues/3587

The user that filled the report said this:

_Adding a CPU model like Haswell--noTSX-IBRS solves the issue. I wonder why qemu does not detect the correct CPU features, though, as it has the cpu set to host-model and does some additional checking of features as well._

My cpu is not a Haswell, its a xeon, however I would like to try adding a CPU model once I figure out where to put this information into virt-manager and I also need to figure out the correct cpu model for my cpu, surely its not just xeon, there are tons of variations of those.

Here is the details log from virt-manager when I was attempting to create a new VM.
```
Unable to complete install: 'internal error: process exited while connecting to monitor: 2021-03-12T18:24:28.949747Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2021-03-12T18:24:28.950415Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-register [bit 8]
2021-03-12T18:24:28.950422Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]
2021-03-12T18:24:28.950426Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2021-03-12T18:24:29.401942Z qemu-system-x86_64: -device vfio-pci,host=0000:02:00.0,id=hostdev2,bus=pci.3,addr=0x0: vfio 0000:02:00.0: group 1 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2089, in _do_async_install
    guest.installer_instance.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 542, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 491, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4034, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2021-03-12T18:24:28.949747Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2021-03-12T18:24:28.950415Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-register [bit 8]
2021-03-12T18:24:28.950422Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]
2021-03-12T18:24:28.950426Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2021-03-12T18:24:29.401942Z qemu-system-x86_64: -device vfio-pci,host=0000:02:00.0,id=hostdev2,bus=pci.3,addr=0x0: vfio 0000:02:00.0: group 1 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
```

Also incase anyone asks, the pci devices I am trying to passthrough are properly using vfio-pci

sudo lspci -nnv
Kernel driver in use: vfio-pci

EDIT: seems to add the cpu model I just enable xml editing and add it there, currently It is set to this as default:

```
  <cpu mode="host-model">
    <topology sockets="1" cores="4" threads="1"/>
  </cpu>
```

EDIT2: I figured out how to find the cpu model:

sudo virsh -c qemu:///system capabilities

`<model>IvyBridge-IBRS</model>`

EDIT3: I edited the XML to this:  (This was unnecessary, you can just uncheck copy host and select your model from the dropdown once you know it.)

```
<cpu mode="custom" match="exact">
  <model>IvyBridge-IBRS</model>
  <topology sockets="1" cores="4" threads="1"/>
</cpu>
```

The install now has a different error:

```
Unable to complete install: 'internal error: qemu unexpectedly closed the monitor: 2021-03-12T19:14:32.176083Z qemu-system-x86_64: -device vfio-pci,host=0000:02:00.0,id=hostdev2,bus=pci.3,addr=0x0: vfio 0000:02:00.0: group 1 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2089, in _do_async_install
    guest.installer_instance.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 542, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 491, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4034, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: 2021-03-12T19:14:32.176083Z qemu-system-x86_64: -device vfio-pci,host=0000:02:00.0,id=hostdev2,bus=pci.3,addr=0x0: vfio 0000:02:00.0: group 1 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
```

EDIT4: This one I think I can fix, I just double checked and two of my gpu are reporting in t he same IOMMU Group so I will need the ACS patch:

```
IOMMU Group 1 00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port [8086:0151] (rev 09)
IOMMU Group 1 00:01.1 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port [8086:0155] (rev 09)
IOMMU Group 1 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF104 [GeForce GTX 460] [10de:0e22] (rev a1)
IOMMU Group 1 01:00.1 Audio device [0403]: NVIDIA Corporation GF104 High Definition Audio Controller [10de:0beb] (rev a1)
IOMMU Group 1 02:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] [10de:1c82] (rev a1)
IOMMU Group 1 02:00.1 Audio device [0403]: NVIDIA Corporation GP107GL High Definition Audio Controller [10de:0fb9] (rev a1)
```

EDIT5: xanmod includes the ACS patch by default, which is great for me! I am already up and running, just had to add the instructions to grub:

```
sudo nano /etc/default/grub

GRUB_CMDLINE_LINUX_DEFAULT="splash quiet iommu=1 intel_iommu=on pcie_acs_override=downstream vfio-pci.ids=10de:1c82,10de:0fb9,8086:1e20"

sudo update-initramfs -u
sudo update-grub
sudo reboot
```

**Comment by crobinso** [comment]
Thanks for the report. According to that kubevirt issue this was a qemu bug that should be fixed by now. Another workaround is likely to use mode='host-passthrough' instead of host-model. virt-manager will be switching to that soon

**Comment by wanfuse123** [comment]
I get the same general set of errors:
2023-01-20 13:57:04.661+0000: shutting down, reason=shutdown
2023-01-20 14:12:05.568+0000: Starting external device: TPM Emulator
/usr/bin/swtpm socket --ctrl type=unixio,path=/run/libvirt/qemu/swtpm/1-Windows-10-swtpm.sock,mode=0600 --tpmstate dir=/var/lib/libvirt/swtpm/6c9ea432-98d0-44e8-91dd-2cd35da7ea90/tpm2,mode=0600 --log file=/var/log/swtpm/libvirt/qemu/Windows-10-swtpm.log --terminate --tpm2
2023-01-20 14:12:05.828+0000: starting up libvirt version: 8.6.0, package: 0ubuntu3.1 (Christian Ehrhardt <christian.ehrhardt@canonical.com> Tue, 22 Nov 2022 11:21:30 +0100), qemu version: 7.0.0Debian 1:7.0+dfsg-7ubuntu2.1, kernel: 5.19.0-29-generic, hostname: Desktop-1d
LC_ALL=C \
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
HOME=/var/lib/libvirt/qemu/domain-1-Windows-10 \
XDG_DATA_HOME=/var/lib/libvirt/qemu/domain-1-Windows-10/.local/share \
XDG_CACHE_HOME=/var/lib/libvirt/qemu/domain-1-Windows-10/.cache \
XDG_CONFIG_HOME=/var/lib/libvirt/qemu/domain-1-Windows-10/.config \
/usr/bin/qemu-system-x86_64 \
-name guest=Windows-10,debug-threads=on \
-S \
-object '{"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-1-Windows-10/master-key.aes"}' \
-machine pc-q35-4.2,usb=off,vmport=off,dump-guest-core=off,memory-backend=pc.ram \
-accel kvm \
-cpu Haswell-noTSX-IBRS,vme=on,ss=on,vmx=on,pdcm=on,f16c=on,rdrand=on,hypervisor=on,arat=on,tsc-adjust=on,umip=on,md-clear=on,stibp=on,arch-capabilities=on,ssbd=on,xsaveopt=on,pdpe1gb=on,abm=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,skip-l1dfl-vmentry=on,pschange-mc-no=on,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff \
-m 4096 \
-object '{"qom-type":"memory-backend-ram","id":"pc.ram","size":4294967296}' \
-overcommit mem-lock=off \
-smp 2,sockets=2,cores=1,threads=1 \
-uuid 6c9ea432-98d0-44e8-91dd-2cd35da7ea90 \
-no-user-config \
-nodefaults \
-chardev socket,id=charmonitor,fd=31,server=on,wait=off \
-mon chardev=charmonitor,id=monitor,mode=control \
-rtc base=localtime,driftfix=slew \
-global kvm-pit.lost_tick_policy=delay \
-no-hpet \
-no-shutdown \
-global ICH9-LPC.disable_s3=1 \
-global ICH9-LPC.disable_s4=1 \
-boot menu=on,strict=on \
-device '{"driver":"pcie-root-port","port":16,"chassis":1,"id":"pci.1","bus":"pcie.0","multifunction":true,"addr":"0x2"}' \
-device '{"driver":"pcie-root-port","port":17,"chassis":2,"id":"pci.2","bus":"pcie.0","addr":"0x2.0x1"}' \
-device '{"driver":"pcie-root-port","port":18,"chassis":3,"id":"pci.3","bus":"pcie.0","addr":"0x2.0x2"}' \
-device '{"driver":"pcie-root-port","port":19,"chassis":4,"id":"pci.4","bus":"pcie.0","addr":"0x2.0x3"}' \
-device '{"driver":"pcie-root-port","port":20,"chassis":5,"id":"pci.5","bus":"pcie.0","addr":"0x2.0x4"}' \
-device '{"driver":"pcie-root-port","port":21,"chassis":6,"id":"pci.6","bus":"pcie.0","addr":"0x2.0x5"}' \
-device '{"driver":"qemu-xhci","p2":15,"p3":15,"id":"usb","bus":"pci.2","addr":"0x0"}' \
-device '{"driver":"virtio-serial-pci","id":"virtio-serial0","bus":"pci.3","addr":"0x0"}' \
-blockdev '{"driver":"file","filename":"/home/steven/Downloads/Win10_21H2_English_x64.iso","node-name":"libvirt-3-storage","auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-3-format","read-only":true,"driver":"raw","file":"libvirt-3-storage"}' \
-device '{"driver":"ide-cd","bus":"ide.1","drive":"libvirt-3-format","id":"sata0-0-1"}' \
-blockdev '{"driver":"file","filename":"/home/steven/Downloads/virtio-win-0.1.215.iso","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-2-format","read-only":true,"driver":"raw","file":"libvirt-2-storage"}' \
-device '{"driver":"ide-cd","bus":"ide.2","drive":"libvirt-2-format","id":"sata0-0-2","bootindex":2}' \
-blockdev '{"driver":"file","filename":"/home/steven/VMs/Windows-10/Windows-10.qcow2","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-1-format","read-only":false,"driver":"qcow2","file":"libvirt-1-storage","backing":null}' \
-device '{"driver":"virtio-blk-pci","bus":"pci.1","addr":"0x0","drive":"libvirt-1-format","id":"virtio-disk0","bootindex":1}' \
-netdev tap,fd=33,vhost=on,vhostfd=35,id=hostnet0 \
-device '{"driver":"virtio-net-pci","netdev":"hostnet0","id":"net0","mac":"52:54:00:ea:be:84","bus":"pci.4","addr":"0x0"}' \
-chardev pty,id=charserial0 \
-device '{"driver":"isa-serial","chardev":"charserial0","id":"serial0","index":0}' \
-chardev spicevmc,id=charchannel0,name=vdagent \
-device '{"driver":"virtserialport","bus":"virtio-serial0.0","nr":1,"chardev":"charchannel0","id":"channel0","name":"com.redhat.spice.0"}' \
-chardev socket,id=chrtpm,path=/run/libvirt/qemu/swtpm/1-Windows-10-swtpm.sock \
-tpmdev emulator,id=tpm-tpm0,chardev=chrtpm \
-device '{"driver":"tpm-crb","tpmdev":"tpm-tpm0","id":"tpm0"}' \
-device '{"driver":"usb-tablet","id":"input0","bus":"usb.0","port":"1"}' \
-audiodev '{"id":"audio1","driver":"spice"}' \
-spice port=5900,addr=127.0.0.1,disable-ticketing=on,image-compression=off,seamless-migration=on \
-device '{"driver":"virtio-vga","id":"video0","max_outputs":1,"bus":"pcie.0","addr":"0x1"}' \
-device '{"driver":"ich9-intel-hda","id":"sound0","bus":"pcie.0","addr":"0x1b"}' \
-device '{"driver":"hda-duplex","id":"sound0-codec0","bus":"sound0.0","cad":0,"audiodev":"audio1"}' \
-chardev spicevmc,id=charredir0,name=usbredir \
-device '{"driver":"usb-redir","chardev":"charredir0","id":"redir0","bus":"usb.0","port":"2"}' \
-chardev spicevmc,id=charredir1,name=usbredir \
-device '{"driver":"usb-redir","chardev":"charredir1","id":"redir1","bus":"usb.0","port":"3"}' \
-device '{"driver":"virtio-balloon-pci","id":"balloon0","bus":"pci.5","addr":"0x0"}' \
-sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny \
-msg timestamp=on
char device redirected to /dev/pts/0 (label charserial0)
2023-01-20T14:12:06.028218Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-register [bit 8]
2023-01-20T14:12:06.028311Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]
2023-01-20T14:12:06.028320Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2023-01-20T14:12:06.028952Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-register [bit 8]
2023-01-20T14:12:06.028960Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]
2023-01-20T14:12:06.028964Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]

kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

my error seems to have occured after upgrading to ubuntu 22.10, this might not be the case though, I have not used it for some time, maybe a couple of months

in addition I am a windows VM (only one I have that is not defunct(hard drive switch) 

runs ok according to the process graph in the background, but when I click on the "open" button it gives me the error:
Error launching details: Host does not support virtualization type hvm for architecture 'x86_64'


and yes virtualization is enabled in the bios (only 2 related settings with this system) does not support passthrough



sudo virsh -c qemu:///system capabilities
<capabilities>

  <host>
    <uuid>61347b80-35cf-11e5-8208-3464a9249942</uuid>
    <cpu>
      <arch>x86_64</arch>
      <model>Westmere-IBRS</model>
      <vendor>Intel</vendor>
      <microcode version='40'/>
      <signature family='6' model='60' stepping='3'/>
      <counter name='tsc' frequency='3591682000' scaling='no'/>
      <topology sockets='1' dies='1' cores='2' threads='2'/>
      <feature name='vme'/>
      <feature name='ds'/>
      <feature name='acpi'/>
      <feature name='ss'/>
      <feature name='ht'/>
      <feature name='tm'/>
      <feature name='pbe'/>
      <feature name='pclmuldq'/>
      <feature name='dtes64'/>
      <feature name='monitor'/>
      <feature name='ds_cpl'/>
      <feature name='vmx'/>
      <feature name='est'/>
      <feature name='tm2'/>
      <feature name='fma'/>
      <feature name='xtpr'/>
      <feature name='pdcm'/>
      <feature name='pcid'/>
      <feature name='movbe'/>
      <feature name='tsc-deadline'/>
      <feature name='xsave'/>
      <feature name='osxsave'/>
      <feature name='avx'/>
      <feature name='f16c'/>
      <feature name='rdrand'/>
      <feature name='arat'/>
      <feature name='fsgsbase'/>
      <feature name='tsc_adjust'/>
      <feature name='bmi1'/>
      <feature name='avx2'/>
      <feature name='smep'/>
      <feature name='bmi2'/>
      <feature name='erms'/>
      <feature name='invpcid'/>
      <feature name='md-clear'/>
      <feature name='stibp'/>
      <feature name='ssbd'/>
      <feature name='xsaveopt'/>
      <feature name='pdpe1gb'/>
      <feature name='rdtscp'/>
      <feature name='abm'/>
      <feature name='invtsc'/>
      <pages unit='KiB' size='4'/>
      <pages unit='KiB' size='2048'/>
      <pages unit='KiB' size='1048576'/>
    </cpu>
    <power_management>
      <suspend_mem/>
    </power_management>
    <iommu support='no'/>
    <migration_features>
      <live/>
      <uri_transports>
        <uri_transport>tcp</uri_transport>
        <uri_transport>rdma</uri_transport>
      </uri_transports>
    </migration_features>
    <topology>
      <cells num='1'>
        <cell id='0'>
          <memory unit='KiB'>16114984</memory>
          <pages unit='KiB' size='4'>4028746</pages>
          <pages unit='KiB' size='2048'>0</pages>
          <pages unit='KiB' size='1048576'>0</pages>
          <distances>
            <sibling id='0' value='10'/>
          </distances>
          <cpus num='4'>
            <cpu id='0' socket_id='0' die_id='0' core_id='0' siblings='0,2'/>
            <cpu id='1' socket_id='0' die_id='0' core_id='1' siblings='1,3'/>
            <cpu id='2' socket_id='0' die_id='0' core_id='0' siblings='0,2'/>
            <cpu id='3' socket_id='0' die_id='0' core_id='1' siblings='1,3'/>
          </cpus>
        </cell>
      </cells>
    </topology>
    <cache>
      <bank id='0' level='3' type='both' size='3' unit='MiB' cpus='0-3'/>
    </cache>
    <secmodel>
      <model>apparmor</model>
      <doi>0</doi>
    </secmodel>
    <secmodel>
      <model>dac</model>
      <doi>0</doi>
      <baselabel type='kvm'>+1000:+1000</baselabel>
      <baselabel type='qemu'>+1000:+1000</baselabel>
    </secmodel>
  </host>

</capabilities>
