### ISSUE TITLE
virt-manager unresponsive / force closes on debian (crostini)

### ISSUE THREAD

**Issue by bmfesta2009** [virt-manager/virt-manager#236]
**Distro**: Debian Buster / Crostini

As of last Friday when ChromeOS updated to version 89 on my device I am unable to hold a Virt-Manager session open.  I get one of two experiences at random:
1. The session is extremely slow and unresponsive to updating the screen at all, I have to keep closing and reopening to get UI updates.
2. The viewer to the virtual session will close with any rapid graphics changes.  An example that causes this is the boot animation, open the start menu, moving a window.  As long as nothing changes it's fine, but once you try just about any action is closes the window.  

I'm looking for help as to how I can diagnose what went from a smoothly running system to something that is unusable.

For your reference here are the related package versions (_I have updated everything to match their latest git source to eliminate legacy defects_)
virt-manager: 3.2
spice: 29-1
qemu: 5.2
libvirt: 7.0
linux: 5.4

**The results of virt-manager --debug option don't help much:**
> [Sat, 20 Mar 2021 21:51:52 virt-manager 2875] DEBUG (storage:139) Found default pool name=default target=/var/lib/libvirt/images
> [Sat, 20 Mar 2021 21:51:52 virt-manager 2875] DEBUG (connection:482) conn=qemu:///system changed to state=Active
> [Sat, 20 Mar 2021 21:51:58 virt-manager 2875] DEBUG (serialcon:17) Using VTE API 2.91
> [Sat, 20 Mar 2021 21:51:58 virt-manager 2875] DEBUG (xmleditor:12) Using GtkSource 4
> [Sat, 20 Mar 2021 21:51:58 virt-manager 2875] DEBUG (vmwindow:184) Showing VM details: <vmmDomain name=Windows10 id=0x7b169c880a80>
> [Sat, 20 Mar 2021 21:51:58 virt-manager 2875] DEBUG (engine:316) window counter incremented to 2
> [Sat, 20 Mar 2021 21:52:05 virt-manager 2875] DEBUG (vmmenu:230) Starting vm 'Windows10'
> [Sat, 20 Mar 2021 21:52:06 virt-manager 2875] DEBUG (connection:631) domain lifecycle event: domain=Windows10 state=VIR_DOMAIN_EVENT_RESUMED reason=VIR_DOMAIN_EVENT_RESUMED_UNPAUSED
> [Sat, 20 Mar 2021 21:52:06 virt-manager 2875] DEBUG (connection:631) domain lifecycle event: domain=Windows10 state=VIR_DOMAIN_EVENT_STARTED reason=VIR_DOMAIN_EVENT_STARTED_BOOTED
> [Sat, 20 Mar 2021 21:52:06 virt-manager 2875] DEBUG (console:721) Starting connect process for proto=spice trans= connhost=127.0.0.1 connuser= connport= gaddr=127.0.0.1 gport=5900 gtlsport=None gsocket=None
> [Sat, 20 Mar 2021 21:52:06 virt-manager 2875] DEBUG (viewers:588) Requesting fd for channel: <SpiceClientGLib.DisplayChannel object at 0x7b1687a1f600 (SpiceDisplayChannel at 0x2a6ab00)>
> [Sat, 20 Mar 2021 21:52:06 virt-manager 2875] DEBUG (console:846) Viewer connected
> 
> (virt-manager:2875): GSpice-WARNING **: 21:52:06.179: Warning no automount-inhibiting implementation available
> [Sat, 20 Mar 2021 21:52:06 virt-manager 2875] DEBUG (viewers:588) Requesting fd for channel: <SpiceClientGLib.CursorChannel object at 0x7b1687a21640 (SpiceCursorChannel at 0x55a0350)>
> [Sat, 20 Mar 2021 21:52:06 virt-manager 2875] DEBUG (viewers:588) Requesting fd for channel: <SpiceClientGLib.InputsChannel object at 0x7b1687a199c0 (SpiceInputsChannel at 0x55a0650)>

**And neither do the libvirt qemu logs:**
> 2021-03-21 01:52:05.334+0000: starting up libvirt version: 7.0.0, package: 3 (Andrea Bolognani <eof@kiyuko.org> Fri, 26 Feb 2021 16:46:34 +0100), qemu version: 5.2.0Debian 1:5.2+dfsg-9, kernel: 5.4.88-12224-gf05236dbdecf, hostname: penguin
> LC_ALL=C \
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
> HOME=/var/lib/libvirt/qemu/domain-11-Windows10 \
> XDG_DATA_HOME=/var/lib/libvirt/qemu/domain-11-Windows10/.local/share \
> XDG_CACHE_HOME=/var/lib/libvirt/qemu/domain-11-Windows10/.cache \
> XDG_CONFIG_HOME=/var/lib/libvirt/qemu/domain-11-Windows10/.config \
> QEMU_AUDIO_DRV=spice \
> /usr/bin/qemu-system-x86_64 \
> -name guest=Windows10,debug-threads=on \
> -S \
> -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-11-Windows10/master-key.aes \
> -machine pc-q35-5.2,accel=kvm,usb=off,vmport=off,dump-guest-core=off,memory-backend=pc.ram \
> -cpu Skylake-Client-IBRS,ss=on,vmx=on,hypervisor=on,tsc-adjust=on,clflushopt=on,umip=on,md-clear=on,stibp=on,arch-capabilities=on,ssbd=on,xsaves=on,pdpe1gb=on,ibpb=on,amd-stibp=on,amd-ssbd=on,rdctl-no=on,ibrs-all=on,skip-l1dfl-vmentry=on,mds-no=on,pschange-mc-no=on,hle=off,rtm=off,hv-time,hv-relaxed,hv-vapic,hv-spinlocks=0x1fff \
> -m 4000 \
> -object memory-backend-ram,id=pc.ram,size=4194304000 \
> -overcommit mem-lock=off \
> -smp 1,sockets=1,cores=1,threads=1 \
> -uuid 2de2cdbb-0a21-43fb-9836-a3081f66cee6 \
> -no-user-config \
> -nodefaults \
> -chardev socket,id=charmonitor,fd=33,server,nowait \
> -mon chardev=charmonitor,id=monitor,mode=control \
> -rtc base=localtime,driftfix=slew \
> -global kvm-pit.lost_tick_policy=delay \
> -no-hpet \
> -no-shutdown \
> -global ICH9-LPC.disable_s3=1 \
> -global ICH9-LPC.disable_s4=1 \
> -boot strict=on \
> -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 \
> -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 \
> -device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 \
> -device pcie-root-port,port=0x13,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3 \
> -device pcie-root-port,port=0x14,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4 \
> -device qemu-xhci,p2=15,p3=15,id=usb,bus=pci.2,addr=0x0 \
> -device virtio-serial-pci,id=virtio-serial0,bus=pci.3,addr=0x0 \
> -blockdev '{"driver":"file","filename":"/var/lib/libvirt/images/Windows10.qcow2","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}' \
> -blockdev '{"node-name":"libvirt-1-format","read-only":false,"driver":"qcow2","file":"libvirt-1-storage","backing":null}' \
> -device ide-hd,bus=ide.0,drive=libvirt-1-format,id=sata0-0-0,bootindex=1 \
> -spice port=5900,addr=127.0.0.1,disable-ticketing,image-compression=off,seamless-migration=on \
> -device VGA,id=video0,vgamem_mb=16,bus=pcie.0,addr=0x1 \
> -device virtio-balloon-pci,id=balloon0,bus=pci.4,addr=0x0 \
> -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny \
> -msg timestamp=on
> 2021-03-21T01:52:05.511332Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48FH).vmx-exit-load-perf-global-ctrl [bit 12]
> 2021-03-21T01:52:05.511444Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(490H).vmx-entry-load-perf-global-ctrl [bit 13]

Let me know what else I can provide.

**Comment by bfestaworkwave** [comment]
Here is some more detail.  Here is the response from an event with the display crashes on me:
```
(virt-manager:4614): GSpice-WARNING **: 08:31:19.645: Warning no automount-inhibiting implementation available
[Mon, 22 Mar 2021 08:31:19 virt-manager 4614] DEBUG (viewers:588) Requesting fd for channel: <SpiceClientGLib.CursorChannel object at 0x7cb00422cfc0 (SpiceCursorChannel at 0x4e14390)>
[Mon, 22 Mar 2021 08:31:19 virt-manager 4614] DEBUG (viewers:588) Requesting fd for channel: <SpiceClientGLib.InputsChannel object at 0x7caff37fe240 (SpiceInputsChannel at 0x4e14690)>
Gdk-Message: 08:32:15.206: Error reading events from display: Broken pipe
```

Any recommendation on how I can see where the error reading events from display is coming from.

**Comment by crobinso** [comment]
Thanks for the report. Not sure what the issue is unfortunately, sounds spice or guest OS related.
Try reproducing with `virt-viewer`, if so that will eliminate virt-manager from the equation.
Next you can switch the VM to using 'VNC' graphics, if it works then you know it's spice related somehow, otherwise it could be a generic guest issue.
If spice is the culprit, you could try switching the video device type to QXL and installing windows QXL drivers inside the guest, they are on the virtio-win iso: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso

**Comment by bfestaworkwave** [comment]
@crobinso thank you for your help, I have been through those, but let me humor the conversation.  

VNC gives me a similar issue and this is using virt-viewer instead of virt-manager when connecting to display server:
`[Wed, 07 Apr 2021 08:44:41 virt-manager 3138] DEBUG (console:846) Viewer connected
[Wed, 07 Apr 2021 08:53:06 virt-manager 3138] DEBUG (console:592) Viewer disconnected
[Wed, 07 Apr 2021 08:53:06 virt-manager 3138] DEBUG (console:838) Viewer disconnected
[Wed, 07 Apr 2021 08:53:21 virt-manager 3138] DEBUG (vmwindow:242) Closing VM details: <vmmDomain name=guestOS id=0x7bedf82a0900>
[Wed, 07 Apr 2021 08:53:21 virt-manager 3138] DEBUG (engine:323) window counter decremented to 1
Gdk-Message: 08:53:21.525: Error reading events from display: Broken pipe`

Side note, I have attempted to create a new Windows 10 VM and starting fresh using the ISO from Microsoft's site it no longer gets into the installation process, it shows the windows boot screen but the dots rotate extremely slow.  I let it sit for 4 hours but no response.

**Comment by bfestaworkwave** [comment]
After digging in more detail I have narrowed the scenario down to spice client.  Thank you for your help in tracing the defect.  Heading over there now.  This case can be closed from virt-manager.
