### ISSUE TITLE
DNS domain name needlessly limited to 20 chars in UI

### ISSUE THREAD

**Issue by sur5r** [virt-manager/virt-manager#238]
https://github.com/virt-manager/virt-manager/blob/f4eed368630d38173ebb40503c36a8a3c1d5c103/ui/createnet.ui#L733

limits the DNS domain name to 20 characters while the XML schema in https://github.com/libvirt/libvirt/blob/master/docs/schemas/network.rng#L255 and https://github.com/libvirt/libvirt/blob/master/docs/schemas/basictypes.rng#L283 does not contain such a limit.

In fact, using the XML part of the network creation dialog allows a longer name just fine.

**Comment by crobinso** [comment]
Thanks for the report, that is indeed bogus. I'll fix it shortly
