### ISSUE TITLE
[RFE] virt-install: Add support for "fwcfg" (firmware configuration)

### ISSUE THREAD

**Issue by kashyapc** [virt-manager/virt-manager#239]
Currently if you want to use the `fwcfg` element[1] in libvirt, you either to manually edit the guest XML via `virsh`.  (Or with a recent enough `virt-manager`, I'm told you can edit the guest XML from the GUI itself.)

It'd be nice to have support for `fwcfg` in `virt-install` (and `virt-xml`), to avoid having to hand-edit the guest XML.

[1] `grep` for "fwcfg" here for documentation: https://libvirt.org/formatdomain.html#smbios-system-information

**Comment by crobinso** [comment]
Thanks for the suggestion, but it's already in virt-install with version 3.0 :) It's under the --sysinfo option, like the domain XML. See commit 65f93e5d60c5076aeba8a3059db4832e4e0db5de
