### ISSUE TITLE
Draft copy_file_range support for reflinks and other zero copy clones

### ISSUE THREAD

**Issue by nicman23** [virt-manager/virt-manager#240]
Hello, first real project i ve messed with python. I am slowly implementing reflink (i am missing the ui code - actual reflink works) through os.copy_file_range

atm it works for local clones only (and stuff breaks). any help appreciated

https://github.com/nicman23/virt-manager/commit/ec2a6c4d013097ba19cdf1c66d81ccd9160d9b55#diff-229854253e95ddb601cf33798468d9bc992eb677428f8889b80bcb9f83ec830f

if the file is nocow and or on a non cow fs it fallbacks to copy.

**Comment by nicman23** [comment]
also support for remote ie system:/// seams to be already in place but with no ui ?

**Comment by crobinso** [comment]
Thanks for the contribution. If you get something working please submit it as a PR and we can discuss there
