### ISSUE TITLE
White Mouse in Windows 10 Guest

### ISSUE THREAD

**Issue by arrmo** [virt-manager/virt-manager#249]
**Distro**: Ubuntu 20.10

Hi,

I'm seeing this only with QXL + virt-manager (or virt-viewer), and with the latest ISO (drivers) installed. The mouse is fully white ... so on a white window ... well, that doesn't work so well 😆. Is this a known issue?

FYI, I don't see the same issue if connection to the VM via VNC or RDP.

Thanks!

**Comment by crobinso** [comment]
qxl has had mouse weirdness in the past but I haven't heard of this issue before. Using Windows 10 I'm guessing? You could try downgrading the qxl driver, a new version came out in February, maybe it's a regression. Unpackaged drivers can be downloaded here: https://www.spice-space.org/download/windows/qxl-wddm-dod/

I think the proper place to report this is here though: https://gitlab.freedesktop.org/spice/win32/qxl-wddm-dod

**Comment by crobinso** [comment]
Also thank you for testing virt-viewer and VNC, that helps narrow down the problem scope a lot!
