### ISSUE TITLE
KVM "autoresize VM with window" greyed out and guest agent is not available

### ISSUE THREAD

**Issue by archalchemy** [virt-manager/virt-manager#250]
**Distro**:  MXLinux

Hello community I wanted to ask your kind help to solve my problem. I cannot resize the Virt-Manager window for a Windows guest. It also doesn't allow me to drag files to the guest. I don't know what is missing in my configuration. Has anyone of you presented the same problem?

I attach images for more detail of the problem:

![IMG_20210508_122218](https://user-images.githubusercontent.com/61000333/117548013-39b75b00-aff8-11eb-82c1-f1cf6987698f.jpg)

It is important to mention that I have the Spice Guest Tools installed:

![2021-05-08_12-33](https://user-images.githubusercontent.com/61000333/117548341-1b525f00-affa-11eb-9042-16a4b6deb69b.png)

I also have the Spice Agent for Linux installed on the host:

![2021-04-27_11-10](https://user-images.githubusercontent.com/61000333/117548383-55236580-affa-11eb-8e30-910f21ccc51d.png)

Quick System Info:

`

System:    Host: <filter> Kernel: 5.10.0-5mx-amd64 x86_64 bits: 64 compiler: N/A 
           Desktop: KDE Plasma 5.14.5 wm: kwin_x11 dm: SDDM Distro: MX-19.4_kde_x64 patito feo March 31  2021 
           base: Debian GNU/Linux 10 (buster) 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Picasso vendor: Hewlett-Packard driver: amdgpu v: kernel bus ID: 04:00.0 
           chip ID: 1002:15d8 
           Display: x11 server: X.Org 1.20.10 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa compositor: kwin_x11 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: AMD Radeon Vega 8 Graphics (RAVEN DRM 3.40.0 5.10.0-5mx-amd64 LLVM 11.0.1) v: 4.6 Mesa 20.3.4 
           direct render: Yes 
Info:      Processes: 278 Uptime: 11h 32m Memory: 13.67 GiB used: 5.20 GiB (38.1%) Init: SysVinit v: 2.93 runlevel: 5 
           default: 5 Compilers: gcc: 8.3.0 alt: 8 Shell: quick-system-in running in: quick-system-in inxi: 3.0.36 

`

Additionally, I add the version of KVM (qemu-kvm) that I have installed on my system, which is the one that I am using to virtualize the Windows guest.

`

$ apt show qemu-system-x86
Package: qemu-system-x86
Version: 1:3.1+dfsg-8+deb10u8
Priority: optional
Section: otherosfs
Source: qemu
Maintainer: Debian QEMU Team <pkg-qemu-devel@lists.alioth.debian.org>
Installed-Size: 26.9 MB
Provides: qemu-system-i386, qemu-system-x86-64
Depends: libaio1 (>= 0.3.93), libasound2 (>= 1.0.16), libbluetooth3 (>= 4.91), libbrlapi0.6, libc6 (>= 2.28), libcacard0 (>= 2.2), libcapstone3 (>= 3.0.0), libepoxy0 (>= 1.3), libfdt1, libgbm1 (>= 7.11~1), libgcc1 (>= 1:4.7), libglib2.0-0 (>= 2.31.8), libgnutls30 (>= 3.6.6), libibverbs1 (>= 1.1.6), libjpeg62-turbo (>= 1.3.1), libncursesw6 (>= 6), libnettle6, libnuma1 (>= 2.0.11), libpixman-1-0 (>= 0.19.6), libpng16-16 (>= 1.6.2-1), librdmacm1 (>= 1.0.15), libsasl2-2 (>= 2.1.27+dfsg), libseccomp2 (>= 2.3.0), libspice-server1 (>= 0.13.1), libtinfo6 (>= 6), libusb-1.0-0 (>= 2:1.0.22), libusbredirparser1 (>= 0.6), libvdeplug2, libvirglrenderer0 (>= 0.7.0), libxendevicemodel1, libxenevtchn1, libxenforeignmemory1, libxengnttab1, libxenmisc4.11, libxenstore3.0 (>= 4.1.0~rc6), libxentoolcore1, zlib1g (>= 1:1.2.0), qemu-system-common (>> 1:2.12~), qemu-system-data (>> 1:3.1+dfsg-8+deb10u8~), seabios (>= 1.10.2-1~), ipxe-qemu (>= 1.0.0+git-20131111.c3d1e78-1~)
Recommends: qemu-system-gui (= 1:3.1+dfsg-8+deb10u8), qemu-utils, ovmf
Suggests: samba, vde2, qemu-block-extra (= 1:3.1+dfsg-8+deb10u8), sgabios
Homepage: http://www.qemu.org/
Tag: uitoolkit::gtk, uitoolkit::ncurses, uitoolkit::sdl
Download-Size: 5,877 kB
APT-Manual-Installed: no
APT-Sources: http://ftp.us.debian.org/debian buster/main amd64 Packages
Description: QEMU full system emulation binaries (x86)
 QEMU is a fast processor emulator: currently the package supports
 i386 and x86-64 emulation. By using dynamic translation it achieves
 reasonable speed while being easy to port on new host CPUs.
 .
 This package provides the full system emulation binaries to emulate
 the following x86 hardware:  i386 x86_64.
 .
 In system emulation mode QEMU emulates a full system, including a processor
 and various peripherals.  It enables easier testing and debugging of system
 code.  It can also be used to provide virtual hosting of several virtual
 machines on a single server.
 .
 On x86 host hardware this package also enables KVM kernel virtual machine
 usage on systems which supports it.

`

**Comment by crobinso** [comment]
This isn't the best forum for these types of questions. better to ask in distro specific forums or generic places like superuser/stackexchange.

I don't know if it's related but your spice-guest-tools version is old. The latest thing to use is virtio-win-guest-tools: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win-guest-tools.exe

qemu version is pretty old too, which probably means spice-gtk version is old as well. Not sure if that impacts things or not. Make sure your VM has a 'Channel spice' device configured which is necessary for the agent to work. spice agent installed on the host doesn't do anything in this case
