### ISSUE TITLE
Mouse pointer disappears when it is over console window

### ISSUE THREAD

**Issue by adrianomarto** [virt-manager/virt-manager#251]
The host mouse pointer disappears when it is over a console window.

I am emulating quite simple hardware: just text console and no mouse. I don't expect the mouse to have any effect on the emulated computers, but I need to know where the mouse pointer is. That is important because I need to use the mouse to switch between applications and to switch between virtual machines (QEMU grabs Alt+Tab events). Also, it is quite tricky to work with multiple screens when we don't know where the mouse pointer is.

I am using:
* Virtual Machine Manager 2.2.1
* QEMU 4.2.0
* Fedora 32
* KDE Plasma 5.18.5
* Distro: Fedora 32

I also reported this issue in
https://bugs.launchpad.net/qemu/+bug/1890208

**Comment by crobinso** [comment]
Does your VM have a 'Tablet' device attached? If so try removing it.

**Comment by adrianomarto** [comment]
I tried it, and it actually made things worse. When I have the tablet device, the mouse pointer disappears when it is over a console window but it reappears when I move the mouse out of the console window. Without the table device, the mouse pointer disappears for good. The only way to bring the mouse pointer back is to stop the virtual machine.

**Comment by crobinso** [comment]
Without the tablet device, when you click inside the VM, it 'grabs' the pointer and confines it to the VM window. You ungrab by clicking ctrl+alt. This should be explained in the window title.

It seems like the root issue is that the guest is not showing the pointer under any circumstance. What is the video model configured for the VM? Try switching it, like from qxl to virtio or vga.

**Comment by adrianomarto** [comment]
You are right about the mouse being grabbed and the ctrl-alt.
I tried using the three video models (qxl, virtio, and vga). They all behave exactly the same. The mouse pointer is not presented when it is over the console window.

**Comment by crobinso** [comment]
It's likely either a spice-gtk or a guest bug at that point then. Try using a new host distro to start, and fully updating your guest. Maybe try a different desktop environment temporarily inside the VM to see if KDE is the culprit. But it's not looking like a virt-manager issue at this point

**Comment by oxygen** [comment]
I'm experiencing the same after doing grab keyboard shortcut then fullscreen keyboard shortcut.

I'm using tablet mouse too which was the only way to get a mouse.

To clarify, the mouse dissapearance means the mouse pointer no longer **exists**, as in mouse move and clicks are no longer registered at all. 

Ungrabbing does not cause the mouse pointer to reappear or register events.

Closing the VM is the only solution.

Rarely, the keyboard goes away too for good, including ungrab and unfullscreen keyboard shortcuts, requiring a reboot of the host to essentially regain control.

These issues appeared after I switched from Ubuntu 20.04 with some qemu 4.x (was it 4.3?) to Ubuntu 22.04 with qemu 6.x

Also, worth mentioning is that if grabbing is done AFTER going fullscreen, then grabbing doesn't actually happen (it worked fine in ubuntu 20.04 with qemu 4). 
However, if grabbing BEFORE going fullscreen then grabbing works (alt tab and such are now registered in the guest OS) but the mouse is destroyed permanently (both pointer and mouse events).

**Comment by widhaya3** [comment]
Press ALT+F for menu drop down, worked for me.

**Comment by shodanx2** [comment]
Just out of curiosity 
Was your disappearing cursor problem like this ?

https://github.com/user-attachments/assets/21498f59-21a2-43f5-9ab3-9fc24b2c17ee

**Comment by adrianomarto** [comment]
Hi @shodanx2,
No, the mouse cursor wasn't disappearing as it does in the video. In my case, the mouse cursor consistently disappeared whenever it was over the emulated VM screen and remained invisible until I moved it out of the emulated VM screen.
I haven't used that setup for quite some time, so I don't know if the bug is still current.
Cheers,
Adriano.
