### ISSUE TITLE
Switch away from distutils

### ISSUE THREAD

**Issue by ptoscano** [virt-manager/virt-manager#252]
The Python `distutils` module is officially deprecated as of Python 3.10, scheduled for removal from the standard library as of Python 3.12. This is documented in PEP 632 [1].

Hence, the buildsystem should be ported away from `distutils`, most likely to `setuptools`; the text of the PEP lists some alternatives for `distutils` bits.

[1] https://www.python.org/dev/peps/pep-0632/

**Comment by crobinso** [comment]
Thanks for the pointer Pino!

**Comment by crobinso** [comment]
There's still one usage of distutils left, but it doesn't appear there's a setuptools replacement for it yet. Maybe one will pop up, but if not it should be easy to hack around it when the time comes.
