### ISSUE TITLE
get no graphical console: "Connecting to graphical console for guest" 

### ISSUE THREAD

**Issue by volker-raschek** [virt-manager/virt-manager#253]
Hi, 
since some weeks I can not any more connect to my remote VMs. When I want to open the graphical console I get a view with the message "Mit grafischer Konsole für Gast wird verbunden" which can be translated to "Connection to graphical console for guest". I can leave this windows open but I get no console after ten minutes. So I can not connect to some newly created remote VMs to setup the network configuration. 

At first I thought it was because my Arch Linux is too new again against the CentOS instances and a breaking change has crept in somewhere. However, the error also occurs when I want to open the graphical console of an remote Arch Linux VM. 

For instances, which are hosted locally I can successfully open the graphical console, but not for remote VMs. 

I have installed virt-manager and the other programs and libraries via the package manager pacman provided by the Arch Linux distro.

Here are some tech details. If more information are required, please let me know it.

![Bildschirmfoto vom 2021-05-17 17-27-39](https://user-images.githubusercontent.com/18311012/118514937-324d2b80-b735-11eb-8fc9-f12111ff9fb9.png)

**UPDATE**

When I use virt-viewer with a connection url, then it works. But not with the virt-manager integrated viewer.

```bash 
$ virt-viewer --connect qemu+ssh://root@192.168.178.10/system ares
```

**Comment by crobinso** [comment]
Thanks for the report. Can you reproduce with:

```console
git clone https://github.com/virt-manager/virt-manager
cd virt-manager
./virt-manager --debug
```

And attach the full debug output

**Comment by volker-raschek** [comment]
@crobinso, I receive the following stack trace when I start virt-manager from github in debug mode.

```bash
$ git clone https://github.com/virt-manager/virt-manager
cd virt-manager
./virt-manager --debug
Klone nach 'virt-manager' ...
remote: Enumerating objects: 57368, done.
remote: Counting objects: 100% (623/623), done.
remote: Compressing objects: 100% (328/328), done.
remote: Total 57368 (delta 467), reused 408 (delta 294), pack-reused 56745
Empfange Objekte: 100% (57368/57368), 84.87 MiB | 5.65 MiB/s, fertig.
Löse Unterschiede auf: 100% (47206/47206), fertig.
Traceback (most recent call last):
  File "/tmp/virt-manager/./virt-manager", line 8, in <module>
    from virtManager import virtmanager
  File "/tmp/virt-manager/./virtManager/virtmanager.py", line 21, in <module>
    from virtinst import BuildConfig
  File "/tmp/virt-manager/./virtinst/__init__.py", line 56, in <module>
    from virtinst.storage import StoragePool, StorageVolume
  File "/tmp/virt-manager/./virtinst/storage.py", line 13, in <module>
    from . import progress
  File "/tmp/virt-manager/./virtinst/progress.py", line 8, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

**Comment by fidencio** [comment]
> ```shell
> tqdm
> ```

You need `python-tqdm` installed. (https://archlinux.org/packages/community/any/python-tqdm/)

**Comment by volker-raschek** [comment]
I have installed the missing package and started virt-manager in debug mode. The error does not occur there. 

Then I updated my system again and installed some python packages. Since then, my virt-manager, which I installed via the package manager, works again. 

Thank you for your help, I think the issue has now been resolved.
