### ISSUE TITLE
Folder sharing feature is too hidden

### ISSUE THREAD

**Issue by lyrebird-sound-cloning-system** [virt-manager/virt-manager#254]
Currently, to use the Folder sharing feature, provided by spice-webdavd, you must run virt-viewer through terminal or after pressing ALT+F2 because is not available in the applications menu.

A possible solution for that would be including an option to run it menu of the VM window, like File > Virt Viewer or including an option in the File menu to open a window, orienting the user that virt-viewer must be opened for the feature to work, with a "launch Virt-Viewer" button.

**Distro**: KDE Neon 5.21.4 (based on Ubuntu 20.04)

**Comment by crobinso** [comment]
virt-viewer is a separate project, issues should be filed here: https://gitlab.com/virt-viewer/virt-viewer

**Comment by lyrebird-sound-cloning-system** [comment]
But is possible to include a shortcut to view-viewer in the File menu? This would help in terms of discoverability.
