### ISSUE TITLE
In the main screen, the text "QEMU/KVM" doesn't adapt to the theme 

### ISSUE THREAD

**Issue by lyrebird-sound-cloning-system** [virt-manager/virt-manager#255]
![Screenshot_20210523_230954](https://user-images.githubusercontent.com/84561213/119287130-3806ad80-bc1c-11eb-99c5-5ba5829abff0.png)

It isn't a color scheming issue (I'm using KDE), because this happens in the default Breeze dark theme:
![Screenshot_20210523_231220](https://user-images.githubusercontent.com/84561213/119287220-71d7b400-bc1c-11eb-9048-d39db6b365fd.png)

It was a recent change, because I remember that it wasn't like that a few weeks ago.

**Distro**:  KDE Neon 5.21.5
**Version** 2.2.1

**Comment by crobinso** [comment]
virt-manager 2.2.1 was released in July 2019. This tracker is for issues affecting latest virt-manager. Please file a bug with your distro

**Comment by lyrebird-sound-cloning-system** [comment]
ok, thanks
