### ISSUE TITLE
Erroneous physical volume size value reported

### ISSUE THREAD

**Issue by Ricky-Tigg** [virt-manager/virt-manager#256]
**OS:** Fedora 34; **Component:** virt-manager-3.2.0-3.fc34.noarch

At _Edit_ | _Connection details_ | _Storage_, files related to a Vagrant VM are dully listed, therefore parameters covering virtual and physical sizes are involved. As noticeable the physical volume _fedora_default.img_ size value reported by `virt-manager` is erroneous.

![Storage_vagent_sizes](https://user-images.githubusercontent.com/26058215/119324428-7c2f9780-bc88-11eb-8635-8b4aa1b2151b.png)

```
$ qemu-img info ~/.local/share/libvirt/images/fedora_default.img | sed -n '2,4p'
file format: qcow2
virtual size: 128 GiB (137438953472 bytes)
disk size: 360 MiB
$ cd $HOME/.local/share/libvirt/images/; stat -Lc '%s %n' *
377356288 fedora_default.img
1450573824 generic-VAGRANTSLASH-fedora33_vagrant_box_image_3.2.14.img
$ ls -l ~/.local/share/libvirt/images/ | sed 1d
-rw-------. 1 yk yk  377356288  9. 4. 13:29 fedora_default.img
-rwxr--r--. 1 yk yk 1450573824  7. 4. 14:14 generic-VAGRANTSLASH-fedora33_vagrant_box_image_3.2.14.img
```

**Comment by phrdina** [comment]
virt-manager correctly shows the `virtual size` as a disk size in the UI, that's the size visible inside the VM. The `disk size` is reporting how much the file actually takes on host.

For more details please check `qemu-img` man page or this document https://gitlab.com/qemu-project/qemu/-/blob/master/docs/tools/qemu-img.rst.
