### ISSUE TITLE
Can't create a vm using virt-install  ERROR : Index out of range

### ISSUE THREAD

**Issue by Matthis-F** [virt-manager/virt-manager#257]
On ArchLinux using kernel 5.12.6-arch1-1
virt-manager version : 3.2.0
virt-install version : 3.2.0 

Command : 
virt-install --debug --name debian --location ~/Downloads/debian-10.9.0-amd64-netinst.iso --memory 1024 --vcpus=1 --disk size=8 

Debug trace :
[Mon, 24 May 2021 19:20:10 virt-install 13662] DEBUG (cli:204) Launched with command line: /usr/bin/virt-install --debug --name debian --location /home/matthis/Downloads/debian-10.9.0-amd64-netinst.iso --memory 1024 --vcpus=1 --disk size=8
[Mon, 24 May 2021 19:20:10 virt-install 13662] DEBUG (virtinstall:212) Distilled --network options: ['default']
[Mon, 24 May 2021 19:20:10 virt-install 13662] DEBUG (virtinstall:144) Distilled --disk options: ['size=8']
[Mon, 24 May 2021 19:20:10 virt-install 13662] DEBUG (cli:216) Requesting libvirt URI default
[Mon, 24 May 2021 19:20:10 virt-install 13662] DEBUG (cli:219) Received libvirt URI qemu:///session
[Mon, 24 May 2021 19:20:10 virt-install 13662] DEBUG (storage:139) Found default pool name=default target=/home/matthis/.local/share/libvirt/images
[Mon, 24 May 2021 19:20:10 virt-install 13662] DEBUG (storage:209) refreshing pool=default
[Mon, 24 May 2021 19:20:10 virt-install 13662] DEBUG (disk:363) Creating volume 'debian.qcow2' on pool 'default'
[Mon, 24 May 2021 19:20:10 virt-install 13662] DEBUG (disk:654) disk.set_vol_install: name=debian.qcow2 poolxml=
<pool type='dir'>
  <name>default</name>
  <uuid>ad99d2a4-3098-42c2-9553-752fa44a13e1</uuid>
  <capacity unit='bytes'>950046859264</capacity>
  <allocation unit='bytes'>31308537856</allocation>
  <available unit='bytes'>918738321408</available>
  <source>
  </source>
  <target>
    <path>/home/matthis/.local/share/libvirt/images</path>
    <permissions>
      <mode>0711</mode>
      <owner>1000</owner>
      <group>1000</group>
    </permissions>
  </target>
</pool>

** (process:13662): WARNING **: 19:20:10.995: Entity http://debian.org/debian/10 referenced but not defined

** (process:13662): WARNING **: 19:20:10.995: Entity http://debian.org/debian/1.3 referenced but not defined
[Mon, 24 May 2021 19:20:11 virt-install 13662] DEBUG (cli:255)   File "/usr/bin/virt-install", line 8, in <module>
    virtinstall.runcli()
  File "/usr/share/virt-manager/virtinst/virtinstall.py", line 1165, in runcli
    fail(main_e)
  File "/usr/share/virt-manager/virtinst/cli.py", line 255, in fail
    log.debug("".join(traceback.format_stack()))

[Mon, 24 May 2021 19:20:11 virt-install 13662] ERROR (cli:256) list index out of range
[Mon, 24 May 2021 19:20:11 virt-install 13662] DEBUG (cli:258) 
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtinst/virtinstall.py", line 1158, in runcli
    sys.exit(main())
  File "/usr/share/virt-manager/virtinst/virtinstall.py", line 1145, in main
    guest, installer = build_guest_instance(conn, options)
  File "/usr/share/virt-manager/virtinst/virtinstall.py", line 585, in build_guest_instance
    guest.set_default_os_name()
  File "/usr/share/virt-manager/virtinst/guest.py", line 324, in set_default_os_name
    self.set_os_name("generic")
  File "/usr/share/virt-manager/virtinst/guest.py", line 319, in set_os_name
    obj = OSDB.lookup_os(name, raise_error=True)
  File "/usr/share/virt-manager/virtinst/osdict.py", line 232, in lookup_os
    if key not in self._all_variants and key in self._aliases:
  File "/usr/share/virt-manager/virtinst/osdict.py", line 211, in _all_variants
    osi = _OsVariant(o)
  File "/usr/share/virt-manager/virtinst/osdict.py", line 373, in __init__
    self.name = self._short_ids[0]
IndexError: list index out of range

**Comment by crobinso** [comment]
Thanks for the report, but it works fine for me with virt-manager.git and Fedora 34 host. Media is detected as debian10 by virt-install and install proceeds. Can you confirm you are seeing this with virt-manager.git too?

```python
git clone https://github.com/virt-manager/virt-manager
cd virt-manager
./virt-install ...
```
However the errors mentioned
```
** (process:13662): WARNING **: 19:20:10.995: Entity http://debian.org/debian/10 referenced but not defined
** (process:13662): WARNING **: 19:20:10.995: Entity http://debian.org/debian/1.3 referenced but not defined
```

come from libosinfo. That makes me think something is wrong with your osinfo-db install.

**Comment by Matthis-F** [comment]
> Thanks for the report, but it works fine for me with virt-manager.git and Fedora 34 host. Media is detected as debian10 by virt-install and install proceeds. Can you confirm you are seeing this with virt-manager.git too?
> 
> ```python
> git clone https://github.com/virt-manager/virt-manager
> cd virt-manager
> ./virt-install ...
> ```
> 
> However the errors mentioned
> 
> ```
> ** (process:13662): WARNING **: 19:20:10.995: Entity http://debian.org/debian/10 referenced but not defined
> ** (process:13662): WARNING **: 19:20:10.995: Entity http://debian.org/debian/1.3 referenced but not defined
> ```
> 
> come from libosinfo. That makes me think something is wrong with your osinfo-db install.

Reinstalling osinfo-db solves the issue.
Thanks a lot !
