### ISSUE TITLE
lvcreate fails when the disk space contains a valid partition signature

### ISSUE THREAD

**Issue by g-v-egidy** [virt-manager/virt-manager#259]
While testing the solution proposed in #208 I came across this problem:

When creating a new LVM volume for a new VM, it can happen that LVM decides to re-use the disk sectors that once belonged to another VM and which LVM volume got deleted. Then these sectors will still contain a valid partition table and so on. When you now have the option "wipe_signatures_when_zeroing_new_lvs = 1" in your /etc/lvm/lvm.conf, the lvcreate program detects this and asks the user if they really want to wipe the partition table. 

This leads to this error message in the virt-manager:

```
Error creating vol: Couldn't create storage volume 'centostest2': 'internal error: Child process (/usr/sbin/lvcreate --name centostest2 -L 20971520K ssd2) unexpected exit status 5: WARNING: gpt signature detected on /dev/ssd2/centostest2 at offset 512. Wipe it? [y/n]: [n]
  Aborted wiping of gpt.
  1 existing signature left on the device.
  Filed to wipe signatures of logical volume ssd2/centostest2.
  Aborting. Failed to wipe start of new LV.
  Logical volume ssd2/centostest2 in use.
  Unable to deactivate failed new LV ssd2/centostest2. Manual intervention required.
```

The volume is still created, but no wiping is done.

To prevent this, lvcreate should be called with ```--yes```. Also it should be called with ```--wipesignatures y``` to make sure that old data never confuses the boot of the newly created VM, regardless of the settings in /etc/lvm/lvm.conf.

**Comment by crobinso** [comment]
Thanks for the report. You'll need to file that against libvirt though, they handle all the storage command invocation: https://gitlab.com/libvirt/libvirt
