### ISSUE TITLE
Freeze trying to boot the newly released Windows 21H1

### ISSUE THREAD

**Issue by C0rn3j** [virt-manager/virt-manager#260]
Arch Linux running git virt-manager build from today (happens on stable release too).

```
virt-manager-git 3.2.0.r91.ga1ddd23c-1
libvirt 1:7.3.0-1
qemu 6.0.0-3
```

sha256 - 6911e839448fa999b07c321fc70e7408fe122214f5c4e80a9ccc64d22d0d85ea  (matches provided hash)
Win10_21H1_English_x64.iso

Image obtained from https://www.microsoft.com/en-us/software-download/windows10ISO (Needs Linux UA for the download to be available).

---

Trying to boot the newly released 21H1 ISO or a VM upgraded to 21H1 freezes virt-manager.

Happens on both BIOS and UEFI(ovmf).

Creating a new VM and clicking next next next with the ISO reproduces the freeze upon booting the VM and opening the view for it.

**Comment by crobinso** [comment]
Thanks for the report. Are you by chance attempting to redirect a USB device to the VM? That's causing app hangs in some situations: https://bugzilla.redhat.com/show_bug.cgi?id=1950258

The fix is updating to the recently released usbredir 0.10.0

If not, the culprit is probably something in the spice stack. Can you follow the debug steps in this page to try and narrow down the culprit: https://bugzilla.redhat.com/show_bug.cgi?id=1950258

**Comment by C0rn3j** [comment]
> Are you by chance attempting to redirect a USB device to the VM?

I can repro it by just creating a new VM without touching any extra settings, so yes, happens without redirection.

> Can you follow the debug steps in this page

I think you posted the wrong link, or did you just mean to run with --debug?

(Un)fortunately, I tried running with --debug, and apparently I do not experience the issue anymore.

Now I can boot my 21H1 VM and 21H1 ISO just fine, both on git and stable virt-manager.

I am not sure whether to blame this on trying to run with --debug magically fixing it, me upgrading my system since yesterday (but I don't see anything too relevant in the [upgrade.log](https://github.com/virt-manager/virt-manager/files/6564289/upgrade.log)) or something else altogether.

I am closing the issue since I can't reproduce it anymore, will comment if it comes back.

**Comment by crobinso** [comment]
Okay thanks for following up. The debugging link I meant to send was: https://github.com/virt-manager/virt-manager/wiki/Debugging-VM-graphical-display-issues
