### ISSUE TITLE
Fails to validate iso image from a local file system if directory has sshfs mount point

### ISSUE THREAD

**Issue by baryluk** [virt-manager/virt-manager#262]
**Distro**: Debian testing, amd64

virt-manager from git master repo @ 0f6b73d4f18090dd698fba7d7461805ad47ade26

I have tmpfs on `/` (including `/home/user`), and sshfs mount on `/home/user/vps1`. That confuses virt-manager.

I fails to see why a failure to read or stat `/home/user/vps1`, should result in unability to use `/home/user/someiso.iso` which is fully readable.

```
[Tue, 01 Jun 2021 15:48:24 virt-manager 2059098] DEBUG (installertreemedia:62) Error validating install location
Traceback (most recent call last):
  File "/home/user/virt-manager/./virtinst/install/installertreemedia.py", line 58, in validate_path
    dev.set_source_path(path)
  File "/home/user/virt-manager/./virtinst/devices/disk.py", line 643, in set_source_path
    (vol_object, parent_pool) = diskbackend.manage_path(self.conn, newpath)
  File "/home/user/virt-manager/./virtinst/diskbackend.py", line 167, in manage_path
    pool = poolxml.install(build=False, create=True, autostart=True)
  File "/home/user/virt-manager/./virtinst/storage.py", line 417, in install
    raise RuntimeError(errmsg)
RuntimeError: Could not start storage pool: cannot stat file '/home/user/vps1': Permission denied
[Tue, 01 Jun 2021 15:48:24 virt-manager 2059098] ERROR (createvm:1800) Error detecting distro.
Traceback (most recent call last):
  File "/home/user/virt-manager/./virtManager/createvm.py", line 1794, in _detect_thread_cb
    installer = virtinst.Installer(self.conn.get_backend(),
  File "/home/user/virt-manager/./virtinst/install/installer.py", line 78, in __init__
    cdrom = InstallerTreeMedia.validate_path(self.conn, cdrom)
  File "/home/user/virt-manager/./virtinst/install/installertreemedia.py", line 71, in validate_path
    raise ValueError(msg) from None
ValueError: Validating install media '/home/user/CentOS-8.3.2011-x86_64-dvd1.iso' failed: Could not start storage pool: cannot stat file '/home/user/vps1': Permission denied
[Tue, 01 Jun 2021 15:48:24 virt-manager 2059098] DEBUG (storagebrowse:49) Closing storage browser
[Tue, 01 Jun 2021 15:48:24 virt-manager 2059098] DEBUG (connection:676) storage pool lifecycle event: pool=user state=VIR_STORAGE_POOL_EVENT_DEFINED reason=0
[Tue, 01 Jun 2021 15:48:24 virt-manager 2059098] DEBUG (connection:676) storage pool lifecycle event: pool=user state=VIR_STORAGE_POOL_EVENT_UNDEFINED reason=0
[Tue, 01 Jun 2021 15:48:24 virt-manager 2059098] DEBUG (createvm:1829) Finished UI OS detection.
[Tue, 01 Jun 2021 15:48:30 virt-manager 2059098] DEBUG (guest:320) Setting Guest osinfo name <_OsVariant name=centos8>
[Tue, 01 Jun 2021 15:48:30 virt-manager 2059098] DEBUG (diskbackend:161) Attempting to build pool=user target=/home/user
[Tue, 01 Jun 2021 15:48:30 virt-manager 2059098] DEBUG (storage:380) Creating storage pool 'user' with xml:
<pool type="dir">
  <name>user</name>
  <target>
    <path>/home/user</path>
  </target>
</pool>

[Tue, 01 Jun 2021 15:48:30 virt-manager 2059098] DEBUG (installertreemedia:62) Error validating install location
Traceback (most recent call last):
  File "/home/user/virt-manager/./virtinst/install/installertreemedia.py", line 58, in validate_path
    dev.set_source_path(path)
  File "/home/user/virt-manager/./virtinst/devices/disk.py", line 643, in set_source_path
    (vol_object, parent_pool) = diskbackend.manage_path(self.conn, newpath)
  File "/home/user/virt-manager/./virtinst/diskbackend.py", line 167, in manage_path
    pool = poolxml.install(build=False, create=True, autostart=True)
  File "/home/user/virt-manager/./virtinst/storage.py", line 417, in install
    raise RuntimeError(errmsg)
RuntimeError: Could not start storage pool: cannot stat file '/home/user/vps1': Permission denied
[Tue, 01 Jun 2021 15:48:30 virt-manager 2059098] ERROR (error:145) Validation Error: Error setting installer parameters. Validating install media '/home/user/CentOS-8.3.2011-x86_64-dvd1.iso' failed: Could not start storage pool: cannot stat file '/home/user/vps1': Permission denied
Traceback (most recent call last):
  File "/home/user/virt-manager/./virtManager/createvm.py", line 1576, in _validate_install_page
    installer = self._gdata.build_installer()
  File "/home/user/virt-manager/./virtManager/createvm.py", line 125, in build_installer
    installer = virtinst.Installer(self.conn, **kwargs)
  File "/home/user/virt-manager/./virtinst/install/installer.py", line 78, in __init__
    cdrom = InstallerTreeMedia.validate_path(self.conn, cdrom)
  File "/home/user/virt-manager/./virtinst/install/installertreemedia.py", line 71, in validate_path
    raise ValueError(msg) from None
ValueError: Validating install media '/home/user/CentOS-8.3.2011-x86_64-dvd1.iso' failed: Could not start storage pool: cannot stat file '/home/user/vps1': Permission denied
```

**Comment by crobinso** [comment]
Thanks for the report, but this is a known configuration difficulty.

virt-install/virt-manager talks to the system instance of libvirtd by default, which is running as root. Your sshfs mount options probably are preventing root from accessing your mount. Try using the `-o allow_other` and/or `-o allow_root` sshfs options (I've used them in the past but it was a long time ago so I forget details).

The other alternative is to use the `qemu:///session` libvirt URI which will run libvirtd as your regular user, which should avoid these permission issues. File->Add Connection->QEMU/KVM user session

**Comment by baryluk** [comment]
> Thanks for the report, but this is a known configuration difficulty.
> 
> virt-install/virt-manager talks to the system instance of libvirtd by default, which is running as root. Your sshfs mount options probably are preventing root from accessing your mount. Try using the `-o allow_other` and/or `-o allow_root` sshfs options (I've used them in the past but it was a long time ago so I forget details).

Sorry, but that doesn't explain why libvirtd should just crash in flames, when it can't stat a file or a file system, that is completely unrelated to the file I am trying to use.

I do know about `-o allow_other`, but that is not a fix, that is a workaround.

**Comment by crobinso** [comment]
Sorry, I missed that libvirt was complaining about a different file in the directory, I thought the media was on the sshfs share. Yes I agree it's a strange case. virt-manager is trying to import $HOME as a libvirt storage pool, and libvirt expects to be able to stat every file in the storage pool, and it errors if it can't.

In a different world libvirt would treat it like `ls` and list the volume but report that it can't stat it in some way, but there's no support for that. And truthfully there likely never will be, because there's not much work happening on the libvirt storage APIs these days. So you'll need to work around it, either with your mount setup, or put the ISO file in a different directory that doesn't contain a file which root can't stat.

**Comment by baryluk** [comment]
> Sorry, I missed that libvirt was complaining about a different file in the directory, I thought the media was on the sshfs share. Yes I agree it's a strange case. virt-manager is trying to import $HOME as a libvirt storage pool, and libvirt expects to be able to stat every file in the storage pool, and it errors if it can't.

Correct.

> In a different world libvirt would treat it like `ls` and list the volume but report that it can't stat it in some way, but there's no support for that. And truthfully there likely never will be, because there's not much work happening on the libvirt storage APIs these days. So you'll need to work around it, either with your mount setup, or put the ISO file in a different directory that doesn't contain a file which root can't stat.

I see. So I could just great a dummy directory , like `/home/user/Foo`, and put the iso file there, and it should work.

The issue is I didn't add a `/home/user` directory as a pool. Instead I clicked "Browse locally", and selected a single file, not a directory. My guess, is that virt-manager adds a temporary libvirt pool, and then selects a file from it, or something.
