### ISSUE TITLE
virt-install | unattended (jeos) | aarch64: debian10 installation breaks if done remotely

### ISSUE THREAD

**Issue by fidencio** [virt-manager/virt-manager#263]
I've been facing some weird behaviour with virt-install, when performing a (JeOS) unattended installation on a Fedora 34 aarch64 host machine.

Basically, `virt-install --install debian10 --unattended admin-password-file=/path/to/file,profile=jeos` works as expected when I run the command from the aarch64 machine.  However, if I ssh into the machine and run the command, the unattended installation will start but will fail with this being the last error message visible:
```
/bin/fetch-url: line 2: mountmedia: not found                                  
```

Please, let me know what kind of logs would be useful, in case you have the time to take a look at it.

I must emphasize that this has **zero** priority on my list, so I don't expect something different on your side, @crobinso.  Still, good to have it reported and visible.

**Comment by crobinso** [comment]
Hmm interesting. No idea what those commands are, I guess debian installer internals? Full `--debug` output of a working run and failing run may help

**Comment by crobinso** [comment]
I don't think this is worth tracking until someone hits it in the wild. Closing
