### ISSUE TITLE
RFE: virt-install: add --audio support

### ISSUE THREAD

**Issue by jwatt** [virt-manager/virt-manager#264]
Libvirt 7.2.0 adds a new `<audio>` element (distinct from the `<sound>` element). Could support for this be added to virt-install?

https://www.libvirt.org/news.html#v7-2-0-2021-04-01
https://github.com/libvirt/libvirt/commit/a7292e07df79b4633cf7297ef307c44550872b2b
https://libvirt.org/formatdomain.html#elementsAudio

**Comment by crobinso** [comment]
Yes this should be added to virt-install. I have an incomplete patch here that adds up the wiring but doesn't fill in many command line options: https://gist.github.com/crobinso/9d37f2c78a4c1746775ddedb57eb8317

I probably won't get to it any time soon. But someone could take that and follow the tutorial [Extending the command line](https://github.com/virt-manager/virt-manager/wiki/Extending-the-command-line) and fill in options and I'll be happy to review

**Comment by jwatt** [comment]
Thank you, @crobinso!
