### ISSUE TITLE
Error starting domain: Cannot access storage file '/media/path/name.qcow2' (as uid:.., gid:..): Permission denied

### ISSUE THREAD

**Issue by mYnDstrEAm** [virt-manager/virt-manager#266]
**Distro**: Debian10

When creating a new virtual machine and selecting "Import existing disk image" OR adding a SATA storage hardware to an existing virtual machine and select to boot from it in the boot options wit the qcow2 file being located on an external SSD I get this error message when I trying to start the virtual machine OR clicking finish.

Full error message:
```
Error starting domain: Cannot access storage file '/media/path/name.qcow2' (as uid:[...], gid:[...]): Permission denied

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/domain.py", line 1400, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1080, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: Cannot access storage file '/media/path/name.qcow2' (as uid:[...], gid:[...]): Permission denied
```

I'm probably missing something trivial and this may be more related to the libvirt repo than here. I already tried changing ownership of the file to root via chown and permissions with chmod but that didn't help (and changing the ownership to root does not get applied: it stays owned by my username).

However, doing exactly the same thing with the same qcow2 file on another machine that has almost the same setup works and does not show this error message.

**Comment by crobinso** [comment]
Thanks for the report. A few things need to go right for this to work. `libvirtd` runs as root so generally can access any file, but qemu runs as nonroot user `qemu`. For qemu to be able to access disk images in this case, it needs read/write permissions on the image, and it needs execute permission for every directory in the chain. virt-manager tries to warn about the directory issue and offer to correct it. libvirt tries to fix the read/write issue by chown'ing the image to `qemu:qemu`. Something must be going wrong here.

On your working machine, check `ls -ld $DIR` for every directory in the chain (`/media`, `/media/path`, ...) and see if it has global `x` bit set. Also check getfacl for each of those paths and see if there's anything set for the `qemu` user. You could also compare `groups qemu` output on both machines and see if they are different.

What filesystem is the external drive?
