### ISSUE TITLE
virt-manager does not detect VM with Arch Linux ISO as Arch Linux automatically

### ISSUE THREAD

**Issue by thm-unix** [virt-manager/virt-manager#269]
**Distro**: Arch Linux
When I create a new virtual machine and select Arch Linux ISO as CD image, virt-manager does not detect it as Arch Linux automatically and I select Arch Linux manually.

**Comment by thm-unix** [comment]
![issue-scr](https://user-images.githubusercontent.com/84270488/123545523-193a9000-d761-11eb-8074-d54253545021.png)

**Comment by crobinso** [comment]
We use libosinfo + osinfo-db for ISO detection. Are they up to date? Try `osinfo-detect /path/to/iso`, if it doesn't detect arch, file a bug against osinfo-db with a link to the ISO you are trying. https://gitlab.com/libosinfo/osinfo-db

**Comment by Toolybird** [comment]
https://gitlab.com/libosinfo/osinfo-db/-/issues/81

**Comment by crobinso** [comment]
Thanks! Look like it was fixed quick
