### ISSUE TITLE
Profiles for recent OSs use EHCI+UHCI controllers instead of XHCI

### ISSUE THREAD

**Issue by cyounkins** [virt-manager/virt-manager#273]
**Distro**: NixOS 21.05

```
> virt-install --version
3.2.0

> virt-install --os-variant linux2020 --print-xml
...
    <controller type="usb" model="ich9-ehci1"/>
    <controller type="usb" model="ich9-uhci1">
      <master startport="0"/>
    </controller>
    <controller type="usb" model="ich9-uhci2">
      <master startport="2"/>
    </controller>
    <controller type="usb" model="ich9-uhci3">
      <master startport="4"/>
    </controller>
...
```

Some profiles generated with recent `os-variant`s, including `linux2020`, attach EHCI and UHCI USB controllers instead of the QEMU-recommended XHCI controller. From https://github.com/qemu/qemu/blob/master/docs/usb2.txt :

> The XHCI hardware design is much more virtualization-friendly when compared to EHCI and UHCI, thus XHCI emulation uses less resources (especially cpu).  So if your guest supports XHCI (which should be the case for any operating system released around 2010 or later) we recommend using it

**Comment by crobinso** [comment]
Thanks for catching that! This is an osinfo-db issue, I just submitted a fix for it here: https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/331

I'm closing this, please track that instead
