### ISSUE TITLE
toolbar icons weirdly sized with GDK_*SCALE usage

### ISSUE THREAD

**Issue by sfjuocekr** [virt-manager/virt-manager#274]
**Ubuntu 21.04**:

From virt-manager:
![Screenshot_20210719_144152](https://user-images.githubusercontent.com/398018/126161516-65d2f7da-6f6a-432e-af49-aed8b119416e.png)

From virt-viewer:
![Screenshot_20210719_144423](https://user-images.githubusercontent.com/398018/126161573-fa6e17e0-fde2-41fa-a357-b18d0120b6b9.png)

The issue is the scaling on the extra button bar when I open from virt-manager, these buttons are huge!

The other issue with scaling is as follow, I have my 4k screen set to 200% scaling.

The viewer does not honor the scaling for the guest, but it does for its window? So when I click resize to VM this happens:

![Screenshot_20210719_144818](https://user-images.githubusercontent.com/398018/126162007-765e71cc-5749-41c2-afa4-cafd0e65c631.png)

My hypothesis is that the scaling is applied double for the button bar and ignored on the viewer?

**Comment by crobinso** [comment]
Huh that's strange. Did this happen on a virt-manager update, or an update to another package like gtk? FWIW virt-manager does not attempt to apply scaling to the UI toolbar at all, just the VM viewer widget

**Comment by sfjuocekr** [comment]
I don't know, I noticed after the upgrade from 20.x to 21.04 and it seems to happen regardless of what scaling is set to as well.

At first I went to my .gtkrc-2.0, but I only have this line in it:

gtk-cursor-theme-size=48

**Comment by sfjuocekr** [comment]
This is at 100% scaling:
![Screenshot_20210801_163031](https://user-images.githubusercontent.com/398018/127774731-9dbc3319-dc94-4a8b-91b7-fafcb4af4958.png)

This is at 200% scaling:
![Screenshot_20210801_163124](https://user-images.githubusercontent.com/398018/127774839-84155425-4688-4138-8d15-b07bbdc2e73d.png)

**Comment by crobinso** [comment]
virt-manager is gtk3, you referenced a gtk 2 config file FWIW.

Are you reproducing with virt-manager git?

**Comment by sfjuocekr** [comment]
I was just trying to figure out why or when it happens.

Will try to build from git later this week!

**Comment by sfjuocekr** [comment]
Starting with GDK_SCALE=2 virt-manager everything is fine on the manager and viewer, but obviously completely unreadable on a 4K screen.

I have my DPI set to 192 and my display scaling to 200% in Plasma.

**Comment by sfjuocekr** [comment]
Yes still seeing this issue!

**Comment by crobinso** [comment]
This may have been indirectly related to our use of deprecated gtk STOCK icon naming, which is fixed upstream now. Do you still have the setup to reproduce? if so can you check if virt-manager.git is fixed? @sfjuocekr

**Comment by sfjuocekr** [comment]
Will do, currently testing something else but when I switch back to my daily use system I'll test it out!

**Comment by sfjuocekr** [comment]
![Screenshot_20220313_044357](https://user-images.githubusercontent.com/398018/158044156-7b13aa7a-0567-48bb-9e84-a741348a335b.png)

Still happening!

**Comment by xalt7x** [comment]
I have the same issue. When the Wayland compositor uses scaling, the graphical console becomes very small.
Reproducible with Mutter (GNOME) and KWin (KDE Plasma).
![kwin_wayland-scaling-125-percent](https://github.com/virt-manager/virt-manager/assets/44649402/6400b630-20fe-4659-adf7-4ec8d8b224ab)

**Comment by xalt7x** [comment]
"View" - "Scale Display" - "Always" workarounds this issue.
I guess that's what "virt-viewer" does as well.

**Comment by LSeelig** [comment]
Same issue here on Fedora Workstation 39. Also occurs with GNOME Boxes.

**Comment by ReillyBrogan** [comment]
[This](https://gitlab.com/virt-viewer/virt-viewer/-/merge_requests/29) is how it was fixed in virt-viewer. Perhaps someone familiar with the code could adapt their solution?

**Comment by rtgiskard** [comment]
Tried to test with similar change as @ReillyBrogan mentioned, but failed to get the point.
Is there any proper way to ping the developer for a focus :)

**Comment by crobinso** [comment]
Let's have the wayland fractional scaling bit tracked in this newer issue: https://github.com/virt-manager/virt-manager/issues/524

This original issue with the large toolbar icons, maybe it was related but the original report is over 2 years old at this point. If anyone is still hitting that specific issue, and it's not related to wayland scaling, please file a new issue and I'll try to take a look in a timely manner. I'm closing this one though
