### ISSUE TITLE
Directory-based storage pool and disk configuration

### ISSUE THREAD

**Issue by m-antonov** [virt-manager/virt-manager#284]
I've found a strange pattern in the XML dump of a virsh-based domain with a directory-based storage pool.
The complete reproduce sequence is as follows:

- Create a pool with the following configuration:

```
<pool type='dir'>
  <name>demo_pool</name>
  <target>
    <path>/home/nice/volume</path>
  </target>
</pool>
```

virsh pool-define pool.xml 
virsh pool-start demo_pool

- Create a volume with the following configuration:

```
<volume type='file'>
  <name>demo_volume</name>
  <capacity unit='G'>10</capacity>
  <target>
    <format type='qcow2'/>
  </target>
</volume>
```

virsh vol-create demo_pool volume.xml

- Create a domain specifying **vol** with the previously created pool and volume as the disk configuration argument and observe the following result:

virt-install --import --name demo --memory 1024 --disk 'vol=demo_pool/demo_volume' --print-xml

```
...
<disk type="file" device="disk">
  <driver name="qemu" type="qcow2"/>
  <source file="/home/nice/volume/demo_volume"/>
  <target dev="hda" bus="ide"/>
</disk>
...
```

- Create a domain specifying **source.pool** and **source.volume** with the same values and observe the following result:

virt-install --import --name demo --memory 1024 --disk 'source.pool=demo_pool,source.volume=demo_volume' --print-xml

```
...
<disk type="volume" device="disk">
  <driver name="qemu" type="qcow2"/>
  <source volume="demo_volume" pool="demo_pool"/>
  <target dev="hda" bus="ide"/>
</disk>
...
```

As you can see from the two examples, the first case produces a **source file** property with a real path, which in my opinion, is useless with a storage pool since it complicates further migration of an instance to another node.
Analysis of the source code showed that the vol argument parses the XML dump of the volume, detects volume type="file" and substitutes the corresponding source type.

In connection with the above, whether this logic is intentional or a consequence of an error?
If the implemented logic is correct and done on purpose, are there any specific reasons for this?

I've found this behavior both in the last stable release and in the upstream one.

Thanks

**Comment by crobinso** [comment]
Thanks for the report. The behavior is intentional. The virt-install command line option `--disk vol=POOLNAME/VOLNAME` predates libvirt `<source pool=XXX volume=XXX/>` by ~5 years IIRC, and not all libvirt drivers that can work with storage pools support that syntax, like the xen driver. So the simplest thing on virt-install side was to keep that vol= option working the same.
