### ISSUE TITLE
Scaling + 3D acceleration = 1/4 of screen only

### ISSUE THREAD

**Issue by lucaszanella** [virt-manager/virt-manager#289]
Ubuntu 20.04 host and guest

This is what happens when I start the VM using Virgil 3D acceleration:

![MLJAk](https://user-images.githubusercontent.com/6632321/130370237-a93ee14b-ab38-448f-bbda-6a66f535ece2.jpg)

The problem does not happen when I set the scale to 100%. However my notebook is in 4K and it's impossible to use it in 100% so I use 200% which gives me this problem.

**Comment by crobinso** [comment]
Hi, thanks for the report. Please help us narrow down the responsible component by following the steps here and reporting your results: https://github.com/virt-manager/virt-manager/wiki/Debugging-VM-graphical-display-issues

**Comment by Apflkuacha** [comment]
Could it be that you simply have to increase the VGA Memory for the video device in virt-manager? 
I do also have a 4K monitor and for increasing the resolution I'd had to double the VGA Memory by setting vgamem="32768" in the "Video QXL" device XML tab.

**Comment by crobinso** [comment]
@Apflkuacha thanks for the tip, but since the original reporter never responded, I'm closing this
