### ISSUE TITLE
Ability to include pure VNC and VNC+SSH machines

### ISSUE THREAD

**Issue by madduck** [virt-manager/virt-manager#290]
I am fully aware that the `virt-manager` is a manager of virtual machines in the sense that it connects to a supervisor/hypervisor, and exposes virtual machines provided by that.

I would like to propose that `virt-manager` be able to connect to VNC servers as well, ideally SSH-tunneled, like `virt-manager` already offers for `qemu` etc..

The use case is virtual machines hosted elsehwere, where one does not have access to the hypervisor.

Right now, I have to remember for each host whether it runs on a hypervisor I control, or whether I have to fire up the awful `ssvnc` viewer to access VNC on virtual machines that I don't host myself.

**Comment by phrdina** [comment]
Hi, unfortunately this is out of scope of virt-manager project. However, you can give [virt-viewer](https://gitlab.com/virt-viewer/virt-viewer) try as it is a spice and vnc client. It can be used even with VMs managed by virt-manager as an alternative to view the screen of VMs.

**Comment by madduck** [comment]
Yeah, I'm aware of virt-viewer, which does not do profiles. I have a couple of dozen such machines to worry about, and it's tedious to try to remember all the details for each. Thanks anyway.
