### ISSUE TITLE
Possibility of grouping, as in subtree, instances of virtual machines 

### ISSUE THREAD

**Issue by RodrigoDLopez** [virt-manager/virt-manager#297]
I looked in the file [DESIGN](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md) if there was already a similar request and I wasn't able to find it. 
If it already existed, please consider this proposal.

My proposal is something that would facilitate the management of virtual machines using the virt manager, bringing the possibility of grouping instances into submenus as in the images below. 

with the subtree contracted:
![grupos_fechados](https://user-images.githubusercontent.com/19981369/131900271-42fead9e-b3b5-4216-90cf-95ebdb893752.png)

with the subtree opened:
![grupos_abertos](https://user-images.githubusercontent.com/19981369/131900356-893001bc-f939-42d0-8b87-816bdb0e9766.png)

Instances that are not inserted in any of the tree's submenus can be displayed before or after the submenus, I think that displaying them before is more effective. 

Maybe the possibility to activate/deactivate this functionality through the preferences menu. Where we could enable the functionality and manage the submenus, creating, removing and inserting instances in this tree. 

**Distro**: 
I'm using the 3.2.0 version of virt-manager on Manjaro 20 (Lysia)

**Comment by crobinso** [comment]
Thanks for the suggestions, but [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md) mentions we've explicitly rejected grouping/collections UI like this, search the page for 'groups' and you'll see it

**Comment by MrPySmart** [comment]
This feature is very needed! One loses the overview when having a lot of virtual machines.
A treeview should be mandatory. Or at least: several projectsfiles that one could open/close and so have a manual grouping.
Very sad, that this was rejected.

**Comment by adonespitogo** [comment]
This is very sad indeed. Grouping is a minute change in Ui design but it adds a huge improvement on user experience.
