### ISSUE TITLE
virt-manager freezes when using libvirt hooks

### ISSUE THREAD

**Issue by wioo** [virt-manager/virt-manager#299]
**Distro**: Arch Linux

Hi,

When vm is started and libvirt hooks are in use, virt-manager would freeze.
This only happens if I start some daemon in background within hook script.

script used for debugging

/etc/libvirt/hooks/qemu
`#!/bin/bash

[[ "$2" != "started" ]] && exit 0
[[ "$1" != "win10" ]] && exit 0
[[ "$2" == "started" ]] && sleep 4000 &`

If I kill sleep process, virt-manager would continue, and vm is already booted (so i guess its not libvirt problem).

I am using master branch (its the same with latest arch package, virt-manager 3.2.0-1)

This is debug output when gui freezes
./virt-manager --no-fork --debug

> [Mon, 06 Sep 2021 07:51:21 virt-manager 96817] DEBUG (vmmenu:230) Starting vm 'win10'
[Mon, 06 Sep 2021 07:51:21 virt-manager 96817] DEBUG (connection:706) node device lifecycle event: nodedev=net_vnet0_fe_54_00_5c_0e_37 state=VIR_NODE_DEVICE_EVENT_CREATED reason=0
[Mon, 06 Sep 2021 07:51:22 virt-manager 96817] DEBUG (connection:631) domain lifecycle event: domain=win10 state=VIR_DOMAIN_EVENT_RESUMED reason=VIR_DOMAIN_EVENT_RESUMED_UNPAUSED

**Comment by crobinso** [comment]
Thanks for the report. virt-manager does not explicitly act on libvirt hooks. What's likely happening is something about your hook is causing a libvirt API call to get stuck. When virt-manager hangs, try sending ctrl+c to the terminal and see if you get a backtrace showing where the hang is. I'm guessing virsh hangs in the same way. 

Looking at your example, it's probably that libvirt is waiting for all child processes to exit before it continues on. Just using `&` does not daemonize the process. You probably need to use `nohup $CMD &`. See this for example: https://stackoverflow.com/questions/525247/how-do-i-daemonize-an-arbitrary-script-in-unix

Either way it's unlikely this is a virt-manager bug
