### ISSUE TITLE
Lack of contrast in toolbar icons

### ISSUE THREAD

**Issue by peteryates** [virt-manager/virt-manager#301]
**Distro**: Fedora 34 (with GNOME 40)

This is quite minor but I find there's very little contrast in the 'play' button, it's difficult to make out whether it's disabled or not. I'm using a vanilla GNOME install on Fedora 34.

Here's how the toolbar looks on my machine:

| Enabled | Disabled |
| ------ | ------- |
| ![Screenshot from 2021-09-29 11-47-07](https://user-images.githubusercontent.com/128088/135254501-12ae12d8-5ac2-4d58-ba98-70d94be9202a.png) | ![Screenshot from 2021-09-29 11-47-26](https://user-images.githubusercontent.com/128088/135254547-e3561527-3037-4403-a259-2507e684b1b3.png) |

As you can see, someone with poor vision would have trouble distinguishing between the two, or even making the icon out at all.

**Comment by crobinso** [comment]
Thanks for the report. unfortunately we just use the stock gnome icons here, and that's how they look. This will look different on other distros with different icon schemes. Maybe try running gnome tweak tool and changing the icon theme to HighContrast or one of the other options.
