### ISSUE TITLE
Question: hotkeys for full screen / minimize

### ISSUE THREAD

**Issue by karypid** [virt-manager/virt-manager#302]
I cannot find any hotkeys for virt-manager.

The only one seems to ne "Grab keys" (this is in Edit->Preferences->Console) which defaults to Ctrl_L-Alt_L.

Are there really no hotkeys for sending a command to the virt-manager running on the host with "Grab Keys + [key]"?

For example, using default grab keys:

- Ctrl_L + Alt_L + F --> toggle full screen
- Ctrl_L + Alt_L + M --> minimize VM window and switch to host
- ...

I usually work in a full screeen VM and sometimes want to minimize the VM so that I can interact with my host, then Alt-Tab back to the VM in full screen. There is no way to do that (I would hope for a Ctrl_L + Alt_L + M from list above) and even in the top toolbar there is only "send key (to guest)" and "toggle fullscreen" entry but no "minimize".

**Comment by crobinso** [comment]
Thanks for the report, but you should be able to accomplish what you want. Starting from the VM in fullscreen, Press `ctrl+alt` which releases keyboard grab from the VM. Then `alt+tab` will be sent to the host, allowing you to switch to a new host window.

**Comment by hede5562** [comment]
So the obvious answer is: no, there are no such hotkeys. There's only the grab keys combination, which defaults to `ctrl+alt`.
