### ISSUE TITLE
When leaving virt-manager, and opening some window in host system, window get focus, but writting to it, it write to VM

### ISSUE THREAD

**Issue by Mlocik97** [virt-manager/virt-manager#312]
When leaving virt-manager, and opening some window in host system, window get focus, but writting to it, it write to VM. This is really bad, as because of this, password I wanted to write to my personal account in host system was send to VM, where I have opened public chat with 4000 people in. This happen randomly.

**Distro**: Ubuntu 20.04.

**Comment by crobinso** [comment]
I haven't seen this behavior in the past few months, but I'm also not using opengl support which has caused window weirdness for me in the past. I don't expect this is a virt-manager bug. @Mlocik97 has this reoccurred for you lately?

**Comment by Mlocik97** [comment]
It didn't happend to me in past ~month, so maybe it's fixed.

**Comment by Mlocik97** [comment]
I will close this issue, if it happens again, I will reopen it.
