### ISSUE TITLE
Convert to FileChooserNative, for xdg portal usage

### ISSUE THREAD

**Issue by Ashark** [virt-manager/virt-manager#315]
When selecting iso image for cd drive, you see gtk dialogs. First you see the dialog with already known locations. There you can press Choose file, and you will see gtk file picker dialog.

With support of xdg desktop portals, it may show kde file dialogs. It is better for users, as there are user's bookmarks in kde. 

**Distro**: Arch Linux
Virt-manager version: 3.2.0

**Comment by Ashark** [comment]
The issue is still valid. Sorry, I cannot remember the example right now.

**Comment by crobinso** [comment]
Okay I think I figured it out, we need to switch to the GtkFileChooserNative API, which will call portal APIs for flatpak case for example.

**Comment by Ashark** [comment]
Ping?

**Comment by crobinso** [comment]
FileChooserNative isn't a drop in replacement, so it's not a trivial change. Might not happen until flatpak support is merged, or gtk4 port
