### ISSUE TITLE
guest viewer window resize issue

### ISSUE THREAD

**Issue by forreggbor** [virt-manager/virt-manager#316]
**Distro**: Ubuntu 20.04.3 LTS

If I open guest viewer window I can't reduce the size of the window. Enlarging the window works fine but reducing doesn't.
I have to turn off the guest to reduce the window's size.

It happens only if I open viewer from virt-manager.
Starting guest, close virt-manager and open viewer from cli (virt-viewer <guest>) then the window resize works fine.
I use QXL. Guest OS doesn't matter.

**Comment by crobinso** [comment]
Are you using the latest version of virt-manager?

If so, please debug further using the steps on this page: https://github.com/virt-manager/virt-manager/wiki/Debugging-VM-graphical-display-issues
