### ISSUE TITLE
Misleading error message for --hostdev "Unknown address type"

### ISSUE THREAD

**Issue by smitterl** [virt-manager/virt-manager#318]
If the `HOSTDEV` for `--hostdev` is passed incorrectly (it's not known to libvirt, ie. it isn't listed with `virsh nodedev-list` then the error message will be `Unknown address type`.

This might look like a small issue but we tried to test the upstream addition of mdev devices, the mdev device wasn't running and we weren't aware of that. So, it wasn't known to libvirt. However, because we got that error message we thought there was a regression maybe upstream (lost support for a specific address type as our parameter value contained an address definition) which took a while to figure out it wasn't the case.

Minimally reproduced by:
```
# virt-install --hostdev anything
ERROR    Error: --hostdev anything: Unknown address type
```

It became very confusing when we actually passed also an address definition:
```
virt-install ... --hostdev mdev_fdad4d13_a9d8_4869_a2d2_49622c4f8004,address.domain=0x0000,address.bus=0x07,address.slot=0x00,address.function=0x0
ERROR    Error: --hostdev mdev_fdad4d13_a9d8_4869_a2d2_49622c4f8004,address.domain=0x0000,address.bus=0x07,address.slot=0x00,address.function=0x0: Unknown address type
```

**Comment by crobinso** [comment]
Thanks for the suggestion. This is fixed in ed7b8769c4d48c89ed593138171bc8dbb1ead108

```
commit ed7b8769c4d48c89ed593138171bc8dbb1ead108
Author: Cole Robinson <crobinso@redhat.com>
Date:   Tue Jan 11 11:39:29 2022 -0500

    nodedev: Improve error with unknown address strings
```
