### ISSUE TITLE
Query: VM Network Attach Difficulty

### ISSUE THREAD

**Issue by PeterKW** [virt-manager/virt-manager#325]
How do I connect a network connection to my vm using virt-manager? I haven't been able to figure it out unfortunately or find instructions somewhere? Thank you very much

![image](https://user-images.githubusercontent.com/13779157/141605372-deffe908-f223-49ec-9b13-24aedf64f69b.png)

![image](https://user-images.githubusercontent.com/13779157/141605444-889ef7a0-2f21-4178-b540-26537a15eafc.png)

![image](https://user-images.githubusercontent.com/13779157/141605405-cafc2c51-8a5a-4c5f-9286-a7560feaf7c8.png)

**Comment by crobinso** [comment]
Sorry this looks like something is wrong with your distro libvirt package dependencies or something like that. Please file a bug against your distro's libvirt
