### ISSUE TITLE
FR: ability to group servers

### ISSUE THREAD

**Issue by jamincollins** [virt-manager/virt-manager#326]
**Distro**: archlinux

I use `virt-manager` to manage KVM virtual machines in a few different physical locations.  It would be useful if I could group the server connections by physical location.  I suspect the grouping option would also be useful for others that have a small to medium number of virtualization hosts.

**Comment by crobinso** [comment]
Sorry but this is already documented as a rejected feature in [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md)
