### ISSUE TITLE
Support extra Mouse-Buttons (4+5/back+forward)

### ISSUE THREAD

**Issue by Apflkuacha** [virt-manager/virt-manager#334]
**Distro**: Manjaro

Things are working really well with virt-manager. Mouse-buttons left, right and middle are working out of the box. But I also want to have the buttons 4+5 for going back and forward while browsing or navigating in the file manager. 
I know that supporting a gaming mouse with 10 buttons isn't possible, but it's a regular one without special drivers. I also found others who were looking for this feature: [here on reddit](https://www.reddit.com/r/Fedora/comments/jrefuw/forwardback_mouse_buttons_in_virtmanager/)

**Comment by crobinso** [comment]
Thanks for the report. It's unclear if this is something we need to support natively in virt-manager or elsewhere in the stack. For example this thread from Dec 2018 suggests that spice didn't support them back then.

Can you follow the steps here to determine if this bug affects virt-viewer too, and if Spice vs VNC makes a difference? That will determine where to file a proper RFE

**Comment by Apflkuacha** [comment]
> For example this thread from Dec 2018 suggests

Which thread do you mean? The reddit entry I posted was Nov 2020. And which steps I should follow?

**Comment by crobinso** [comment]
According to that spice link I think this may be fixed with spice 0.15 and qemu 5.2.0. There may be missing support in spice-gtk or some other component so maybe it's not wired up. But either way I don't think there's anything specific that virt-manager can do here, we either get the feature from spice-gtk or we don't. So I'm closing this

**Comment by Apflkuacha** [comment]
I could tell you following news: it is fixed in the Spice-GTK package since version 0.40, on Ubuntu 22.04 it is still version 0.39 and not yet working but on arch or some other distros version >= 0.40 is used and it works with linux guests. 
When using Windows as guest you also need the Win32 guest agent, that one haven't got an official update yet - you could comment here that someone creates a new version of it: https://gitlab.freedesktop.org/spice/win32/vd_agent/-/issues/24

Until the guest agent isn't released yet - you could install it like described here: https://gitlab.freedesktop.org/spice/spice/-/issues/45#note_1628223
