### ISSUE TITLE
Prevent user nobody from access to home directory

### ISSUE THREAD

**Issue by DmitruMoth** [virt-manager/virt-manager#335]
Before this experiment:
```
$ getfacl /home/dmitru
# file: home/dmitru
# owner: dmitru
# group: dmitru
user::rwx
group::---
other::---
```
Steps to reproduce:
1. Run virt-manager
2. Create new pool in your home directory
3. Create new virtual machine, go to fourth step.
4. Pick "Select or create custom storage"
5. Press "Manage"
6. Pick your poll in your home directory you create before
7. Press "+"
8. Create new volume
9. Pick your volume
10. Go to the next step
11. You get message "The emulator may not have search permissions for the path. Do you want to correct this now?"
12. Press "Yes"
13.
```
$ getfacl /home/dmitru
# file: home/dmitru
# owner: dmitru
# group: dmitru
user::rwx
user:nobody:--x
group::---
mask::--x
other::---
```
I think this is a big security bug and there should be any more elegant solution.

**Comment by crobinso** [comment]
capabilities should also print info about what uid/gid libvirt will run qemu as, which affects the virt-manager behavior here

**Comment by crobinso** [comment]
I think this is due to misconfigured libvirt build,  so closing. If you disagree, please post full capabilities output like suggested above, and reopen
