### ISSUE TITLE
Unable to launch virt-manager on Arch Linux

### ISSUE THREAD

**Issue by Eeblan** [virt-manager/virt-manager#336]
**Distro**: Arch Linux
I have made all the appropriate steps for my distro and my CPU is compatible. Console output:

$ virt-manager
Traceback (most recent call last):
  File "/usr/bin/virt-manager", line 6, in <module>
    from virtManager import virtmanager
  File "/usr/share/virt-manager/virtManager/virtmanager.py", line 15, in <module>
    import gi
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 40, in <module>                              #it's "_ _ init_ _.py" (without spaces), github just shows it as thick text instead
    from . import _gi
ImportError: libffi.so.8: cannot open shared object file: No such file or directory

**Comment by phrdina** [comment]
Hi, this issue tracker is for upstream bugs. The issue you have described seems like arch linux packaging issue so you should report it here: https://bugs.archlinux.org/ as there seems to by something wrong with the python gobject module that is just imported by virt-manager code.

**Comment by Eeblan** [comment]
So thanks to you (phrdina) i found out that it was the python-gobject that was causing issues so i basically reinstalled everything but installed pygobject from pip this time 
(i started writing this as a bit of a guide but ran into an issue later on)

Steps i took:
I installed pygobject from pip:
pip install pygobject
(this should also install python-cairo as a dependency for pygobject)

I made pacman ignore python-gobject and python-cairo (dependency of gobject) by going into /etc/pacman.conf and writing
IgnorePkg   = python-gobject python-cairo

then i installed the dependencies for virt-install and virt-manager excluding python-gobject and python-cairo:
sudo pacman -S gtk-vnc gtksourceview4 libvirt-glib spice-gtk vte3 python-docutils cdrtools cpio libosinfo libvirt-python python-requests libisoburn python-requests python-pytest

also installed some other standard stuff
sudo pacman -S qemu vde2 ebtables dnsmasq bridge-utils openbsd-netcat


Due to issue #338 the virt-manager and virt-install couldn't be installed using pacman -S so i downloaded them manually by going to both of their package pages and clicks "Download From Mirror" and then installed both of them using
pacman -Udd <package file location>
(adding dd will ignore all dependencies which is needed since some of the dependencies were installed from pip)

Configured libvirtd and stuff like that

Tried to launch but this time i was met with a different error

$ sudo virt-manager
Traceback (most recent call last):
  File "/usr/bin/virt-manager", line 6, in <module>
    from virtManager import virtmanager
  File "/usr/share/virt-manager/virtManager/virtmanager.py", line 16, in <module>
    gi.require_version('LibvirtGLib', '1.0')
AttributeError: module 'gi' has no attribute 'require_version'

things i have tried:
1:
Tried to install libvirt-python from pip but that didn't work with this error message (my guess is that it might be irrelevant for this issue)
(github showed it a bit wierd so i attached the output instead)

[Github_VirtManager_Issue336.txt](https://github.com/virt-manager/virt-manager/files/7708246/Github_VirtManager_Issue336.txt)

2: i gave up lol

**Comment by Eeblan** [comment]
Alright so a simple update fixed the issue
sudo pacman -Syu
