### ISSUE TITLE
virt-install-3.2.0-3-any is corrupted and can't download

### ISSUE THREAD

**Issue by MPilonieta** [virt-manager/virt-manager#338]
i'm using archlinux 5.15.7, when pacman is installing virt-manager package, jump an error: 
`error: virt-install: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
:: File /var/cache/pacman/pkg/virt-install-3.2.0-3-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]`

**Distro**: 5.15.7-arch1-1

**Comment by Eeblan** [comment]
I've experienced the same problem, my solution was to go to the virt-manager and virt-install pages, clicking "download from mirror" and then running the pacman -U <package file location>,
for example:
sudo pacman -U ~/Download/virt-manager-3.2.0-3-any.pkg.tar.zst
altho i should mention that i have had problems with actually running it Issue #336

**Comment by phrdina** [comment]
Hi, this issue tracker is for upstream bugs. The issue you have described seems like arch linux packaging issue so you should report it here: https://bugs.archlinux.org/

**Comment by MPilonieta** [comment]
thanks, and looking for information about i found that most of this kind of problems could be solved updating the " archlinux-keyring " package. so thanks again
