### ISSUE TITLE
IDE selection missing for disk bus

### ISSUE THREAD

**Issue by hamishmb** [virt-manager/virt-manager#346]
**Distro**: Linux Mint 20.2 Cinnamon x86_64

**Virt-manager version**: 3.0.0 (3.2.0 runs from git but displays incorrect version - something is wrong with that)

For machine types that support/require IDE (eg ppc mac99) the IDE option is not available in the GUI when adding a new disk (even though the preconfigured setup for mac99 includes an IDE disk, as SATA and others aren't supported).

I appreciate that IDE doesn't work for all machines, but having it there (not as the default) makes sense.

**Comment by crobinso** [comment]
Thanks for the report. Like I mentioned in the other issue, we get this info from libvirt, and libvirt isn't good at probing mac99 here. So it's mostly the same root cause as the other bug

**Comment by hamishmb** [comment]
Thanks, will report in libvirt then.
