### ISSUE TITLE
IDE-related error for QEMU binary that supports IDE (tested using commandline).

### ISSUE THREAD

**Issue by hamishmb** [virt-manager/virt-manager#347]
**Distro**: Linux Mint 20.2 x86_64

**Virt-manager version**: 3.0.0 (3.2.0 displays incorrect version so something seems afoot).

**QEMU version**: 6.0.0

When trying to set up a mac99 ppc machine using virt-manager, it reports that "IDE controllers are unsupported for this QEMU binary or machine type". The full text under "view details" is:

`Unable to complete install: 'unsupported configuration: IDE controllers are unsupported for this QEMU binary or machine type'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 66, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2005, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 691, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 639, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4366, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: unsupported configuration: IDE controllers are unsupported for this QEMU binary or machine type
`
However, when run from the commandline with: `qemu-system-ppc -L pc-bios -boot d -M mac99,via=pmu -m 2048 -drive file=lubuntu-16.04-desktop-powerpc.iso,if=ide,index=1,media=cdrom`

QEMU starts successfully and Linux reports through dmesg that IDE/PATA is indeed being used for the CD drive.

Perhaps this relates to the following change from [https://qemu.readthedocs.io/en/latest/about/removed-features.html](https://qemu.readthedocs.io/en/latest/about/removed-features.html) :

`
ide-drive (removed in 6.0)

The ‘ide-drive’ device has been removed. Users should use ‘ide-hd’ or ‘ide-cd’ as appropriate to get an IDE hard disk or CD-ROM as needed.`

If I can do anything more to help, let me know. I'm not sure how libvirt and QEMU interface exactly but with some instruction I'm happy to do some probing.

**Comment by crobinso** [comment]
Thanks for the report. I don't think there's ever been any serious work to get libvirt working with the ppc mac99 machine type. Libvirt likely needs to be extended to understand that mac99 has a built in IDE controller, and that knowledge will trickle up to virt-manager via the domcapabilities API.

That said these obscure platforms just never tend to get much love with libvirt so I wouldn't wait for it. You can file a libvirt bug but that's no guarantee anything will come of it.

As it stands though this isn't a virt-manager bug, so I'm closing it

**Comment by hamishmb** [comment]
Thanks, will report for libvirt.
