### ISSUE TITLE
Virtual machine monitor SPICE fail after upgrade (VNC server works)

### ISSUE THREAD

**Issue by qt1** [virt-manager/virt-manager#349]
A  VM that worked OK stopped opening the monitor  after upgrade .

Switching from spice to vnc enabled connection to the VM.

**The error:**

Error starting domain: internal error: process exited while connecting to monitor: 2022-01-05T10:14:35.969689Z qemu-system-x86_64: egl: eglInitialize failed
2022-01-05T10:14:35.969726Z qemu-system-x86_64: Failed to initialize EGL render node for SPICE GL

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 101, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1329, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2022-01-05T10:14:35.969689Z qemu-system-x86_64: egl: eglInitialize failed
2022-01-05T10:14:35.969726Z qemu-system-x86_64: Failed to initialize EGL render node for SPICE GL

**System info**
$ virt-manager --version
3.2.0
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

display info:

id: | display
-- | --
description: | VGA compatible controller
product: | TU104GL [Quadro RTX 4000]
vendor: | NVIDIA Corporation
physical id: | 0
bus info: | pci@0000:01:00.0
version: | a1
width: | 64 bits
clock: | 33MHz
capabilities: | vga_controller bus_master cap_list rom
configuration: | driver=nvidia latency=0 | driver | = | nvidia | latency | = | 0
driver | = | nvidia
latency | = | 0
resources: | irq:162 memory:42000000-42ffffff memory:60000000-6fffffff memory:70000000-71ffffff ioport:5000(size=128) memory:43000000-4307ffff | irq | : | 162 | memory | : | 42000000-42ffffff | memory | : | 60000000-6fffffff | memory | : | 70000000-71ffffff | ioport | : | 5000(size=128) | memory | : | 43000000-4307ffff
irq | : | 162
memory | : | 42000000-42ffffff
memory | : | 60000000-6fffffff
memory | : | 70000000-71ffffff
ioport | : | 5000(size=128)
memory | : | 43000000-4307ffff

output of attached:
lshw  > system.html  
[system.txt](https://github.com/virt-manager/virt-manager/files/7814205/system.txt)

**Comment by crobinso** [comment]
Thanks for the report but this looks outside of virt-managers control. Could be libvirt, qemu, kernel, mesa, video driver, virgl issue or even elsewhere if permissions are messed up. Check `/var/log/libvirt/qemu/VMNAME.log`, there may be more error info from qemu. There's a recentish hit here for a similar error that the user fixed by reinstalling their video driver: https://forum.level1techs.com/t/solved-help-pls-qemu-virgl-libvirt/174043

If you just want to keep spice working, disable spice gl in the virt-manager UI.

I'm closing this though because I don't think it's a virt-manager specific issue
