### ISSUE TITLE
network 'default' is not active

### ISSUE THREAD

**Issue by Morkhelt** [virt-manager/virt-manager#351]
**Distro**: Arch Linux

I was trying to create a Windows 10 Virtual machine in Arch under Virt-Manager and when I went through the final steps, I was asked to enable network manager 'default' I clicked yes and was immediately greeted with the error message enclosed below 
![Screenshot_20220108_185402](https://user-images.githubusercontent.com/63564377/148665336-c26be80b-5c6c-4412-824b-ad98c8452620.png)

I'm not exactly sure if this is a bug or not but I tried to re-enable the network manager through the terminal.
![Screenshot_20220108_185230](https://user-images.githubusercontent.com/63564377/148665361-81258adc-e8b5-42c5-8313-ed79cc77ff62.png)

When I restarted Virt-Manager and went through the process of setting up the Win10 virtual machine by plugging in the ISO and everything. I received the same error message again. If this is a bug on Arch Linux then hopefully it will be patched. If this isn't a bug and this could have something to do with my Arch Setup. Then I may be entirely lost and have no idea how to fix this

**Comment by Morkhelt** [comment]
I'm sorry but I hardly remember. I gave up on trying to do a gpu
passthrough on my virtual machine as a result of my gpu being proprietary

**Comment by m666m** [comment]
I have the same issue ，somtimes happen

    $ sudo virsh net-list --all
    Name      State      Autostart   Persistent
    ----------------------------------------------
    default   inactive   yes         yes           

    $ sudo virsh net-start default
    error: Failed to start network default
    error: internal error: Network is already in use by interface virbr0

    $ sudo virsh net-dumpxml default
    <network>
      <name>default</name>
      <uuid>01141adc-bec5-46e7-8162-203e093db2c4</uuid>
      <forward mode='nat'/>
      <bridge name='virbr0' stp='on' delay='0'/>
      <mac address='52:54:00:fd:e0:ef'/>
      <ip address='192.168.124.1' netmask='255.255.255.0'>
        <dhcp>
          <range start='192.168.124.2' end='192.168.124.254'/>
        </dhcp>
      </ip>
    </network>

    $ sudo cat /etc/NetworkManager/system-connections/virbr0.nmconnection
    [connection]
    id=virbr0
    uuid=0b36af14-4301-4e09-9f41-835549a4cab8
    type=bridge
    interface-name=virbr0
    timestamp=1693032155

    [ethernet]

    [bridge]
    forward-delay=2

    [ipv4]
    address1=192.168.124.1/24
    method=manual

    [ipv6]
    addr-gen-mode=eui64
    method=ignore

    [proxy]

    $ ip addr
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
        inet6 ::1/128 scope host noprefixroute 
           valid_lft forever preferred_lft forever
    2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
        link/ether 1c:1b:0d:95:29:06 brd ff:ff:ff:ff:ff:ff
        inet 192.168.0.101/24 brd 192.168.0.255 scope global dynamic noprefixroute enp0s31f6
           valid_lft 6434sec preferred_lft 6434sec
        inet6 2...78/64 scope global dynamic noprefixroute 
           valid_lft 86261sec preferred_lft 14261sec
        inet6 fe80::7...e3/64 scope link noprefixroute 
           valid_lft forever preferred_lft forever
    3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
        link/ether d6:ea:5e:6e:65:f7 brd ff:ff:ff:ff:ff:ff
        inet 192.168.124.1/24 brd 192.168.124.255 scope global noprefixroute virbr0
           valid_lft forever preferred_lft forever

**Comment by cmburn** [comment]
To anyone searching for this in the future- there's a good chance dnsmasq wasn't installed by default with virt-manager, which is required for QEMU networking. 

For Arch Linux specifically, try:
`sudo pacman -S dnsmasq`

**Comment by m666m** [comment]
My solution is create a new network2, change the setting of exists vm.
 
        $ systemctl status dnsmasq.service 
        ○ dnsmasq.service - DNS caching server.
             Loaded: loaded (/usr/lib/systemd/system/dnsmasq.service; disabled; preset: disabled)
            Drop-In: /usr/lib/systemd/system/service.d
                     └─10-timeout-abort.conf
             Active: inactive (dead)
