### ISSUE TITLE
PortGroups are not shown on virt-manager version 3.2.1

### ISSUE THREAD

**Issue by yilgo** [virt-manager/virt-manager#355]
## Steps:

Openvswitch portgroups(vlan) has been created.

```bash
ovs-vsctl add-br OVS0
ovs-vsctl add-port OVS0 <physical interface>
```

## Network defined

```xml
<network>
 <name>OVS0</name>
 <forward mode='bridge'/>
 <bridge name='OVS0'/>
 <virtualport type='openvswitch'/>
 <portgroup name='vlan100'>
   <vlan>
     <tag id='100'/>
   </vlan>
 </portgroup>
<portgroup name='TRUNK'>
   <vlan trunk='yes'>
     <tag id='100'/>
   </vlan>
 </portgroup>
</network>
```
```bash
virsh net-define --file OVS0.xml
virsh net-start --network OVS0
```

It is working fine on virt-manager version 2.2.1

**Distro**: 

Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish

**Comment by crobinso** [comment]
This was intentionally removed, but there's an issue tracking whether to bring it back: https://github.com/virt-manager/virt-manager/issues/169
