### ISSUE TITLE
virt-xml: Cannot hot-unplug hostdevice with dynamic device number

### ISSUE THREAD

**Issue by skobyda** [virt-manager/virt-manager#357]
Description of problem:
If usb hostdevice, which is attached to the VM, will change bus number upon reattachment to host, hot-unplug of this device from the VM will fail and the device will stay in VM's offline XML. 

How reproducible:
Steps to Reproduce:
1. Have a USB host device that can change device number during runtime. In my case, such device was `Bus 001 Device 004: ID 8087:0026 Intel Corp. AX201 Bluetooth` (extracted form "lsusb")
2. Attach this device to the VM
3. Start the VM
4. Detach this defice form the VM using: `virt-xml -c qemu:///system fedora-clone --remove-device --hostdev 8087:0026 --update`

Actual results:

Command returns `ERROR    No matching objects found for --remove-device 8087:0026`
Also only the live VM XML is updated, offline VM XML is not updated.

Also, the device number of attached device has changed. In my case, "lsusb" now shows: `Bus 001 Device 005: ID 8087:0026 Intel Corp. AX201 Bluetooth`. Therefore it seems that sometime during hot-unplug, the device number has changed (mayb when the hostdevice was reattached back to the host). This can be futher confirmed by `dmesg` log:
```
[  604.289162] usb 1-10: reset full-speed USB device number 4 using xhci_hcd
[  604.417357] Bluetooth: hci0: Firmware revision 0.0 build 121 week 7 2021
[  608.438373] usb 1-10: USB disconnect, device number 4
[  608.941945] usb 1-10: new full-speed USB device number 5 using xhci_hcd
[  609.069403] usb 1-10: New USB device found, idVendor=8087, idProduct=0026, bcdDevice= 0.02
[  609.069408] usb 1-10: New USB device strings: Mfr=0, Product=0, SerialNumber=0
```

Expected results:

Both live and offline XML's are updated and don't contain host device anymore.

**Distro**: Fedora 34

**Comment by skobyda** [comment]
I have a feeling that what probably happens is that virt-xml successfully removes the usb device from live XML, reattaches it back to the host (and a new device number is assigned to it), and only then it tries to remove it from VM's offline XML. By that time, the device number of usb hostdevice has already changed, so virt-xml is then unable to find the device in offline XML.

**Comment by crobinso** [comment]
Thanks for the report. Might be hard for me to reproduce locally without a similar device. If you can capture full `virt-xml --debug` output that will help me

**Comment by skobyda** [comment]
> Thanks for the report. Might be hard for me to reproduce locally without a similar device. If you can capture full `virt-xml --debug` output that will help me

```
[root@fedora machines]# virt-xml -c qemu:///system fedora --remove-device --hostdev 8087:0026 --update --debug
[Tue, 25 Jan 2022 19:54:20 virt-xml 59571] DEBUG (cli:204) Launched with command line: /usr/bin/virt-xml -c qemu:///system fedora --remove-device --hostdev 8087:0026 --update --debug
[Tue, 25 Jan 2022 19:54:20 virt-xml 59571] DEBUG (cli:216) Requesting libvirt URI qemu:///system
[Tue, 25 Jan 2022 19:54:20 virt-xml 59571] DEBUG (cli:219) Received libvirt URI qemu:///system
[Tue, 25 Jan 2022 19:54:20 virt-xml 59571] DEBUG (cli:255)   File "/usr/bin/virt-xml", line 8, in <module>
    virtxml.runcli()
  File "/usr/share/virt-manager/virtinst/virtxml.py", line 556, in runcli
    sys.exit(main())
  File "/usr/share/virt-manager/virtinst/virtxml.py", line 508, in main
    devs, action = prepare_changes(active_xmlobj, options, parserclass)
  File "/usr/share/virt-manager/virtinst/virtxml.py", line 330, in prepare_changes
    devs = action_remove_device(xmlobj, options, parserclass)
  File "/usr/share/virt-manager/virtinst/virtxml.py", line 181, in action_remove_device
    devs = _find_objects_to_edit(guest, "remove-device",
  File "/usr/share/virt-manager/virtinst/virtxml.py", line 108, in _find_objects_to_edit
    fail(_("No matching objects found for %s") %
  File "/usr/share/virt-manager/virtinst/cli.py", line 255, in fail
    log.debug("".join(traceback.format_stack()))

[Tue, 25 Jan 2022 19:54:20 virt-xml 59571] ERROR (cli:256) No matching objects found for --remove-device 8087:0026

```

**Comment by crobinso** [comment]
Thanks. Can you check with virt-manager.git too? The code has changed a bit.

From that backtrace it doesn't look like any hotplug operations are happening, the error is happening much earlier, virt-xml is just failing to find the specified device in the XML at all. Did that instance generate the dmesg issues mentioned above?

Please also provide `sudo virsh dumpxml VMNAME` and `sudo virsh dumpxml --inactive VMNAME`

**Comment by crobinso** [comment]
@skobyda can you still reproduce? If so please see the comment above
