### ISSUE TITLE
`--cloud-init` with Ubuntu 20.04 also requires `--sysinfo system.serial='ds=nocloud'`

### ISSUE THREAD

**Issue by ljrk0** [virt-manager/virt-manager#359]
**Distro**: ArchLinux
**Guest Distro**:  [Ubuntu 20.04 Cloud Image](https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img)
**Virt-Manager Version**: 3.2.0

### Steps to Reproduce

1. Download the Ubuntu Cloud Image
2. Create a cloud-init User-Data Configuration e..g., a `my_host-userdata.yaml`:
    ```yaml
    #cloud-config
    hostname: my-host
    users:
      - default
    ```
3. Run the installation:
    ```
    virt-install --name 'my-host' --virt-type kvm --memory 1G --graphics none --cloud-init "user-data=my_host-userdata.yaml"
    ```
4. Try to login after the installation has completed.  Note that SSHd tries to start (the VM doesn't even request an IP via DHCP) and the default users aren't created (so are any additional non-default users).

### Fix

Use `--sysinfo system.serial='ds=nocloud'` as hinted at [here](https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html) to specify that the data source used should be the NoCloud DS.
I'm didn't check whether virt-manager is at fault here e.g., by creating a metadata ISO that doesn't fit the spec:

> You can provide meta-data and user-data to a local vm boot via files on a [vfat](https://en.wikipedia.org/wiki/File_Allocation_Table) or [iso9660](https://en.wikipedia.org/wiki/ISO_9660) filesystem. The filesystem volume label must be cidata or CIDATA.

or Ubuntu by simply ignoring such ISOs by default unless `ds=nocloud` is specified either via Kernel command line or SMBIOS serial.

**Comment by crobinso** [comment]
Thanks for the report and the detailed info. Seems like this is something on ubuntu or cloud-init side, as there's hits about it that are independent of virt-install's --cloud-init usage: https://askubuntu.com/questions/1375589/what-are-the-different-versions-available-as-ubuntu-cloud-images-general-guid

@cpaelzer do you know if it's expected ubuntu cloud-init with iso/nocloud data source requires explicit opt in via kernel command line or smbios?

If so virt-install should probably pass this `--sysinfo system.serial='ds=nocloud'`  annotation when --cloud-init is requested

**Comment by ljrk0** [comment]
Thanks for the quick response!

The link (and the links there) are most insightful!  When I'm back home I will try to extract the `/etc/cloud/` config files from the Ubuntu image, maybe this will shed some more light into the behavior and whether it's intended or not.

**Comment by crobinso** [comment]
I did some more digging. ubuntu -kvm-disk.img doesn't work, but plain cloud image _does_ work, which a user reported here: https://stackoverflow.com/questions/68512432/cannot-login-to-vm-using-qemu-nocloud-cloud-init-on-macos-with-ubuntu-cloud-imag

`--machine pc` does work while our default `--machine q35` does not work. Difference is IDE vs SATA cdrom. Guest debugging shows that in the SATA case the cdrom drive is enumerated too late to be detected by cloud-init. This is also affected upcoming ubuntu 22.04. I filed an ubuntu bug: https://bugs.launchpad.net/cloud-init/+bug/1961832

**Comment by crobinso** [comment]
@ljrk0 nice find! Definitely seems like the same root issue, whatever it is.

**Comment by TheRealFalcon** [comment]
> do you know if it's expected ubuntu cloud-init with iso/nocloud data source requires explicit opt in via kernel command line or smbios?
If so virt-install should probably pass this --sysinfo system.serial='ds=nocloud' annotation when --cloud-init is requested

Cloud-init doesn't normally require this, but if you know you want cloud-init to be enabled in a virtualized environment, passing `--sysinfo system.serial='ds=nocloud'` will guarantee that cloud-init runs with the NoCloud datasource. Since the `--cloud-init` flag indicates the user wants cloud-init to run, I think that this is a reasonable default.

**Comment by crobinso** [comment]
Okay I added the `--sysinfo system.serial='ds=nocloud'` equivalent to the boot XML when there's any use of `--cloud-init`. User can override it by setting their own serial or using `--boot smbios.mode=none` if for some reason it's causing problems. So from virt-install perspective this is fixed
