### ISSUE TITLE
Icons missing with adwaita-icon-theme 42

### ISSUE THREAD

**Issue by AdamWill** [virt-manager/virt-manager#361]
**Distro**: Fedora 36

adwaita-icon-theme 42 landed recently in Fedora Rawhide (and is pending for Fedora 36). It drops a lot of 'legacy' non-symbolic icons, which looks to be causing quite a lot of fallout so far.

I ran virt-manager to help debug a case of this, and saw that virt-manager itself seems to be affected: the 'Show virtual hardware details', 'Power on the virtual machine' and 'Pause the virtual machine' buttons are all missing their icons.

[Upstream release notes](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/42.beta/NEWS#L5) suggest the choices here are: carry the icons you want downstream, or switch to the symbolic ones.

**Comment by crobinso** [comment]
Thanks for the report. I dropped usage of (deprecated) gtk STOCK icon naming + APIs and it seemed to fix it, even though I didn't add any explicit reference to symbolic icon names. Tested with f35 and adwaita-icon-theme from rawhide, hopefully that's good enough

**Comment by AdamWill** [comment]
yeah, it seems that if you use the right interfaces, GTK+ or whatever will give you 'foo-symbolic' if you ask for 'foo' and there is no 'foo' but there is a 'foo-symbolic'...
