### ISSUE TITLE
Migrating vm from hypervisor

### ISSUE THREAD

**Issue by voidplayer** [virt-manager/virt-manager#366]
**Distro**: debian, redhat, fedora

I have not tried it, but i think right now it would be possible by doing

```
virsh connect qemu:///system
virsh dumpxml > machine.xml
virsh undefine machine
virsh connect qemu:///session
virsh define machine.xml
```

The use case here is being able to easily move machines from the limited userspace and viceversa

Moving disks optionally (or not at all)

Thanks for reading!

**Comment by crobinso** [comment]
Thanks for the suggestion. This would be useful for some users, but I think it's outside the scope of the virt-manager UI per [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md). I think users that understand the distinction between system vs session enough to know they need to move their VMs are capable of figuring it out themselves. 

Trying to explain this in the UI to someone who doesn't understand session vs system, making it clear it's not a reversible situation etc sounds like a total pain. The actual operation would probably be 20% of the dev effort.

Though there's an opportunity here for someone to write a cli script to move VMs between system and session and blog about it IMO

**Comment by voidplayer** [comment]
I dont know, i was forced to understand about `qemu:///system` and `qemu:///session`, which admittedly has non intuitive names

I then was forced to know a few more things before was able to do this things comfortably. I still dont how comfortably i am doing this, because i dont know the implications of running a system machine having the image in a user space with user permissions

I would feel much more confortable if virt-manager offered me the option and presenting this option **only** when more than one connection is open would save 20% of the dev effort :)

Also, why is not a reversible situation?

(By forced i mean, i was given a box with some vms i wasnt able to see until i learned how to connect to session)
