### ISSUE TITLE
Add bullseye to list of distros

### ISSUE THREAD

**Issue by KwadroNaut** [virt-manager/virt-manager#368]
Current main branch lacks the current stable Debian version in the installer.  There is only 9, 10 and testing. The automatic detection for my Tails image failed too, fwiw.

![virtmanager](https://user-images.githubusercontent.com/99527/156387484-fa7ba88c-aa60-4921-a97c-2680824f3982.png)

**Distro**: Debian Bullseye
commit 9db16377e89e0cb54ce0051b65c9e521cf96f06b (HEAD -> main, origin/main, origin/HEAD)
Author: Cole Robinson <crobinso@redhat.com>
Date:   Tue Mar 1 14:52:26 2022 -0500

**Comment by crobinso** [comment]
Thanks for the report. We get the list of distros from osinfo-db. The latest osinfo-db has debian bullseye in it. Please put in a request for your distro to update osinfo-db.

As for tails detection, that's probably missing from osinfo-db. You can file an issue with them here: https://gitlab.com/libosinfo/osinfo-db
