### ISSUE TITLE
no titlebar, please

### ISSUE THREAD

**Issue by lucaszanella** [virt-manager/virt-manager#369]
On Ubuntu 21.04, the virt-manager window when I open a VM has a titlebar that occupies too much space. It should work just like firefox, where if I want to use an option I press ALT and I see the menu. Otherwise, no titlebar at all. It occupies too much usable space from my screen.

**Comment by crobinso** [comment]
This is explicitly listed as a previously rejected feature in [DESIGN.md](https://github.com/virt-manager/virt-manager/blob/main/DESIGN.md) which the issue template requested you read first.
