### ISSUE TITLE
Support hirerachial names in ZFS pool

### ISSUE THREAD

**Issue by rugubara** [virt-manager/virt-manager#374]
**Distro**: Gentoo

Creating a storage volume in ZFS pool is supported only in the top level pool dataset. Also the procedure of using the storage volume in creation of a VM or changing a VM config assumes that the volume is located in the top level dataset. This is not always the case. I can create volumes to store VM data manually via a zfs tool and locate them further down the zfs dataset tree. Moreover, this is the only way to create sparse volumes and also indicate a different block size (windows VMs run much better with 4K block size rather than the default of 8K that virt-manager creates).

Such volumes do show in the VM creation dialog, but when I pick them for a VM, the path is constructed as if they were created at the top level dataset and the VM fails to start (unless I manually correct the path to zvol).

**Comment by rugubara** [comment]
After further testing, I'm not able to change the path to zvol in the VM creation dialog. When I edit the XML and change the <source> tag and apply changes, the path is reset back to the incorrect one - from /dev/zvol/fast/VM/storage/schneider/system2021 back to /dev/zvol/fast/system2021

I tried to change other parts of <disk> in XML editor - they are applied w/o issue.

**Comment by crobinso** [comment]
I don't know much about zfs. Can you provide the libvirt storage XML you are referring to? Or run `virt-manager --debug`, reproduce the whole VM creation sequence you are trying, and attach the debug output here
