### ISSUE TITLE
again about virt-manager and screen readers

### ISSUE THREAD

**Issue by ilyapashuk** [virt-manager/virt-manager#376]
hello

I already written about virt-manager and screen reader interaction in the following issue:
https://github.com/virt-manager/virt-manager/issues/206

you closed that issue and adviced me to request spiceGtk developers

I tried to contact spice gtk but without success.

in particular this issue was opened:
https://gitlab.freedesktop.org/spice/spice-gtk/-/issues/147
no progress, as you can see

that's why I'm requesting this change on your side again.

**Comment by crobinso** [comment]
I'm sorry your spice-gtk issue didn't get traction. But my comments in the original issue still stand and my thoughts haven't changed. I gave a possible shell workaround you can do on your end. But I do not plan to add a virt-manager specific workaround here with all the maintenance burden that entails.
