### ISSUE TITLE
keygrabbing key combination sometimes don't work

### ISSUE THREAD

**Issue by ilyapashuk** [virt-manager/virt-manager#377]
hello

when vm is running, and focus is in the vm window I should be able to switch keyboard to the vm by pressing keygrabbing combination, ctrl+alt by default, and then switch back again.

but sometimes I can't use this combination, it is ignored by the virt-manager.

instead of this I need to simulate mouse click with my screen reader to make it to grab keys.

after this I can't free the keyboard by ctrl+alt and I need to shutdown the guest to free the keyboard.

I'm a screen reader user, so I'm using a keyboard without mouse and don't know how it is working with mouse and how it handles mouse events in this case.

keygrabbing keyboard combination should work independently of mouse position.
it should always work when keyboard focus is in the machine window and vm console is visible.
and it should always work to free the keyboard.

no matter where mouse is.n

**Comment by crobinso** [comment]
Sorry I never responded. These often tend to be transient desktop/window manager bugs, or transient bugs in spice. if you can still reproduce with latest virt-manager and a recent distro, please open a new issue, and perform the debugging requested in this page to help narrow down where the issue lives: https://github.com/virt-manager/virt-manager/wiki/Debugging-VM-graphical-display-issues
