### ISSUE TITLE
Virt-Manager Created VM With Existing Windows 11 Enterprise Evaluation Image Converted from VirtualBox Image Not Booting

### ISSUE THREAD

**Issue by KaziQ** [virt-manager/virt-manager#386]
Hi,

Running on Ubuntu 22.04 kernel 5.17.2. I have multiple VMs running including a trial Windows 11 one I installed from an ISO image. That runs fine. But when I download the developer trial edition VirtualBox image from Microsoft, convert that image to qcow2 and try to deploy it, it won't boot. Just goes to shell. When I use the command line I can successfully boot the drive with such command.

sudo qemu-system-x86_64 -display sdl -cpu host -smp 4,sockets=1,cores=2,threads=2 -M q35 -accel kvm -m 8192 -chardev socket,id=chartpm,path=/tmp/mytpm1/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chartpm -device tpm-tis,tpmdev=tpm0 -drive file=Win11DevTrial.qcow2

Virt-Manager settings are very similar to that of my working Win 11 VM. I am not sure what the problem is. Figured I'd ask here. 

Thanks.

**Comment by crobinso** [comment]
Thanks for the report. I don't know off hand either. Generally in these cases I'd work backwards from the libvirt config and forward from the qemu config until I found what culprit is tickling the issue. But it's a lot of work that generally requires deep knowledge of libvirt and qemu commandline...

**Comment by bug** [comment]
Are you sure to have UEFI selected in virt-manager's setting for your image?

**Comment by KaziQ** [comment]
I believe that may have been the culprit. I'll try again in 24 hours hopefully and report here. I didn't try again after creating the ticket.

**Comment by KaziQ** [comment]
I'm afraid I can't boot the current VirtualBox image using the same steps I have before. I'll be away for a while. When I can try again, I'll post my results here.

**Comment by KaziQ** [comment]
Correction, I was able to do it now using UEFI x86_64: /usr/share/OVMF/OVMF_CODE_4M.ms while creating the VM.
