### ISSUE TITLE
Which package provides virt-install CLI tool in Yocto?

### ISSUE THREAD

**Issue by elliotmtx** [virt-manager/virt-manager#388]
Hi, 
Does anyone know which package provides virt-install CLI tool in Yocto or how to use virt-install tool in yocto environment?
I have added below packages in my bb file but I don't see virt-install tool getting built 
+    packagegroup-core-boot \
+    qemu \
+    libvirt \
+    libvirt-libvirtd \
+    libvirt-virsh \
+    libvirt-python \
+    kernel-module-kvm \
+    kernel-module-kvm-intel \
+    kernel-module-kvm-amd \

Please help me.

**Comment by phrdina** [comment]
Hi, this tracker is for upstream virt-manager, for linux distribution specific issues you need to ask Yocto community. On their web site they have a info how to contact them https://www.yoctoproject.org/community/
