### ISSUE TITLE
Ubuntu 22.04 is not detected by virtmanager

### ISSUE THREAD

**Issue by sisyphus74** [virt-manager/virt-manager#390]
Ubuntu 22.04 is not detected in the list of operating systems when creating a new virtual machine.
Last detected os ubuntu is 21.10.
I am on latest arch linux, virt-manager version 4.0.0-1

**Comment by mhussaincov93** [comment]
hi,

doo correct me if i'm incorrect,

but is this a osinfodb issue?

again correct me if i'm incorrect but I thought that osinfo-db is used
for o.s detection?

Majid

**Comment by sisyphus74** [comment]
Sorry. I think you are right. It should be an osinfodb issue

**Comment by mhussaincov93** [comment]
no need to say sorry :)

**Comment by crobinso** [comment]
Thanks for the report. Indeed this is an osinfo-db issue that is fixed in osinfo-db git I believe, so this will be fixed when the release trickles out to distros.
