### ISSUE TITLE
VMM 4.0.0 does not save preferences,  only CPU graph works - Ubuntu 22.04/JJ

### ISSUE THREAD

**Issue by stump-ed** [virt-manager/virt-manager#391]
Its more of an annoyance - creation and management all seem to function OK.
Cannot get the VMM to save polling preferences under Edit->Preferences (checking the boxes doesn't seem to actually update the preferences)
Under View->Graph only the Guest CPU is checked, Host CPU is avail, Mem,Disk,Network are greyed out. Checking Host CPU does nothing except return you to main screen.   Hovering over greyed indicates "Disabled in Preferences Dialog"

Ubuntu 22.04 - running as sudo -E from ssh session with X11 forwarding to a remote session (tried different remote session clients).  Other X11 forwarded graphical programs (ie gparted, gedit) seem to work correctly in all cases.

**Comment by crobinso** [comment]
thanks for the report. probably means something about the ssh and sudo combo are making the gtksettings/dconf settings backend non-functional, I've seen similar years ago. Try running `virt-manager --debug` in those conditions and attach the full output, it might show a warning that explains it

**Comment by stump-ed** [comment]
I know it's been a while since I posted this issue.  I should have followed up sooner.

The reason this was happening was indeed user rights - when running as sudo, virt manager stores in the users home directory .config and .cache as root, so the user doesn't have access to files in their own directory.

I don't know if I solved it, or made a decent work around - but I have in the last few days been able to get virt-manager to work correctly (Ubuntu 22.04) by doing the following:

To turn on all functions in virt-manager (save pref)
1.add yourself to libvirt group
    sudo usermod -a -G libvirt (username)
2.  open sockets
	sudo nano /etc/libvirt/libvirtd.conf
	remove # before    unix_sock_group = "libvirt"  (around line 85)
        remove # before    unix_sock_rw_perms = "0770"   (around line 102)
  save and exit
3.  sudo systemctl restart libvirtd.service

Now run just virt-manager  (instead of sudo -E virt-manager)
If you are still having issues,  run virt-manager --debug
**you may need to sudo chown -R (username):(username) .config  and .cache in your (username) directory**
Now open preferences and click on all the polling features.
from the virt-manager main screen, click on view-> graphs and enable those you want to see consistently (you will need to repeat this step for each graph - I don't know why it closes after one click)

**Comment by crobinso** [comment]
Ok sounds like this was an environment issue, so I'm closing it. Thanks for following up
