### ISSUE TITLE
vm installation fails when adding inactive mdev

### ISSUE THREAD

**Issue by jonner** [virt-manager/virt-manager#392]
If you try to add a `MDEV Host Device` to a vm, virt-manager presents a list of available mediated devices that you can choose to attach to the vm. This list includes both active mediated devices and inactive ("defined") mediated devices. If the user chooses an inactive device and adds it to the vm, the vm will fail to start with an error similar to this:
```
Error starting domain: device not found: mediated device '1a343fa3-b8b5-40f8-bc3e-2c4f4830a43f' not found

Traceback (most recent call last):
  File "/home/jjongsma/work/virt-manager/./virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/home/jjongsma/work/virt-manager/./virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/home/jjongsma/work/virt-manager/./virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/home/jjongsma/work/virt-manager/./virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib64/python3.10/site-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: device not found: mediated device '1a343fa3-b8b5-40f8-bc3e-2c4f4830a43f' not found
```

The current workaround is to use `virsh nodedev-start` (or `mdevctl start` directly) to start the mediated device and then the domain should start successfully.

Potential options for improving this experience in virt-manager:
 - provide a way to start the inactive mdev within virt-manager
 - only allow a user to choose active mdevs to add to the domain

**Comment by crobinso** [comment]
I prefer your second option: disable those entries in the addhardware UI: make them visible but not selectable.

**Comment by crobinso** [comment]
I don't recall if this was fixed, but we've never had an active complaint about it so I don't think it's worth tracking anymore
