### ISSUE TITLE
Add system tray icon support for Wayland

### ISSUE THREAD

**Issue by PAI5REECHO** [virt-manager/virt-manager#393]
**Distro**: `Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05.20220505.c777cdf`
See: https://bugzilla.redhat.com/show_bug.cgi?id=1666597

What's the reasoning behind 147a3b4790b9c7bf47271a01f23ef08aa527479d? Why doesn't the systray work on Wayland, how could this be fixed?

**Comment by crobinso** [comment]
The gtk statusicon API is x11 only and behind the scenes depends explicitly on x11 behavior. If you're on wayland you need some desktop component that exposes the appindicator API, like https://github.com/ubuntu/gnome-shell-extension-appindicator

Once that's enabled virt-manager should be able to use it to embed in the systray

**Comment by crobinso** [comment]
@benyaminl virt-manager.git has a `--show-systray` cli option. Aiming for a new release at end of the month
