### ISSUE TITLE
RFE Access to virtual machine settings without taking display from others

### ISSUE THREAD

**Issue by titchy** [virt-manager/virt-manager#394]
**Distro**: Fedora 35

I manage a few VMS and the display is often in use when I would like to check or adjust some machine settings. If I use virt-manager I am forced to "open" the machine, which defaults to the display, this drops the other users connection, where in actual fact I only need to get to the settings tab.
A right click option to open settings directly would be a much better interface.

Thank you and regards,
Chris.

**Comment by crobinso** [comment]
There's already a couple ways around this. You can disable the 'View->Autoconnect' setting in the VM console details window. Every time the window is open it will make you click a button before autoconnecting to the console and booting other users. You can also get straight to the edit window with a command line switch: sudo virt-manager --connect qemu:///system --show-domain-edit VMNAME`

I think those mostly cover it. I'm trying to reduce general UI changes unless there's very strong reasons. Co-existing with multiple viewer clients is pretty niche though
