### ISSUE TITLE
Not ask for SPICE password for local connection?

### ISSUE THREAD

**Issue by HubKing** [virt-manager/virt-manager#395]
By default, SPICE is set to localhost-only. I allowed remote access and set a password. I thought only remote access would need typing the password, but it asked the password even for local view, each and every time I start the VM. Even if I save the password, I still have to click the "Login" button.

I see no point of this. I can see and change the password in the details tab right next to the console view; what is the point of typing that password I view the console locally? Can't Virt-Manager read the password from the next tab and type in (and click the "login" button, too) automatically? What security advantage does this have?

Why type the same password
![b](https://user-images.githubusercontent.com/10900489/168240747-d83c7008-5665-4a89-8322-dcdf0713e2bf.png)
that I can see/edit right in the next tab?
![a](https://user-images.githubusercontent.com/10900489/168240734-6d54c644-8349-49a6-9fb7-4a45a78fff85.png)

**Comment by calestyo** [comment]
Well who else should do anything but virt-manager?

And I think this is pretty much independent of whether the connection is local or not - what's IMO actually desired is: that **if** a passphrase is available in the keystore, it should immediately send it, and not requiring that extra click.

That click is not just annoying, but it typically also prevents that one sees the very start of the boot sequence (or at least in my experience).

The best would be perhaps, if there was an option which allows to control whether any available passphrase is automatically sent (maybe some people don't want to see the console per default, e.g. for privacy reasons).
