### ISSUE TITLE
Fedora ELN cannot install from a network tree

### ISSUE THREAD

**Issue by sgallagher** [virt-manager/virt-manager#397]
**Distro**: 
Fedora 36 attempting to install Fedora ELN from https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/x86_64/os/

It appears that the code that detects whether an install location is in the Red Hat family doesn't recognize Fedora ELN as being a Fedora variant like Rawhide. As such, virt-install falls back to trying to use `method=` at the kernel command-line instead of `inst.repo=` and the installation attempt fails.

See also https://github.com/fedora-eln/eln/issues/93

**Comment by sgallagher** [comment]
I've fixed this on the .treeinfo side of things, so we can close this.

**Comment by crobinso** [comment]
Sorry for not responding in a timely manner. Thanks for resolving it!
