### ISSUE TITLE
Add qxl/virtio then remove vga video produces problematic PCI attachment

### ISSUE THREAD

**Issue by kevinoid** [virt-manager/virt-manager#402]
**Distro**: Debian (also confirmed with ddead3228)

If a domain is created with the QEMU q35 machine type, then a second video device (qxl or virtio) is added and the first is removed, it results in a machine which has invalid PCI connections or can not use VESA BIOS Extensions (VBE).

If the second video device is virtio, it is attached to a PCIe Root Port.  This is valid when it is the second video device, since the QEMU driver creates a virtio-gpu-vga (PCIe) device.  However, it is invalid when it is the only video device, since the QEMU driver creates a virtio-vga (PCI) device and PCI devices can not be connected to a PCIe Root Port, as [explained by Laszlo Ersek on qemu-devel](https://lore.kernel.org/qemu-devel/63e991af-0dd2-3aea-2f15-7460a6fb87db@redhat.com/).

If the second video device is qxl, it is attached to a PCIe-to-PCI bridge which is attached to a PCIe Root Port.  Although this is a valid PCI(e) configuration (as far as I know), the ioport accesses are not fowarded over PCI(e) bridges, which prevents access to the [VBE](https://en.wikipedia.org/wiki/VESA_BIOS_Extensions) registers and use of VBE display modes, as [explained by Gerd Hoffmann on seabios](https://mail.coreboot.org/hyperkitty/list/seabios@seabios.org/message/XVP3I2KQVZHSTDA4SNVKOITWGRGSDU3F/).

#### Steps to Reproduce

1. Create a domain with VGA and qxl/virtio video: `virt-install --osinfo linux2020 --memory 1024 --disk none --video vga --video virtio --import --noautoconsole`
3. Stop the domain: `virsh destroy linux2020`
4. Remove the VGA video: `virt-xml linux2020 --remove-device --video vga`
5. Start the domain: `virsh start linux2020`
6. Observe the PCI configuration: `virsh qemu-monitor-command --hmp linux2020 'info qtree'`
7. Observe the lack of VBE modes in the guest: Boot Linux with `vga=ask` kernel parameter, or observe the Windows installer appear in grayscale at 640x480.

Note: It can also be reproduced in virt-manager by adding a qxl or virtio video device, then removing the original VGA video device.

Thanks,
Kevin

**Comment by kevinoid** [comment]
**Correction:**  When `virtio-vga` is connected to a PCIe Root Port it becomes a PCI Express device (unless `disable-legacy`/`disable-modern` are used) as explained in the [QEMU PCI Express Guidelines](https://github.com/qemu/qemu/blob/v7.0.0/docs/pcie.txt#L304-L307) (and which I confirmed with `lspci` in a guest).  So the PCI topology is valid, but the same issue as `qxl-vga` occurs because the PCI Root Port does not forward VBE register access.

**Comment by crobinso** [comment]
Thanks for the details report! So the fixed XML diff comes down to:

```diff
--- 2.xml	2022-06-18 14:46:46.121440766 -0400
+++ 3.xml	2022-06-18 14:48:04.400711741 -0400
@@ -150,7 +150,7 @@
     <audio id='1' type='spice'/>
     <video>
       <model type='virtio' heads='1' primary='yes'/>
-      <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
+      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
     </video>
     <redirdev bus='usb' type='spicevmc'>
       <address type='usb' bus='0' port='2'/>
```
If you check [libvirt code](https://gitlab.com/libvirt/libvirt/-/blob/master/src/qemu/qemu_domain_address.c#L1990) you'll see there's special address allocation behavior for the first video device. All other video devices are assigned the next free PCIe slots like any other random device. This is then baked into the XML config the first time the VM is defined. When the first video device is removed, the address for the second video device is not touched, because it's already hardcoded in the XML. Apparently that affects VGA/VBE behavior like you describe.

So to fix this in virt-manager and/or virt-xml, we could kill the `<address>` line for all other video devices if the first one is removed, and let libvirt fill in a new address for us. These types of hacks are kind of a pain for maintenance though, and TBH this feels like a pretty niche issue to add code to address.

What's the initial usecase for adding 2 video cards and removing one later? Or is this just something you noticed when experimenting?

**Comment by kevinoid** [comment]
Thanks for the explanation @crobinso.

> What's the initial usecase for adding 2 video cards and removing one later?

I didn't discover the issue until several months after I had made the change, since I normally use the OS drivers rather than VGA/VBE.  As I recall, I was initially using a VGA device and either added the virtio-vga device and immediately removed the VGA device or booted once in between to check that the virtio-vga device was recognized by the guest and the drivers were loaded.  I don't recall ever intending to use multiple video devices simultaneously.

I'm afraid I don't have an elegant solution to suggest.  Some ideas:

1. Removing or resetting `<address>` for remaining video devices after one is removed, as you suggested.
2. Producing a warning when removing a second video device (perhaps only if the remaining device is not attached to the Root Complex).  This would at least alert users, if they understand the warning and act on it or remember it if/when they experience issues.
3. Disallowed adding a second video device.  This would be fine for my use cases, but probably not for other users.  It would also be unfortunate to lose support for a libvirt/QEMU feature like this.
4. Leave the situation as-is.  The current situation is not terrible, although inexplicably losing VBE is unfortunate.  It took me quite a while to diagnose the issue (which initially manifested as the Windows installer appearing in 640x480 grayscale) and track down the root cause.  It would be nice to save future users that pain.  Although perhaps other users are more likely to remove and re-add the video device and not waste too much time on it than I was.
