### ISSUE TITLE
Edit / Connection Details is disabled until a VM is selected

### ISSUE THREAD

**Issue by calestyo** [virt-manager/virt-manager#403]
Hey.

Since quite a while now, when starting `virt-manager`, the menu Edit / Connection Details is disabled until a VM or group item (like the "QEMU/KVM") is selected in the main window.

Since Connection Details is not really related to a specific VM, why is it disabled?

Thanks,
Chris.

**Comment by crobinso** [comment]
The UI can have multiple connections, so we require you to have a VM or connection row selected, so we know which connection to show details for.

I'd take a patch to special case when there's only a single connection in the UI and nothing is selected. But I'd need to see the patch to know whether the code and testcase is worth it for a small UI nicety
