### ISSUE TITLE
GUI Request: Cancel button on Clone Virtual Machine:Clone Storage progress window

### ISSUE THREAD

**Issue by isghj5** [virt-manager/virt-manager#409]
**Distro**: Fedora 35 (tested with `7ae10b5566ac4d8c7afd94499a9733ed42cf3d07`)

The progress window for cloning a storage disk as part of cloning a virtual machine is missing a cancel button and cancel method. It seems like the only method to cancel the file clone job close the entire virt-manager process. If the user forgets to unselected clone storage when making a copy of their VM, they could enter this UI without a clean way to stop the disk clone.

Could a cancel button please be added?

![Screenshot_2022-06-29_17-02-39](https://user-images.githubusercontent.com/42048411/176566033-fcb01e8e-abb5-4323-8b7c-341fb7810eff.png)

**Comment by crobinso** [comment]
Thanks for the suggestion. We would add one if we could, but most cloning operations happen through libvirt and are not cancellable. There was vague ideas to add new cloning APIs that use libvirt's job support, which would enable cancellation, but it never happened and I don't expect it to happen. So this isn't something we can sanely implement in virt-manager
