### ISSUE TITLE
Unable to boot VM with virtio-gpu 3D support

### ISSUE THREAD

**Issue by jm33-m0** [virt-manager/virt-manager#410]
**Distro**: Arch

I am using the latest version of virt-manager and qemu, etc, under Arch. When a VM is configured to use virtio-gpu with opengl enabled, I got a crash from `qemu` process, which virt-manager complains about.

**Comment by crobinso** [comment]
Thanks for the report, but this is likely a qemu, virglrenderer, spice/spice-gtk error, so you'll need to file the bug elsewhere. If you grab the error from /var/log/libvirt/qemu/$VMNAME.log , or a backtrace of qemu from the crash, I might be able to tell where the bug should be directed.
