### ISSUE TITLE
'Adding a connection' failed: 'incompatible' iptables-nft, use `nft` tool.

### ISSUE THREAD

**Issue by egberts** [virt-manager/virt-manager#413]
Debian 11
virt-manager 3.2.0
libvirt0/stable,now 7.0.0-3 amd64

# Error Message

An untitled popup appeared with:
```
Error creating virtual network: 
    Internal error: Failed to apply firewall rules /usr/sbin/iptables -w --table nat --list-rules:
     iptables v1.8.7 (nf_tables): table 'nat' is incompatible, use 'nft' tool.
```

# Steps to Error

* Start virt-manager (v3.2.0)
* `Edit` on menu bar, select
* `Connection Detail` on submenu, select; new `QEMU/KVM - Connection Details` window/dialog appears
* `Virtual Network`, select
* `+`, select to add a connection, new `Create a new virtual network` dialog appears
*  keep all default values
* `Finish`, select the button
* new (untitled) popup appears with error message as described above

# Packages installed/not

This system has no `iptables` package installed; also has block all `iptables`-related kernel modules to be safe.

`/etc/modprobe.d/nft-only.conf` content:
```
blacklist x_tables
blacklist iptable_nat
blacklist iptable_raw
blacklist iptable_mangle
blacklist iptable_filter
blacklist ip_tables
blacklist ipt_MASQUERADE
blacklist ip6table_nat
blacklist ip6table_raw
blacklist ip6table_mangle
blacklist ip6table_filter
blacklist ip6_tables
```

This is a fressh-install Debian 11 with focus on zero `iptables` support (or at least, I tried to)

# Details in Error popup

```
Error creating virtual network: internal error: Failed to apply firewall rules /usr/sbin/iptables -w --table nat --list-rules: iptables v1.8.7 (nf_tables): table `nat' is incompatible, use 'nft' tool.



Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createnet.py", line 428, in _async_net_create
    netobj.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 3436, in create
    raise libvirtError('virNetworkCreate() failed')
libvirt.libvirtError: internal error: Failed to apply firewall rules /usr/sbin/iptables -w --table nat --list-rules: iptables v1.8.7 (nf_tables): table `nat' is incompatible, use 'nft' tool.
```

**Comment by crobinso** [comment]
I'm sorry you are having issues, but please read the issue template before filing an issue. None of your libvirt or virt-manager packages are up to date, so you should be asking about this in distro support channels. My guess is you need to install a newer libvirt
