### ISSUE TITLE
Tails USB image: "No bootable device" !

### ISSUE THREAD

**Issue by ObiSandwich** [virt-manager/virt-manager#417]
**LMDE 4**

Followed the "USB image" install instructions here: https://tails.boum.org/doc/advanced_topics/virtualization/virt-manager/index.en.html

Each time I get the following error :(
```
Booting from Hard Disk...
Boot failed: not a bootable disk
No bootable device.
```
I've attached some Settings screenshots for more info - Is there any one out there knows how to fix this please?

Cheers,

![Screenshot from 2022-07-27 21-02-13](https://user-images.githubusercontent.com/41534480/181363765-83d360e0-a071-4bb7-8831-28822d8980c6.png)
![Screenshot from 2022-07-27 21-01-38](https://user-images.githubusercontent.com/41534480/181363785-a5f6739e-d456-4eb8-9df3-2b8291796750.png)

**Comment by crobinso** [comment]
Those screenshots show the disk format as 'qcow2'. It should be 'raw'. I could not reproduce this bug with latest virt-manager, it worked following tails instructions. The UI in your screenshots is older too so this must be an non-latest version of virt-manager

**Comment by ObiSandwich** [comment]
I got this (old version) from the Software Manager on my system (LMDE4).

This gets the same old version too - shame it's not up to date;
`sudo apt-get install virt-manager`

I have now uninstalled this old version.

I have just downloaded v4 via your latest releases and then ran;

`sudo ./setup.py install`

But then hit this error;
```
./virt-manager
pygobject3 3.31.3 or later is required.
```
Can't seem to figure out how to install pygobject3, do you have any advice on this please?

Cheers,

**Comment by crobinso** [comment]
You'll want to ask in support channels for your distro, maybe there's a way to pull in updated packages. You probably don't want to attempt to manually build new pygobject, it will not be easy
