### ISSUE TITLE
channel for qemu agent not created automatically for FreeBSD guest machines

### ISSUE THREAD

**Issue by srinaths93** [virt-manager/virt-manager#418]
I am running a Debian 11 KVM Host and I created 2 VMs using virt-install.

vm1 is Debain 11
vm2 is FreeBSD 13

Below is the virt-install command used to create them

vm1 (Debian 11)

> virt-install --connect qemu:///system -n vm1 -r 4096 --memorybacking hugepages=on --vcpus cpuset=0-63,sockets=2,cores=16,threads=2 --disk path=/dev/vg001/vm1,cache=none,io=native --nonetworks --host-device=pci_0000_12_12_1 --host-device=pci_0000_12_12_1 --cpu host-passthrough --graphics vnc --video=cirrus --noautoconsole --memballoon model=none --hvm --autostart --rng /dev/random --watchdog i6300esb,action=reset --location=http://xx.xx.xx.xx/mirror/Debian11/ -x ks=http://xx.xx.xx.xx/ks/Debian11 --boot hd,network,menu=on --os-type linux --os-variant debian10

vm2 (FreeBSD 13)

> virt-install --connect qemu:///system -n vm2 -r 4096 --memorybacking hugepages=on --vcpus cpuset=0-63,sockets=2,cores=16,threads=2 --disk path=/dev/vg001/vm21,cache=none,io=native --nonetworks --host-device=pci_0000_12_12_2 --host-device=pci_0000_12_12_2 --cpu host-passthrough --graphics vnc --video=cirrus --noautoconsole --memballoon model=none --hvm --autostart --rng /dev/random --watchdog i6300esb,action=reset --boot hd,kernel=/root/freebsd/FreeBSD13/memdisk,initrd=/root/freebsd/FreeBSD13/initrd.img,network,menu=on --os-type unix --os-variant freebsd7.0

The virt-install configs are same except for Debian OS I use --location and install over n/w but for FreeBSD VM, I install the OS from HDD.

In Debian VM, if i check the created VM xml, I can see the virtio serial channel created automatically but in FreeBSD VM, it is not created.

```
grep -A3 \<channel vm1.xml 
    <channel type='unix'>
      <target type='virtio' name='org.qemu.guest_agent.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
```

I changed the Host to CentOS7.9 and I could see the same issue for FreeBSD VM

Version Details in Host Debian: 
virt-install  - 3.2.0
libvirtd - 7.0.0
libosinfo - 1.8.0-1

Note: I have seen and used the option --channel to create channel on FreeBSD 13 but why it is not created automatically like it is created for Debian VM

**Comment by ptoscano** [comment]
> why it is not created automatically like it is created for Debian VM

According to what I see in the sources:
https://github.com/virt-manager/virt-manager/blob/0d84bcfbfa2aa08396e836cb37fd0df167a6f6a4/virtinst/guest.py#L987-L1000

the qemu-ga channel is added automatically if the guest OS, i.e. what you specified using `--os-variant`, lists either `virtio-console` or `virtio1.0-console` as available device. The definitions of the OSes comes from osinfo-db [1] (part of the libosinfo project), and at the time of this writing none of the FreeBSD OSes list any of those devices. (And actually, the device coverage in osinfo-db for FreeBSD OSes is not that great, only 4 devices are listed.)

So IMHO the right fix here would be to determine whether `virtio-console` is supported in any released FreeBSD, and add it from that version. Possibly as larger project, also check whether virtio1.0 is supported, and add the proper devices for it.

[1] https://gitlab.com/libosinfo/osinfo-db

**Comment by srinaths93** [comment]
Thanks. I came across this code and was debugging further. As you have mentioned, virtio console is created only when it is supported by libosinfo for the given OS variant.

virtio1.0-console is represented by http://pcisig.com/pci/1af4/1043 
and virtio-console by http://pcisig.com/pci/1af4/1003

Refer Source: 

https://github.com/virt-manager/virt-manager/blob/0d84bcfbfa2aa08396e836cb37fd0df167a6f6a4/virtinst/osdict.py#L410-L417

The devices were not present in any of the FreeBSD OSes. 
Upon checking for Debain, I could see the device present only in debian7 and debian9 OS variant.

> /usr/share/osinfo/os# grep -rl 'http://pcisig.com/pci/1af4/1043\|http://pcisig.com/pci/1af4/1003' | grep -i debian
> debian.org/debian-9.xml
> debian.org/debian-7.xml

But I have debian-10.xml under - /usr/share/osinfo/os/debian.org which does not have any devices tag, but my debian VM is getting created with channel even though it is not present/given by libosinfo.

Also the installation correctly detected the debian10 as OS variant.

```
DEBUG (virtinstall:212) Distilled --network options: ['none']
DEBUG (virtinstall:144) Distilled --disk options: ['path=/dev/vg001/vm1,cache=none,io=native']
DEBUG (cli:216) Requesting libvirt URI qemu:///system
DEBUG (cli:219) Received libvirt URI qemu:///system
DEBUG (guest:320) Setting Guest osinfo name <_OsVariant name=generic>
DEBUG (guest:320) Setting Guest osinfo name <_OsVariant name=debian10>
DEBUG (urlfetcher:38) Using scratchdir=/var/lib/libvirt/boot
DEBUG (urldetect:284) Finding distro store for location=http://xx.xx.xx.xx/mirror/Debian11/
DEBUG (urldetect:874) variant=debian10 has distro=debian, looking for matching distro store to prioritize
DEBUG (urldetect:883) Prioritizing distro store=<class 'virtinst.install.urldetect._DebianDistro'>
DEBUG (urldetect:45) Failed to acquire file=current/images/MANIFEST
DEBUG (urldetect:45) Failed to acquire file=current/legacy-images/MANIFEST
DEBUG (urldetect:45) Failed to acquire file=daily/MANIFEST
DEBUG (urldetect:45) Failed to acquire file=.disk/info
DEBUG (urlfetcher:72) Fetching URI: http://xx.xx.xx.xx/mirror/Debian11/.treeinfo
DEBUG (urldetect:74) treeinfo family=Debian
DEBUG (urldetect:78) Found treeinfo version=11
DEBUG (urldetect:82) Found treeinfo name=Debian11
DEBUG (urldetect:93) Didn't match treeinfo family regex=.*Fedora.*
DEBUG (urldetect:93) Didn't match treeinfo family regex=.*(Red Hat Enterprise Linux|RHEL).*
DEBUG (urldetect:93) Didn't match treeinfo family regex=.*CentOS.*
DEBUG (urldetect:93) Didn't match treeinfo family regex=.*Scientific.*
DEBUG (urldetect:93) Didn't match treeinfo family regex=.*SUSE Linux Enterprise.*
DEBUG (urldetect:45) Failed to acquire file=content
DEBUG (urldetect:93) Didn't match treeinfo family regex=.*SUSE Linux Enterprise.*
DEBUG (urldetect:93) Didn't match treeinfo family regex=.*openSUSE.*
DEBUG (urldetect:45) Failed to acquire file=VERSION
DEBUG (urldetect:369) <virtinst.install.urldetect._GenericTreeinfoDistro object at 0x7fe70b4b8700> does not implement any osdict detection
DEBUG (urldetect:297) Detected class=_GenericTreeinfoDistro osvariant=None
DEBUG (installer:544) installer.detect_distro returned=None
DEBUG (osdict:344) No recommended value found for key='n-cpus', using minimum=1 * 2
DEBUG (disk:242) DeviceDisk.check_path_search path=/var/lib/libvirt/boot
DEBUG (disk:242) DeviceDisk.check_path_search path=/dev/vg001/vm1
DEBUG (cli:265)
Starting install...
```

If the hardware configs for a VM are taken from devices tag from the libosinfo xmls of each os variant, then my Debian10 VM should not be having channel created in it but it has one.

Not sure what I am missing.

**Comment by ptoscano** [comment]
>  Upon checking for Debain, I could see the device present only in debian7 and debian9 OS variant.

- `debian-7` adds `virtio-console`
- `debian-9` adds `virtio1.0-console`

since each Debian OS derives from the previous version (`<derives-from>`), it means all the devices are inherited automatically. This means `debian-10` has all the devices in all the previous versions.

**Comment by srinaths93** [comment]
Thanks for the info. 
'<derives-from>' is what I had overlooked.

**Comment by ptoscano** [comment]
@novel FYI, this needs extra devices on FreeBSD in osinfo-db.

**Comment by srinaths93** [comment]
Looks like [virtio](https://www.freebsd.org/cgi/man.cgi?query=virtio&sektion=4&apropos=0&manpath=FreeBSD+13.1-RELEASE+and+Ports) is supported from FreeBSD9 but the xml is not updated even in the [latest version](https://gitlab.com/libosinfo/osinfo-db/-/blob/master/data/os/freebsd.org/freebsd-13.1.xml.in) on osinfo-db. ​
