### ISSUE TITLE
Test fails with libvirt 8.5

### ISSUE THREAD

**Issue by Fantu** [virt-manager/virt-manager#420]
Hi, time ago I fixed a fail to build in debian packages with libvirt 8.1 adding these upstream patches: (thanks to @crobinso  )
- tests: Drop usage of sgio=unfiltered
- tests: Fix another sgio=filtered case

Today after saw that virt-manager will be removed from debian testing if not will be fixed the new fails to build with latest libvirt (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013667) I did a fast try to fix it (even if I very busy and I don't have enough time to dedicate).
I applied also these 3 patches:
- tests: Fix with latest osinfo-db
- tests: Fix with latest argcomplete
- tests: Fix with latest libvirt

I think can be useful also for other have a new bigfix release that build correctly on latest stable libvirt version.

Thanks for any reply and sorry for my bad english.

edit:
after another look out of tests/ I found the other patch needed and solved but I still think a new bigfix version that build correctly with latest libvirt stable version can be useful, (and also other fixes if important)

**Comment by crobinso** [comment]
Thanks for the report. I just cut release 4.1.0 which should be fixed with libvirt.git
