### ISSUE TITLE
Add label/category support for Virtual Machines

### ISSUE THREAD

**Issue by jelly** [virt-manager/virt-manager#425]
**Distro**: Fedora

I think this was not rejected in the past yet, but in cockpit-machines we recently got this feature request https://github.com/cockpit-project/cockpit-machines/issues/778 to add a label/category to a virtual machine (and filtering but that can be implemented in cockpit-machines not virt-manager).

This is somewhat related to:

https://github.com/virt-manager/virt-manager/issues/363
https://bugzilla.redhat.com/show_bug.cgi?id=1193303
https://bugzilla.redhat.com/show_bug.cgi?id=1548879
https://github.com/virt-manager/virt-manager/issues/147

I believe in Cockpit-machines we could create our own custom metadata but I think it would make sense that there is a somewhat standardised way to label/categorize a virtual machine in the same way for all libvirt frontends.

**Comment by crobinso** [comment]
This type of categorizing has been explicitly rejected before. Search for 'organizing' in DESIGN.md: https://github.com/virt-manager/virt-manager/blob/main/DESIGN.md

If there was some attempt at making this cross app, like requesting a new specific field in libvirt XML, then I'd consider adding it to virt-manager. But not some app specific bespoke solution.

You can get some basic organizing using the 'title' field to rename your VM in the UI. It is decoupled from the VM name. This is obviously very limited but it's better than nothing.

**Comment by 3ri4nG0ld** [comment]
Couldn't the possibility of adding this feature be reevaluated?

I sincerely believe that Virt-Manager is a very good virtual machine manager, and a feature like this would help many users to get familiar with the software (especially those coming from vmware or vbox).

Honestly, I would like to see in the future the possibility to group my virtual machines.
