### ISSUE TITLE
4.1.0 regression: Specifying --boot no longer implies no_install=yes

### ISSUE THREAD

**Issue by Vogtinator** [virt-manager/virt-manager#426]
**Distro**: openSUSE Tumbleweed

Found by openQA: https://openqa.opensuse.org/tests/2504818#step/virt_install/17

It runs the following command:

```virt-install --name TESTING --osinfo detect=on,require=off --memory 512 --disk none --boot cdrom --graphics vnc```

This worked before 4.1.0, but since then, it fails with

```
ERROR    
An install method must be specified
(--location URL, --cdrom CD/ISO, --pxe, --import, --boot hd|cdrom|...)
```

I bisected this to 5e48307e9d9d3c811ccbdb6463b6ccb79a029c4d, more precisely the addition of https://github.com/virt-manager/virt-manager/blob/11a887ece5b5bab287ff77b09337dc44c4e6e976/virtinst/virtinstall.py#L628

Removing that line makes it work again.

It's not entirely clear to me whether allowing this combination of option makes sense, as it effectively boots from an empty CDROM drive, but according to the error message and the man page it should be fine:

```
       no_install=yes|no
              Tell  virt-install  that there isn't actually any install happening, and you just want to create the VM. --import is just an alias for this, as is specifying --boot without any other install options. The deprecated --live
              option is the same as '--cdrom $ISO --install no_install=yes'
```

**Comment by crobinso** [comment]
Thanks for the report, I've fixed in git now.

Unfortunately the way the conditional was formatted later in the code meant coverage wasn't flagging this as a miss. I fixed that and added regression tests for this case too.

I'll get a bugfix release out this week.

**Comment by Vogtinator** [comment]
Fix confirmed to work, thanks!
