### ISSUE TITLE
Cannot detach the keyboard when I switch to other virtual desktop.

### ISSUE THREAD

**Issue by zhaodice** [virt-manager/virt-manager#428]
**Distro**: https://launchpad.net/ubuntu/+source/virt-manager/1:4.1.0-1/
Bug Step:
1.the virt-manager uses the mouse/keyboard alone in FULLSCREEN (catch all of the mouse/keyboard event)
2.leave the virtual machine by shortcut key 
3.use KDE's hot corners to switch others virtual desktop
4.keyboard doesn't work,what I have typed will be redirected to the virtual machine but I have exited it, and virtual machine window is in the other virtual desktop.

**Comment by crobinso** [comment]
Thanks for the report. Can you follow the debugging steps here to help narrow down what config is involved: https://github.com/virt-manager/virt-manager/wiki/Debugging-VM-graphical-display-issues

**Comment by crobinso** [comment]
This could also be a KDE bug potentially, if it's only reproducing with a non-standard config, but you'd want to confirm with multiple VM graphics configs first. Would be interesting to see if the issue reproduces without GPU passthrough too. 

Either way it doesn't sound like this is virt-manager specific. If you narrow it down more you can try filing a bug against spice-gtk: https://gitlab.freedesktop.org/spice/spice-gtk
