### ISSUE TITLE
Indirect usage of console for extracting logs and executing commands

### ISSUE THREAD

**Issue by pmury** [virt-manager/virt-manager#43]
Compare Docker calls:

```
docker run ....
docker logs...
docker exec ...
```
Is, or could be there an equivalent also with virsh? For example, during system installation Ubuntu installer uses tty/S0 to show a progress bar, and tty/S3 (at least what I guess the "4th console" should be) to display error messages. This is of course more complex.

Nevertheless, maybe following calls or similar could be possible?
```
virsh logs --console ttyX <domain>
virsh exec --console ttyX <domain> command
```
In both cases, virsh could be used with more flexibility in headless/non-interactive environments to extract logs either execute commands indirectly.

**Comment by crobinso** [comment]
virsh is part of the libvirt project, not virt-manager. that said, qemu does not provide any way presently to seamlessly access ttyX inside the VM. ttySX yes, with <serial> devices configured in the VM XML, and using virsh console or virt-manager to connect. But not ttyX unless there's some magic linux config to redirect those to a serial console. So while it's a nice idea for starters it would need work lower in the stack and realistically I don't see it happening
