### ISSUE TITLE
virt-xml: Change disk's address type accordingly to the bus type

### ISSUE THREAD

**Issue by skobyda** [virt-manager/virt-manager#430]
1. Have virtio disk attached to the VM, for example:
```
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw'/>
      <source file='/tmp/someDisk'/>
      <target dev='vdb' bus='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </disk>
```
2. Try to change the bus type to "sata": `virt-xml vmName --edit target.dev=vdb --disk target.bus=sata`

Expected output: Disk bus type is changed succesfully
Actual output: ERROR    internal error: unexpected address type for sata disk

It seems that virt-xml is trying to persist `<address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>`. However, "sata" disk expects `<address type="drive" ... />`  in the XML. 
I believe the ideal behaviour should be that virt-xml automatically changes address type to "drive".
Alternatively, virt-xml could just delete the whole "address" element altogether and let libvirt generete correct address element.

**Comment by skobyda** [comment]
Changing address.type manually through virt-xml parameters doesn't help either:
```
./virt-xml vmName --edit target.dev=vdb --disk target.bus=sata,address.type=drive
ERROR    XML error: Invalid value for attribute 'bus' in element 'address': '0x00'. Expected integer value
```

**Comment by crobinso** [comment]
Thanks for the report. 

Dealing with this transparently in virt-xml is a pain. virt-xml isn't really designed to be a 'do the right thing' tool when it comes to XML editing, more like 'do only what the user requested'. If we make virt-xml start clearing out the `<address>` block for disks when the bus changes, we may well hit a case in the future where a user desires _not_ to clear the `<address>` block, and now we need to add a cli option to turn the behavior off. So with XML editing I always lean towards no magic behavior.

You _can_ ask virt-xml 4.1.0 to delete the `<address>` block for you, with `--disk target.bus=NEWBUS,xpath.delete=./address` . But you may hit other problems, like needed to regenerate disk target= as well (which libvirt should really do for us, and in the mean time virt-xml could probably use a target=auto option or some such...)

Conceptually, the difficulty here is that changing bus= values for an existing disk is not really an 'editable' type of operation. From the point of view of the VM it's likely a different device on a different bus, and changing bus is much more likely to cause guest visible issues than say switching network model (like will windows handle switching IDE boot disk to SATA? no idea)

For these reasons, in virt-manager UI, we restrict disk bus editing to disk creation time only: via the `Add Hardware` wizard, and at VM install time. For an existing disk, if users want to change the bus, they are forced to delete the `<disk>` and recreate. This lets virt-manager sidestep these XML problems, and I think this helps make the guest OS implications more clear too.

Does cockpit UI allow editing bus= value for an existing VM?

**Comment by skobyda** [comment]
Ah I see.
I wasn't aware of the option `--disk target.bus=NEWBUS,xpath.delete=./address`, that would solve our problem. 
Cockpit doesn't allow setting `bus=` value at all, even for new disks.
So if we combine it with some warning (e.g. "Changing bus type may affect disk's address bus"), and keep in mind that address.bus was never specified by the user, and always generated by libvirt, that would make deleting `<address>` block a bit more "acceptable" in Cockpit.

Anyway I consider `--disk target.bus=NEWBUS,xpath.delete=./address` good solution to my problem, so I think this issue is resolved.
