### ISSUE TITLE
feature request Backup

### ISSUE THREAD

**Issue by TorbenMartin** [virt-manager/virt-manager#431]
Hey. 

I am missing a Backup Button. Is there any Chance for get it?
For now i am using my own Script. A very simple Script and i think its easy to put something better than in the Snapshot Area.
In my Script i use only a Loop for all Disks, 4 virsh Commands and i create a Backup Folder first.
I am NOT a Programer. I am only interested into scripting.

Can you please take a look on it and maybe i have good luck for a Backup Button in Future?! Thanks.

virsh snapshot-create-as --domain $1 --name $moment \
    --diskspec $typ,file=''$filename'' \
    --disk-only --atomic \
    --no-metadata
    
rsync --progress ''$file''  ''$backupdir'/'$datum'/'
virsh blockcommit "$1" "$typ" --wait --active --verbose 
virsh blockjob "$1" "$filename" --pivot
 
virsh dumpxml "$1" > ''$backupdir'/'$datum'/'$1'.xml'

![backup](https://user-images.githubusercontent.com/97087023/188652811-34f5c968-0f26-4c5f-9585-177453225c28.png)

**Comment by catborise** [comment]
```
virsh backup-begin --help
  NAME
    backup-begin - Start a disk backup of a live domain

  SYNOPSIS
    backup-begin <domain> [--backupxml <string>] [--checkpointxml <string>] [--reuse-external]

  DESCRIPTION
    Use XML to start a full or incremental disk backup of a live domain, optionally creating a checkpoint

  OPTIONS
    [--domain] <string>  domain name, id or uuid
    --backupxml <string>  domain backup XML
    --checkpointxml <string>  domain checkpoint XML
    --reuse-external  reuse files provided by caller

```
there is a better way for backup. but it is implemented after libvirt version> 8 and qemu > 6

**Comment by TorbenMartin** [comment]
ah ok thanks. it mean after upgrade libvirt and qemu it shows a button? nice. thanks.

for "virsh backup-begin" it not work on beginning.
after reseach i have to setup all domain xml files and add:

on top of config file:
<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">

before </domain>:
  <qemu:capabilities>
    <qemu:add capability='incremental-backup'/>
  </qemu:capabilities>

the backup file is in the same path with the original domain.qcow2
now have to wait until its finish. 

thanks.

![Bildschirmfoto zu 2022-09-07 18-10-24](https://user-images.githubusercontent.com/97087023/188927555-2f912d2a-bde6-4d06-b5d1-c522f4b2f56f.png)

**Comment by crobinso** [comment]
Thanks for the suggestion. There's no current UI support for VM this type of backup, and there's no plans to add it. It's definitely a power user type feature, and we aren't generally adding those to the UI.

It's possible virt-manager will add support for libvirt external snapshots, when libvirt grows support for all the features we need for the current snapshot UI to keep working. If that happens, then maybe we would extend the snapshot UI to have some kind of backup action. This type of backup feature you are talking about requires external snapshots. But that's all very fuzzy and may never happen.

So right now this is a 'soft no' but we could revisit it in the future

**Comment by TorbenMartin** [comment]
Okay Thanks.

**Comment by catborise** [comment]
> ah ok thanks. it mean after upgrade libvirt and qemu it shows a button? nice. thanks.
> 
> for "virsh backup-begin" it not work on beginning. after reseach i have to setup all domain xml files and add:
> 
> on top of config file ![Bildschirmfoto zu 2022-09-07 18-12-49](https://user-images.githubusercontent.com/97087023/188928052-15a5a7ad-1b8c-4587-b4c6-561aabec3ac5.png)
> 
> on end: ![Bildschirmfoto zu 2022-09-07 18-13-07](https://user-images.githubusercontent.com/97087023/188928080-77f20da3-a3f3-4110-9417-036e73ff8dc4.png)
> 
> the backup file is in the same path with the original domain.qcow2 now have to wait until its finish.
> 
> thanks.
> 
> ![Bildschirmfoto zu 2022-09-07 18-10-24](https://user-images.githubusercontent.com/97087023/188927555-2f912d2a-bde6-4d06-b5d1-c522f4b2f56f.png)

if your libvirt version is lesser than 8, backup support is experimental. but with version 8 it becomes general. 
my recommendation is that wait for ubuntu to compile 8 version. after that you dont have to modify instance XML to backup.

**Comment by abbbi** [comment]
> there is a better way for backup. but it is implemented after libvirt version> 8 and qemu > 6

you might want to check: https://github.com/abbbi/virtnbdbackup
implements the pull based approach.
