### ISSUE TITLE
"Scale Display: Always" makes the image blurry by making it 1 pixel too narrow

### ISSUE THREAD

**Issue by kparal** [virt-manager/virt-manager#434]
**Distro**: Fedora 37

I'm using **Scale Display: Always**. When I hit **Resize to VM**, it produces a blurry image (visible on fonts). I noticed that when I switch to **Scale Display: Never** (and _don't_ resize the window), the image gets perfectly sharp. It seems that "Scale Display: Always" add an extra pixel padding or similar, and the image is then scaled down a bit. I can resize the window to add the extra pixel, but when I use "Resize to VM", it resizes back to the "1 pixel missing" size.

Note: VMs now start in 1280x800 default size instead of 1024x768. I know that's a qemu change, but perhaps it can be related somehow.

See this video (be sure to watch it in 100% size, otherwise the sharpness changes might not be visible):
[virt-blurry.webm](https://user-images.githubusercontent.com/755451/190605541-990c4cb8-ae21-408c-9cf2-69b4d484cc7b.webm)

```
virt-manager-4.1.0-1.fc37.noarch
qemu-kvm-7.0.0-9.fc37.x86_64
libvirt-libs-8.6.0-3.fc37.x86_64
```

**Comment by crobinso** [comment]
Thanks for the report, sorry for response delay. I see what you mean in the video. But on f40 with virt-manager.git, f40 VM using spice, I couldn't reproduce this. I'm assuming this got fixed at spice level at some point. If you are still reproducing with latest bits, please reopen or file a new issue.

**Comment by kparal** [comment]
I tested it now on Fedora 41 and it really seems to be fixed. Thanks.
