### ISSUE TITLE
Unable to register ivshmem device with newer qemu and libvirt

### ISSUE THREAD

**Issue by siredmar** [virt-manager/virt-manager#438]
I'm trying to make a GPU passthrough'ed Win10 VM and succeeded for the biggest part - VM is booting, Nvidia drivers are installed. I tried to make looking glass working but that failed because the way how the ivshmem device is configured for qemu changed for qemu >= 6.2 and libvirtd >= 7.9. https://looking-glass.io/docs/B5-451-646a725c/module/#libvirt

My setup isn't special at all. Vanilla Ubuntu 22.04 that ships with these versions.

```
$ qemu-system-x86_64 --version
QEMU emulator version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.3)
$ libvirtd --version
libvirtd (libvirt) 8.0.0
```

So, unless virt-manager does not use the new syntax for the ivshmem device, this seems broken to me.

Looking at the qemu logs, i can see that the ivshmem device is configured the "old" way

```
-object '{"qom-type":"memory-backend-file","id":"shmmem-shmem0","mem-path":"/dev/shm/looking-glass","size":67108864,"share":true}' \
-device ivshmem-plain,id=shmem0,memdev=shmmem-shmem0,bus=pci.16,addr=0x1 \
```

However it should look something like this:
```
-object '{"qom-type":"memory-backend-file","id":"looking-glass","mem-path":"/dev/kvmfr0","size":67108864,"share":true}' \
-device '{"driver":"ivshmem-plain","id":"shmem0","memdev":"looking-glass"}' \
```

**Distro**:

**Comment by crobinso** [comment]
virt-manager doesn't have any UI for adding ivshmem, and without that, virt-manager would not be impacting anything here.

If the suggested looking glass libvirt XML is not producing the expected qemu output, you should try reproduce with latest qemu and latest libvirt, and if it still reproduces, then file a bug against upstream libvirt, or ask on looking glass support forums
