### ISSUE TITLE
hello， do you know what happend?

### ISSUE THREAD

**Issue by fgheng** [virt-manager/virt-manager#44]
![image](https://user-images.githubusercontent.com/50551377/59497439-134d1b80-8ec6-11e9-9e76-5153e38944c0.png)

this button can not click
![image](https://user-images.githubusercontent.com/50551377/59497530-3a0b5200-8ec6-11e9-93a0-b64eeb5e42d8.png)

**Comment by crobinso** [comment]
Where is that browser launched from? If the browser is meant to choose a directory, it won't let you select qcow2 volumes. Or check 'virt-manager --debug' output for a backtrace

**Comment by fgheng** [comment]
> Where is that browser launched from? If the browser is meant to choose a directory, it won't let you select qcow2 volumes. Or check 'virt-manager --debug' output for a backtrace

hello, i know what's wrong, i connected to lxc not a kvm/qemu, now all it is ok, thank you very much.
