### ISSUE TITLE
Feature request: have icons in the system tray menu

### ISSUE THREAD

**Issue by daladim** [virt-manager/virt-manager#440]
**Distro**: Ubuntu 22.04.1 (64bit)
**DE**: Gnome 42.4 (using Wayland)

Hello. Thanks for virt-manager, which is great, and its preinstalled, as-easy-as-ticking-a-box, "system tray icon" works like a charm.
However, I would love to have icons in this "system tray" menu, so that I can see at a glance which VM is running and which ones are not.

My use case is: when I shut down my PC, virt-manager is not always open, but some VMs may still be running. Shutting down my PC then would either slow down the sutdown and/or eventually brutally stop the running VMs and/or cause data loss. I'm that kind of guy who likes to shut down my PC (and my VMs) properly every evening anyway.
Having a quick way, in this menu, to see which VMs to shutdown would be great.

That's the current menu, where I have to unfold every VM to see whether they are running or not (by reading at whether their "Run" option is grayed out or not...not terribly handy)
![image](https://user-images.githubusercontent.com/6873361/192973938-f0e0d310-a1cd-4070-be9d-b8ccd1545d5b.png)

It looks like it is possible to add icons (at least on Gnome), see e.g. the "system" menu
![image](https://user-images.githubusercontent.com/6873361/192974295-bdabd612-43f5-43ca-96eb-a2e0c4ee60cd.png)

Having icons (gray/green circles? or monochrome but filled/empty circles) would really help here.
I'd be happy to contribute in case you give me a few pointers (because I've never developped anything Gnome-related so far)

Thanks

**Comment by crobinso** [comment]
Thanks for the suggestion but it's kinda impossible to get a consistent experience here across the two different types of status icons, gnome-shell extensions, etc. In fact IIRC we originally had icons in the systray on gnome 2 but on they stopped appearing on gnome 3 and we eventually ripped out the implementation. So I don't think this is worth pursuing
