### ISSUE TITLE
request for separate windows for console and details 

### ISSUE THREAD

**Issue by brainchild0** [virt-manager/virt-manager#441]
I am new to VMM, and am running version 4.0.0 over Linux Mint 21, through the official distribution packages.

I  have found the clean appearance of the user interface very tasteful, but the integration of the *Console* and *Details* panes into a single window has made use rather counterintuitive and cumbersome. 

To begin, it was  hard even to find the details pane. Direct access to it is not even possible  from the main window, the one showing the list of installed machines, but instead only by opening the window corresponding to the specific machine and then switching panes. Then, sizing is an issue, because the window dimensions that accommodate best use of the guest system desktop have been very different from the ones that correspond best to the layout of the details pane.   I am constantly resizing the window to compensate for its changing use between the two tasks, which have no strong relation in terms of their graphical layout. 

I would suggest that VMM would be easier to use if  the details and the console views were accessible directly from the machines list as separate  windows. Such a design would correspond closely to those of  other software packages, such as VirtualBox, of the same application domain.

**Comment by crobinso** [comment]
Thanks for the report. I agree there would be some benefits to splitting the console and details window. However the current UI architecture has been that way for over a decade and there's no plans to change it, given current engineering resources, and the pain that comes with big changes like that.
