### ISSUE TITLE
`--cloud-init` on aarch64 does not get expected `virtio-scsi` controller

### ISSUE THREAD

**Issue by crobinso** [virt-manager/virt-manager#445]
Reproducer: `sudo ./virt-install --arch aarch64 --disk none --cloud-init --os-variant fedora36 --print-xml`

There should be a `virtio-scsi` controller, but there isn't. The cdrom device added by `Installer` is happening after `Guest.set_defaults` so it isn't added, and libvirt defaults to lsi controller. Need to figure out how to fix

**Comment by dustymabe** [comment]
workaround by adding `--controller type=scsi,model=virtio-scsi` to the `virt-install` command line.

**Comment by creshal** [comment]
x86 defaulting to SATA is just as problematic these days, the default images by e.g. Debian no longer include the necessary drivers. virtio-scsi should be made the default for all archs.

**Comment by gnoutchd** [comment]
> x86 defaulting to SATA is just as problematic these days, the default images by e.g. Debian no longer include the necessary drivers. virtio-scsi should be made the default for all archs.

Can confirm, as of Debian 12.x "bookworm" (if not earlier) the "genericcloud" images from <https://cloud.debian.org/images/cloud/> cannot access the emulated CD-ROM drive.  A workaround is to use the "generic" images, which do work.

**Comment by gnoutchd** [comment]
> workaround by adding `--controller type=scsi,model=virtio-scsi` to the `virt-install` command line.

Sadly (at least for x86_64) this doesn't work for me as of virt-install 4.1.0 (as shipped in Fedora 40), virt-install generates `<target [...] bus="sata"/>` regardless.

**Comment by crobinso** [comment]
@gnoutchd this bug is specifically about aarch64, in which case the fix would work. Can you file a separate issue about debian bookworm cloud images not working? Please provide a link to the affected image, and the full command line you are using

**Comment by crobinso** [comment]
The issue here with aarch64 was fixed in a91e23c85881daa8a4f86d26bae07d35ca3e6934
