### ISSUE TITLE
Ubuntu 22.04 LTS:  virt-manager package not found...

### ISSUE THREAD

**Issue by jgbarto** [virt-manager/virt-manager#446]
Greetings,  I just decided to upgrade my Hypervisor from Ubuntu 20.04 LTS to 22.04 LTS (Jammy Jellyfish).  

The upgrade went very smoothly, with only one interactive pause for : /etc/ssh/sshd-config  
I chose to keep the existing configuration file for now. 

When the system came up after clean-up/removal of unused packages, VMM / Virtal Machine Manager was gone. 

 I tried to install it via:

sudo apt update
sudo apt install virt-manager

APT came back saying that the package doesn't exist.    Can anyone provide guidance on how to install VMM on 22.04 LTS? This has been my preferred GUI for managing my Virtual Machine Guests up to this point.

I will research how to start my VM's via command line, but VMM works so well...

**Comment by ptoscano** [comment]
Hi @jgbarto, thanks for your report.

virt-manager is definitely available in Ubuntu 22.04: https://packages.ubuntu.com/jammy/virt-manager
Maybe there is some repository misconfiguration on your system? I'd better ask in an Ubuntu forum or user support venue.

I'm closing this issue, as it is not an issue in virt-manager itself.

**Comment by jgbarto** [comment]
Ciao Pino,

Era dovuto alle chiavi PGP del sito www x repos cercati da 'APT UPDATE'.

Key format and path from 20.04 LTS were obsolete. Generated new keys based on the obsolete ones, placed in new keystore directory and then
'apt install virt-manager' worked fine.

Cordiali Sauti,

John Giulio Bartolucci (Seattle).

-------- Original Message --------
