### ISSUE TITLE
Installation problems on Windows - x64 msi version

### ISSUE THREAD

**Issue by x0341** [virt-manager/virt-manager#447]
**Distro**: Windows 11

Instalation issues on Windows 11 Pro x64 - virt-viewer-x64-11.0-1.0.msi does not do anything.

**Comment by CadburyCat** [comment]
There is a problem when attempting to install this, as it does not complete.  Additionally, it seems to just stop mid-install -- and it looks like the installation is incomplete.  

How to fix?

**Comment by qrkourier** [comment]
I suspected the same, but now I think the files may be correctly installed without any friendly, visual indication. I see `\Program Files\VirtViewer v11.0-256\bin\virt-viewer.exe` and I'm able to run it. This may be merely an issue where the installer lacks desktop integration, e.g., launcher shortcut for Start menu.

**Comment by crobinso** [comment]
virt-viewer is a separate project, you'll need to report this issue over there: https://gitlab.com/virt-viewer/virt-viewer
