### ISSUE TITLE
virt-install/virt-manager does not generate working xen pvh XML

### ISSUE THREAD

**Issue by ArthurBorsboom** [virt-manager/virt-manager#448]
Currently Virt-Manager creates by default for Xen a HVM domain.

```
type arch="x86_64" machine="xenfv">hvm</type>
```

How can this default be changed in the GUI to PV or even better PVH?

**Comment by ArthurBorsboom** [comment]
To answer my own question: the [Create a new virtual machine] dialog offers 'architecture options', where the Xen type can be changed between: xen fullvirt (= Xen HVM), xen paravirt (= Xen PV) and xen (= Xen PVH).

![Screenshot_2022-10-25_09-38](https://user-images.githubusercontent.com/6639859/197713385-e007d67e-3f6f-4fda-b2ee-7a1b059201a2.png)

It generated an invalid XML, due to a tablet device being on a non existing USB bus. After manually removing this device, the following XML was valid.

[web4.xml.txt](https://github.com/virt-manager/virt-manager/files/9858178/web4.xml.txt)

Unfortunately, the new Xen PVH VM (domU) crashes instantly after starting, for which I have created a bug report at libvirt.

https://gitlab.com/libvirt/libvirt/-/issues/390

Any help is appreciated getting a Xen PVH DomU running.

**Comment by ArthurBorsboom** [comment]
The cause of the crash has been found and explained in 

https://gitlab.com/libvirt/libvirt/-/issues/390

I believe that virt-manager should add and configure the mandatory kernel element on VM creation for Xen PVH, since right now it creates an invalid XML.

**Comment by crobinso** [comment]
Thanks for reporting this, and the follow up info. Yes it sounds like libvirt xenpvh handling needs to be improved, tools should not be required to pass in the pygrub path if it's a required option. libvirt or libxl fills that in automatically for us for traditional xen PV, for example.

If you get a full working XML config, post it here please, it may help others, and could be used as a source to make virt-install work better with pvh

**Comment by ArthurBorsboom** [comment]
Here is a working Xen PVH XML.

[web3.xml.txt](https://github.com/virt-manager/virt-manager/files/9869652/web3.xml.txt)

Replacing the pygrub 

```
  <os>
    <type arch='x86_64' machine='xenpvh'>xenpvh</type>
    <kernel>/opt/grub/lib/pvhgrub.bin</kernel>
  </os>
```

with direct kernel load (the kernel and initrd have been copied from the guest to the host (/tmp) for testing purposes)

```
  <os>
    <type arch='x86_64' machine='xenpvh'>xenpvh</type>
    <kernel>/tmp/vmlinuz-linux</kernel>
    <initrd>/tmp/initramfs-linux.img</initrd>
    <cmdline>root=UUID=d03cdf45-a8e3-4e76-b632-1cfdab74c78c rw loglevel=3 quiet audit=0 console=hvc0</cmdline>
  </os>
```

works as well.

**Comment by crobinso** [comment]
Any idea if this is still relevant? Do you still care about this issue?

virt-manager definitely worked for xen PV VMs at one point in time. And in those days, libvirt or xen itself would add path to pygrub automatically for us. It seems strange that libvirt or libxl should require us to specify the path to the magic pygrub location. But figuring that the libvirt issue hasn't seen any response either, I can't tell if anyone at libvirt level even really cares about xen PV.

**Comment by ArthurBorsboom** [comment]
> Do you still care about this issue?

Yes, I do. Because I prefer to create a new domains by virt-manager than by manual copying/pasting/editing an XML.

> where did you get the /opt/grub/lib/pvhgrub.bin binary? Did you build that yourself?

This pvhgrub is build by myself, however there is also a similar package provided by the AUR of ArchLinux called 'xen-pvhgrub'. The AUR is a package repository managed by Arch users.

> Any idea if this is still relevant?

I have retested this, since it was a long time ago. :)

- [Virt-manager] > [New Virtual Machine]
- OS install: [Manual install]
- Architecture options Xen Type: [xen]
- Enable storage: unchecked (for easier testing)
- The rest all defaults and [Finish]

Results in "unsupported input bus usb", as mentioned previously in the bug report.

![2024-02-29-094627_402x441_scrot](https://github.com/virt-manager/virt-manager/assets/6639859/344978f3-8a42-4ea8-a535-378373215faa)

I guess this tablet device should have been attached to the xen bus, or not automatically added at all. For testing purposes, 
I can manually remove the Tablet device through [Customize configuration before install] and then [Begin Installation].

Results in 'Input/output error'. 

![2024-02-29-100310_402x498_scrot](https://github.com/virt-manager/virt-manager/assets/6639859/ed8413a9-8396-47ea-935b-cb12e958171b)

Xen creating the domain (VM), which has crashed instantly.
I have to destroy this domain to get rid of the remainings.

![2024-02-29-100332_796x211_scrot](https://github.com/virt-manager/virt-manager/assets/6639859/a9d254d3-07f1-4238-ac63-0b7392a808e0)

This is the invalid XML that was created (including the tablet device).

```
<domain type="xen">
  <name>archlinux</name>
  <uuid>c941b9d9-c7d2-4cf9-a57f-dbb01c2f3ba9</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://archlinux.org/archlinux/rolling"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory>1048576</memory>
  <currentMemory>1048576</currentMemory>
  <vcpu>1</vcpu>
  <os>
    <type arch="x86_64" machine="xenpvh">xenpvh</type>
    <boot dev="hd"/>
  </os>
  <devices>
    <emulator>/usr/lib/xen/bin/qemu-system-i386</emulator>
    <interface type="network">
      <source network="default"/>
      <mac address="00:16:3e:d4:1e:b2"/>
    </interface>
    <console type="pty"/>
    <input type="tablet" bus="usb"/>
    <graphics type="vnc" port="-1"/>
  </devices>
</domain>
```

This is an arbitrary and working xenpvh domain example.

```
<domain type='xen'>
  <name>web3</name>
  <uuid>b5d30580-2abd-4e29-8d0c-38baff445f67</uuid>
  <title>web3: Test websites</title>
  <memory unit='KiB'>10485760</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <os>
    <type arch='x86_64' machine='xenpvh'>xenpvh</type>
    <kernel>/opt/grub/lib/pvhgrub-arch.bin</kernel>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <disk type='block' device='disk'>
      <driver name='qemu' type='raw'/>
      <source dev='/dev/disk/by-partuuid/7e5571b9-bd62-48ec-99c4-3b79353cb74c'/>
      <target dev='xvda' bus='xen'/>
    </disk>
    <controller type='xenbus' index='0'/>
    <interface type='network'>
      <mac address='00:16:3e:26:bd:d5'/>
      <source network='default'/>
    </interface>
    <console type='pty'>
      <target type='xen' port='0'/>
    </console>
    <input type='mouse' bus='xen'/>
    <input type='keyboard' bus='xen'/>
    <graphics type='vnc' port='-1' autoport='yes'>
      <listen type='address'/>
    </graphics>
    <video>
      <model type='xen' vram='4096' heads='1' primary='yes'/>
    </video>
    <memballoon model='xen'/>
  </devices>
</domain>
```

**Comment by crobinso** [comment]
I fixed the usb tablet issue in https://github.com/virt-manager/virt-manager/commit/83daac0489bcd8f6441ba02d418271585e487ca7

If you still hit issues with xenpvh, please file a new bug, and please provide full `virt-manager --debug` output when reproducing, this will also give us `virsh capabilities` XML which is useful.
