### ISSUE TITLE
Cannot create vm with machine type raspi2b

### ISSUE THREAD

**Issue by darkbasic** [virt-manager/virt-manager#449]
**Distro**: Gentoo Linux ppc64le

I'm trying to use virt-manager to create a Raspberry Pi 2 virtual machine on my Talos 2 ppc64le workstation.
In virt-manager I click on `New`, then `Manual install`, architecture `arm` and machine type `raspi2b`.
Next I set either `Generic or unknown OS` or `Debian 11` as operating system, I keep the default 1024 memory and 1 cpu and then I disable storage for this virtual machine (because I want to use an existing image with direct kernel boot, see https://raspi.debian.net/tested-images/).
I check `Customize configuration before instal`" and I click `Finish`.

Unfortunately I get the following error:

`Error starting installation: Did not find any UEFI binary path for arch 'armv7l'`

So I've decided to start from scratch and select `virt` as machine type instead of `raspi2b` and change it back later.
With `virt` I manage to reach the configuration overview before the installation begins.

At this point I have three options for Firmware:
```
Default
UEFI
UEFI armv7l:/usr/share/qemu/edk2-arm-code.fd
```

`UEFI` is the default and if I change the machine type to `raspi2b` I still have the same three options (`/usr/share/qemu/edk2-arm-code.fd` does indeed exist in my file system).

Unfortunately clicking on `Begin Installation` leads me to yet another error:

`Unable to complete install: 'internal error: Required option 'modelName' is not set for PCI controller with index '1', model 'pcie-root-port' and modelName 'none''`

If I change the machine type back to "virt" I don't get any error.

I'm using `app-emulation/qemu 7.1.0`, `app-emulation/libvirt-8.8.0` and `virt-manager-4.1.0` on Gentoo Linux ppc64le with a 4K page size kernel.

**Comment by crobinso** [comment]
Thanks for the report. I'm guessing this has no chance of working. In libvirt code, there's no unittests for generating a VM with `raspi2b` machine type, which usually means it has no chance of working without libvirt code changes.

If you can get a working libvirt XML example, feel free to file a new bug and I will evaluate what we need to do to get it working in virt-manager/virt-install. But until then there's likely nothing we can do here
