### ISSUE TITLE
Mount a host folder as a floppy disk either USB drive

### ISSUE THREAD

**Issue by pmury** [virt-manager/virt-manager#45]
What I have found out so far, you can perform an unattended install for a Windows OS if its installer can discover an "anwers file" in the root folder of a connected device like floppy disk or an USB drive.

Is it possible to provide this file to the Windows installer directly from a local host path pretending it to be a floppy or USB drive?

Alternatively, I would also have a floppy disk image and mount it, is it possible if the above option is not available?

**Comment by crobinso** [comment]
Hello. It's not possible to pass just a single file to floppy/USB and have it show up in the windows VM in a way that windows installer can handle it, the file would need to be built into a floppy image, or into a formatted filesystem image for the USB. You can however generate a floppy image on your own, and attach it to the VM as part of a floppy device. Or format a real USB stick yourself, put the answer file on it, and pass the USB device to your VM. But there are no plans to add specific support to simplify either of these operations to the virt-manager UI
