### ISSUE TITLE
Please restore sb16 and add remaining QEMU sound cards like gus and adlib

### ISSUE THREAD

**Issue by grepwood** [virt-manager/virt-manager#454]
Hi,

I wanted to test create a profile for FreeDOS that would best support QEMU under libvirt, for purposes of training convention staff on how to handle DOS computers. These will be displayed and available for convention attendees to play on.

However, I found that under libvirt I can't add a sb16, even though QEMU supports it and I remember that a few years ago libvirt could still add sb16s.

Nevertheless, adding sb16 does not make a full DOS experience. It needs a MPU and for that, adlib fits the bill. I tried to hack the config by adding sb16 and adlib via XML. The sb16 part worked, but pretty much anything that isn't sb16, ich[0-9] or ac97 won't pass XML verification. When I tried to invoke QEMU manually rather than through libvirt and added `-device sb16 -device adlib` to the commandline, it worked fine.

I'd like to let it be known that there is at least minimal demand for such a feature, from yours truly. If I could be pointed to the right direction I could probably write a patch for those. The bare minimum I'm asking for is sb16 and adlib support. Everything else is extra, and anything is appreciated.

**Comment by morecache** [comment]
* From libvirt's angle:
We know that the sb16 and adlib are helpful for DOS applications, But unfortunately, libvirt only supports the sb16 isa sound card, it doesn't support the isa audio device 'adlib'.
Even you propose a patch to libvirt dev mailing list to add support for this ancient adlib device, It's likely won't be accepted in my opinion.

But you can add the adlib into domain xml via qemu cli passthrough by virsh or virt-manager's XML Editor. Of course, any devices adding via qemu cli passthrough are out of libvirt control. E.g:
@@ -1,4 +1,4 @@
-<domain type='kvm'>
+<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
   <name>tw</name>
   <uuid>9c5c47c6-1a43-4078-a083-4102e3c25be6</uuid>
   <metadata>
@@ -159,5 +159,9 @@
       <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
     </rng>
   </devices>
+  <qemu:commandline>
+    <qemu:arg value='-device'/>
+    <qemu:arg value='adlib,audiodev=audio1'/>
+  </qemu:commandline>
 </domain>

Please refer to https://libvirt.org/kbase/qemu-passthrough-security.html

So the final libvirt domain xml which containing both of  sb16 and adlib looks like:
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  ......
  <devices>
    ......
    <sound model='sb16'/>
    ......
  </devices>
  <qemu:commandline>
    <qemu:arg value='-device'/>
    <qemu:arg value='adlib,audiodev=audio1'/>
  </qemu:commandline>
</domain>


* From virt-manager GUI's angle:
  - not support sb16
  - not support adlib
  But you can manually add them by the XML Editor, 'Edit -> Preferences -> Enable XML Editing'

* From virt-install's angle:
  - it does support sb16, E.g:
      virt-install \
      ... \
      --sound sb16 \
      ...
  - not support adlib, But you can add it via qemu cli passthrough, E.g:
      virt-install \
      ... \
      --sound sb16 \
      --qemu-commandline="-device adlib,audiodev=audio1" \
      ...

**Comment by morecache** [comment]
* From libvirt's angle:
We know that the sb16 and adlib are helpful for the dos applications, but unfortunately, libvirt only supports the sb16 isa sound card, it doesn't support the isa audio device 'adlib'.
Even you propose a patch to libvirt dev mailing list to add support for this ancient adlib device, It's likely won't be accepted in my opinion.
But you can add the adlib into domain xml via qemu cli passthrough by virsh or virt-manager's XML Editor. Of course, any devices adding by qemu cli passthrough are out of libvirt control. E.g:
`@@ -1,4 +1,4 @@`
`-<domain type='kvm'>`
`+<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>`
`   <name>tw</name>`
`   <uuid>9c5c47c6-1a43-4078-a083-4102e3c25be6</uuid>`
`   <metadata>`
`@@ -159,5 +159,9 @@`
`       <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>`
`     </rng>`
`   </devices>`
`+  <qemu:commandline>`
`+    <qemu:arg value='-device'/>`
`+    <qemu:arg value='adlib,audiodev=audio1'/>`
`+  </qemu:commandline>`
` </domain>`

Please refer to https://libvirt.org/kbase/qemu-passthrough-security.html
So the final libvirt domain xml which containing both of sb16 and adlib looks like:
`<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>`
`  ......`
`  <devices>`
`    ......`
`    <sound model='sb16'/>`
`    ......`
`  </devices>`
`  <qemu:commandline>`
`    <qemu:arg value='-device'/>`
`    <qemu:arg value='adlib,audiodev=audio1'/>`
`  </qemu:commandline>`
`</domain>`

* From virt-manager GUI's angle:
  - not support sb16
  - not support adlib
  - But you can manually add them by the XML Editor, 'Edit -> Preferences -> Enable XML Editing'

* From virt-install's angle:
  - it does support sb16, E.g:
`virt-install \`
`... \`
`--sound sb16 \`
`...`
  - not support adlib, But you can add it by qemu cli passthrough, E.g:
`virt-install \`
`... \`
`--sound sb16 \`
`--qemu-commandline="-device adlib,audiodev=audio1" \`
`...`

**Comment by crobinso** [comment]
Like morecache says, this is largely about missing libvirt support. Check grep libvirt sources for `MODEL_SB16` to see how `sb16` value is handled for qemu driver, and use that as a starting point to extend things to cover adlib. It's possible libvirt won't accept it, but showing up with a nice patch and test cases is your best chance

There's not much we can do solely in virt-manager though, so I'm closing this
