### ISSUE TITLE
virt-install `--wait -1` should exit gracefuly when VM is destroyed and undefined

### ISSUE THREAD

**Issue by skobyda** [virt-manager/virt-manager#455]
Creating a VM with virt-install with infinite waining `--wait -1` and then deleting will result in an exception

**How to reproduce:**
1. Create VM `virt-install --os-variant fedora36 --name myMachine --wait -1 --noautoconsole --cdrom /path/to/iso --debug`
2. Destroy the VM, followed **immediatelly** by undefining it (the issue is a race-condition so it's necessary that there is no timeout between destroy and undefine)
`virsh destroy myMachine; virsh undefine myMachine`

Actual behavior:
virt-install process will exit with exception:
```
Traceback (most recent call last):
  File "/home/skobyda/Work/virt-manager/virtinst/virtinstall.py", line 970, in start_install
    _process_domain(domain, guest, installer,
  File "/home/skobyda/Work/virt-manager/virtinst/virtinstall.py", line 921, in _process_domain
    _wait_for_domain(installer, instdomain, autoconsole, waithandler)
  File "/home/skobyda/Work/virt-manager/virtinst/virtinstall.py", line 892, in _wait_for_domain
    if instdomain.check_inactive():  # pragma: no cover
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skobyda/Work/virt-manager/virtinst/virtinstall.py", line 838, in check_inactive
    dominfo = self._domain.info()
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libvirt.py", line 1674, in info
    raise libvirtError('virDomainGetInfo() failed')
libvirt.libvirtError: Domain not found: no domain with matching uuid '514b6f69-79de-4021-8b48-148c84afc497' (fedora36-2022-11-9)
```

Expected behavior:
virt-install should exit gracefully, as deleting and undefining VM is nothing unexcpected

**Comment by skobyda** [comment]
Additional notes:

You can achieve the same result if you first undefine the VM:
`virsh undefine myMachine`
and then destroy it:
`virsh destroy myMachine`

**Comment by crobinso** [comment]
PR #486 attempted to fix this with an eventloop, which is certainly the most thorough, but I think that approach needs more work. I think it'd be ok to just check for VIR_ERR_NO_DOMAIN and not throw a backtrace. It's still an error condition though
