### ISSUE TITLE
Error stopping pool 'sdb': internal error: Child process (/usr/sbin/vgchange -aln drive-hdd) unexpected exit status 5:   Logical volume <<name>> contains a filesystem in use.

### ISSUE THREAD

**Issue by gitzone83** [virt-manager/virt-manager#461]
**Ubuntu 22.04 LTS 

I quite accidentally added LVM Volume Group to the Storage config of the QEMU/KVM and when trying to delete it, I am getting the following error

Error stopping pool 'sdb': internal error: Child process (/usr/sbin/vgchange -aln drive-hdd) unexpected exit status 5:   Logical volume drive-hdd/nextcloud contains a filesystem in use.
  Can't deactivate volume group "drive-hdd" with 1 open logical volume(s)

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/storagepool.py", line 203, in stop
    self._backend.destroy()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 3898, in destroy
    raise libvirtError('virStoragePoolDestroy() failed')
libvirt.libvirtError: internal error: Child process (/usr/sbin/vgchange -aln drive-hdd) unexpected exit status 5:   Logical volume drive-hdd/nextcloud contains a filesystem in use.
  Can't deactivate volume group "drive-hdd" with 1 open logical volume(s)

I have tried pretty much anything, including purging whole kvm/qemu subsystem, erasing config files, and re-installing, only to be presented with the very same error. I do not want to lose the lvm because it has important data on it, but on the other hand, the presence of this entry in the storage pool section drives me nuts. 

Add-on information - the pool is not used by any virtual machine instance, so it should not be in "use" at this time. 

Is this a bug or expected behavior in the virt-manager?

**Comment by crobinso** [comment]
Sorry for lack of response. I assume you resolved it by now, but basically you'll need to just `virsh pool-undefine $POOLNAME` from the command line, and then reboot, and libvirt will forget about it
