### ISSUE TITLE
When running virt-install, an error appears: ERROR    list index out of range

### ISSUE THREAD

**Issue by sszaytsev83** [virt-manager/virt-manager#468]
Hello.
When running virt-install, an error appears:
-------
[root@homekvm virt-manager]# ./virt-install

** (process:5382): WARNING **: 12:26:13.231: Entity http://redhat.com/rhel/9 referenced but not defined
ERROR    list index out of range
[root@homekvm virt-manager]#
-----------------

as OS I use Oracle linux 9.1
help solve the problem.

**Distro**:

**Comment by crobinso** [comment]
This is due to missing or out of date osinfo-db. If you are still hitting this with your distro, please file a bug with them
