### ISSUE TITLE
why not place qcow2 snapshot selection in gui ? 

### ISSUE THREAD

**Issue by TeaCult** [virt-manager/virt-manager#473]
**Distro**: 

Hello Everyone. 
I have tried qcow2 snapshots today with qemu-img. They are working very well. 
Would you consider adding snapshot selection and disk snapshot option to right click  menu ? 
It would be very practical If we may be able run different versions of software and os in same machine configuration and switching them by only right clicking and selecting disk and one of its snapshots. 

Thank you.

PS: I could not find where to recommend and request such thing and used issues. I am sorry if it causes any inconvenience.

**Comment by github2099** [comment]
What version is your virt-manager? On 4.0.0, you have the option to create a snapshot on gui
