### ISSUE TITLE
virt-xml: Hotunplugging watchdog device provides false positive

### ISSUE THREAD

**Issue by skobyda** [virt-manager/virt-manager#474]
Distro: fedora 37
version: origin/main

Description: There is a race condition where if you start a VM, hotplug a watchdog device, edit watchdog's action, and then hotunplug it, virt-xml will hotunplug was successful even though it wasn't. Pay attention that hotplug, edit and hotunplug must be run immediately after each other for a race condition to take effect.

Steps to reproduce:
1. Have a running VM (e.g. "fedora") with no watchdog device attached
2. `./virt-xml fedora --add-device --watchdog action=reset,model=i6300esb --update; ./virt-xml fedora --edit --watchdog action=pause,model=i6300esb; ./virt-xml fedora --remove-device --watchdog model=i6300esb --update`

Actual behaviour:
Command output says that hotunplug was successful: `Device hotunplug successful`
However checking an XML of the running VM: `virsh dumpxml fedora` still shows watchdog device present:

Expected behaviour: 
VM's live XML should either contain watchdog device or the virt-xml output should not say `Device hotunplug successful`

Additional notes: 
Adding timeout of several seconds before `./virt-xml fedora --remove-device --watchdog model=i6300esb --update` _sometimes_ helps to prevent the issue, so this problem is a race condition.

**Comment by crobinso** [comment]
Getting proper hotplug success/fail from the guest is kinda a best effort attempt. I'm pretty sure that's what's going on here and not something we can fix on virt-xml side
