### ISSUE TITLE
Error Launching - Host does not support virtualzation type hvm

### ISSUE THREAD

**Issue by wanfuse123** [virt-manager/virt-manager#481]
I get the same general set of errors as an old closed issues on the latest in Ubuntu 22.10 

2023-01-20 13:57:04.661+0000: shutting down, reason=shutdown
2023-01-20 14:12:05.568+0000: Starting external device: TPM Emulator
/usr/bin/swtpm socket --ctrl type=unixio,path=/run/libvirt/qemu/swtpm/1-Windows-10-swtpm.sock,mode=0600 --tpmstate dir=/var/lib/libvirt/swtpm/6c9ea432-98d0-44e8-91dd-2cd35da7ea90/tpm2,mode=0600 --log file=/var/log/swtpm/libvirt/qemu/Windows-10-swtpm.log --terminate --tpm2
2023-01-20 14:12:05.828+0000: starting up libvirt version: 8.6.0, package: 0ubuntu3.1 (Christian Ehrhardt [christian.ehrhardt@canonical.com](mailto:christian.ehrhardt@canonical.com) Tue, 22 Nov 2022 11:21:30 +0100), qemu version: 7.0.0Debian 1:7.0+dfsg-7ubuntu2.1, kernel: 5.19.0-29-generic, hostname: Desktop-1d
LC_ALL=C
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
HOME=/var/lib/libvirt/qemu/domain-1-Windows-10
XDG_DATA_HOME=/var/lib/libvirt/qemu/domain-1-Windows-10/.local/share
XDG_CACHE_HOME=/var/lib/libvirt/qemu/domain-1-Windows-10/.cache
XDG_CONFIG_HOME=/var/lib/libvirt/qemu/domain-1-Windows-10/.config
/usr/bin/qemu-system-x86_64
-name guest=Windows-10,debug-threads=on
-S
-object '{"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-1-Windows-10/master-key.aes"}'
-machine pc-q35-4.2,usb=off,vmport=off,dump-guest-core=off,memory-backend=pc.ram
-accel kvm
-cpu Haswell-noTSX-IBRS,vme=on,ss=on,vmx=on,pdcm=on,f16c=on,rdrand=on,hypervisor=on,arat=on,tsc-adjust=on,umip=on,md-clear=on,stibp=on,arch-capabilities=on,ssbd=on,xsaveopt=on,pdpe1gb=on,abm=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,skip-l1dfl-vmentry=on,pschange-mc-no=on,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff
-m 4096
-object '{"qom-type":"memory-backend-ram","id":"pc.ram","size":4294967296}'
-overcommit mem-lock=off
-smp 2,sockets=2,cores=1,threads=1
-uuid 6c9ea432-98d0-44e8-91dd-2cd35da7ea90
-no-user-config
-nodefaults
-chardev socket,id=charmonitor,fd=31,server=on,wait=off
-mon chardev=charmonitor,id=monitor,mode=control
-rtc base=localtime,driftfix=slew
-global kvm-pit.lost_tick_policy=delay
-no-hpet
-no-shutdown
-global ICH9-LPC.disable_s3=1
-global ICH9-LPC.disable_s4=1
-boot menu=on,strict=on
-device '{"driver":"pcie-root-port","port":16,"chassis":1,"id":"pci.1","bus":"pcie.0","multifunction":true,"addr":"0x2"}'
-device '{"driver":"pcie-root-port","port":17,"chassis":2,"id":"pci.2","bus":"pcie.0","addr":"0x2.0x1"}'
-device '{"driver":"pcie-root-port","port":18,"chassis":3,"id":"pci.3","bus":"pcie.0","addr":"0x2.0x2"}'
-device '{"driver":"pcie-root-port","port":19,"chassis":4,"id":"pci.4","bus":"pcie.0","addr":"0x2.0x3"}'
-device '{"driver":"pcie-root-port","port":20,"chassis":5,"id":"pci.5","bus":"pcie.0","addr":"0x2.0x4"}'
-device '{"driver":"pcie-root-port","port":21,"chassis":6,"id":"pci.6","bus":"pcie.0","addr":"0x2.0x5"}'
-device '{"driver":"qemu-xhci","p2":15,"p3":15,"id":"usb","bus":"pci.2","addr":"0x0"}'
-device '{"driver":"virtio-serial-pci","id":"virtio-serial0","bus":"pci.3","addr":"0x0"}'
-blockdev '{"driver":"file","filename":"/home/steven/Downloads/Win10_21H2_English_x64.iso","node-name":"libvirt-3-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-3-format","read-only":true,"driver":"raw","file":"libvirt-3-storage"}'
-device '{"driver":"ide-cd","bus":"ide.1","drive":"libvirt-3-format","id":"sata0-0-1"}'
-blockdev '{"driver":"file","filename":"/home/steven/Downloads/virtio-win-0.1.215.iso","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-2-format","read-only":true,"driver":"raw","file":"libvirt-2-storage"}'
-device '{"driver":"ide-cd","bus":"ide.2","drive":"libvirt-2-format","id":"sata0-0-2","bootindex":2}'
-blockdev '{"driver":"file","filename":"/home/steven/VMs/Windows-10/Windows-10.qcow2","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-1-format","read-only":false,"driver":"qcow2","file":"libvirt-1-storage","backing":null}'
-device '{"driver":"virtio-blk-pci","bus":"pci.1","addr":"0x0","drive":"libvirt-1-format","id":"virtio-disk0","bootindex":1}'
-netdev tap,fd=33,vhost=on,vhostfd=35,id=hostnet0
-device '{"driver":"virtio-net-pci","netdev":"hostnet0","id":"net0","mac":"52:54:00:ea:be:84","bus":"pci.4","addr":"0x0"}'
-chardev pty,id=charserial0
-device '{"driver":"isa-serial","chardev":"charserial0","id":"serial0","index":0}'
-chardev spicevmc,id=charchannel0,name=vdagent
-device '{"driver":"virtserialport","bus":"virtio-serial0.0","nr":1,"chardev":"charchannel0","id":"channel0","name":"com.redhat.spice.0"}'
-chardev socket,id=chrtpm,path=/run/libvirt/qemu/swtpm/1-Windows-10-swtpm.sock
-tpmdev emulator,id=tpm-tpm0,chardev=chrtpm
-device '{"driver":"tpm-crb","tpmdev":"tpm-tpm0","id":"tpm0"}'
-device '{"driver":"usb-tablet","id":"input0","bus":"usb.0","port":"1"}'
-audiodev '{"id":"audio1","driver":"spice"}'
-spice port=5900,addr=127.0.0.1,disable-ticketing=on,image-compression=off,seamless-migration=on
-device '{"driver":"virtio-vga","id":"video0","max_outputs":1,"bus":"pcie.0","addr":"0x1"}'
-device '{"driver":"ich9-intel-hda","id":"sound0","bus":"pcie.0","addr":"0x1b"}'
-device '{"driver":"hda-duplex","id":"sound0-codec0","bus":"sound0.0","cad":0,"audiodev":"audio1"}'
-chardev spicevmc,id=charredir0,name=usbredir
-device '{"driver":"usb-redir","chardev":"charredir0","id":"redir0","bus":"usb.0","port":"2"}'
-chardev spicevmc,id=charredir1,name=usbredir
-device '{"driver":"usb-redir","chardev":"charredir1","id":"redir1","bus":"usb.0","port":"3"}'
-device '{"driver":"virtio-balloon-pci","id":"balloon0","bus":"pci.5","addr":"0x0"}'
-sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny
-msg timestamp=on
char device redirected to /dev/pts/0 (label charserial0)
2023-01-20T14:12:06.028218Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-register [bit 8]
2023-01-20T14:12:06.028311Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]
2023-01-20T14:12:06.028320Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2023-01-20T14:12:06.028952Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-register [bit 8]
2023-01-20T14:12:06.028960Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]
2023-01-20T14:12:06.028964Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]

kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

my error seems to have occured after upgrading to ubuntu 22.10, this might not be the case though, I have not used it for some time, maybe a couple of months

in addition I am a windows VM (only one I have that is not defunct(hard drive switch)

runs ok according to the process graph in the background, but when I click on the "open" button it gives me the error:
Error launching details: Host does not support virtualization type hvm for architecture 'x86_64'

and yes virtualization is enabled in the bios (only 2 related settings with this system) does not support passthrough

sudo virsh -c qemu:///system capabilities
61347b80-35cf-11e5-8208-3464a9249942 x86_64 Westmere-IBRS Intel tcp rdma 16114984 4028746 0 0 apparmor 0 dac 0 +1000:+1000 +1000:+1000
Error launching details: Host does not support virtualization type 'hvm' for architecture 'x86_64'

Traceback (most recent call last):
File "/usr/share/virt-manager/virtManager/vmwindow.py", line 40, in get_instance
cls._instances[key] = vmmVMWindow(vm)
File "/usr/share/virt-manager/virtManager/vmwindow.py", line 83, in init
self._details = vmmDetails(self.vm, self.builder, self.topwin,
File "/usr/share/virt-manager/virtManager/details/details.py", line 389, in init
self._init_details()
File "/usr/share/virt-manager/virtManager/details/details.py", line 807, in _init_details
vmmAddHardware.build_video_combo(self.vm, video_dev)
File "/usr/share/virt-manager/virtManager/addhardware.py", line 816, in build_video_combo
default = DeviceVideo.default_model(vm.xmlobj)
File "/usr/share/virt-manager/virtinst/devices/video.py", line 47, in default_model
if (guest.lookup_domcaps().supports_video_virtio() and
File "/usr/share/virt-manager/virtinst/guest.py", line 656, in lookup_domcaps
if not self._domcaps or not _compare(self._domcaps):
File "/usr/share/virt-manager/virtinst/guest.py", line 646, in _compare
if self.os.machine and not _compare_machine(domcaps):
File "/usr/share/virt-manager/virtinst/guest.py", line 633, in _compare_machine
capsinfo = self.lookup_capsinfo()
File "/usr/share/virt-manager/virtinst/guest.py", line 674, in lookup_capsinfo
self._capsinfo = self.conn.caps.guest_lookup(
File "/usr/share/virt-manager/virtinst/capabilities.py", line 303, in guest_lookup
raise ValueError(msg)
ValueError: Host does not support virtualization type 'hvm' for architecture 'x86_64'

ls /dev/kvm
/dev/kvm

ls /dev/kvm
/dev/kvm

core 2 duo system , hp prodesk (2 core, 2 thread)
does not support PCIe pass through

**Comment by crobinso** [comment]
Sorry for lack of response. I assume you figured this out by now. If you are still hitting an issue, please open a new virt-manager discussion
