### ISSUE TITLE
Invalid pixbuf on create snapshots with libvirt 9.0.0 and qemu 7.2

### ISSUE THREAD

**Issue by rmk177** [virt-manager/virt-manager#490]
With libvirt9.0.0 and qemu 7.2 deafult screenshot format is PNG. Make screenshot works perfectly and saves image in png format, but when I want to create snapshot I have screen in strange color scheme because of PNG nature.

**Comment by crobinso** [comment]
Sorry for the late response. On Fedora 38 with libvirt 10.0.0 and qemu 7.2.8 and virt-manager.git this all seems to be working correctly, so I assume this was transient breakage.

If you can still reproduce with latest bits, please open a new issue, list your distro, and I will help debug
