### ISSUE TITLE
LIBUSB_ERROR_NOT_FOUND when trying to redirect Xbox Elite Series 2 Wireless Controller

### ISSUE THREAD

**Issue by FZXizzbKv7jg** [virt-manager/virt-manager#496]
**Distro**: Manjaro Linux

Kernel 6.2
Virt-manager 4.1.0-1 with KVM QEMU
VM with Win11

Redirecting e.g. DualSense Controller works fine

**Comment by crobinso** [comment]
Sorry for the late response. These errors are not related to virt-manager though. If you can still reproduce you probably need to file a report with usbredir: https://gitlab.freedesktop.org/spice/usbredir
