### ISSUE TITLE
Try refreshing storage pool a few times before failing

### ISSUE THREAD

**Issue by eskultety** [virt-manager/virt-manager#498]
**Distro**: RHEL-9
**version**: 4.0.0 (but the code in question is still the same in upstream)

Recently I came across the following on the libvirt upstream CI bare metal systems:
```
[Mon, 06 Mar 2023 10:37:01 virt-install 131421] ERROR (cli:256) internal error: pool 'boot-scratch' has asynchronous jobs running.
[Mon, 06 Mar 2023 10:37:01 virt-install 131420] DEBUG (storage:703) Storage volume 'virtinst-vouz1to3-cloudinit.iso' install complete.
[Mon, 06 Mar 2023 10:37:01 virt-install 131420] DEBUG (storage:440) Couldn't lookup storage volume in prog thread.
[Mon, 06 Mar 2023 10:37:01 virt-install 131421] DEBUG (cli:258)
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtinst/virtinstall.py", line 941, in start_install
    domain = installer.start_install(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 685, in start_install
    self._prepare(guest, meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 397, in _prepare
    self._prepare_cloudinit(guest, meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 379, in _prepare_cloudinit
    iso = self._upload_media(guest, meter, [iso])[0]
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 311, in _upload_media
    newpaths, tmpvols = volumeupload.upload_paths(
  File "/usr/share/virt-manager/virtinst/install/volumeupload.py", line 137, in upload_paths
    pool = _build_pool(conn, meter, system_scratchdir)
  File "/usr/share/virt-manager/virtinst/install/volumeupload.py", line 23, in _build_pool
    StoragePool.ensure_pool_is_running(pool, refresh=True)
  File "/usr/share/virt-manager/virtinst/storage.py", line 210, in ensure_pool_is_running
    pool_object.refresh(0)
  File "/usr/lib64/python3.9/site-packages/libvirt.py", line 4002, in refresh
    raise libvirtError('virStoragePoolRefresh() failed')
libvirt.libvirtError: internal error: pool 'boot-scratch' has asynchronous jobs running.
```

Reproducer steps:
1. Prepare a machine template to use as a storage backing image
2. Use the template to create a bunch of cloud-init configured machines concurrently and instantiate them in a loop (sample CLI command below)
    - note that `default/foo_$i` in the sample CLI below is a volume that is created dynamically using a script that has the template base image set as backing
4. At some point (like 1 in 20 runs) creation of such a machine fails with the error above

**Sample CLI:**
```
$ virt-install \
--connect qemu:///system \
--os-variant unknown \
--name foo_$i \
--disk vol=default/foo_$i,bus=virtio 
--vcpus 4 \
--ram 8192 \
--machine q35 \
--network network=default,model=virtio \
--graphics none \
--sound none \
--transient \
--console pty \
--noautoconsole \
--cloud-init user-data=/tmp/foo_$i-cloud-configq3cwrg78 \
--import \
--quiet
```

**Actual results:**
virt-install fails immediately after failing to refresh the self-created 'boot-scratch'  storage pool because some other instance (or more) of virt-install is writing or deleting a cloud-init config for some other VM in the same pool

**Expected results:**
virt-install uses a grace period where it re-tries to refresh the storage pool in libvirt and then fails fatally.

Would it be possible to use something like a 3 round grace period where virt-install catches the internal error from libvirt and IF there's a mention on asynchronous jobs re-tries refreshing the pool in a few miliseconds?

**Comment by berrange** [comment]
Perhaps it would be a worth having a VIR_STORAGE_POOL_REFRESH_WAIT API constant added to libvirt to make it wait for async jobs to complete, instead of returning immediately, so clients don't have to poll in a loop ?

**Comment by eskultety** [comment]
Hmm, yeah, we could definitely tackle this in libvirt.
