### ISSUE TITLE
RFE: virt-install `--network` support for `type=hostdev` for SR-IOV

### ISSUE THREAD

**Issue by srinaths93** [virt-manager/virt-manager#500]
Do we have the support to configure PCI device (SRIOV) as a network device via virt-install?

It is supported in libvirt. 

1. [Libvirt Ref 1](https://libvirt.org/formatdomain.html#pci-passthrough) 
2. [Libvirt Ref 2](https://wiki.libvirt.org/Networking.html#assignment-with-interface-type-hostdev-sriov-devices-only)
3. [Redhat Ref 3](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/virtualization_administration_guide/chap-guest_virtual_machine_device_configuration#sect-PCI_devices-Configuring_PCI_assignment_passthrough_with_SR_IOV_devices)

Had to manually edit the xml file to do this. Wondering if its supported in virt-install so I can do this while creating the VM itself.
FYI: I know I can do it by having it as a Host Device using --hostdev, but I would like to have it as a network device as given in those reference links.

**Comment by srinaths93** [comment]
Any update on this ?

**Comment by opoplawski** [comment]
I would really like to see this as well.

**Comment by opoplawski** [comment]
Maybe something like `--network hostdev=0000:04:00.2,mac=00:...`?

**Comment by crobinso** [comment]
> Maybe something like `--network hostdev=0000:04:00.2,mac=00:...`?

I added this, with format that matches what `--hostdev` already supports
