### ISSUE TITLE
Dark mode (on KDE) makes buttons look "greyed out"

### ISSUE THREAD

**Issue by freekvh** [virt-manager/virt-manager#503]
**Distro**: EndeavourOS, KDE 5.27

I think this image says enough, in my install it took me a long time to realize these buttons were active and could be pushed:

![image](https://user-images.githubusercontent.com/12241293/228756480-da06a69f-b52c-44bd-8dbe-52371597aa53.png)

Thank you for an otherwise great experience :)

**Comment by lacouture** [comment]
I think the proper fix for this consists in choosing KDE Plasma's appropriate icon set for dark mode.
Here's what I see when choosing the default "Breeze" icon set:
 
![Screenshot_20230603_111927](https://github.com/virt-manager/virt-manager/assets/3317671/a097d1d4-d1e3-4449-bf01-59742aaae02b)

Here's what I get when choosing the "Breeze Dark" icon set:
 
![Screenshot_20230603_112021](https://github.com/virt-manager/virt-manager/assets/3317671/8cc27a70-e089-4554-9a4a-a307a5a0d01e)

This setting is in the Settings app, under Appearance → Icons:
![System-settings](https://github.com/virt-manager/virt-manager/assets/3317671/432839d4-30e5-495a-8535-615a4c3d8995)

By the way, this fixes similar dark mode issues in many other applications.

I think this issue should be closed, as it's not specific to Virt-Manager.

**Comment by freekvh** [comment]
Ah, yes you're right, I set "Breeze Dark Endeavour OS", I guess that didn't select the right icon set. Thanx.

**Comment by rokejulianlockhart** [comment]
Maybe close the issue then, @freekvh?

![image](https://github.com/virt-manager/virt-manager/assets/42837531/bea78695-c6e3-4c40-a33e-00837773f704)
