### ISSUE TITLE
Wiki page for how to use VMM

### ISSUE THREAD

**Issue by eiger3970** [virt-manager/virt-manager#504]
**Distro**: 
VMM 2.2.1 I’m trying to create a shared directory between the host and guest. 
A wiki showing how would be useful. 
Any chance of creating a How To Use wiki page?
I can then update the page as I figure out the GUI navigation.

**Comment by crobinso** [comment]
Thanks for the suggestion. I'm not really interested in maintaining documentation, it just tends to get out of date and inaccurate and create a maintenance burden. Feel free to create a github gist or something similar to share your steps with others.
