### ISSUE TITLE
How to tunnel all traffic of a VM through a Proxy?

### ISSUE THREAD

**Issue by FabioNevesRezende** [virt-manager/virt-manager#511]
This is not a bug actually, just a question in usage of the program

I'm trying to make a VM in which all its traffic goes through a proxy (like a tor proxy or any other ip/port proxy). I've found [this article][1] showing that it is possible in command line, however I'm using the GUI manager virtual manager and didn't found in anywhere a place to setup a proxy for the VM. So I'm asking if is it possible to make through the GUI?

I want to make it on the host machine so it doesn't happen to make any connection by mistake inside the virtual machine to outside using my default connection.

  [1]: https://lists.gnu.org/archive/html/qemu-devel/2017-05/msg01433.html

**Comment by crobinso** [comment]
It doesn't look like that qemu support ever even ended up in qemu.git FWIW

There's likely some way to do this with custom networking configuration. You could create a local bridge, connect the VM to it, and then manipulate traffic way you want with iptables/nftables. But there's no out of the box way to do it that I know of
