### ISSUE TITLE
Deleted ISO image still appears on selection list

### ISSUE THREAD

**Issue by github2099** [virt-manager/virt-manager#514]
![Screenshot from 2023-04-25 23-52-51](https://user-images.githubusercontent.com/49584984/234540407-e01c51ae-9838-41c0-a475-de8b4753b8ed.png)

In the picture, There is nothing in the Download folder, but I still "can" choose the iso I deleted...

**Comment by phrdina** [comment]
These paths are not related to storage pools but it is a history of paths used there so it will not be removed if you delete files. Closing as not a but.

**Comment by github2099** [comment]
> history of paths used there
is there a way to clear those, they are pilling up as I import different .iso

**Comment by phrdina** [comment]
From virt-manager ui no it's not possible. It is stored using dconf so you can use external dconf editor to do that.

**Comment by github2099** [comment]
> dconf

Thanks! That enlightened me. dconf editor!!
I tried this on terminal and works too : 
`gsettings reset org.virt-manager.virt-manager.urls isos`
