### ISSUE TITLE
UI strings clarification - close vs quit item in File menu of app windows(s)

### ISSUE THREAD

**Issue by p-bo** [virt-manager/virt-manager#516]
Hello,
trying to express these in translation to communicate to users this supposedly different meaning/function of these two menu items.
Would it be possible to clarify/elaborate regarding this please?
Thanks

**Comment by phrdina** [comment]
Hi, 

if you go to `Edit -> Preferences -> General` and check `Enable system tray icon` the behavior of the two option will be different. Using the `Close` option will only close the main window but virt-manager itself will continue running and you will still see the tray icon. Using `Quit` would terminate virt-manager completely.

If the tray icon is disabled both options it terminate virt-manager.

**Comment by p-bo** [comment]
Many thanks for explanation!

From own observation:
(main manager window with list of VMs opened and multiple windows of VMs too)
- Close item closes only that particular window (be it main manager or with VM one)
- Quit closes all windows related to virt-manager (or minimizes them to tray, if that option is set, as you described)

So both menu items could be possibly expressed like:

Close -> Close this window

Quit -> Quit app / send to tray
(or: Quit whole app / send it to tray)

Right?

**Comment by phrdina** [comment]
Yeah that is correct.
