### ISSUE TITLE
Install Windows 10 away from the Home folder on Fedora 38

### ISSUE THREAD

**Issue by FakhrEldinTeama** [virt-manager/virt-manager#517]
I own a computer with 2 hard disks
The first one: a 128 GB SSD hard drive inside the system case with Fedora 38 only

The second hard drive inside the system case is a 1 terabyte HDD, divided into one partition named MyHard of NTFS type.
I store all my files on it and it has the most free space on my device

Currently, I do not want to deal with the Windows system on my computer completely
And if I had to Windows, for example, to use Office 365 programs, for example, I would use a virtual system on virt-manager to get the job done only.

But when I installed Fedora for the entire 128 GB SSD and mount the MyHard partition for Fedora 38
And I wanted to install the virt-manager program and create a virtual Windows 10 system. All the steps were correct, because the virtual system created Windows 10 on the Home folder inside the SSD on which Fedora 38 is located.
But I encountered a problem that the Windows system grows in size with time, and therefore the Fedora 38 SSD will fill up

I want the virtual system files to be Windows 10, whether the installation file for Windows is .iso or the virtual system file of type .qcow2 with a size of 120 GB on a 1 terabyte HDD so that I can take advantage of the large disk space
And to prevent the SSD 128 of Fedora 38 from becoming full

When I do the normal steps to create the virtual system on virt-manager, but I give it the path of the VirtM folder in which the files required for the virtual system are located on the one-terabyte HDD, an error appears in the permissions, which is as follows:
  Unable to complete install: 'internal error: process exited while connecting to monitor: 2023-04-28T03:19:17.899461Z qemu-system-x86_64: -blockdev {"driver":"file","filename":"/mnt /MyHard/Programs/VirtM/Win1032HardDisk.qcow2","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/ mnt/MyHard/Programs/VirtM/Win1032HardDisk.qcow2': Permission denied'

Traceback (most recent last call):
   File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
     callback(asyncjob, *args, **kwargs)
   File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
     installer. start_install(guest, meter=meter)
   File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
     domain = self._create_guest(
              ^^^^^^^^^^^^^^^^^^^
   File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
     domain = self.conn.createXML(initial_xml or final_xml, 0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/lib64/python3.11/site-packages/libvirt.py", line 4481, in createXML
     raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2023-04-28T03:19:17.899461Z qemu-system-x86_64: -blockdev {"driver":"file","filename":"/mnt/MyHard /Programs/VirtM/Win1032HardDisk.qcow2","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/mnt/ MyHard/Programs/VirtM/Win1032HardDisk.qcow2': Permission denied

I modified a file
sudo nano /etc/fstab
To make the HDD readable and writable by deleting the letters
",ro"

Note that I ran virt-manager with root privileges by command
sudo virt-manager
And I did the steps giving virt-manager the path to the required files on the VirtM folder on the MyHard disk, but I also got the same problem.

**Comment by crobinso** [comment]
Thanks for the report but this doesn't look like a bug, just some permissions problem you need to sort out.

* Try rebooting and making sure that the filesystem is actually mounted read/write
* Disable selinux or apparmor to be sure
* Make sure every directory in the path has +x permissions, so the qemu user can access it.

If you still have issues, please open a virt-manager `discussion`, and provide full `virt-manager --debug` output so people can help debug
