### ISSUE TITLE
Host will go to sleep even virt-manager is running

### ISSUE THREAD

**Issue by github2099** [virt-manager/virt-manager#518]
Host: Pop!_OS 22.04
Kernel: 6.2.6
Virt-Manager: 4.0.0
libvirtd: 8.0.0

virt-manager is running.. and playing video in VM.. mouse not moving.  Host goes into sleep mode after "inactivity"

#514

**Comment by crobinso** [comment]
Thanks for the suggestion. This seems like something the spice-gtk and/or gtk-vnc widget should handle, since they are the ones responsible for processing sound playback etc. You should file a request there: https://gitlab.freedesktop.org/spice/spice-gtk
