### ISSUE TITLE
Can't use <qemu:commandline> in xml File

### ISSUE THREAD

**Issue by MtFBella109** [virt-manager/virt-manager#519]
I tried several times to add something with <qemu:commandline> in the xml file from my Vm, I edited it via the virt-manager and I enabled the XML editing in Preferences. But everytime I add something with <qemu:commandline> and added to the <domain type=kvm> Tag the following: "xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'" and then pressed apply, virt manager removed it automatically. This happens regularly only if the config is wrong, but it doesn't is a wrong config for the xml file, I tried with virt-manager --debugging but in the console it writes, that it was added to the xml file, but it wasn't. I edited other Parts of the xml File and this worked

**Comment by MtFBella109** [comment]
Okay, i can only add it with virt-xml command, but I needed to put the extra --connect qemu:///system Argument to the complete command. But in the virt manager I couldn't add it

**Comment by crobinso** [comment]
Sorry for late response. Is this still valid? If so, please reproduce with `virt-manager --debug` and attach the full output here
