### ISSUE TITLE
Connection name is hard to read with dark theme

### ISSUE THREAD

**Issue by slokhorst** [virt-manager/virt-manager#52]
![image](https://user-images.githubusercontent.com/8083666/64907236-fc4ddd80-d6ef-11e9-9283-bbd4ebea96b5.png)

The black text on dark background is hard to read.

This is because of the hard-coded color in [`_build_conn_color()`](https://github.com/virt-manager/virt-manager/blob/d6d97c658771f75d2a1fdfeeac02ee7bfb106b88/virtManager/manager.py#L595) in `virtManager/manager.py`.

**Comment by crobinso** [comment]
Thanks for the report, fixed now. There's probably more but I'll need to do some research what the proper way to handle setting explicit colors across different themes

**Comment by slokhorst** [comment]
Thanks, big improvement! This is the only problematic text I've found so far. I'll let you know if I find something else.
