### ISSUE TITLE
IDE is no longer listed when creating storage devices

### ISSUE THREAD

**Issue by ghost** [virt-manager/virt-manager#529]
I object to this change. I'm using virt-manager together with libvirt and qemu to do things on FreeDOS and other systems, where IDE was either the only mass storage bus, or was in process of being phased out by SATA. Please revert this change. Having this kind of support doesn't cost virt-manager anything.

EDIT: this doesn't happen on all types of machines. Sorry about the initial sensationalism. My FreeDOS stuff is safe and I can breathe a sigh of relief. Trying Mac OS9 on the other hand, isn't even possible.
The problem exists when trying to create a mac99 machine with qemu-system-ppc. According to https://wiki.qemu.org/Documentation/Platforms/PowerPC#PowerMac_G4_and_G3_emulation the correct incantation for getting started with installing Mac OS9 is:
```
qemu-system-ppc -L pc-bios -boot d -M mac99 -m 512 -hda <hd image file> -cdrom <iso file of installation media>
```
By specifying it as `-hda` it is heavily implied that it's an IDE device. The error I got was that I cannot have IDE devices with either `qemu-system-ppc` or `mac99` type machine - which is demonstrably false:
![obraz](https://github.com/virt-manager/virt-manager/assets/20668811/667591fc-757f-4f9d-9004-7cc851c036cc)

**Comment by crobinso** [comment]
For emulating esoteric systems, virt-manager and libvirt are always going be painful. For example, there's no 'mac99' test case in libvirt's basic unit test suite, which likely means no one has successfully tested it with libvirt.

For these historical emulation cases you are generally much better off just using qemu directly.
