### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by rokejulianlockhart** [virt-manager/virt-manager#530]
# Issue

My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245. However, more specifically, there is no forum for https://github.com/virt-manager/virt-manager.

# Examples

This is problematic, for instance, because I'd like to ask what

> [ISO media volume](https://github.com/virt-manager/virt-manager/assets/42837531/ab8bcfd0-0b01-4b83-9afd-df69c53aaa04)

or

> ![image](https://github.com/virt-manager/virt-manager/assets/42837531/79feeb9a-d8b4-4ab2-95a3-cd663aedd8db)

mean, but this isn't worth notifying the mailing list for, and I shall never understand how to use unbridged-to-Matrix IRC like https://virt-manager.org/communicate.html describes.

# Template

**Distro**: cpe:/o:opensuse:tumbleweed:20230529

**Comment by crobinso** [comment]
Thanks for the suggestion, it's enabled now. If your questions are still relevant, feel free to discussions a try, will help me figure out how to use it too :)
