### ISSUE TITLE
[Feature Request] Release a Windows version

### ISSUE THREAD

**Issue by Tarek-Hasan** [virt-manager/virt-manager#536]
Currently, there's no decent GUI application to run QEmu on Windows. Which lefts the average Windows user with only option of using VirtualBox. Existing solution to use QEmu includes, running prebuild VM in virt-viewer and Quickemu, or using QtEmu; which last release was in 2019. Moreover, it lacks new QEmu functionality, buggy and slow. It takes about eye watering 16 minutes to just to start the program.
Please, consider releasing a Windows version.

**Comment by AliYar-Khan** [comment]
definitely needs a windows version

**Comment by crobinso** [comment]
There's a newer issue here where people have tried to get virt-manager running on windows. Interested users should follow that one

https://github.com/virt-manager/virt-manager/issues/590

**Comment by AliYar-Khan** [comment]
@crobinso 
Doesn't solve the problem. The solution provided is a work around and it is not correct way!!! Definitely need to be reconsidered for having a windows version.
