### ISSUE TITLE
virt-manager closes/crashes when waking from suspend

### ISSUE THREAD

**Issue by bitestring** [virt-manager/virt-manager#537]
**Host Distro**: Fedora 38 (Silverblue) + GNOME + Wayland

**virt-manager version**: 4.1.0

**Bug**: If virt-manager is open and connected to a VM, after a suspend and wake cycle on the host, virt-manager occasionally crashes and closes all it's windows. There is no pattern but it happens randomly and it does not matter which guests are running. VMs are still running. Reopening the virt-manager and connecting to the VM restores the graphical console.

**Steps to reproduce:**
1. Start a VM and connect to the graphical console.
2. Suspend the host
3. Wake up the host

**Expected Behavior:**
virt-manager and graphical console window should be still running.

**Actual Behavior:**
virt-manager window is closed / crashed.

**Comment by crobinso** [comment]
Thanks for the report. You'll need to grab a backtrace using coredumpctl or abrt or some other tool for us to have a chance of debugging this.

It's probably this issue though: https://github.com/virt-manager/virt-manager/issues/501

So I'm closing this. But if you catch a backtrace and it looks different, please file a new issue
