### ISSUE TITLE
USB port passthrough

### ISSUE THREAD

**Issue by residentcode** [virt-manager/virt-manager#538]
Please add support for usb switch ,
-usb \
-device usb-host,hostbus=1,hostport=11.3 \

**Comment by crobinso** [comment]
Libvirt does not have support for that feature. That would be a prerequisite for us to even consider adding it to the UI, so you'll need to file a request with libvirt first but if they haven't added it yet, chances are low itll end up being implemented IMO

So you best bet is using qemu commandline passthrough. Try this

```console
virt-xml VMNAME --confirm  --edit --qemu-commandline="-device usb-host,hostbus=1,hostport=11.3"
