### ISSUE TITLE
virt-convert fails to convert disks in ova

### ISSUE THREAD

**Issue by bersace** [virt-manager/virt-manager#54]
Hi,

I'm using virt-convert to deploy an OVA. I hit the following error message:

```
$ virt-convert --debug --disk-format qcow2 vm.ova
Running /usr/bin/qemu-img convert -O qcow2 vm-sda.vmdk /home/bersace/.local/share/libvirt/images/vm-sda.qcow2
ERROR    /usr/bin/qemu-img convert -O qcow2 vm-sda.vmdk /home/bersace/.local/share/libvirt/images/vm-sda.qcow2: failed with exit
RuntimeError: qemu-img convert -O qcow2 vm-sda.vmdk /home/bersace/.local/share/libvirt/images/vm-sda.qcow2: failed with exit status 1: b"qemu-img: Could not open 'vm-sda.vmdk': Could not open 'vm-sda.vmdk': No such file or directory\n"

```

I runned with pdb. The problem is that `absin` variable in https://github.com/virt-manager/virt-manager/blob/master/virtconv/formats.py#L238 is not absolute at all.

OVA support seems implemented by extracting the archive, then replacing input with extracted directory. But qemu-img is still runned in CWD instead of temp-dir.

If I extract locally the ova with tar, it works even when passing the original ova file as argument :

``` console
$ tar -xf vm.ova
$ virt-convert --disk-format qcow2 vm.ova
...
[ven., 20 sept. 2019 11:56:00 virt-convert 32536] DEBUG (formats:78) Running command: /usr/bin/qemu-img convert -O qcow2 /home/bersace/src/vm-sda.vmdk /home/bersace/.local/share/libvirt/images/vm-sda.qcow2
[ven., 20 sept. 2019 11:59:53 virt-convert 3699] DEBUG (formats:85) stdout=b''
[ven., 20 sept. 2019 11:59:53 virt-convert 3699] DEBUG (formats:86) stderr=b''   
...
```

thus, the vm-sda.vmdk used is not the one in ova !

What am I missing ?

**Comment by crobinso** [comment]
Thanks for the repor. I'm not sure what the issue is, but FYI virt-convert is slated for removal: https://www.redhat.com/archives/virt-tools-list/2019-June/msg00117.html

I suggest extracting the disk image from the .ova, and just passing it to 'virt-install --disk X' with a valid --os-variant to fill in defaults. The truth is virt-convert was never particularly complete so even if you solve this problem it's probably not going to give great results

**Comment by bersace** [comment]
@crobinso Yes, i worked around this by extracting ova before running virt-convert.

Too bad for the removal. Do you know other format that may be shared between vSphere and libvirt/qemu ?

**Comment by crobinso** [comment]
If you want to optimally convert from vmware to libvirt+kvm, I suggest checking out virt-v2v. It's much more powerful and interesting. virt-convert isn't much better than the virt-install method

**Comment by bersace** [comment]
I'm using virt-convert to test an OVA in libvirt before shipping it to vSphere.
