### ISSUE TITLE
new user troubles

### ISSUE THREAD

**Issue by ZCGreen** [virt-manager/virt-manager#543]
I am a new user of your your program, so I don't think this is actually a bug, but I couldn't find anywhere else to ask for help. I'm trying to install Windows on my Chromebook. I read about doing it on Chrome Ready. I've followed their directions with your program using both Windows 10 and 11 ISO files, and I got the same error message both times. What am I doing wrong? Please help. Thank you. I am attaching a screenshot of the error.

![Screenshot 2023-07-15 4 00 00 PM](https://github.com/virt-manager/virt-manager/assets/139653594/85507c85-50e6-4796-b27b-ff9b809ac8e2)

**Comment by crobinso** [comment]
Hey, sorry you hit issues. I believe this was a temporary libvirt bug that was fixed in later versions. If you are still seeing this with the latest packages in your distro, file a libvirt bug there.
