### ISSUE TITLE
[Feature request] gsettings to define space between the Virtual Machine Manager and the Virtual Machine screen

### ISSUE THREAD

**Issue by davidhedlund** [virt-manager/virt-manager#553]
![image](https://github.com/virt-manager/virt-manager/assets/6416073/6ac2292a-5dea-422f-9f88-bb28366eadd6)

I'd like 0 px dead space. A gsettings for that would be helpful.

Thanks.

**Comment by phrdina** [comment]
There is no specific dead space hardcoded in virt-manager. The VM screen is aligned in middle so if it's smaller it will have the same empty space at top and bottom. So there is nothing to be implemented and no gsettings needed.
