### ISSUE TITLE
[Feature request] Add VirtualBox to "Add connection..." dropdown

### ISSUE THREAD

**Issue by agowa** [virt-manager/virt-manager#569]
Virt Manager surprisingly works with VirtualBox as well, but a user needs to know that the custom URL for connecting to are `vbox:///session` and `vbox:///system`.

**Distro**: ArchLinux

**Comment by crobinso** [comment]
Thanks for the suggestion, but IMO we should not add that. We have zero unit testing for anything vbox related, we don't do manual testing etc, so we shouldn't advertise it in the UI in any way IMO. I'm glad it works though!
