### ISSUE TITLE
huge memory leak (80 GB RAM usage)

### ISSUE THREAD

**Issue by Germano0** [virt-manager/virt-manager#571]
Hello, on Fedora 38 KDE I am experiencing `virt-manager-4.1.0-2.fc38.noarch` using 80 GB RAM.
I tried to hunt memory leaks with heaptrack, but I found out that virt-manager is written in Python, so heaptrack seem to not work with such stack.
Do you have any idea how I could provide useful data? I haven't killed yet the running process
Best regards

**Comment by Germano0** [comment]
> During this time, did you have a VM window actively open?

I had a VM window open only for maybe one or two days. The remaining days I just had the virt-manager window (with the list of VMs)

> Did you have VMs regularly starting and stopping?

Yes

> Can you try re-running virt-manager --debug from the terminal, recreate the open connections and windows, and see if there's periodic errors in the terminal output, or does it quiet down after a minute?

Thank you. I am doing it right now and trying to keep the process running for a week and see what happens

**Comment by Germano0** [comment]
I have run virt-manager for days till it crashed (see attachment below). I had no huge memory leaks this time
[virt-manager_debug_output.txt](https://github.com/virt-manager/virt-manager/files/12642337/virt-manager_debug_output.txt)

**Comment by crobinso** [comment]
Ok since there were no memory leaks, I'm closing this. If you can capture --debug output with a leaking virt-manager, please open a new issue
