### ISSUE TITLE
[feature request] Reuse Ubuntu's Virtual Machine's XML configuration settings for Trisquel

### ISSUE THREAD

**Issue by davidhedlund** [virt-manager/virt-manager#575]
Upstream issue link: https://github.com/virt-manager/virt-manager/issues/575

Trisquel 10 is based on Ubuntu 20.04, and Trisquel 11 is based on Ubuntu 22.04. However, IDE disk and IDE CDROM is used by the Trisquel hardware detail templates in virt-manager, while Ubuntu uses VirtIO and SATA CDROM, which is faster. Also, I have [problems to access USB devices in Trisquel](https://gitlab.trisquel.org/trisquel/package-helpers/-/issues/113) if they use IDE, but not VirtIO.

When the hardware setup is not identical between Trisquel VMs and Ubuntu VMs, it might be difficult to recognize that it can cause the distros to behave differently.

| OS information[1] | Hardware profiles (generated by "Choose the operating system you are installing" (see screenshot)) |
|-: | -: |
| Trisquel 10 LTS           | Chipset: i440FX. IDE (hda), IDE CDROM (hdb) |
| Trisquel 11 LTS           | Chipset: i440FX. IDE (hda), IDE CDROM (hdb) |
| Ubuntu 20.04 LTS          | Chipset: Q35. VirtIO (vda), SATA CDROM (sda) |
| Ubuntu 22.04 LTS          | Chipset: Q35. VirtIO (vda), SATA CDROM (sda) |

1: See https://gitlab.trisquel.org/trisquel/package-helpers/-/issues/116 for screenshots

# Suggested solution
Based on the findings in the table above, a package helper script could copy:
* Copy the Virtual Machine's XML configuration settings from "Ubuntu 22.04 LTS" to "Trisquel 11 LTS"
* Copy the Virtual Machine's XML configuration settings from "Ubuntu 20.04 LTS" to "Trisquel 10 LTS"

It's not an option to rename "Ubuntu 22.04 LTS" to "Trisquel 11 LTS / Ubuntu 22.04 LTS", and "Ubuntu 20.04 LTS" to "Trisquel 10 LTS / Ubuntu 20.04 LTS", because Ubuntu is not a [free GNU/Linux distribution](https://www.gnu.org/distros/free-distros.en.html), so it will not be accepted in Trisquel that is listed as an approved free distro.

# virt-manager package info
```
$ apt-cache show virt-manager
Package: virt-manager
Architecture: all
Version: 1:4.0.0-1
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Libvirt Maintainers <pkg-libvirt-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2298
Depends: gir1.2-gtk-3.0 (>= 3.10), gir1.2-gtk-vnc-2.0, gir1.2-gtksource-4, gir1.2-libosinfo-1.0, gir1.2-libvirt-glib-1.0, gir1.2-vte-2.91, python3-dbus, python3-gi (>= 3.31.3~), python3-gi-cairo, python3-libvirt (>= 0.7.1), virtinst (= 1:4.0.0-1), dconf-gsettings-backend | gsettings-backend, python3:any
Recommends: gir1.2-ayatanaappindicator3-0.1 | gir1.2-appindicator3-0.1, gir1.2-spiceclientglib-2.0, gir1.2-spiceclientgtk-3.0, libvirt-daemon-system (>= 1.2.7)
Suggests: gir1.2-secret-1, gnome-keyring, python3-guestfs, ssh-askpass, virt-viewer
Filename: pool/main/v/virt-manager/virt-manager_4.0.0-1_all.deb
SHA512: b6618d34087f2f5edb7fb19ce5b7e7fa151c4190b82ce5360b03050229837996d589af7965f5509c6a6570a605d17780733a57e9f4e76880cce8d4cf627fb0aa
Homepage: https://virt-manager.org/
Size: 261800
SHA256: 5f54b22d8dd4dd2db7e82f5267e72981699d97600a9ee56bfd98a6f2ea58538c
SHA1: 72b92481fcccaffaf2a947da85ae6f772ec8b258
MD5sum: 548c6d54a2aab650eb87db324a8ba502
```

**Comment by davidhedlund** [comment]
It looks like virt-manager is trying to redirect the USB device to /dev/sda but it fails for distros with the system installed on /dev/sda since it occupies the device.

**Comment by davidhedlund** [comment]
Cannot reproduce the issue. When I reinstalled the distros the target hard disk drive device was set to "vda" in virt-manager.

**Comment by ajgringo619** [comment]
`vda` device names are only used when using VirtIO disk devices. I use VirtIO SCSI on all of my systems, which uses `sda`. And, any redirected USB devices show up as `sdb`.

**Comment by davidhedlund** [comment]
> `vda` device names are only used when using VirtIO disk devices. I use VirtIO SCSI on all of my systems, which uses `sda`. And, any redirected USB devices show up as `sdb`.

Thanks! I updated the top post: The "Trisquel 10", and "Trisquel 11" OS templates failed to mount the USB devices. Should these templates be updated by the developers?

**Comment by davidhedlund** [comment]
* https://github.com/virt-manager/virt-manager/issues/589

**Comment by ptoscano** [comment]
This is already the case in osinfo-db: each Trisquel version properly `<derives-from>` the Ubuntu version it was forked from.

This is a downstream issue (in Trisquel), see my explanations in #589. Hence, closing.

**Comment by davidhedlund** [comment]
@ptoscano Your help is deeply appreciated. Thank you so much for spending time to help us with Trisquel development!

**Comment by davidhedlund** [comment]
Fixed in Trisquel 11: "Fixed by [!1202 (merged)](https://github.com/trisquel/package-helpers/-/merge_requests/1202), soon to land on the repositories vía,

osinfo-db (0.20221130-2+11.0trisquel7)" - https://gitlab.trisquel.org/trisquel/package-helpers/-/issues/116#note_10763
