### ISSUE TITLE
Disabling Autoconnect for Serial Console not working

### ISSUE THREAD

**Issue by agowa** [virt-manager/virt-manager#584]
**Distro**: ArchLinux

Disabling the Autoconnect option for QEMU/KVM VMs that only have a Serial port (and thereby the auto generated serial console) doesn't work and this causes data corruption for other clients connected to its pty as somehow some of the input and output arrive at virt-manager and some at the script/client that actually should be connected to the pty.

This is additionally annoying as virt-manager also connects to the console when a user is trying to only access the virtual hardware configuration screen (like when trying to find the issue that causes corrupted output on the serial port. And here it comes full circle)

Selecting/Deselecting this option changes nothing:
![image](https://github.com/virt-manager/virt-manager/assets/2544867/c079afce-2157-4b18-b577-10a01adb8913) ![image](https://github.com/virt-manager/virt-manager/assets/2544867/db65f53d-4da8-492a-a1a4-04e0724d5b46)

**Comment by crobinso** [comment]
Thanks for the report, this should be fixed in git now
