### ISSUE TITLE
No graphical console with localhost qemu+tcp

### ISSUE THREAD

**Issue by enool** [virt-manager/virt-manager#592]
**Distro**: Any

When connecting virt-manager to libvirt on localhost with TCP, graphical console bound to localhost is unavailable.

I'm using virt-manager with:

`virt-manager -c qemu+tcp://localhost/system`

Libvirtd is configured to listen TCP on localhost with `/etc/libvirt/libvirtd.conf`:
```
listen_tcp = 1
listen_addr = "127.0.0.1"
```

Spice is configured to listen TCP on localhost with `/etc/libvirt/qemu.conf`:
```
spice_listen = "127.0.0.1"
```

The error message suggests that I'm trying to connect to a remote host:

```
Error connecting to graphical console:
Guest is on a remote host with transport 'tcp' but is only configured to listen locally. To connect remotely you will need to change the guest's listen address.
```

Neither Spice nor VNC work when bound to localhost. The same configuration works fine when connected to with virt-viewer. Tried with the following:

`virt-viewer -c qemu+tcp://localhost/system`

This seems like an edge case that was missed in graphical device configuration validation. The use case is with containers where using TCP and variable bind address is easiest solution for configurability.

There is a proposed fix in PR #591.

edit: added some configuration snippets to help verify the issue

**Comment by crobinso** [comment]
That PR was merged, so this can be cloed.
