### ISSUE TITLE
virt-viewer/remote-viewer 11 on Windows 10 crashes right after launching.

### ISSUE THREAD

**Issue by johjeff** [virt-manager/virt-manager#593]
What version of msvcrt.dll (Visual C++) was virt-viewer 11 for Windows x64 built for? It installs as remote-viewer and when you run it without the *.vv file it also crashes shortly after loading, so it's not even getting to "spice" or "qxl".

OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19045 N/A Build 19045

PS C:\Users\johje> Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*  | select DisplayName, Publisher, InstallDate | Where-Object {$_.DisplayName -like "Microsoft Visual C*"}

DisplayName                                                    Publisher             InstallDate
-----------                                                    ---------             -----------
Microsoft Visual C++ 2022 X64 Additional Runtime - 14.36.32532 Microsoft Corporation 20230826
Microsoft Visual C++ 2005 Redistributable (x64)                Microsoft Corporation 20180526
Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219    Microsoft Corporation 20180526
Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030  Microsoft Corporation 20180108
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.4148 Microsoft Corporation 20180108
Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.40660  Microsoft Corporation 20200105
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161 Microsoft Corporation 20180408
Microsoft Visual C++ 2005 Redistributable (x64)                Microsoft Corporation 20191127
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.17   Microsoft Corporation 20200105
Microsoft Visual C++ 2005 Redistributable (x64)                Microsoft Corporation 20180527
Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.40660     Microsoft Corporation 20200105
Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030     Microsoft Corporation 20180108
Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.36.32532    Microsoft Corporation 20230826

The XML below is from Windows Application Event Viewer and shows msvcrt.dll crashing.

```xml
[-](https://github.com/virt-manager/virt-manager/issues/new#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/virt-manager/virt-manager/issues/new#) <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-10-13T05:12:51.1531954Z" /> 
  <EventRecordID>186647</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>LAPTOP-0N5OVFBH</Computer> 
  <Security /> 
  </System>
[-](https://github.com/virt-manager/virt-manager/issues/new#) <EventData>
  <Data>1787916120948541318</Data> 
  <Data>4</Data> 
  <Data>APPCRASH</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>remote-viewer.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>619cd97c</Data> 
  <Data>msvcrt.dll</Data> 
  <Data>7.0.19041.3570</Data> 
  <Data>9bf60e04</Data> 
  <Data>c0000005</Data> 
  <Data>000000000005d2f1</Data> 
  <Data /> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE51D.tmp.dmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE627.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE647.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE647.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE668.tmp.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_remote-viewer.ex_407a81771ebeb2f81d97e51e26bbfb245a9311_9a99f3df_c24343f4-104c-4916-a4ac-7c12726a8fdc</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>89a60a0a-324d-4067-84ce-f07485051675</Data> 
  <Data>268435456</Data> 
  <Data>57d33555c1016dd608cff43d3d550786</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>
```

**Comment by ptoscano** [comment]
Hi @johjeff,

`remote-viewer.exe` is part of a different project, i.e. virt-viewer:
https://gitlab.com/virt-viewer/virt-viewer

Hence, please report the issue to that project, thanks!
