### ISSUE TITLE
Some storage path is hardcoded somewhere, breaking virt-manager's new VM dialog when home dir is renamed

### ISSUE THREAD

**Issue by ell1e** [virt-manager/virt-manager#596]
Some storage path is hardcoded somewhere, breaking virt-manager to ever add a new VM again when the home dir was previously renamed. Any attempt after logging out, renaming the home dir, and then creating any virtual machine will error out with `virStoragePoolCreate() failed`. Gnome boxes doesn't have this problem so this seems to be a virt-manager bug. Hardcoding such paths ever seems like a bad idea, so I hope this can be addressed.

**Distro**: openSUSE Leap 15.5

![Screenshot from 2023-10-22 15-25-43](https://github.com/virt-manager/virt-manager/assets/64124388/826456a0-5b37-4234-9ec3-39299765b6ef)

virt-manager 4.1.0

**Comment by ell1e** [comment]
Is there a known workaround for this of some kind?

**Comment by ell1e** [comment]
Okay, so I found where the problem is: the storage path is saved *with the full home path expanded rather than `~`* in `~./.config/libvirt/storage/default.xml`. Needless to say, I would like to suggest that's a big problem and should be changed because as soon as the home dir ever changes, e.g. due to the user being renamed, it just breaks virt-manager. Alternatively, the UI would instead of just breaking when the default storage path doesn't exist, need to allow the user to enter a new one.

**Comment by crobinso** [comment]
Thanks for the report. I agree that this is suboptimal. Disappearing homedir or default pool location seems like a rare enough thing that adding code to detect or handle it isn't really warranted IMO. So I don't think anything will change here.

**Comment by ell1e** [comment]
Could maybe the error message at least change, and/or offer some button or setting for the path to fix it right there? I actually wasn't able to use virt-manager for years for VM creation because I just had no idea how to fix it. So this is sadly pretty high impact, even if rare. I only found out how to fix it by doing a find for the old path throughout my entire user folder at some point, which seems like a pretty arcane way to address this.
