### ISSUE TITLE
virtinst: output XML should have quotation consistent with virsh

### ISSUE THREAD

**Issue by TheHillBright** [virt-manager/virt-manager#603]
**Distro**: Ubuntu 22.04

Currently, CLI tools from virtinst that support outputting XML (e.g. via flag `--print-xml`) has the output XML using double quotes (`"`) only. This is different from the XML from `virsh` (e.g. dumpxml) that uses mostly single quotes (`'`) except for libosinfo-related nodes. In general, consistency is wanted. In this case, consistent XML quotation makes it friendlier to interact with other tools requiring text-based operation (e.g. `diff` and `git`). One use case is that we want to check the difference between the XML from `virt-clone` and the original before we define it. Since virtinst depends on libvirt, it might make sense to change the quotation on the virtinst side. This doesn't seem to be a breaking change since the quotation of choice is not specified.

**Comment by crobinso** [comment]
Thanks for the request.  I agree it's annoying that things 
are different here.  But it's been different for a long time, and changing it now will cause a different type of pain that isn't worth the churn IMO.

If you need to diff generated XML in some kind of structured way, you could feed both documents through something like `xmlstarlet c14n` or similar, to sanitize them both
