### ISSUE TITLE
user question: install windows VM with USB install media

### ISSUE THREAD

**Issue by newsguygeorge** [virt-manager/virt-manager#604]
I want to install a Windows 10 virtual machine, either with libvirt or using Virtual Box. My legit Win10 iso is on a usb drive. And, for the life of me, I can’t find a way for either of these VMs to see the usb drive. It is incomprehensible to me in the 21st century that this capacity isn’t built into the applications themselves. In fact, on one site I read about usb connecting, it asserted that the virt-manager has this on the “left pane.” So much of working with Ubuntu is hard because the websites’ instructions are either too technical or don’t comport with the screen in front of me.

The Linux community keeps grumbling about winning over Windows users, but it isn’t going to happen when it’s this hard. I spent the entire afternoon trying and failing to install FileZilla; and the entire evening dealing with the above problem.

Thanks for listening.

Thank you!
-->

**Distro**:

**Comment by ajgringo619** [comment]
For installing VMs from ISOs, there's no reason to keep it on a USB stick. Copy it over to the host and use it from there. As far as why your systems can't see the USB, that I'm not sure. I just got done doing some beta testing for a new ISO that I used to install an OS on a passed-through USB stick (from virt-manager).

I've personally never had a problem using any major VM host software with passed-through USBs, so I'm not entirely sure what's going on here. You need to post more info about your host and the software you've installed; anything less and we're just guessing. Along with your host info, also post your VM's config; maybe the USB pass-through device is not installed.

As far as "...Linux community grumbling...", posts like this are just going to get ignored as pointless complaining. Nothing you've posted about is hard, unless you have no experience in VM creation/management on Linux-based systems.

**Comment by newsguygeorge** [comment]
Sorry for the grumbling. I have been trying for years to become a Linux user. I finally found Ubuntu 22.04 and I'm feeling more comfortable with it than I ever have with any other distro.

I'm using a virtual manager to run a Windows 10 emulation on an ASUS laptop. It has a 2.3 gigahertz Intel X64 processor with 16 gigabytes of ram and a 1- terabyte SSD drive. I am running virt-manager. I have looked online to find how to redirect to USB's and followed the directions to set up a USB 2. I also found a setting that was a redirect for the Toshiba hard drive that I attached through one of the USB ports. I don’t know what all that means but I have followed the directions blindly and I'm not having any luck. 

Thank you again for the possibility of helping me and I apologize for taking so long to get back to this issue. At age 78, some things are slower than others.

**Comment by newsguygeorge** [comment]
Intel Core i7-3610QM, if that helps.

**Comment by crobinso** [comment]
I will try to describe a way to do what you want. Indeed virt-manager doesn't make it simple to install using USB media.

* Open New VM wizard
* Select `Manual Install`, click forward
* Select your windows flavor or the closest you can find, click forward
* Set mem, cpus, storage size per your preferences
* On the last page, select 'customize before install'. Click 'Finish'
* Select boot options on the left, click `enable boot menu`, click `Apply`
* Plug your USB device into your host, wait 5-10 seconds for host to detect it
* Click `Add Hardware`
* Select `USB Host device` on the left
* Select your USB device, click finish.
* Back in the previous dialog, click 'begin installation'
* Wait a bit. VM should boot off the USB

I just confirmed this is working for a windows USB I have handy.
