### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Grand-Cherokee** [virt-manager/virt-manager#607]
from the website: No link to actual documentation, the existing docs link contains only faq, screenshots.
I have provided the screenshot.

![vman-nodoc](https://github.com/virt-manager/virt-manager/assets/117134136/f5e3b49b-a13e-4619-8c55-f364c64bc931)

**Comment by crobinso** [comment]
Unfortunately that's all there really is for documentation, so there's not much to fix here besides we need to redesign the website, but that's a known issue

**Comment by jcrben** [comment]
@crobinso is there a tracking issue for redesigning the website?

I don't think a full redesign is needed to improve the officialdocs - just publishing the existing manpage and such would be a big improvement. they are published elsewhere so could point to them also https://linux.die.net/man/1/virt-manager

**Comment by crobinso** [comment]
Man pages are accessible in nicer format with linking etc in the git tree: https://github.com/virt-manager/virt-manager/blob/main/man/virt-manager.rst

**Comment by jcrben** [comment]
@crobinso even easier than to link to them from your website docs

I suggest linking them in a third bullet at https://virt-manager.org/documentation.html
