### ISSUE TITLE
Unable to create a new VM on Fedora Silverblue 39

### ISSUE THREAD

**Issue by broomstickengine** [virt-manager/virt-manager#610]
**Upon configuring the VM and clicking "finish", I receive the following error:**

Unable to complete install: 'internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/var/log/swtpm/libvirt/qemu/win11-swtpm.log' for details.'

**The log file shows the following:**

Starting vTPM manufacturing as tss:tss @ Wed 20 Dec 2023 05:58:44 PM MST
Successfully created RSA 2048 EK with handle 0x81010001.
  Invoking /usr/bin/swtpm_localca --type ek --ek a4528233fe080e9465da3f2904bf66be1da0eadddd515a238e006f42af472cd0d34e844fb07a030045ca9c89935b5cc0dfbb18c17def4dcb084afcd44be2ebbc9356e84a9c2876f6e4ed5e1000ac1ec8e6bba8b0631e7a3206b8976a6ac2940795a09366f0450272dbec4005b28e349890b6a7328d36964db5c1c84fd8b524678820c9b9ac3d620f570bd270607b46402798ef56e7d205f4d6340bb414529b4a62f4e0ff3f5325ae18a6f391c28126f97e200d544ce00596d1c2ed63445228b8321b8b8ef572afa78b26c4aeb65af250362cc16214835a19eacd5e77f9ee56dfb615f45e3f6358b63ef87b23c50de7a565546194346c4cca5c324144374b9ee5 --dir /tmp/swtpm_setup.certs.0728F2 --logfile /var/log/swtpm/libvirt/qemu/win11-swtpm.log --vmid win11:91eee591-fb2d-471c-bf66-5c8d9ddd05d1 --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 164 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20191023 --tpm2 --configfile /etc/swtpm-localca.conf --optsfile /etc/swtpm-localca.options
Creating swtpm-localca dir '/var/lib/swtpm-localca'.
Could not create directory for 'statedir': Permission denied
swtpm_localca exit with status 1: 
An error occurred. Authoring the TPM state failed.
Error getting next filename: No child processes
Ending vTPM manufacturing @ Wed 20 Dec 2023 05:58:44 PM MST

**Comment by firefoxlover** [comment]
did you report this on 

https://bugzilla.redhat.com/enter_bug.cgi?classification=Fedora

?

**Comment by broomstickengine** [comment]
> did you report this on
> 
> https://bugzilla.redhat.com/enter_bug.cgi?classification=Fedora
> 
> ?

No. Do I have to?

That site literally gives me a migraine. Bugzilla’s UI/UX is atrocious. I can’t believe a company the size of Red Hat/IBM still uses Bugzilla :(

**Comment by firefoxlover** [comment]
This may be a packaging issue though, so first there, if upstream then here.

Bugzilla is fine and has way more features than Github

**Comment by crobinso** [comment]
What version of fedora and libvirt are you running? 

This sounds like this bug which is supposedly fixed with libvirt 7.9.0+: https://bugzilla.redhat.com/show_bug.cgi?id=2010649

I'm closing this since it's unlikely anything virt-manager can fix (we do very little here except send some XML to libvirt), but if you follow up I'll try and help debug
