### ISSUE TITLE
[FEATURE] Adding support for "virtio-snd"

### ISSUE THREAD

**Issue by ManuLinares** [virt-manager/virt-manager#613]
Is this possible easily?

qemu 8.2 supports this. https://wiki.qemu.org/ChangeLog/8.2#virtio-sound

https://www.qemu.org/docs/master/system/devices/virtio-snd.html

Win drivers issue link:
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/929

**Comment by crobinso** [comment]
Thanks for the suggestion. First step would be enabling it in libvirt, it does not seem to be supported there yet. You could submit a bug there if there's not already a request: https://gitlab.com/libvirt/libvirt

Once it's in libvirt you could enter it into the sound model field in virt-manager UI easy enough, and we could pre-populate it in the drop down if libvirt advertises that it is supported.

Until then there's not much use in tracking this here IMO
