### ISSUE TITLE
FR: add a "not enough RAM" warning

### ISSUE THREAD

**Issue by firefoxlover** [virt-manager/virt-manager#616]
I had my Desktop freeze because Virt-manager didn't have enough RAM and it seems on Linux/Fedora/KDE the RAM Management is not working at all.

So it would be really great to use `free` to get the amount of RAM and stop a VM from launching that has more RAM assigned than is free + 500MB as buffer.

This seems like a small thing, but would be an easy but incredibly useful improvement of UX.

**Comment by crobinso** [comment]
Thanks for the suggestion and I understand how that would be useful in certain situations, but virt-manager is not in a position to do a good job here: VMs can be started in other ways, memory limits could be exceeded after the VM is started, etc. This is really a much more general problem than specific to virtual machines. Look into systemd-oomd or similar to handle system wide `out of memory` handling, or google about `sysctl disable memory overcommit` to disallow it systemwide.
