### ISSUE TITLE
RFE: virt-install: `--video model.blob=on|off`

### ISSUE THREAD

**Issue by smitterl** [virt-manager/virt-manager#617]
Libvirt supports the following setting:

```
<video>
 <model type="virtio" blob="on"/>
</video>
```

`blob` is currently not exposed on the `--video` option. I tried with `--xml` but failed. The attribute doesn't yet exist so the XPATH won't match and `xpath.create` seems to only support element configuration, not attributes.

**Comment by crobinso** [comment]
Thanks for the report.

I did get `--xml` to work here. For example:

`sudo ./virt-install --print-xml ... --xml xpath.set=./devices/video/model/@blob=on`

Or to edit an existing VM:

`sudo ./virt-xml --print-diff VMNAME --edit --xml xpath.set=./devices/video/model/@blob=on`

If you can't get it working, post your command and I'll take a look

**Comment by crobinso** [comment]
This is in git now 6a65def684cf2b83d7f4809457965b698755e26c

**Comment by smitterl** [comment]
Thank you @crobinso Sorry I didn't see your reply from February earlier.
