### ISSUE TITLE
pools with lots of storage volumes can trigger libvirt client disconnect timeouts

### ISSUE THREAD

**Issue by q234rty** [virt-manager/virt-manager#623]
**Distro**: Arch Linux rolling latest

Same as #533, I have built virt-manager from latest master and the issue persists with the exact same symptoms.

**Comment by crobinso** [comment]
@q234rty Thanks for following up. Can you reproduce with `virt-manager --debug` and attach the full terminal output?

**Comment by crobinso** [comment]
Hmm interesting. There's lots of backtraces like:

```
libvirt.libvirtError: 内部错误：已关闭客户端插槽
[四, 08 2月 2024 01:22:56 virt-manager 111007] ERROR (hostnets:172) 内部错误：已关闭客户端插槽
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/hostnets.py", line 170, in _refresh_current_network
    self._populate_net_state(net)
  File "/usr/share/virt-manager/virtManager/hostnets.py", line 251, in _populate_net_state
    autostart = net.get_autostart()
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/network.py", line 87, in get_autostart
    return self._backend.autostart()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libvirt.py", line 3527, in autostart
    raise libvirtError('virNetworkGetAutostart() failed')
```

and

```
[四, 08 2月 2024 01:22:56 virt-manager 111007] ERROR (hoststorage:362) 无法写入数据: 断开的管道
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/hoststorage.py", line 360, in _refresh_current_pool
    self._populate_pool_state(pool)
  File "/usr/share/virt-manager/virtManager/hoststorage.py", line 304, in _populate_pool_state
    auto = pool.get_autostart()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/storagepool.py", line 274, in get_autostart
    return self._backend.autostart()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libvirt.py", line 3935, in autostart
    raise libvirtError('virStoragePoolGetAutostart() failed')
libvirt.libvirtError: 无法写入数据: 断开的管道
```

Can't say I've ever seen that before. That's a libvirt call failing which shouldn't fail in normal circumstances

Can you translate those errors for me?
Does `sudo virsh net-info default` with same LANG also throw an error? And/or `sudo virsh pool-info default`

**Comment by q234rty** [comment]
> Can you translate those errors for me?

"内部错误：已关闭客户端插槽" should be "Internal error: client socket is closed"
"无法写入数据: 断开的管道" should be "Cannot write data: Broken pipe"

And no, using virsh directly via `sudo LANG=zh_CN.UTF-8 virsh net-info default` or `sudo LANG=zh_CN.UTF-8 virsh pool-info default` does not throw an error.

**Comment by crobinso** [comment]
Thanks for checking. Hmm, I wonder if it's python binding related. Can you drop this code in a script and run it as root, something like `sudo python SCRIPTNAME` 

```python
import libvirt

conn = libvirt.open("qemu:///system")

for obj in conn.listAllNetworks() + conn.listAllStoragePools():
    print(obj)
    print(obj.name())
    print(obj.autostart())
    print()
```

**Comment by q234rty** [comment]
```

**Comment by crobinso** [comment]
Ok thanks. This is annoying :)

So that first error 'Cannot write data: Broken pipe' usually means one of the libvirt daemons crashed. All subsequent error messages 'client socket is closed' indicate nothing is listening on the other side (eg crashed daemon).

Is libvirt up to date on your system?

We can get a bit more info from virt-manager if you reproduce with `virt-manager --debug --trace-libvirt=all`

Are you using systemd? Any coredumps in `coredumpctl`? Or any segfault mentions for *virt* binaries in `journalctl --boot`?

**Comment by q234rty** [comment]
There's no coredump in `coredumpctl`, though libvirtd(10.0.0 on my system) did exit.
`journalctl -u libvirtd -b 0` shows that
<details><summary>Details</summary>
<p>

2月 15 01:09:10 arch-g14 systemd[1]: Starting libvirt legacy monolithic daemon...
2月 15 01:09:10 arch-g14 systemd[1]: Started libvirt legacy monolithic daemon.
2月 15 01:09:10 arch-g14 dnsmasq[2153]: started, version 2.90 cachesize 150
2月 15 01:09:10 arch-g14 dnsmasq[2153]: compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset nftset auth cryptohash DNSSEC loop-detect inotify dumpfile
2月 15 01:09:10 arch-g14 dnsmasq-dhcp[2153]: DHCP, IP range 192.168.122.2 -- 192.168.122.254, lease time 1h
2月 15 01:09:10 arch-g14 dnsmasq-dhcp[2153]: DHCP, sockets bound exclusively to interface virbr0
2月 15 01:09:10 arch-g14 dnsmasq[2153]: reading /etc/resolv.conf
2月 15 01:09:10 arch-g14 dnsmasq[2153]: using nameserver 1.1.1.1#53
2月 15 01:09:10 arch-g14 dnsmasq[2153]: using nameserver 8.8.4.4#53
2月 15 01:09:10 arch-g14 dnsmasq[2153]: read /etc/hosts - 3 names
2月 15 01:09:10 arch-g14 dnsmasq[2153]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 names
2月 15 01:09:10 arch-g14 dnsmasq-dhcp[2153]: read /var/lib/libvirt/dnsmasq/default.hostsfile
2月 15 01:09:56 arch-g14 libvirtd[2057]: libvirt version: 10.0.0
2月 15 01:09:56 arch-g14 libvirtd[2057]: hostname: arch-g14
2月 15 01:09:56 arch-g14 libvirtd[2057]: 内部错误：由于 keepalive 超时而关闭连接
2月 15 01:11:56 arch-g14 systemd[1]: libvirtd.service: Deactivated successfully.
2月 15 01:11:56 arch-g14 systemd[1]: libvirtd.service: Unit process 2153 (dnsmasq) remains running after unit stopped.
2月 15 01:11:56 arch-g14 systemd[1]: libvirtd.service: Unit process 2154 (dnsmasq) remains running after unit stopped.
2月 15 01:11:56 arch-g14 systemd[1]: libvirtd.service: Consumed 6.239s CPU time, 1.4G memory peak, 0B memory swap peak.

</p>
</details> 

The chinese part translates to "Internal error: connection closed due to keepalive timeout"

Here are the logs from `virt-manager --debug --trace-libvirt=all`:
[virt-m-all.log](https://github.com/virt-manager/virt-manager/files/14284186/virt-m-all.log)

**Comment by crobinso** [comment]
Ok thanks for continuing to provide info. This is still confusing me

The debug logs show that some of your storage pools have a lot of files in them. Like the pool name `下载` has thousands of files. This takes a long time for virt-manager to query. Maybe that has something to do with the timeout. I'm not sure why LOCALE would affect that though.

Does stopping that pool let things work correctly? That would be an interesting data point.

There's multiple timeouts at play. virt-manager sets one to 20 seconds to detect if libvirtd is dead, and libvirtd sets one for clients to detect if they are dead or hung, which defaults to 30 seconds. Neither should be triggering here though since your logs say errors hit after like 15 seconds.

**Comment by q234rty** [comment]
> Does stopping that pool let things work correctly? 

Yeah, stopping the unneeded pools fixed it.

**Comment by crobinso** [comment]
There was some work added to git recently to improve speed of storage volume lookup in the host window, it may help here. If you are still affected, give .git a shot and open a new issue if problems persist
