### ISSUE TITLE
Unable to connect to libvirt qemu:///system.

### ISSUE THREAD

**Issue by birbmotorsports** [virt-manager/virt-manager#625]
I double-clicked on "QEMU/KVM - Not Connected" after installing virt-manager.

`authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'`

I am running Arch latest with Hyprland as my WM.

Here are the details of the error message:

```
Unable to connect to libvirt qemu:///system.

authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 923, in _do_open
    self._backend.open(cb, data)
  File "/usr/share/virt-manager/virtinst/connection.py", line 171, in open
    conn = libvirt.openAuth(self._open_uri,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libvirt.py", line 147, in openAuth
    raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'
```

**Comment by ptoscano** [comment]
Hello,

it looks like there is no policykit-1 agent running for your user. libvirt uses policykit-1 by default to determine the ACL for the various actions.

See for example these couple of links:
- https://wiki.hyprland.org/Useful-Utilities/Must-have/ (the `Authentication Agent` section)
- https://www.reddit.com/r/hyprland/comments/12ej2cl/problem_with_polkitauthenticators/

Note I don't use neither Arch nor Hyprland.

**Comment by birbmotorsports** [comment]
> Hello,
> 
> it looks like there is no policykit-1 agent running for your user. libvirt uses policykit-1 by default to determine the ACL for the various actions.
> 
> See for example these couple of links:
> 
>     * https://wiki.hyprland.org/Useful-Utilities/Must-have/ (the `Authentication Agent` section)
> 
>     * https://www.reddit.com/r/hyprland/comments/12ej2cl/problem_with_polkitauthenticators/
> 
> 
> Note I don't use neither Arch nor Hyprland.

Ah, I just grabbed KDE's polkit and added a line to my `hyprland.conf`, now it works. Thank you for the information. :3

**Comment by ell1e** [comment]
For what it's worth, I'm also seeing this on alpine now:
```
$ ps aux | grep polkit
 5106 polkitd   0:10 /usr/lib/polkit-1/polkitd --no-debug
 7924 user     0:00 grep polkit
$
```
Probably an Alpine bug of some kind. But I do wonder, why there isn't some alternate route like for example just offering to use the root password without polkit. That would probably work fine for most single-user installs. Polkit always strikes me as slightly overly complex and error prone in terms of setup.
