### ISSUE TITLE
Add loongarch cpu support for virt-manager

### ISSUE THREAD

**Issue by lixianglai** [virt-manager/virt-manager#628]
LoongArch is the general processor architecture of Loongson.
You can follow the links below to learn more information related to loongarch:
https://en.wikipedia.org/wiki/Loongson#LoongArch
https://github.com/loongson/LoongArch-Documentation

At present, loongarch is committed to the development of virtualization and open source work.

The latest version of qemu has been very good support loongarch architecture, You can use qemu tcg to emulate loongarch.

The libvirt related patch supporting loongarch has been submitted to the third version and will soon be accepted by the libvirt community. 

Therefore, we plan to submit virt-manager related patches supporting loongarch to the community so that the open source work of loongarch virtualization is complete.

  You can get the virt-manager code with loongarch patch from the link below:
https://github.com/lixianglai/virt-manager
branch: loongarch

The libvirt-related patch is not yet accepted by the community, but you can get the corresponding patch from the following link：
https://gitlab.com/lixianglai/libvirt
branch: loongarch

  loongarch's virtual machine bios is not yet available in qemu,So you need to compile loongarch UEFI yourself,
you can refer to the following link to compile UEFI:
https://github.com/tianocore/edk2-platforms/blob/master/Platform/Loongson/LoongArchQemuPkg/Readme.md

Here we provide compiled UEFI for ease of testing,you can get it from the following link:
https://github.com/lixianglai/LoongarchVirtFirmware
(Note: You should clone the repository using git instead of downloading the file via wget or you'll get xml)
We named the bios QEMU_EFI.fd, QEMU_VARS.fd is used to store pflash images of non-volatile variables.
After installing qemu-system-loongarch64,You can install the loongarch bios by executing the script
install-loongarch-virt-firmware.sh 

  Since there is no fedora operating system that supports the loongarch
architecture, you can find an iso that supports loongarch at the link below for testing purposes:
  https://github.com/fedora-remix-loongarch/releases-info
The operating system provided above may have minor problems of one kind or another,
but you can also find out from the following link that openEuler's operating system supports loongarch:
https://muug.ca/mirror/openeuler/openEuler-22.03-LTS/ISO/loongarch64/

  Well, if you have completed the above steps I think you can now install loongarch virtual machine,
you can install it through the virt-manager graphical interface, or install it through vrit-install,
here is an example of installing it using virt-install:
virt-install  \
--virt-type=qemu \
--name  loongarch-test \
--memory 4096 \
--vcpus=4 \
--arch=loongarch64 \
--boot cdrom \
--disk device=cdrom,bus=scsi,path=/root/livecd-fedora-mate-4.loongarch64.iso \
--disk path=/var/lib/libvirt/images/debian12-loongarch64.qcow2,size=10,format=qcow2,bus=scsi \
--network network=default \
--osinfo archlinux   \
--video=virtio  \
--graphics=vnc,listen=0.0.0.0

**Comment by HougeLangley** [comment]
I have tested in my Gentoo LoongArch, working great.
![Screenshot_20240223_003433](https://github.com/virt-manager/virt-manager/assets/1161594/b9bc0bda-d9d9-473e-8809-8b2fd9a383ae)

@crobinso

**Comment by crobinso** [comment]
Please submit the code as a PR, even if it's not fully ready yet.

I looked briefly at the branch and didn't see any tests. I described how to get some basic test coverage for loongarch in this older PR comment: https://github.com/virt-manager/virt-manager/pull/600#issuecomment-1906172744

If you wanted to do a first pass of getting a basic test case into virt-manager.git, even if it shows virt-install generating blatantly incorrect results because the rest of the loongarch bits aren't present, that is a good starting point for future review IMO

**Comment by lixianglai** [comment]
Thank you very much. I will improve it as suggested

**Comment by andreabolognani** [comment]
@lixianglai I think this can be closed now.

**Comment by lixianglai** [comment]
OK
