### ISSUE TITLE
Add dark/light mode option in preferences menu

### ISSUE THREAD

**Issue by ZGuardianTV** [virt-manager/virt-manager#642]
Please add an option in the preferences menu to change the theme to either dark or light mode. Virt Manager sometimes changes the theme automatically depending on the theme of the desktop environment but most of the times it's in light mode and there's no way to change this.

**Comment by crobinso** [comment]
Thanks for the suggestion but there's nothing theme specific that virt-manager is doing here natively, it's all GTK plumbing AFAIK. For example on default gnome-shell you can force the app to use dark theme with `GTK_THEME=Adwaita:dark virt-manager`. More details here: https://unix.stackexchange.com/questions/14129/gtk-enable-set-dark-theme-on-a-per-application-basis
