### ISSUE TITLE
Icons hard to read on KDE 6 with dark environment

### ISSUE THREAD

**Issue by m-czernek** [virt-manager/virt-manager#643]
When I updated KDE to 6, I noticed that the black information icons are hard to read. This was definitely not the case with KDE 5, though not sure who needs to provide the fix (KDE or virt-manager). Adding images:

![image](https://github.com/virt-manager/virt-manager/assets/16302538/6bda47ca-2fc1-414d-8c9c-92fc4f514c81)

![image](https://github.com/virt-manager/virt-manager/assets/16302538/77bda8a6-134a-4c1a-9b4e-4a69e09ed256)

![image](https://github.com/virt-manager/virt-manager/assets/16302538/43ad4fd4-e22c-4261-af61-a8327b2a6209)

**Distro**: openSUSE Tumbleweed
**Packages**: 

```
$ rpm -qa | grep -iE "(virt-manager|plasma6-desktop)"
...
plasma6-desktop-6.0.2-1.1.x86_64
virt-manager-4.1.0-17.1.noarch
virt-manager-common-4.1.0-17.1.noarch
```

**Comment by phrdina** [comment]
What theme do you have configured in KDE 6? Virt-manager doesn't provide any icons on it's own, it just requests specific icon, for example `media-playback-start`.

**Comment by m-czernek** [comment]
I use `breeze-dark`, the default dark theme. Thanks for the hint @phrdina , I investigated the KDE config and realized that I can use the `Adwaita` icons, which fixes the issue. The default `Breeze` and `Breeze Dark` icon packs both result in the dark, hard-to-see icons as per the issue.

So this is a bug for the KDE theme, I assume?

**Comment by phrdina** [comment]
Correct, not a virt-manager bug. I would report it in bug tracker for your distribution, it could be downstream only issue.
