### ISSUE TITLE
I am trying to install Windows 10 with .iso file.

### ISSUE THREAD

**Issue by abd153** [virt-manager/virt-manager#644]
![Screenshot 2024-03-25 20 37 23](https://github.com/virt-manager/virt-manager/assets/164929955/13c7eaef-e8c0-4347-aad2-0840efaaa31d)

I still getting this error.  I tried to restart the app and my Chromebook. Please help! 

Error code: 

,,Unable to complete install: 'Unable to set XATTR trusted.libvirt.security.dac on /var/lib/libvirt/qemu/domain-7-win10/master-key.aes: Operation not permitted'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4481, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: Unable to set XATTR trusted.libvirt.security.dac on /var/lib/libvirt/qemu/domain-7-win10/master-key.aes: Operation not permitted,,.

**Comment by phrdina** [comment]
This error comes from libvirt so not virt-manager issue and most likely not libvirt issue as well. I'm not familiar with chromebook but quick web search for this error results in some solutions how to "fix" this issue. Basically changing the user that is used for QEMU to `root`. I'm not sure why that is required or why the default user doesn't work, might be related to how the linux environment is done on chromebook which again I have no experience with.
