### ISSUE TITLE
VMs Crash, Stop Responding

### ISSUE THREAD

**Issue by gitoutsub** [virt-manager/virt-manager#650]
**Distro**: 

Hello,
 I ran through the debugging steps above and suggests I open a request with virt-manager. The VM will either just stop responding or will crash out right. Sometimes it crashs/reboots the host.
I believe this was requested.
virt-manager --debug
[Fri, 05 Apr 2024 13:49:57 virt-manager 2732] DEBUG (cli:204) Launched with command line: /usr/bin/virt-manager --debug
[Fri, 05 Apr 2024 13:49:57 virt-manager 2732] DEBUG (virtmanager:167) virt-manager version: 4.0.0
[Fri, 05 Apr 2024 13:49:57 virt-manager 2732] DEBUG (virtmanager:168) virtManager import: /usr/share/virt-manager/virtManager
[Fri, 05 Apr 2024 13:49:57 virt-manager 2732] DEBUG (virtmanager:205) PyGObject version: 3.42.1
[Fri, 05 Apr 2024 13:49:57 virt-manager 2732] DEBUG (virtmanager:209) GTK version: 3.24.33
[Fri, 05 Apr 2024 13:49:57 virt-manager 2732] DEBUG (systray:84) Imported AppIndicator3=<IntrospectionModule 'AyatanaAppIndicator3' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/AyatanaAppIndicator3-0.1.typelib'>
[Fri, 05 Apr 2024 13:49:57 virt-manager 2732] DEBUG (systray:90) Using AppIndicator3 for systray
[Fri, 05 Apr 2024 13:49:57 virt-manager 2732] DEBUG (engine:244) Connected to remote app instance.

Thanks for the help

**Comment by crobinso** [comment]
What's your distro?

If VMs are crashing your whole machine, it's way outside the scope of virt-manager. Try downgrading your kernel to something a few months older and see if you are still getting crashes.

**Comment by gitoutsub** [comment]
Are there specific logs that virt-manager generates or does everything get logged in syslog?
