### ISSUE TITLE
Release >=4.2.0 with meson rather than distutils/setuptools

### ISSUE THREAD

**Issue by hartwork** [virt-manager/virt-manager#652]
Hi virt-manager team,

thanks for the recent work getting off dead distutils in 231a3dbc875333c73347fc6be8b39d9fc5542460. It would be great to have a release with the new Setuptools support, so that e.g. Gentoo can start using PEP 517 builds for it (https://bugs.gentoo.org/909876).

Thank you!

CC @ptoscano @crobinso

**Comment by ptoscano** [comment]
> thanks for the recent work getting off dead distutils in [231a3db](https://github.com/virt-manager/virt-manager/commit/231a3dbc875333c73347fc6be8b39d9fc5542460). It would be great to have a release with the new Setuptools support, so that e.g. Gentoo can start using PEP 517 builds for it (https://bugs.gentoo.org/909876).

Unfortunately I don't do releases, that's mostly up to Cole.

If you are in pressing need (at least from what I can see from the gentoo bug), I recommend backporting 4f4e73d0170fdd7efdc552c7baebdf739b60df6a and 231a3dbc875333c73347fc6be8b39d9fc5542460 to gentoo until a new release is available. They are only build system changes, so they have no impact on the actual functionalities of virt-manager.

**Comment by hartwork** [comment]
Hi @ptoscano, thanks for your reply!

> > thanks for the recent work getting off dead distutils in [231a3db](https://github.com/virt-manager/virt-manager/commit/231a3dbc875333c73347fc6be8b39d9fc5542460). It would be great to have a release with the new Setuptools support, so that e.g. Gentoo can start using PEP 517 builds for it (https://bugs.gentoo.org/909876).
> 
> Unfortunately I don't do releases, that's mostly up to Cole.

I see, @crobinso is there a chance for a new release in the coming weeks?

> If you are in pressing need (at least from what I can see from the gentoo bug), I recommend backporting [4f4e73d](https://github.com/virt-manager/virt-manager/commit/4f4e73d0170fdd7efdc552c7baebdf739b60df6a) and [231a3db](https://github.com/virt-manager/virt-manager/commit/231a3dbc875333c73347fc6be8b39d9fc5542460) to gentoo until a new release is available. They are only build system changes, so they have no impact on the actual functionalities of virt-manager.

Thanks for pointing out the two commits! The thing is that every downstream patch that is _not_ specific to that very distro is one too much — the goal is zero downstream patches — and it would go into Gentoo Git history forever for nothing similar to Debian applying 6e5c1db6b4a0af96afeb09a09fb2fc2b73308f01 of 2023-08-29 still today just because there is no recent release. 2022-08-04 is a very long time ago. If you're with Fedora, I'm probably preaching to the choir here, I'm sure that Fedora is targeting zero downstream patches also.

Have a nice weekend! :beers:

**Comment by phrdina** [comment]
Hi, I've already talked to Cole few days ago and there will be a new release in coming weeks so stay tuned!

**Comment by hartwork** [comment]
@phrdina cool! :tada:

**Comment by branchvincent** [comment]
Homebrew is also interested in pep 517 builds, I just created #657 with some minor changes that we needed

**Comment by nater1983** [comment]
Any news of this since it is now June 10th??????

**Comment by neitsab** [comment]
August checking in! Will there be a new release in the near future? Thanks for your work 🙏🏻

**Comment by crobinso** [comment]
I'm alive. I will do my best to get a release out by end of the month.

**Comment by hartwork** [comment]
@crobinso any news?

**Comment by phrdina** [comment]
Most of the work we wanted to do before release is done. I'm now working on last bit, packaging. We need to modernize and rework setuptools usage or switch to meson.

**Comment by phrdina** [comment]
The issue with current `setup.py` is that we are using deprecated commands. Calling `setup.py ....` is deprecated and must not be used. We should use `python -m build`, `python -m pip install .` and so on.

Due to that fact I would prefer making new release without deprecated build system, however the new approach using setuptools or any other builder together with `pyproject.toml` and/or `setup.py` and/or `setup.cfg` and if you want custom commands you should use some other 3rd party tools feels like step backwards in python packaging.

There are some other challenges with the new python packaging system that affects virt-manager. That's why I'm working on introducing meson instead of using setuptools.

**Comment by phrdina** [comment]
Yes, as I wrote, our current usage of setuptools is deprecated and based on docs https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#setup-py-deprecated running `setup.py` directly must not be used. Our current state of setup.py is not ready for the new packaging and we need to fix that as well. So it doesn't matter if we fix current setuptools or migrate to meson.

**Comment by hartwork** [comment]
@phrdina I understand deprecated but what is stopping a release of status quo for downstreams without distutils (that is beyond deprecated) to use while waiting for the next generation build system? Please help me see what I am missing.

**Comment by phrdina** [comment]
You want to use PEP 517 builds in Gentoo for virt-manager but virt-manager is not PEP 517 ready at this moment. The MR that tries to fix that https://github.com/virt-manager/virt-manager/pull/657 and is linked in the Gentoo bug as well is far from complete. Like I wrote, we need to make changes to how we use setuptools to be PEP 517 ready or drop setuptools completely and use meson instead.

**Comment by hartwork** [comment]
@phrdina I understand, thanks for elaborating!

**Comment by phrdina** [comment]
Switch to meson is fixed by #742 , once we make new release I'll close this issue. We will wait a bit to make sure everything is working correctly and there are no issues with the meson switch.

**Comment by phrdina** [comment]
New virt-manager v5.0.0 was just released.

**Comment by hartwork** [comment]
Awesome! Thank you! :pray:
