### ISSUE TITLE
Inconsistent Language Localization: Some Strings Displaying Correctly, Others Remaining in English

### ISSUE THREAD

**Issue by DomHeadroom** [virt-manager/virt-manager#653]
Yo, I noticed a issue in the user interface of virt-manager where some strings are displayed in the language set in my distribution, while other menus and buttons appear in English. 
This inconsistency is present not just in the Italian translation, but also in other languages like French, despite the translation strings being available in the .po files. For example, the string #: ui/createvm.ui:2431 is translated in the it.po file. 
And this true for the Fedora package and persists even when running virt-manager directly from the GitHub repository.

**Distro**: Fedora KDE (Tested on Fedora Workstation too)

![Screenshot_20240412_102350-1](https://github.com/virt-manager/virt-manager/assets/50798132/378c60c1-80e2-43d1-a9dc-02018704cbcc)

**Comment by phrdina** [comment]
Hi, everything works correctly. Latest upstream virt-manager release is 4.1.0 and that one doesn't contain translation for "Forward". The translation was added after the release. We are planning to make new release soon, once that happens and your distribution will pickup the new release it will get fixed.

**Comment by DomHeadroom** [comment]
Tho shouldn't the problem not occur if I run the App directly from the source code downloaded from the github repo?

**Comment by phrdina** [comment]
If you still have your distribution provided virt-manager installed and you run virt-manager directly from the git repository it will use translation from the already installed virt-manager. If you remove virt-manager installed by your distribution there would be no translation at all running virt-manager directly from git repository.
