### ISSUE TITLE
ed25519_sk against remote host requires multiple presence confirmations in VM window

### ISSUE THREAD

**Issue by grisu48** [virt-manager/virt-manager#655]
When using `virt-manager` against a remote host using `ed25519_sk`, e.g. a Yubikey, the application requires an excessive amount of presence confirmations.

ssh connections using `ed25519_sk` require the user to push a button on their hardware dongle, e.g. Yubikey or Nitrokeys. In virt-manager, when connecting to a remote host that uses this method for connecting via ssh, I need to push the button three times to connect to the host. Then opening a virtual machine on that host, `virt-manager` requires even more presence confirmation button pushes, making it cumbersome to operate.

**Distro**: openSUSE Tumbleweed, virt-manager 4.1.0

**Comment by grisu48** [comment]
I counted 8 times I needed to push the button in order to connect a VM with graphical display.

**Comment by phrdina** [comment]
That is strange, connecting to remote host should require only one authentication. Opening VM with Spice graphics will require multiple connections because spice uses multiple channels.

Can you provide `virt-manager --debug` logs?

**Comment by grisu48** [comment]
Of course, find the attached file for the full log here: [virt-manager.txt](https://github.com/virt-manager/virt-manager/files/15010989/virt-manager.txt)

Also you are right, connecting to the remote host now required only one authentication, and also the logs only show one connection open.

So this reduces the issue to the VM window itself.

**Comment by phrdina** [comment]
I'm not sure if this is something we can improve in virt-manager. The reason is virt-manager is creating a connection to libvirt daemon on the remote host using libvirt API and that will ask you for authentication. Once the VM is started virt-manager will create a new ssh tunnel in order to connect to Spice server and once that connection is established Spice will request additional channels where each channel gets a new ssh tunnel.

I never used a setup where I would have to use Yubikey but possibly ssh-agent could help you to reduce the number of authentication requests.

**Comment by grisu48** [comment]
I understand, so this looks like a WONTFIX because it looks like there is not much that could be done.

I'm using an ssh-agent at the moment but am not aware of any methods to cache the presence confirmation. I would assume that's intentional by design and therefore forbidden.

**Comment by grisu48** [comment]
There is a workaround. Assuming the remote host is `jellyfish`, one can do the following in your `~/.ssh/config`:
```
  Host jellyfish
  ControlMaster auto
  ControlPath ~/.ssh/S.%r@%h:%p
  ControlPersist 5m
```
With this configuration I need to only push the button once. Opening a VM Window works then nicely as it should.

**Comment by phrdina** [comment]
That's good to hear there is a configuration solving this issue for you and yeah this is even most likely cantfix so I'll close the issue.

**Comment by grisu48** [comment]
Thank you for taking care!
