### ISSUE TITLE
[Feature Request] Spice to use egl-headless rendernode for hardware acceleration

### ISSUE THREAD

**Issue by Rabcor** [virt-manager/virt-manager#661]
If nvidia users want to use their nvidia gpu for virgl or indeed at all (without passthrough anyhow) they need to use egl-headless to do it.

At it's most basic, you add the nvidia stuff to cgroups and then configure something like this:

```
<graphics type='spice' autoport='yes'/>
<graphics type='egl-headless'>
  <gl rendernode='/dev/dri/renderD128'/>
</graphics>
<video>
  <model type="virtio" heads="1" primary="yes">
    <acceleration accel3d="yes"/>
  </model>
  <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
</video>

```

And now you have virgl running on the nvidia gpu.

The problem then becomes that the spice renderer (be that through virt-viewer or remmina or virt-manager) just plain and simple won't work properly at modern resolutions (probably not even at just 1080p, i tried 1440p) whenever it doesn't have <gl enabled="yes"> so that it's rendered by a gpu.

But you can only have one gl display, one <gl> entry in your entire xml right now which means there is currently no way at all for nvidia users to use their card with virgl and have hardware accelerated spice to go with it (actually... I don't think they have an option for hardware accelerated spice **at all** because you can only use their cards with passthrough or with the above method in the first place unless I missed something).

A way for <graphics type='spice'> to leverage the gl rendernode defined by <graphics type='egl-headless'> would fix this issue.

**Comment by phrdina** [comment]
There is already an issue to track this feature request #632 so closing this one.
