### ISSUE TITLE
RFE: Could VMM show the `virt-install` command in a log somewhere?

### ISSUE THREAD

**Issue by paul-hammant** [virt-manager/virt-manager#663]
This would help people learn the command line way of scripting bits and pieces

Thanks for you great work.

**Comment by crobinso** [comment]
Interesting idea, but virt-manager doesn't call virt-install directly, instead it interacts with library code shared between the two. We would need to write some custom support to generate an equivalent virt-install command which doesn't sound worth the maintenance burden IMO.
