### ISSUE TITLE
virt-manager doesn't switch to dark theme with OS (except icons)

### ISSUE THREAD

**Issue by nose-gnome** [virt-manager/virt-manager#664]
**Distro**: Kubuntu 23.10

When my system goes to dark virt-manager remains with the light theme, except for the icons, which do switch, becoming invisible.
![image](https://github.com/virt-manager/virt-manager/assets/71675376/eca1bde2-4a25-49c0-a573-733be796be69)
This is an image of what virt-manager looks like when it's meant to be in dark theme

When it's in light theme everything is fine and the icons are still visible, it's just unable to switch to dark theme properly

**Comment by nose-gnome** [comment]
> I did install fresh Kubuntu 23.10 and changed the default theme to Dark and it worked correctly. In virt-manager we don't do anything with the GTK theme so this is not most likely virt-manager issue.
> 
> Make sure you have your theme installed correctly and possibly try different themes as well. All the theme bits are handled by GTK directly, not by virt-manager itself.

I'll check the theme installation.  I'm just using Breeze dark.   This has been happening since I had a fresh installation of kubuntu.

**Comment by adonespitogo** [comment]
This also happens on Gnome 46. I think it has to do with the GTK version. To fix it, I had to use Gnome-Tweaks tool and set the `Appearance > Legacy Applications` option to `HichContrastInverse`.

**Comment by Joa98Dev** [comment]
In my case (using Gnome) I had to go to **Tweaks Tools** -> **Appearance** -> **Legacy Applications** and select **Adw-gtk3-dark**

**Comment by crobinso** [comment]
Sounds like this isn't virt-manager specific then, so I'm closing
