### ISSUE TITLE
Virt-install randomly swaps disk order during dual disk boot

### ISSUE THREAD

**Issue by SanRam** [virt-manager/virt-manager#665]
virt-install --name "rockyvm"
             --memory 15000
             --vcpus 12
             --metadata "description=Rocky9"
             --location ./"{{ rocky_image_file_name }}"
             --noautoconsole
             --nographics
             --disk path=./files/1rockyvm.qcow2,target=sda,bus=scsi,boot_order=1
             --disk path=./files/2datavm.qcow2,target=sdb,bus=scsi,boot_order=2
             --initrd-inject=./files/{{ IMAGE_KICKSTART }}
             --extra-args="inst.ks=file:/{{ IMAGE_KICKSTART }} ip=dhcp net.ifnames=0  ipv6.disable=1 inst.sshd inst.text consoleblank=0 console=tty0 console=ttyS0,115200n8"
             --network network=default
             --wait=-1
             --controller=scsi,model=virtio-scsi
             --os-variant "rocky9.0"
             --arch x86_64
             --machine q35
             --serial=pty
             --features smm=on
             --boot firmware=efi,loader_secure=no

**Distro**: Rocky 9

the disk sda and sdb gets swapped. the root OS installs randomly on either sda or sdb.
we want it to always install on sda

**Comment by SanRam** [comment]
@phrdina any way to overcome this behaviour. we want sda and sdb to be specific size for a kickstart installation of OS to VM.
In kickstart we have to specify only the disk names like sda and sdb.

**Comment by phrdina** [comment]
Checking kickstart documentation a lot of places allow `disk/by-id/{the_id_you_want}` instead of the simple `sdX`.

I don't know if it's possible to tell kernel to probe the devices synchronously.
