### ISSUE TITLE
Using virt-manager in Mac mini 2023 - M2 -  MacOS Ventura 13.5

### ISSUE THREAD

**Issue by dnoliver** [virt-manager/virt-manager#666]
**Distro**: Mac mini 2023 with M2 cpu, MacOS Ventura 13.5

Hi! I am trying to make libvirt, qemu, and virt-manager to work on the platform referenced above.

To install virt-manager, I followed this instructions: https://medium.com/@aryangodara_19887/qemu-virt-manager-and-libvirt-on-macos-with-apple-silicon-m2-dc677e6b8559

I took ports and brew from their official pages https://www.macports.org/install.php https://brew.sh
I had to install this X11 server for MacOS, otherwise virt-manager doesn't start https://www.xquartz.org

After that, I got virt-manager up and running, the window flickers from time to time, but still usable:

![Screenshot 2024-05-15 at 1 46 45 PM](https://github.com/virt-manager/virt-manager/assets/7730267/abfc58bb-ad46-4afb-96f3-39053e56b829)

Then, I tried following this thread to install Ubuntu for ARM: https://www.reddit.com/r/Ubuntu/comments/1bzalbu/ubuntu_mac_m2_pro_virtual_machine/. I downloaded the referenced iso file in the reddit post, and tried to create a VM with it.

![Screenshot 2024-05-15 at 1 50 10 PM](https://github.com/virt-manager/virt-manager/assets/7730267/195fea15-61b9-4119-b5cf-5827ac088a7f)

I selected some default options, and when I try to create the VM, I get the following error:

![Screenshot 2024-05-15 at 1 54 03 PM](https://github.com/virt-manager/virt-manager/assets/7730267/1633ec15-9140-4c64-bd3c-71559d59093e)

The error text is below, for better readability 

```
Unable to complete install: 'internal error: process exited while connecting to monitor: qemu_madvise: Invalid argument
madvise doesn't support MADV_DONTDUMP, but dump_guest_core=off specified
qemu_madvise: Invalid argument
madvise doesn't support MADV_DONTDUMP, but dump_guest_core=off specified
qemu_madvise: Invalid argument
madvise doesn't support MADV_DONTDUMP, but dump_guest_core=off specified
2024-05-15T20:51:25.266737Z qemu-system-aarch64: VCPU supports less PA bits (36) than requested by the memory map (40)'

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/share/virt-manager/virtManager/createvm.py", line 2010, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/libvirt.py", line 4545, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: internal error: process exited while connecting to monitor: qemu_madvise: Invalid argument
madvise doesn't support MADV_DONTDUMP, but dump_guest_core=off specified
qemu_madvise: Invalid argument
madvise doesn't support MADV_DONTDUMP, but dump_guest_core=off specified
qemu_madvise: Invalid argument
madvise doesn't support MADV_DONTDUMP, but dump_guest_core=off specified
2024-05-15T20:51:25.266737Z qemu-system-aarch64: VCPU supports less PA bits (36) than requested by the memory map (40)
```

Any alternative methods to get this setup created? Arm VM on Arm Hardware?

**Comment by phrdina** [comment]
Hi, this is not an issue in virt-manager. Seems like QEMU doesn't work correctly on your HW by default. After some searching online you can try editing your VM configuration using: 
`virt-xml VMNAME --edit --qemu-commandline "-machine highmem=off"`
to see if it fixes the issue.

As the error message from that log you posted `qemu-system-aarch64: VCPU supports less PA bits (36) than requested by the memory map (40)'` suggest your CPU has limited support and as already pointed out that error is from QEMU. So closing this issue and it the workaround doesn't solve it I would suggest contacting QEMU community.

**Comment by dnoliver** [comment]
Thanks for the follow up, will take into account for further exploration
