### ISSUE TITLE
[Question]: Is it possible to map virtual monitors to physical ones?

### ISSUE THREAD

**Issue by Stroopwafe1** [virt-manager/virt-manager#669]
**Distro**: Arch Linux kernel 6.9.1-arch1-1
**Desktop Environment**: KDE Plasma 6.0.4

This is just a question, but I can not find the answer anywhere.
What I want to be able to do is the following:

1. Add multiple monitors (video hardware) to my guest VM
2. When starting the VM, have multiple VM windows/graphical consoles open
3. Be able to fullscreen each individual VM window

OR

1. Add multiple monitors (video hardware) to my guest VM
2. When starting the VM and going into fullscreen mode, have a button that will expand the virtual monitors onto the physical monitors.

Essentially, I would like to know if the functionality that VMWare Workstation has, is also possible on VirtManager.

Is this possible? And if not, is this something that is worth becoming a feature request?

My usecase for this is so that I can utilise my multiple monitor setup on my host, and also so that I have a proper compartmentalisation between work (VMs) and 'play' (Host).

**Comment by phrdina** [comment]
Hi, this is not possible with virt-manager. But you can use Virt-viewer one you configure your VM and the VM is running and that will allow you to have multiple windows for each "monitor".
