### ISSUE TITLE
Problem installing in Win64 from MSI download.

### ISSUE THREAD

**Issue by the-moog** [virt-manager/virt-manager#679]
**Distro**: None

OS: Win 11 Enterprise

Hi,

I tried to install virt-viewer x64 (MSI) for Windows from [https://virt-manager.org/download](https://virt-manager.org/download) and found that it can't be installed as the .MSI is unsigned.  A .gpg is not enough any more.

It possible, please provide a signed binary installer for Windows 10/11 (x64).
Alternately, perhaps link a supported third party app that provides spice client and is found to work with the current spice release builds.

I note that the release on these links seems to be lagging behind this repo, are there any plans to automate builds and keep the binaries in sync?

Here is the page section from the above link.

---
### virt-viewer

[virt-viewer 11.0](https://releases.pagure.org/virt-viewer/virt-viewer-11.0.tar.xz)  [(gpg)](https://releases.pagure.org/virt-viewer/virt-viewer-11.0.tar.xz.asc) Friday November 18th, 2021  [Win x86 MSI](https://releases.pagure.org/virt-viewer/virt-viewer-x86-11.0-1.0.msi)  [(gpg)](https://releases.pagure.org/virt-viewer/virt-viewer-x86-11.0-1.0.msi.asc)  ****[Win x64 MSI](https://releases.pagure.org/virt-viewer/virt-viewer-x64-11.0-1.0.msi)**** [(gpg)](https://releases.pagure.org/virt-viewer/virt-viewer-x64-11.0-1.0.msi.asc)

Virt-viewer releases are curently GPG signed by Daniel P. Berrange using a key having the fingerprint:
```text
DAF3 A6FD B26B 6291 2D0E 8E3F BE86 EBB4 1510 4FDF (4096R)
```
---

**Comment by phrdina** [comment]
Hi, virt-viewer is different project so please report the issue here https://gitlab.com/virt-viewer/virt-viewer/-/issues.
