### ISSUE TITLE
Global menu bug

### ISSUE THREAD

**Issue by Leonardo5681** [virt-manager/virt-manager#684]
Hi, I use Fedora 40 KDE, on KDE I have the global menu active, so virt manager works fine, but the menu bar is buggy, how can I fix it?

https://github.com/virt-manager/virt-manager/assets/92219720/88015286-33ad-4981-b947-8f11e46963eb

**Comment by Who-are-me** [comment]
add GDK_BACKEND=x11 to .desktop file (line Environment Variables in KDE gui)

**Comment by phrdina** [comment]
Can you run virt-manager with `--debug` and provide the debug log to see if there is anything that would help us figure this out?

**Comment by JulienDlq** [comment]
This might be related to what is mentioned here: https://bugs.kde.org/show_bug.cgi?id=424485

**Comment by crobinso** [comment]
Yeah seems like this is the KDE bug mentioned, so I'm closing this
