### ISSUE TITLE
RFE: need virt-install `--boot bios` to override UEFI default

### ISSUE THREAD

**Issue by andreabolognani** [virt-manager/virt-manager#692]
With more and more operating systems becoming UEFI-first (if not outright UEFI-only), we can expect that at some point in the not-so-distant future virt-install will start preferring it to BIOS. When that happens, we will need a way to opt out of UEFI.

The obvious expectation on the user's part would probably be to be able to use `--boot bios`, mirroring `--boot uefi` that can currently be used to opt into the non-default firmware choice. That option doesn't currently exist.

What *does* exist is `--boot firmware=bios`. That's a bit more verbose and less discoverable, but that in itself would probably not be a big issue. The problem is that it doesn't really work right now:

```
$ virt-install --name cirros-bios --osinfo linux2022 --boot firmware=bios --import --disk /var/lib/libvirt/images/cirros.qcow2 
Starting install...
ERROR    operation failed: Unable to find 'bios' firmware that is compatible with the current configuration
```

It's easy to see why this happens: `--boot firmware=bios` translates to `<os firmware='bios'>`; however, despite having the SeaBIOS package installed on my system, there is no firmware descriptor for any of the files it contains, so libvirt is unable to come up with a reasonable match for the requirements.

We could push for distro packages to introduce such a firmware descriptor, making this argument somewhat moot, but I also think that we might want to have a way to just explicitly generate an empty `<os>` element, as a way to really maintain the current/historical behavior.

While poking around a bit, I've also noticed that `--boot uefi` and `--boot firmware=uefi` seem to have slightly different behaviors. I'm not yet sure whether the two can be reconciled, but if at all possible I think we should aim for that as the current situation can be a significant source of confusion IMO.

Before I start sinking time into this, I'd like to hear the maintainers' opinions on the topic, specifically:

* would introducing `--boot bios` be welcome?
* should `--boot uefi` and `--boot firmware=uefi` behave the same way?
* should there be a way to generate `<os>` with no firmware information, and if so what would be a good CLI for it?

Thanks!

**Comment by phrdina** [comment]
`--boot uefi` and `--boot firmware=efi` are not equivalent options. The former is a shortcut to request default UEFI firmware for a VM which will make necessary changes to the VM XML. The letter directly translates to VM XML attribute and does nothing else. Nowadays it behaves the same for libvirt that supports firmware auto-selection but before that features was introduced in libvirt it was getting loader path from libvirt capabilities and setting necessary XML bits.

Based on libvirt documentation `bios` is valid value for `firmware` attribute but as you've already stated it currently doesn't work so ideally that should be fixed somehow. So for virt-install the only way to request BIOS is to create XML without any firmware/loader/etc bits. That is currently not possible for VM where virt-install will prefer UEFI so introducing `--boot bios` sounds reasonable.

Currently the `--boot bios` would create `<os>` with no firmware information but once `firmware=bios` is fixed and we can detect it in virt-install the `--boot bios` option can do the same thing as `firmware=bios`. I don't think it is necessary to add different way to generate `<os>` without firmware information.

**Comment by andreabolognani** [comment]
The distinction between the high-level `--boot foo` and low-level `--boot firmware=foo` makes sense, thanks for explaining it.

At this point, I'm not sure there would be any advantage to using `<os firmware='bios'>` on x86 as opposed to just `<os>`. It's a bit more explicit, which is nice, but other than that QEMU will already know to look for SeaBIOS' `bios-256k.bin` and load it, so it's effectively the same thing.

I'll prepare patches that implement `--boot bios` the only way that's currently possible. We'll see about changing the rest later if needs be.

**Comment by 0x6A7232** [comment]
For real?

I've just been banging my head into the wall all this time editing the virt domain xml for my qemu / kvm trying to get a Legacy / CSM / BIOS booting to work so I can install my legacy OS (Win XP, Win '98, Win '95, heck, I might even try Win 3.1 and DOS )  on QEMU.

Because I tried replacing   `<os firmware="efi">` with   `<os firmware="bios">`
And getting 
`Error starting domain: operation failed: operation failed: Unable to find any firmware to satisfy 'bios'`
When _**obviously**_, the solution was to replace   `<os firmware="efi">` with `<os>`, **_cause that makes sense..._** 

And why doesn't the virt-manager / Virtual Machine Manager GUI have an option to choose which firmware you would like to POST the VM with?

Yeesh.

Now I just need to figure out the boot order issue...

Why can't BIOS / Legacy booting be implemented as a CSM under the EFI firmware?  And just allow people to get into BIOS setup and turn it on / off as needed?  You can save the settings in a .nvram.cfg file for that VM or something.

Hope the search engines pick up on the terms and this helps someone.

**Comment by phrdina** [comment]
> For real?
> 
> I've just been banging my head into the wall all this time editing the virt domain xml for my qemu / kvm trying to get Legacy / CSM / BIOS booting to work so I can install legacy OSes (Win XP, Win '98, Win '95, heck, I might even try Win 3.1 and DOS ) on QEMU. And nothing worked. Because I tried replacing `<os firmware="efi">` with `<os firmware="bios">` And kept getting this error when trying to start the VM using BIOS firmware: `Error starting domain: operation failed: operation failed: Unable to find any firmware to satisfy 'bios'` When _**obviously**_, the solution was to replace `<os firmware="efi">` with `<os>`, **_cause that makes sense..._**

That's a bug in libvirt, nothing we can do about that in virt-manager except adding the cli option `--boot bios` or using the current option `--boot uefi=off`.

> And why doesn't the virt-manager / Virtual Machine Manager GUI have an option to choose which firmware you would like to POST the VM with?

You can select it in GUI when installing a new VM, on the last page you have `Customize configuration before install`, that will open a new window where you can change any default virt-manager will pick including firmware.

There were multiple requests to add UI that would allow users to change it for existing VMs. The main reason is that for a lot of OSes it will just not work out of the box if you install with bios and switch to uefi. This is considered advanced feature and can be changed using `virt-xml` or editing the XML directly, for example see this open issue https://github.com/virt-manager/virt-manager/issues/245 .

> Yeesh.
> 
> Now I just need to figure out the boot order issue...
> 
> Why can't BIOS / Legacy booting be implemented as a CSM under the EFI firmware? And just allow people to get into BIOS setup and turn it on / off as needed? You can save the settings in a .nvram.cfg file for that VM or something.

That's a question for the EDKII project that provides UEFI firmware for qemu/kvm VMs. But my guess would be extra work that nobody has time for and there is already BIOS firmware that can be used if your VM needs to run OS that doesn't support UEFI.

> 
> Hope the search engines pick up on the terms and this helps someone.

**Comment by andreabolognani** [comment]
> [...] I tried replacing `<os firmware="efi">` with `<os firmware="bios">` And kept getting this error when trying to start the VM using BIOS firmware: `Error starting domain: operation failed: operation failed: Unable to find any firmware to satisfy 'bios'`

That's basically a packaging issue. If you create a file called `/usr/share/qemu/firmware/20-seabios.json` with the following contents:

```json
{
    "description": "SeaBIOS",
    "interface-types": [
        "bios"
    ],
    "mapping": {
        "device": "memory",
        "filename": "/usr/share/seabios/bios.bin",
        "format": "raw"
    },
    "targets": [
        {
            "architecture": "x86_64",
            "machines": [
                "pc-i440fx-*",
                "pc-q35-*"
            ]
        }
    ],
    "features": [],
    "tags": []
}
```

then `<os firmware='bios'>` will start working.

There's probably a bunch of nuance involved, since at least in Fedora the `seabios-bin` package contains a number of builds. But the point is that the mechanism needed to make that work exists, it just needs to be used.

> Why can't BIOS / Legacy booting be implemented as a CSM under the EFI firmware? And just allow people to get into BIOS setup and turn it on / off as needed? You can save the settings in a .nvram.cfg file for that VM or something.

CSM is a kludge that was necessary during the transition from BIOS to UEFI. These days, many physical machines are shipping with UEFI-only firmware.

The reason why CSM needed to exist in the first place is that, on physical hardware, you have to pick a firmware type at the factory and that's it, you can't really change it afterwards. For virtual hardware, there are no such restrictions.

edk2, the UEFI firmware used for QEMU VMs, actually comes with CSM support, but it's usually compiled out because enabling it makes the firmware build bigger and is a security/support liability. Interestingly, CSM support in edk2 is implemented by embedding SeaBIOS, the BIOS firmware used for QEMU VMs.
