### ISSUE TITLE
Nvidia Driver 555, 560 Supports 3D Acceleration

### ISSUE THREAD

**Issue by ZacPost** [virt-manager/virt-manager#695]
Hi, I did notice that whit Nvidia driver 555 and 560 it finally supports Wayland natively, whit the driver 560 whit prime-run I was able successfully to run QEMU from terminal whit the OpenGL 3D Acceleration whit GTK Display, the graphics where a bit biggy and some weird Display glitches but it was working very well, I wanted to try whit Virtual machine manager and the result was that it gives me an Error whit the Display, was about some Error Display Connection, it did one time run whiteout this Error but there literally was no display like not even the black one that would say at last no display output even that one was not there, so could you please update and modify Virtual machine manager for the New Nvidia driver 555 and 560+? Because it supports now OpenGL Acceleration just need I think the software to be updated to actually support whit the NVIDIA GPUs whit this new driver's, please 🥺, fix this issue.

**Comment by ZacPost** [comment]
And Here is an Image of the Error and the Logs of the Message:
![Screenshot from 2024-07-30 12-28-31](https://github.com/user-attachments/assets/3a35d754-342b-4aac-8205-dc379d1bde3c)
![Screenshot from 2024-07-30 12-28-22](https://github.com/user-attachments/assets/b78bd0d5-0048-481d-b8e4-79b098b01c34)
The Logs: Error starting domain: internal error: process exited while connecting to monitor

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1379, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: process exited while connecting to monitor

**Comment by phrdina** [comment]
Hi, can you please provide full VM XML when this happened? The error message suggest that QEMU process crashed so if possible can you also provide content of `/var/log/libvirt/qemu/Ubuntu2404.log`?

**Comment by ZacPost** [comment]
> Hi, can you please provide full VM XML when this happened? The error message suggest that QEMU process crashed so if possible can you also provide content of `/var/log/libvirt/qemu/Ubuntu2404.log`?

Yeha for sure here is the .log file

**Comment by ZacPost** [comment]
![Screenshot from 2024-08-06 11-27-11](https://github.com/user-attachments/assets/b02cb3e1-9b05-4ac6-a999-1703bb43052c)
![Screenshot from 2024-08-06 11-26-58](https://github.com/user-attachments/assets/b814da46-7475-4c1a-8221-aace6520ea38)

**Comment by ZacPost** [comment]
> Hi, can you please provide full VM XML when this happened? The error message suggest that QEMU process crashed so if possible can you also provide content of `/var/log/libvirt/qemu/Ubuntu2404.log`?

![Uploading Screenshot from 2024-08-06 11-29-08.png…]()

**Comment by ZacPost** [comment]
> Hi, can you please provide full VM XML when this happened? The error message suggest that QEMU process crashed so if possible can you also provide content of `/var/log/libvirt/qemu/Ubuntu2404.log`?

![Screenshot from 2024-08-06 11-29-08](https://github.com/user-attachments/assets/bcf87ab9-23c5-4e39-91bb-112b51bc7119)

**Comment by phrdina** [comment]
Checking the log file it seems like it could be related to this issue https://github.com/virt-manager/virt-manager/issues/632.

As a workaround you need to remove the `OpenGL` bit from the spice graphics and add another graphics `egl-headless` by using `virt-xml win11 --add-device --graphics egl-headless,gl.rendernode=/dev/dri/renderD128`. Nvidia requires this specific configuration to make the 3d acceleration work with virtio video device.

**Comment by ZacPost** [comment]
> Checking the log file it seems like it could be related to this issue https://github.com/virt-manager/virt-manager/issues/632.
> 
> As a workaround you need to remove the `OpenGL` bit from the spice graphics and add another graphics `egl-headless` by using `virt-xml win11 --add-device --graphics egl-headless,gl.rendernode=/dev/dri/renderD128`. Nvidia requires this specific configuration to make the 3d acceleration work with virtio video device.

I did fallow a YouTube tutorial about this thing, is quite interesting because the dude that did show the video it did worked but for me it doesn't, it simply give me the same error even whit egl-headless, by the way I would like to know if the project will ever get Vulkan 3D Acceleration whit SPICE, I know that VMware Graphics use Vulkan for Windows VMs and that's why I can even play smoothly games on VMware,

**Comment by crobinso** [comment]
Your log file has these errors:

2024-07-04T03:49:45.024183Z qemu-system-x86_64: warning: spice: no gl-draw-done within one second
2024-07-04T03:49:45.024230Z qemu-system-x86_64: warning: console: no gl-unblock within one second
2024-07-04T03:49:51.477640Z qemu-system-x86_64: Spice: ../server/red-qxl.cpp:435:spice_qxl_gl_scanout: condition `qxl_state->gl_draw_cookie == GL_DRAW_COOKIE_INVALID' failed

So spice is crashing. It shouldn't do that. You should file a spice bug with your distribution, it's unlikely this is virt-manager specific.
