### ISSUE TITLE
macOS Sononma 14.5 issue: Unable to connect to qemu:///system, name libxml2 not defined

### ISSUE THREAD

**Issue by 4WvgqJu** [virt-manager/virt-manager#698]
**Distro**: macOS Sonoma 14.5

It confuses me. No package of libxml2-python, libxml2-python3, m3-libxml2-python is compatible with python3/pip3! Why isn't libxml2 not replaced with lxml in source code?
 
![Bildschirmfoto 2024-08-02 um 17 42 09](https://github.com/user-attachments/assets/4c2cbb51-cb55-4e57-a5a7-df47d1e132a0)

(.venv) folkertmeeuw@MacBook-Pro-von-Folkert virt-manager % sudo python virt-manager --debug --no-fork
Password:
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (cli:204) Version 4.1.0 launched with command line: virt-manager --debug --no-fork
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (virtmanager:169) virt-manager version: 4.1.0
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (virtmanager:170) virtManager import: /Users/folkertmeeuw/virt-manager/virtManager
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (virtmanager:207) PyGObject version: 3.48.2
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (virtmanager:211) GTK version: 3.24.41
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (systray:479) Showing systray: False
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (inspection:205) python guestfs is not installed
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (engine:112) No stored URIs found.
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (engine:489) processing cli command uri= show_window=manager domain=
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (engine:498) No cli action requested, launching default window
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (manager:185) Showing manager
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (engine:317) window counter incremented to 1
[Fri, 02 Aug 2024 17:20:05 virt-manager 9704] DEBUG (engine:212) Initial gtkapplication activated
[Fri, 02 Aug 2024 17:20:06 virt-manager 9704] DEBUG (engine:136) Probed default URI=None
[Fri, 02 Aug 2024 17:21:23 virt-manager 9704] DEBUG (createconn:91) Showing open connection
[Fri, 02 Aug 2024 17:21:28 virt-manager 9704] DEBUG (createconn:277) Generate URI=qemu:///system, auto=True
[Fri, 02 Aug 2024 17:21:28 virt-manager 9704] DEBUG (connection:484) conn=qemu:///system changed to state=Connecting
[Fri, 02 Aug 2024 17:21:28 virt-manager 9704] DEBUG (connection:912) Scheduling background open thread for qemu:///system
[Fri, 02 Aug 2024 17:21:28 virt-manager 9704] DEBUG (connection:128) libvirt URI versions library=10.2.0 driver=10.2.0 hypervisor=9.0.2
[Fri, 02 Aug 2024 17:38:11 virt-manager 10616] DEBUG (connection:847) conn.close() uri=qemu:///system
[Fri, 02 Aug 2024 17:38:11 virt-manager 10616] DEBUG (connection:484) conn=qemu:///system changed to state=Disconnected
[Fri, 02 Aug 2024 17:38:11 virt-manager 10616] DEBUG (error:102) error dialog message:
summary=Unable to connect to libvirt qemu:///system.

name 'libxml2' is not defined

Would you still like to remember this connection?
details=Unable to connect to libvirt qemu:///system.

name 'libxml2' is not defined

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/Users/folkertmeeuw/virt-manager/virtManager/connection.py", line 932, in _do_open
    self._backend.open(cb, data)
  File "/Users/folkertmeeuw/virt-manager/virtinst/connection.py", line 184, in open
    self._get_caps()  # cache and log capabilities
    ^^^^^^^^^^^^^^^^
  File "/Users/folkertmeeuw/virt-manager/virtinst/connection.py", line 108, in _get_caps
    self._caps = Capabilities(self, capsxml)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/folkertmeeuw/virt-manager/virtinst/capabilities.py", line 205, in __init__
    XMLBuilder.__init__(self, *args, **kwargs)
  File "/Users/folkertmeeuw/virt-manager/virtinst/xmlbuilder.py", line 547, in __init__
    self._xmlstate = _XMLState(self.XML_NAME,
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/folkertmeeuw/virt-manager/virtinst/xmlbuilder.py", line 438, in __init__
    self.parse(parsexml, parentxmlstate)
  File "/Users/folkertmeeuw/virt-manager/virtinst/xmlbuilder.py", line 454, in parse
    self.xmlapi = XMLAPI(parsexml)
                  ^^^^^^^^^^^^^^^^
  File "/Users/folkertmeeuw/virt-manager/virtinst/xmlapi.py", line 291, in __init__
    libxml2.keepBlanksDefault(1)
    ^^^^^^^
NameError: name 'libxml2' is not defined
[Fri, 02 Aug 2024 17:42:30 virt-manager 10616] DEBUG (createconn:86) Closing open connection

**Comment by phrdina** [comment]
Non of the libxml2 on pypi.org are up to date. The libxml2 python bindings are part of the library source code https://gitlab.gnome.org/GNOME/libxml2 and that's what we are using in virt-manager.

How did you install virt-manager on your system?  The easiest way is to use homebrew or macports, they will handle all the dependencies for you. If you want to do it manually out need to get the libxml2.

There is no plan to switch to lxml.

**Comment by 4WvgqJu** [comment]
homebrew. yes!

virt-manager (Release 4.1.0 (August 04, 2022)) 
- in zsh on macOS
- with PyCharm for debug, but without libxml2

**Comment by phrdina** [comment]
So you've fixed the libxml2 issue and now that part is working.

From the screenshot I can see that you have two connection defined in virt-manager and from the debug log I see that you've started virt-manager with `--connect qemu:///system?socket=/opt/local/var/run/libvirt/libvirt-sock --debug --no-fork` but virt-manager tries to connect to default connection as well. You can simply remove the connection that doesn't work and the error should go away.

**Comment by 4WvgqJu** [comment]
From what .conf file is the default connection then?

**Comment by 4WvgqJu** [comment]
For the connection qemu.///system is network an additional issue.

<img width="912" alt="Bildschirmfoto 2024-08-03 um 16 52 45" src="https://github.com/user-attachments/assets/f8950199-1c5f-45d6-87ce-343a1060f251">

<img width="1552" alt="Bildschirmfoto 2024-08-03 um 16 56 24" src="https://github.com/user-attachments/assets/d8fdeb74-600a-45e5-863a-fcdcd10f7f27">

```
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:962) Connection doesn't seem to support nodedev APIs.
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:739) Using domain events
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:778) Using network events
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:797) Using storage pool events
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:825) Error registering node device events: Diese Funktion wird vom Verbindungstreiber nicht unterstützt: virConnectNodeDeviceEventRegisterAny
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:1072) network=default status=Inaktiv added
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:691) storage pool refresh event: pool=default
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:1072) pool=default status=Aktiv added
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:691) storage pool refresh event: pool=images
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:1072) pool=images status=Aktiv added
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:691) storage pool refresh event: pool=coreos
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:1072) pool=coreos status=Aktiv added
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (storage:137) Found default pool name=default target=/var/lib/libvirt/images
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (connection:482) conn=qemu:///system?socket=/opt/local/var/run/libvirt/libvirt-sock changed to state=Aktiv
[Sa, 03 Aug 2024 16:51:43 virt-manager 5893] DEBUG (engine:428) Launching requested window 'manager'
[Sa, 03 Aug 2024 16:51:44 virt-manager 5893] DEBUG (manager:185) Showing manager
[Sa, 03 Aug 2024 16:51:44 virt-manager 5893] DEBUG (engine:316) window counter incremented to 1
[Sa, 03 Aug 2024 16:52:00 virt-manager 5893] DEBUG (xmleditor:12) Using GtkSource 4
[Sa, 03 Aug 2024 16:52:00 virt-manager 5893] DEBUG (host:85) Showing host details: <vmmConnection uri=qemu:///system?socket=/opt/local/var/run/libvirt/libvirt-sock id=0x107a133c0>
[Sa, 03 Aug 2024 16:52:00 virt-manager 5893] DEBUG (engine:316) window counter incremented to 2
[Sa, 03 Aug 2024 16:53:19 virt-manager 5893] DEBUG (hostnets:284) Starting network 'default'
[Sa, 03 Aug 2024 16:53:19 virt-manager 5893] DEBUG (error:101) error dialog message:
summary=Fehler beim Starten des Netzwerks »default«: Kann auf dieser Plattform die Schnittstelle 'bridge2' nicht auf 'bridge1' umbenennen: Function not implemented
details=Traceback (most recent call last):
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/object/network.py", line 69, in start
    self._backend.create()
  File "/opt/homebrew/opt/libvirt-python/lib/python3.12/site-packages/libvirt.py", line 3569, in create
    raise libvirtError('virNetworkCreate() failed')
libvirt.libvirtError: Kann auf dieser Plattform die Schnittstelle 'bridge2' nicht auf 'bridge1' umbenennen: Function not implemented

[Sa, 03 Aug 2024 16:54:55 virt-manager 5893] DEBUG (hostnets:284) Starting network 'default'
[Sa, 03 Aug 2024 16:54:55 virt-manager 5893] DEBUG (error:101) error dialog message:
summary=Fehler beim Starten des Netzwerks »default«: Kann auf dieser Plattform die Schnittstelle 'bridge3' nicht auf 'bridge1' umbenennen: Function not implemented
details=Traceback (most recent call last):
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/object/network.py", line 69, in start
    self._backend.create()
  File "/opt/homebrew/opt/libvirt-python/lib/python3.12/site-packages/libvirt.py", line 3569, in create
    raise libvirtError('virNetworkCreate() failed')
libvirt.libvirtError: Kann auf dieser Plattform die Schnittstelle 'bridge3' nicht auf 'bridge1' umbenennen: Function not implemented

[Sa, 03 Aug 2024 16:56:00 virt-manager 5893] DEBUG (hostnets:284) Starting network 'default'
[Sa, 03 Aug 2024 16:56:00 virt-manager 5893] DEBUG (error:101) error dialog message:
summary=Fehler beim Starten des Netzwerks »default«: Kann auf dieser Plattform die Schnittstelle 'bridge4' nicht auf 'bridge1' umbenennen: Function not implemented
details=Traceback (most recent call last):
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/virt-manager/4.1.0_7/share/virt-manager/virtManager/object/network.py", line 69, in start
    self._backend.create()
  File "/opt/homebrew/opt/libvirt-python/lib/python3.12/site-packages/libvirt.py", line 3569, in create
    raise libvirtError('virNetworkCreate() failed')
libvirt.libvirtError: Kann auf dieser Plattform die Schnittstelle 'bridge4' nicht auf 'bridge1' umbenennen: Function not implemented

```

**Comment by phrdina** [comment]
Seems like network with libvirt is not currently supported on macos, see https://gitlab.com/libvirt/libvirt/-/issues/75, so there is nothing we can do in virt-manager until the support for it is implemented in libvirt.

Since you've solved missing libxml2 I'm closing this issue.

**Comment by 4WvgqJu** [comment]
Agreed! Thanks for your support.
