### ISSUE TITLE
Japanese translation mistake: OpenGL

### ISSUE THREAD

**Issue by naota** [virt-manager/virt-manager#70]
https://github.com/virt-manager/virt-manager/blob/d52c9d1ffa2d8c204fbb2a714f89b007fa6227ec/po/ja.po#L6201

"OpenGL" is translated to "GL を開く". But, this translation interpret a proper noun "OpenGL" as "Open" (verb) and "GL" (noun), so it's meaning "to open a GL" which is confusing.
Correct translation should keep the proper noun as is, so "Open_GL:" is fine here.

**Comment by crobinso** [comment]
Sorry, translations are in flux at the moment, we are in the process of moving the platform from zanata to weblate. I will get to this when that transition is straightened out

**Comment by crobinso** [comment]
My patch was reverted, it didn't full fix this either. Please help out with japanese translation in the Fedora weblate system, the translation can be fixed there:

https://translate.fedoraproject.org/projects/virt-manager/virt-manager/
