### ISSUE TITLE
Virt-Install - The PXE option `--pxe` should be renamed `--ipxe`

### ISSUE THREAD

**Issue by mgrzybek** [virt-manager/virt-manager#705]
**Distro**: NixOS 24.05 (but not revelant)
**Virt-Manager**: 4.1.0

Using `virt-install --pxe` to create virtual machines, I realised that in fact it uses iPXE. This is confusing from a user's point of view.

Two solutions are possible:
1. Some platforms are only capable of using legacy PXE protocol. Both `--pxe` and `--ipxe` should be available (or not) depending of their capabilities.
2. iPXE is always used. The `--pxe` option should be renamed `--ipxe`.

What do you think?

**Comment by crobinso** [comment]
Thanks for the suggestion. I agree the `--pxe` naming is poor. Really what it is doing is telling the VM to mark network devices as bootable. What that means in practice depends on the firmware you are using. For default qemu nowadays that's IPXE but it was GPXE before that.

The wordier way on virt-install CLI to request `--pxe` is `--install bootdev=network` which is more exact. I don't think we should add any different `--pxe` related naming though
