### ISSUE TITLE
KVM - SMBIOS table not found !

### ISSUE THREAD

**Issue by Kamcloud** [virt-manager/virt-manager#706]
Hi,

I'm using GNS3 to simulate routers with qcow2 image. Everything works fine on Ubuntu 22.04.4 LTS. After upgrading to Ubuntu 24.04.1 LTS, the routers reboot continuously with the following message :

SMBIOS table not found !
ERROR: Failed to detect BIOS parameters

Is someone experienced the same issue?

Thanks.

**Comment by crobinso** [comment]
I have not heard of that error. Unlikely to be virt-manager specific and probably related to your usecase. I'd ask in support forums for wherver you got that qcow2 image

**Comment by lsamba** [comment]
Hello
I have the same issue as **Kamcloud**, I have upgrade my Jammy Ubuntu to Noble, before upgrade I was running SROS on GNS3, after upgrade, when I start my SROS router on GNS3, I had this message:

KVM based vcpu
Running in a KVM/QEMU virtual machine
SMBIOS table not found !
ERROR: Failed to detect BIOS parameters
ACPI: found 2 cores, 2 enabled
SMBIOS table not found !
ERROR: Failed to detect BIOS parameters

Any suggestion will be wellcome.

Thank you

**Comment by jmarino83** [comment]
hi guys, anyone can resolve this? 

thanks

**Comment by lsamba** [comment]
Hello @jmarino83 
I find a solution on GNS3 forum, someone advise me to add additional settings options: 
"
**-machine smbios-entry-point-type=32**, -smbios type=1,product="TIMOS:slot=A chassis=SR-1 card=cpm-1 mda/1=me12-100gb-qsfp28 license-file=cf3:\license2" -uuid 3b867e37-3b57-406f-9823-fe05616332da
"
Option in bold is the added options, in non bold was the option I have before. You can adapt to your case and let us know if you solve your problem, for me it works now.

![Capture d’écran du 2025-01-13 04-28-21](https://github.com/user-attachments/assets/d21cb4c6-3e11-4727-90b1-3eeba5f52504)

**Comment by chris1350** [comment]
> > Hello [@jmarino83](https://github.com/jmarino83) I find a solution on GNS3 forum, someone advise me to add additional settings options: " **-machine smbios-entry-point-type=32**, -smbios type=1,product="TIMOS:slot=A chassis=SR-1 card=cpm-1 mda/1=me12-100gb-qsfp28 license-file=cf3:\license2" -uuid 3b867e37-3b57-406f-9823-fe05616332da " Option in bold is the added options, in non bold was the option I have before. You can adapt to your case and let us know if you solve your problem, for me it works now.
> 
> Hello [@lsamba](https://github.com/lsamba) you save my life =). I can confirm is working again SROS
> 
> thanks a lot

@lsamba Many thanks ! I also confirm, working fine on Ubuntu 24.04 LTS with GNS3 2.2.54 and SROS 25.3.R1
