### ISSUE TITLE
Error starting a guest mashine

### ISSUE THREAD

**Issue by alecskup** [virt-manager/virt-manager#71]
I'm starting the virt-manager and create a new virtual machine. And I get error:
![2019-12-22_06-27](https://user-images.githubusercontent.com/58822727/71316695-0a489280-2485-11ea-8cbf-5baaeca71169.png)
What do I do?

**Comment by crobinso** [comment]
I have no idea, that issue sounds like something is wrong with your libosinfo gobject-introspection install. What distro is this? Did you install from source or from distro packages?

**Comment by alecskup** [comment]
This is a blackarch linux. I'm installed a distro packages from live-iso

**Comment by crobinso** [comment]
I think you need to file a bug with your distro. Their libosinfo package is probably broken

**Comment by tonyfinn** [comment]
Also encountering this on regular Arch Linux
