### ISSUE TITLE
Update test suite aarch64 domcaps

### ISSUE THREAD

**Issue by crobinso** [virt-manager/virt-manager#714]
We could use more modern aarch64 domcapabilities for our test suite.

@andreabolognani can you provide something modern for machvirt? Attaching here is fine, or PR to update `tests/data/capabilities/kvm-aarch64-domcaps.xml` if you're feeling frisky. Thanks in advance!

**Comment by andreabolognani** [comment]
Sure, I can do that.

**Comment by andreabolognani** [comment]
#716
