### ISSUE TITLE
Comments are vanishing in the XML configuration of Connection Details.

### ISSUE THREAD

**Issue by GamePlayer-8** [virt-manager/virt-manager#723]
Good evening,

Adding the comments (`<!-- -->`) inside the advanced XML config settings, makes them vanish once pressing `Apply` button.

**Distro**: `Alpine Linux v3.20`
**Latest version**:
```
# virt-manager --version
4.1.0
```

**Comment by crobinso** [comment]
This is a fundamental limitation of libvirt that will never change IMO.

For VMs you can stash some notes in in `<description>` field. VMs and network objects have `<metadata>` that you can stick some comment like content in, but the format is funky. Those are the only options I can think of though.

But there's nothing we can do on virt-manager side, so I'm closing this
