### ISSUE TITLE
virt-install --connect lxc:/ unnecessarily requires --memory

### ISSUE THREAD

**Issue by emojifreak** [virt-manager/virt-manager#73]
I can run `virt-install --memory 2048  --connect lxc:/ --os-variant fedora31 --filesystem /var/lib/lxc/fedora31test/rootfs,/ --network none   --transient --import --name fedora31test` without any error on Fedora Rawhide, but if I remove `--memory 2048` I get an error `ERROR --memory amount in MiB is required` and virt-install fails. As far as I understand LXC containers do not need memory amount.

Package versions:

```
# dnf list --installed
virt-install.noarch 2.2.1-2.fc31
libvirt-daemon-driver-lxc.x86_64 5.10.0-2.fc32 
libvirt-daemon-lxc.x86_64        5.10.0-2.fc32 
lxc.x86_64                       3.2.1-1.fc32   
lxc-libs.x86_64                  3.2.1-1.fc32  
lxc-templates.x86_64             3.2.1-1.fc32 
```

**Comment by crobinso** [comment]
Indeed, the libvirt lxc:/// driver doesn't appear to do anything with the memory setting. The libvirt XML parser though will reject XML without <memory> in it. I pushed a commit to make virt-install just silently default to '--memory 64' if no memory setting was specified for lxc:/// . Thanks for the report!

**Comment by Antique** [comment]
That's not true, we need to revert that patch.  Memory is used by cgroups so if we default to 64 you would not be able to do a lot of things inside the container by default.

**Comment by crobinso** [comment]
@Antique hmm I checked src/lxc libvirt code but couldn't find anything that looked like actual usage of cur_balloon. Did I miss it?

**Comment by Antique** [comment]
Well, --memory translates to <memory> element which in code is stored as total_memory.  Now in src/lxc/lxc_cgroup.c in function virLXCCgroupSetupMemTune we call virDomainDefGetMemoryInitial which gets the value from total_memory excluding empty memory modules and uses that to set cgroup memory max which limits how much of memory can container use.

**Comment by crobinso** [comment]
My bad, thanks for catching that. I change things to default to --memory 1024, and print it so the user gets notified, like we do when default to memory based on --os-variant for qemu
