### ISSUE TITLE
Icons are grayed out and missing with custom icon set

### ISSUE THREAD

**Issue by TheDogHusky** [virt-manager/virt-manager#737]
**Distro**: Arch Linux

Hey!

I use Arch Linux with libadwaita and a custom icon set (tela-circle) but the issue is that all menu icons from the interface are kind of grayed out or missing (video here: https://safe.classydev.fr/2024_10_16_11_55_58-Gw0NreeNccfWCyS2tRClTBnEkKMGaedB.mkv).
Running qemu-kvm and virt-manager 4.1.0-3.

Here is a screen of Neofetch if anyone needs my hardware infos or the detailed info: 
![image](https://github.com/user-attachments/assets/dc1272b2-c1fe-497b-a335-e2e8d6d8d83c)

Thank you in advance!

**Comment by crobinso** [comment]
Thanks for the report but I have no idea what's going on there and I have to assume it's not virt-manager's fault. When using icons we aren't doing anything fancy or attempting to change their look or anything, just using standard gtk APIs to look up an icon name at a requested size.

So you'll probably need to dig into your setup a bit more, or the custom icon set to figure out what's going on.
