### ISSUE TITLE
[BUG]-drops wifi connection when using another VM with wifi adapter.

### ISSUE THREAD

**Issue by FlailAway** [virt-manager/virt-manager#743]
Mint-22+Cinnamon, current 4.1.0-virt-manager: 

I have 2-VMs, both running the same OS as Host, Intel 13th-gen i5, 1TB-NVMe, 32GB memory. I have tried this with both the distro-virt-manager updated and a download-install from here and same results.

VM-01: I use a TPLink wifi adapter on this Guest for running Klipper. I assign the USB to that VM and all runs fine.

If I go to VM-02 and use it, it is just fine, VM-01 still happily running the wifi+Klipper.

However, if I am on VM-02 and assign a USB drive, the VM-01 drops the wifi connection. The check-mark still shows it as connected on VM-01. Including when I go back to VM-01, but the wifi connected has been dropped.

I have tested it several times and it is repeatable. As soon as I open the "redirect USB device" and select a USB-drive, it drops it.

**Comment by phrdina** [comment]
This is expected behavior. You cannot redirect one device to two VMs at the same time. What happens is that the USB device is taken from VM1 and redirected to VM2.

**Comment by FlailAway** [comment]
But it is not the same USB on the other VM. Are you saying that it takes all USB-channels? I have 3-USB-redirectins in each VM. Why does it have to take all?

I can understand your comment if it were the same USB-device. It's a wifi on one and a drive on the other. If it is "takes-all" then you should not be able (allowed)  to assign it on the other VM.

It balks if I try to assign a USB-drive already in use on another VM -- **that's** expected behavior. Being able to assign it and it **silently** takes out all others without a warning, is not.

If it is not a bug then it is poor HI-design. If **anything** is going to cause damage in another VM, at least warn before dropping the VM running a USBxxx. It crashed a 5-hour print 10-minutes before it completed.

**Comment by phrdina** [comment]
My bad, from the original description it was not clear to me that you are assigning different USB devices to different VMs.

Do you keep all VM windows open the whole time? This feature redirect devices to VM using SPICE channels and for that you need to keep the SPICE viewer open the whole time, which means the VM window. SPICE usb redirection can be sometimes tricky, you can disable automatic redirection in `Edit -> Preferences -> Console -> SPICE USB Redirection`.

If you want to have long-term USB assignment you can edit your VM and in the hardware list attach specific USB device to specific VM. This is handled by libvirt and works even without SPICE.
