### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by gdarko** [virt-manager/virt-manager#746]
Hey - 

I follow the virt-manager project for quite some time and i see a healthy movement. Some sources say it is deprecated in favor of Cockpit. I really don't like Cockpit and i really like the simplicity and ease of use of Virt Manager. I was hoping virt-manager will be kept as alternative. Is there any plans for new version given the ongoing development efforts?

Best Regards,
DG

**Distro**: Fedora 41 GNOME

**Comment by phrdina** [comment]
Hi,

No worries, virt-manager as upstream project is not deprecated. It was deprecated only in RHEL. I'm not aware of any other distribution deprecating  virt-manager.
