### ISSUE TITLE
RFE: momory.high cannot be set by virt-install --memory

### ISSUE THREAD

**Issue by emojifreak** [virt-manager/virt-manager#75]
This is an RFE related to libvirt LXC driver and somewhat related to #73.
When `virt-install --memory=1024` is used on a pure CGroup V2 distro (e.g. Fedora 31 and newer), `memory.max` is set. When total real memory usage exceeds 1024 MB, OOM killer is invoked to a process in the LXC container made by virt-install.

On the other hand, if `memory.high` is used, OOM killer is not invoked, but memory pages are swapped out to a swap partition. But virt-install does not seem to provide an option to set memory.high

libvirt provides a way to set `memory.high` as

https://github.com/libvirt/libvirt/blob/2feaa925bba06e77be918bcbfab63bc8201c8f19/src/util/vircgroupv2.c#L1317-L1341

and

https://github.com/libvirt/libvirt/blob/2feaa925bba06e77be918bcbfab63bc8201c8f19/src/lxc/lxc_cgroup.c#L165-L167

**Comment by crobinso** [comment]
Thanks for the report, but from my reading of the code it looks like this maps to virt-install's `--memtune soft_limit` value. Does that work?

**Comment by emojifreak** [comment]
Yes, you are right! Sorry for this unnecessary issue report.
