### ISSUE TITLE
RFE: Convenience option for passt port forwarding

### ISSUE THREAD

**Issue by andreabolognani** [virt-manager/virt-manager#751]
With #697 merged, it is now possible to create VMs that use passt for networking.

Unfortunately, due to how the libvirt XML is designed and how virt-install maps its structure to command line options, doing something as common as making a guest port accessible to the host requires fairly unwieldy invocations, for example:

```
--network backend.type=passt,portForward0.proto=tcp,portForward0.range0.start=8080,portForward0.range0.to=80
```

For comparison's sake, when using podman the same result can be achieved with

```
-p 8080:80
```

It would be nice to introduce a shorthand syntax that makes at least the straightforward scenarios more accessible. For example it could look like

```
--network passt,port-forward=8080:80
```

**Comment by andreabolognani** [comment]
@phrdina since you were the one who implemented passt support in the first place, do you have any thoughts about this idea? Or possibly, maybe, by any chance, even a shred of interest in working on it yourself? O:-)

**Comment by crobinso** [comment]
I submitted this: https://github.com/virt-manager/virt-manager/pull/765  . Example: `--network backend.type=passt,portForward=123:456,portForward1=127.0.0.1:8080:80/udp`

**Comment by andreabolognani** [comment]
@crobinso thanks for looking into this!

I suppose the use of `portForward=...,portForward1=...` is needed to tell the various instances apart. Is this a technical question, i.e. virt-install's CLI parser is completely unable to tell two instances of the same parameter apart, or a matter of consistency with how other options are handled?

As you can probably tell I'm not very familiar with this part of the code, but I see that a callback is involved, which naively makes me hope that perhaps it would be possible to make things even more user-friendly by removing the need to number instances?

Similarly, in the interest of making things as convenient for users as possible, is there any chance that we could support `--network passt` as a shorter alias for `--network backend.type=passt`, or is that out of the question?

Don't get me wrong, what you've implemented is already leaps and bounds more usable than the 1:1 mapping to XML elements that was there before! But if we could somehow manage to accept a more svelte `--network passt,portForward=123:456,portForward=127.0.0.1:8080:80/udp` I think we would *really* be on to a winner!

**Comment by andreabolognani** [comment]
P.S. if we start accepting bespoke syntax that's not 1:1 mapped to XML elements we might as well call this either `forward`, `ports` (following passt's lead) or `publish` (following that of docker/podman).

Not only would they be significantly less typing (and no shift key involved!), but the difference in naming would also make it obvious that they're an _alternative_ to the XML-mapped options, not a subset of them.

**Comment by crobinso** [comment]
> @crobinso thanks for looking into this!
> 
> I suppose the use of `portForward=...,portForward1=...` is needed to tell the various instances apart. Is this a technical question, i.e. virt-install's CLI parser is completely unable to tell two instances of the same parameter apart, or a matter of consistency with how other options are handled?
> 
> As you can probably tell I'm not very familiar with this part of the code, but I see that a callback is involved, which naively makes me hope that perhaps it would be possible to make things even more user-friendly by removing the need to number instances?
> 

The PR way is simplest to code and maintain since it's using existing cli infrastructure. It's also the pattern we follow everywhere with option strings: if you see the same property twice, the last instance is the one that's used. There's functional differences too: treating `portForward` as append-only means there's no clean way to use virt-xml to edit just the second `<portForward>` range using this sugar syntax.

FWIW I agree the syntax is not pretty

> Similarly, in the interest of making things as convenient for users as possible, is there any chance that we could support `--network passt` as a shorter alias for `--network backend.type=passt`, or is that out of the question?
> 

Yeah that's a good idea, I pushed an extra commit to the PR to add that!




> P.S. if we start accepting bespoke syntax that's not 1:1 mapped to XML elements we might as well call this either `forward`, `ports` (following passt's lead) or `publish` (following that of docker/podman).

FWIW docker full option is `--expose`. Generally though I've been bitten multiple times straying from libvirt XML naming. If tomorrow libvirt adds some named parameter 'publish' somewhere in the `<interface>` XML we've now got ambiguity on virt-install cli. Also hurts cross googleability with libvirt docs, and virt-install man page or `--network help` grepability if you already know the XML naming. None of those are absolute dealbreakers but my spidey sense starts tingling when I start trying to get cute with cli naming.

**Comment by andreabolognani** [comment]
@crobinso thanks for elaborating on the technical impact of changing the name of the option or the way it gets handled. Given the constraints, I agree that what you have implemented is a very reasonable compromise.

@sbrivio-rh do you have any further concerns or can we move forward with the syntax implemented in #765?

**Comment by sbrivio-rh** [comment]
> In this case I don't see saving 7 characters of typing worth it to diverge from libvirt's XML naming.

It's not just seven characters, it's remembering those seven characters (which are rather different from the syntax of other tools) and typing them for each port or port range (at least from what I gather of the current change... or would `portForward=x0:y0,x1:y1` also be possible?). Would the second port forwarding need `portForward1...`, by the way?

> And frankly, strongly preferring libvirt XML naming helps avoid these types of naming discussions which usually come down to a matter of taste and can go round and round.

I would say that preferring the XML syntax over usability (even though I understand it's not just for the sake of it) is also a matter of taste.

> IMO virt-install is more akin to qemu where people write their invocations once and stuff them in bash scripts

I see shell scripts as a separate tool I would need to develop, and virt-install as a tool that adds usability to QEMU (and helpers).

In this case we need 10 characters to forward port 2222 to 22 in the back-end (passt, `-t 2222:22`), and 23 characters (of course excluding the back-end selection) in virt-install (`portForward=2022:22/tcp`).

Two ports like that, and it's 47 characters (`portForward=4022:22/tcp,portForward=8080:80/tcp`) compared to 18 characters (`-t 2222:22,8080:80`). I mean, I understand that that's all passt does, so we try to keep that short... but it's not like libvirt's passt back-end does much more than that.

Anyway, if that's all we can get, it's still a vast improvement over the original (79 characters for one port, 159 for two ports), so I'm thankful for that, don't get me wrong.

**Comment by andreabolognani** [comment]
> It's not just seven characters, it's remembering those seven characters (which are rather different from the syntax of other tools)

Different tools use different names for their options. For example, passt doesn't use the same name as docker/podman. This is expected.

> and typing them for each port or port range (at least from what I gather of the current change... or would `portForward=x0:y0,x1:y1` also be possible?).

Comma is used to separate key-value entries from each other, e.g.

```
--network passt,portForward=8080:80,model=virtio,mac=52:54:00:af:e8:95
```

so obviously it can't be reused to separate entries within a single value.

Could we use a different separator? The only one that could possibly work would be `+` I think. Not sure if that would be a good idea.

> Would the second port forwarding need `portForward1...`, by the way?

Yes. This is how lists are provided to virt-install in general.

> In this case we need 10 characters to forward port 2222 to 22 in the back-end (passt, `-t 2222:22`), and 23 characters (of course excluding the back-end selection) in virt-install (`portForward=2022:22/tcp`).

TCP is used by default, so you don't need to specify it.

**Comment by sbrivio-rh** [comment]
> > and typing them for each port or port range (at least from what I gather of the current change... or would `portForward=x0:y0,x1:y1` also be possible?).
> 
> Comma is used to separate key-value entries from each other, e.g.
> 
> ```
> --network passt,portForward=8080:80,model=virtio,mac=52:54:00:af:e8:95
> ```
> 
> so obviously it can't be reused to separate entries within a single value.

Ouch, of course.

> Could we use a different separator? The only one that could possibly work would be `+` I think. Not sure if that would be a good idea.

'+' looks a bit problematic for shell expansions, and it's not so obvious for people to find out/remember. Maybe ';` is slightly better, but I'm not sure if it can be used. I personally have a slight preference for '+' or ';' over repeating "portForward".

> > Would the second port forwarding need `portForward1...`, by the way?
> 
> Yes. This is how lists are provided to virt-install in general.

So '+' (or ';') would save users from having to number their port forwarding listings as well... that becomes a bigger plus in my eyes.

> > In this case we need 10 characters to forward port 2222 to 22 in the back-end (passt, `-t 2222:22`), and 23 characters (of course excluding the back-end selection) in virt-install (`portForward=2022:22/tcp`).
> 
> TCP is used by default, so you don't need to specify it.

Ah, I didn't know, that's nice.

**Comment by andreabolognani** [comment]
> `+` looks a bit problematic for shell expansions, and it's not so obvious for people to find out/remember. Maybe `;` is slightly better, but I'm not sure if it can be used. I personally have a slight preference for `+` or `;` over repeating "portForward".

Where does `+` cause problems with shell expansion? I've never encountered that.

`;` would be the obvious choice (given that `,` is already taken) to separate list items, but that's not really usable on the shell:

```
$ echo foo;bar
foo
bash: bar: command not found
```

**Comment by sbrivio-rh** [comment]
> > `+` looks a bit problematic for shell expansions, and it's not so obvious for people to find out/remember. Maybe `;` is slightly better, but I'm not sure if it can be used. I personally have a slight preference for `+` or `;` over repeating "portForward".
> 
> Where does `+` cause problems with shell expansion? I've never encountered that.

Hmm, I guess you're right, it sounded a bit messy to me but after all it's kind of niche stuff (parameter substitution).

> `;` would be the obvious choice (given that `,` is already taken) to separate list items, but that's not really usable on the shell:
> 
> ```
> $ echo foo;bar
> foo
> bash: bar: command not found
> ```

I guess I got so much used to type `\;` in `nft` commands (not a good example...) that I actually forgot about this. `+` looks like the best choice to me, and perhaps it can be reused to address similar "issues" as well in the future.
