### ISSUE TITLE
Support for CentOS Stream 10

### ISSUE THREAD

**Issue by renich** [virt-manager/virt-manager#770]
**Distro**: Fedora 41

I would like to, humbly, ask for CentOS Stream 10 support. 

https://mirror.stream.centos.org/10-stream/

Thank you.

**Comment by phrdina** [comment]
If by support you mean that virt-manager would be able to detect it as CentOS Stream 10 when installing new VM it needs to be implemented in osinfo-db project where we get the list of distributions.

There is already existing MR to add CentOS Stream 10, you can follow it here https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/782 .

**Comment by renich** [comment]
I meant virt-install support. I would like to say: `virt-install --install centos-stream10`. Sorry for not explaining correctly.

**Comment by phrdina** [comment]
No worries, virt-install uses the sama data from osinfo-db as virt-manager so the original answer still applies.
