### ISSUE TITLE
Doesn't apply dark mode

### ISSUE THREAD

**Issue by github2099** [virt-manager/virt-manager#773]
**Distro**: Pop!_OS 24.04

Virt-Manager Gui doesn't apply dark mode, even it is applied as the system default.

![screenshot](https://github.com/user-attachments/assets/b0b36c11-cf5d-4339-98c3-28ef0c32d284)

also filed in Pop!_OS repo, https://github.com/pop-os/cosmic-comp/issues/1011

**Comment by phrdina** [comment]
This is not a virt-manager bug. Based on these two issues:
https://github.com/pop-os/cosmic-settings/issues/617
https://github.com/pop-os/cosmic-settings-daemon/issues/52
you need to enable `Apply this theme to GNOME apps.` in experimental settings.
