### ISSUE TITLE
Feature request: Addt'l view

### ISSUE THREAD

**Issue by canDry** [virt-manager/virt-manager#79]
Could I request that an addt'l view be added (or perhaps just addt'l columns to the existing view).  I have many VM's and sorting them out via the main view in virt-manager is quite tedious - as it simply shows the name given to the VM image.  
  
I'm hoping it would be possible to add columns to the main view that list VM name,title, description,  image location, last run/modified date, and creation date.  
  
It might be best if these info columns were a different list view from those that are running - the useful CPU and memory graphs could be kept to a different/switchable listing/view.  
  
I hope this might be considered generally useful enough to incorporate into a new release.

**Comment by crobinso** [comment]
Thanks for the suggestion, however we have explicitly rejected these types of UI scalability features for virt-manager's UI. You can read more about it here: https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md
