### ISSUE TITLE
limit i/o disk

### ISSUE THREAD

**Issue by BedoM** [virt-manager/virt-manager#80]
Hello,

Is it possible to limit disk iops in virt-manager for one or more VM?

thank you

Linux Y520 5.4.17-200.fc31.x86_64 #1 SMP Sat Feb 1 19:00:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
virt-manager --version
2.2.1

**Comment by crobinso** [comment]
No, sorry, and we don't plan to add explicit UI field for it, per our UI policy this falls under advanced config IMO:

https://github.com/virt-manager/virt-manager/blob/master/DESIGN.md

If you enabled raw XML editing mode you can write the XML in the UI manually. Or use a tool like `virt-xml` from the command line

**Comment by BedoM** [comment]
It's a shame thank you anyway
