### ISSUE TITLE
Q: will 'virt-manager' be ported to get usable with python3.x?

### ISSUE THREAD

**Issue by RogerWeihrauch** [virt-manager/virt-manager#82]
Hello Community
As stated above, will there be done any effort/steps to get virt-manager usable with Python3 as system-wide python-env?
Or, do I have to migrate to another app?
If so, which one could be a valueable/featured similar app?

Thanks for your response.
Regards,
Roger

**Comment by Antique** [comment]
Hi @RogerWeihrauch, can you please specify what do you mean by "usable with python3.x"?
virt-manager is python3 only since version 2.0.0.  If you have any issue with virt-manager and your system-wide python please past the error here so we can figure out what's wrong.

**Comment by RogerWeihrauch** [comment]
Hello @Antique 
Well, you are right, and I was wrong. I am very sorry to have been bothering you with this 'issue'.
I t is running w/ Python3.x. I did not try it already with debian Buster.
I will close this if you don't mind.
Thanks and kind regards,
Roger

**Comment by Antique** [comment]
No problem, glad to help.
