### ISSUE TITLE
Unable to launch virt-manager after building with the python file (crashing)

### ISSUE THREAD

**Issue by AnErrupTion** [virt-manager/virt-manager#87]
I was trying to upgrade my version of virt-manager from 1.5.0 to github's latest (I have Ubuntu MATE 18.04 LTS). The build is successful, however, when I try to launch it, it crashes, and the title is "virt-manager crashed with ValueError in require_version(): Namespace LibvirtGLib not available". I think it's because I didn't install all dependencies, but the specs.in file isn't clear to me.

Is there a command that can install all dependencies?
~ AnErrupTion

**Comment by crobinso** [comment]
The package names on debian/ubuntu for some libraries are a little weird. It might be this: https://packages.ubuntu.com/bionic/gir1.2-libvirt-glib-1.0
