### ISSUE TITLE
specific access for user

### ISSUE THREAD

**Issue by Alterjerof** [virt-manager/virt-manager#88]
hi,
I use Kimchi, that use libvirt and i try have a specific access for a simple users.
I tryed with polkit but i don't have rules's file, and when user is in a libvirt group they are so much access (create, delete, ...).
If your have issu for have just a start, a shutdown and a reboot for a simple user.
thx for help.

**Comment by crobinso** [comment]
If you want to allow a specific user to have fine grained permission access only to certain API calls, you need libvirt's polkit ACL rules: https://libvirt.org/aclpolkit.html

It's outside the scope of virt-manager though

**Comment by Alterjerof** [comment]
thx i will see that
