### ISSUE TITLE
virt-manager with qemu-system-sparc64 - cannot remove piix3-usb-uhci device

### ISSUE THREAD

**Issue by c0d3st0rm** [virt-manager/virt-manager#89]
I'm running Debian 10, virt-manager 2.0.0, libvirt 5.0.0. After installing `qemu-system-sparc` and `openbios-sparc`, I've tried both the `sun4u` and `sun4v` (niagara complains about missing firmware, but I guess that's a separate issue), and selecting "Begin Installation" gives the following error:
```
qemu-system-sparc64: -device piix3-usb-uhci,id=usb,bus=pci,addr=0x2: PCI: slot 2 function 0 not available for piix3-usb-uhci, reserved
```
Defining the machine manually using virsh and the base given on the [Debian wiki](https://wiki.debian.org/Sparc64Qemu#VM_setup_using_virsh_and_xml) results in a similar error, and removing the USB device causes it to be recreated when the machine is started. Is there any way to prevent it being added?

**Comment by crobinso** [comment]
You can try using `<controller type='usb' model='none'/>`. But I'm not sure it's every going to work particularly well, I don't think anyone has spent time making sure that libvirt gets the defaults correct for qemu-system-sparc. My recommendation is to use plain qemu on the command line
