### ISSUE TITLE
Feature request: Don't capture specific key combination

### ISSUE THREAD

**Issue by jrandiny** [virt-manager/virt-manager#92]
Hi, could it be possible to add a specific key combination whitelist that will not be captured by the guest VM. 

I'm currently running a VM on a separate workspace on Gnome desktop. Gnome has some key combination for moving between workspaces. It would be great if I can make my VM fullscreen and still be able to move easily between workspaces (similar to Parallels on MacOS)

I don't know where this behavior is supposed to be implemented (by virt-manager, libvirt, or other component) so I'm sorry if this is not in the scope of virt-manager.

Thanks

**Comment by crobinso** [comment]
I'm not certain but it's possible this _could_ be implemented in virt-manager by watching for keyboard input and dropping the keyboard grab behavior on certain combos, but the spice-gtk/gtk-vnc plumbing may not work like that. You could try using /usr/bin/spicy and disabling keyboard grab entirely, but that means all ctrl+XXX sequences would be sent to the host not the VM I think.

That said on Fedora 32 it seems to work for me like this: You have VM in fullscreen. Hit left ctrl+left alt once and release. Then do ctrl+alt+up/down to switch workspaces on the host. The first ctrl+alt combo will release the keyboard grab of the VM, meaning now special control sequences are sent to the host. When you click the mouse in the VM, it will regrab the keyboard. The ctrl+alt sequence can be changed in virt-manager's preferences
