### ISSUE TITLE
configuring default settings for OS.

### ISSUE THREAD

**Issue by ameeno** [virt-manager/virt-manager#95]
Hello,

When I want to create a new VM. My preference is (On linux) to have a virtio gpu, and a virtio_scsi main disk.

how do I change the default configuration for new Linux VM's?

**Comment by crobinso** [comment]
virt-manager doesn't provide any native way to permanently change the default like that, and I don't expect we will add one. You can manually set the values via 'customize before install' but I realize that doesn't solve your problem. For those types of cases if you need reproducible different defaults I usually tell people to write a command line `virt-install` invocation that does what you want, and use that.
